### ISSUE TITLE
Partial authorization for Google account

### ISSUE THREAD

**Issue by eason9487** [woocommerce/google-listings-and-ads#1000]
Since around mid-July, Google changed the permissions to be optional checkboxes when requesting Google account authorization from users. Those checkboxes are unchecked by default, but the GLA plugin needs at least two permissions to proceed with the MC onboarding flow, and needs another one when setting up the ads account.

To avoid users getting stuck when using the GLA plugin without giving required permission, we'll need to implement a way to gracefully handle incremental and partial consent.

- Add relevant descriptions on the MC onboarding and ads account setup pages to inform the permissions we need.
- Loop at the account connection phase if users didn't allow the minimum required permissions.

## Technical

- The current endpoint `/wc/gla/google/connect` for getting the Google auth URL could be used directly. If a user only checked off the "Manage your product listings and accounts for Google Shopping" for the first time, it only displayed the previously unauthorized permissions when going to the next returned auth URL.
    ![image](https://user-images.githubusercontent.com/17420811/132839208-e2bbc764-7c6d-4c8a-88ba-cea02b00ce5e.png)

#### MC onboarding

- Add relevant descriptions to the Googe account connection card.
- Loop to re-ask permissions process if the required two permissions were not provided. And the above descriptions would be changed to an error message.
- Show the Google Merchant Center account list if available in advance once a Google account is connected. But disable its card UI if the required permissions didn't provide.

#### Ads account setup

- Re-ask the ads account control permission before starting the ads account creation if the required permission was not provided.
- Add a new redirection path for bringing users back to the ads account setup page from Google auth page.
   - Frontend ref: https://github.com/woocommerce/google-listings-and-ads/blob/1.4.3/js/src/settings/reconnect-accounts/reconnect-google-account.js#L104-L106
   - Backend ref: https://github.com/woocommerce/google-listings-and-ads/blob/1.4.3/src/API/Site/Controllers/Google/AccountController.php#L90-L95

### Backend development tasks

- TBC

## Link to internal design explorations

pcTzPl-3s

## Figma link

https://mc.a8c.com/pb/2a299/

## Out of bounds/rabbit holes

1. The Google account re-connection page may need these adjustments as well. The flow can be found in the demo of #838.
    - If a user had created an ads account (and maybe with paid campaigns) via the GLA, and the GLA lost token/connection of their Google account, probably we have to ask them to give all three permissions during the re-connection process?
2. If the re-auth endpoint is the same as the current `/wc/gla/google/connect`, there would be an account selection step before the permission checklist.
    - What happens if a user switches to another Google account when we re-asking for permission?
    - Would the previously stored token and etc be cleared before overriding to the new one?
    - Or is there a way to avoid this offered by Google auth API?
    - This may be a more significant concern when re-asking auth in the ads account setup.
    ![image](https://user-images.githubusercontent.com/17420811/132845080-84fcdeeb-da45-4820-bae2-efa98e44da17.png)

## Event tracking

- TBC

**Comment by j111q** [comment]
> If a user had created an ads account (and maybe with paid campaigns) via the GLA, and the GLA lost token/connection of their Google account, probably we have to ask them to give all three permissions during the re-connection process?

**Yes**, we should ask for all 3 permissions during the re-connection process shown in #838. 

> What happens if a user switches to another Google account when we re-asking for permission?

We should not allow the user to have one Google account for MC and a different Google account for Ads. So I'm guessing we'd need some kind of warning or info here to the user to guide them to choose the correct Google account?

**Comment by eason9487** [comment]
Closing this issue due to all functions having been completed and merged to `develop`.
