### ISSUE TITLE
Support pasting the phone verification code.

### ISSUE THREAD

**Issue by tomalec** [woocommerce/google-listings-and-ads#1001]
## User story

As a merchant, I'd like to easily copy the verification code from SMS and past it into GLA input fields.
(Personally, I find such flow useful when using my mobile)

Currently, when I paste, only the first character is put into the first number field.

![paste](https://user-images.githubusercontent.com/17435/132680130-2ad011e4-5db3-4f7f-bda1-21e22a762a26.gif)

**Comment by puntope** [comment]
@tomalec

I'm working on this issue.

Possible to have step by step guide in order to reproduce the issue?

Thanks!

**Comment by puntope** [comment]
> Possible to have step by step guide in order to reproduce the issue?

1. Setup merchant page
2. Section 4 (Confirmation)
3. Send Verification code

![Screenshot 2021-11-17 at 13 12 38](https://user-images.githubusercontent.com/5908855/142198630-6d8ccde7-0afb-4433-97fb-8e3284b8d0f5.png)

**Comment by tomalec** [comment]
> Possible to have step by step guide in order to reproduce the issue?

Sorry, that I didn't add detailed steps in advance. I created it in the times when the flows and URLs where this component was available were quite volatile. And I consider this a feature request for a single component, regardless of its placement.

Yep, that's one way to get this view:
#### Setup
1. Start the setup `/wp-admin/admin.php?page=wc-admin&path=%2Fgoogle%2Fsetup-mc`
2. Complete the setup through 4th step `/wp-admin/admin.php?page=wc-admin&path=%2Fgoogle%2Fsetup-mc&google-mc=connected`
3. Provide a real phone number
![go to phoneverification](https://user-images.githubusercontent.com/17435/142239820-d9c9354e-426a-40d2-a54d-f78be2826e30.gif)

#### Settings
The other is, once you're set up
1. Go to settings
2. Click "Edit" in phone number card, and go to [`/wp-admin/admin.php?page=wc-admin&subpath=%2Fedit-phone-number&path=%2Fgoogle%2Fsettings`](https://wp581wc580.test/wp-admin/admin.php?page=wc-admin&subpath=%2Fedit-phone-number&path=%2Fgoogle%2Fsettings)

**Comment by mikkamp** [comment]
Phone number verification is being removed in #2653 so I'm closing this issue as no longer applicable.
