### ISSUE TITLE
First number of phone verification is not cleared when clicking "Resend…" button

### ISSUE THREAD

**Issue by tomalec** [woocommerce/google-listings-and-ads#1002]
_(This is a belated follow up from https://github.com/woocommerce/google-listings-and-ads/pull/993)_
### Describe the bug:
When I click "Resend code" button all the inputs are cleared except the first one, then the number is cleared when I move the focus away.

![first](https://user-images.githubusercontent.com/17435/132681800-c8f7f3b4-90cf-483c-9e15-60919aed6914.gif)

### Expected behavior:
All numbers should be cleared.

### Actual behavior:
The first one is still there.

### Steps to reproduce:

1. Go to phone verification settings [`/wp-admin/admin.php?page=wc-admin&path=%2Fgoogle%2Fsettings`](https://gla1.test/wp-admin/admin.php?page=wc-admin&path=%2Fgoogle%2Fsettings)
2. Click "Send verification code"
3. Type `123456`
4. Click "Resend code" (once ready)
5. :red_square: the `1` is still there
6. Click somewhere, to move focus away from the focused first field.

**Comment by eason9487** [comment]
I think it was introduced by the `value={ value }` in https://github.com/woocommerce/google-listings-and-ads/commit/808e70ec309ce9e1f4a80b1de560a39ea2af0cc2. 🤦‍♂️
