### ISSUE TITLE
Probable issue in `CompleteSetup` inbox notification criteria 

### ISSUE THREAD

**Issue by danielbitzer** [woocommerce/google-listings-and-ads#1011]
Originally brought up here: https://github.com/woocommerce/google-listings-and-ads/pull/1010#pullrequestreview-755283245

@layout noted that:

- `\Automattic\WooCommerce\GoogleListingsAndAds\Notes\CompleteSetup` Line 67:
   > `* Check if it is > 3 days ago from DATE OF START OF SETUP (installation date)`

This doesn't seem to be [a criteria anymore](https://github.com/woocommerce/google-listings-and-ads/commit/41c16313e8e0ee77fbcaff4b29c2d1be4033ff72#diff-7cebe8ef86c9f8e3c886840da6fb713ecc52c220c6967a71fa5a57b2254815b0), can probably remove the line from the documentation.
- Line 81 - it's also a bit weird that it checks for EXACTLY five orders, I wonder if that was supposed to be five **or more** orders? @jconroy

**Comment by findingsimple** [comment]
> doesn't seem to be a criteria anymore

🤔 

That might be a mistake based on https://github.com/woocommerce/google-listings-and-ads/issues/546#issuecomment-833195030

**Comment by findingsimple** [comment]
> it's also a bit weird that it checks for EXACTLY five orders, I wonder if that was supposed to be five or more orders?

Yeah unless I am missing something that's a logic mistake 🙈  I'm not allowing myself to code anymore.

**Comment by danielbitzer** [comment]
> 🙈 I'm not allowing myself to code anymore.

We all make mistakes sometimes, well I know I do 😆

**Comment by danielbitzer** [comment]
I just checked the code in question and it _is_ checking for 5 or more orders 🙌

**Comment by danielbitzer** [comment]
I removed that incorrect comment in cee235c17d7fa7095ab69f3e0fc023cd18a139f0

Closing as there are no more issues here to fix.
