### ISSUE TITLE
Norwegian not recognized as a supported language

### ISSUE THREAD

**Issue by drwpcom** [woocommerce/google-listings-and-ads#1013]
### Describe the bug:
When Norwegian is the Site language in WordPress, it's impossible to set up Google Listings & Ads. The error is: 
<img width="789" alt="Screen Shot on 2021-09-17 at 09-08-55" src="https://user-images.githubusercontent.com/30090682/133778334-1e335c3f-da91-46ab-8cd7-bd026c7e8e46.png">

### Expected behavior:
Since [Norwegian is one of the supported languages by Google](https://support.google.com/merchants/answer/160637), I expect the setup to work.

### Actual behavior:
Using Norwegian as the site language, the error is "This language is currently not supported by Google listings & Ads" as shown in the screenshot above.

### Steps to reproduce:
1. Change the site language to Norsk bokmål.
2. Try to connect and set up Google Listings & Ads.

### Additional details:

As discussed [in Slack](p1631875980351000-slack-C7U3Y3VMY), In the WP language setting, the language code of Norsk nynorsk is `nn_NO` and `nb_NO` for Norsk bokmål. In the GLA plugin, the code takes the first two letters to compare, while the Norwegian language code is the last two letters in this case.

Might there be other affected languages?

Reported in #4305036-zen. We need to update the user when this is resolved.

**Comment by eason9487** [comment]
Some references:

- Language code - https://www.loc.gov/standards/iso639-2/php/langcodes-keyword.php?SearchTerm=Norwegian&SearchType=ALL
- Currently, GLA uses `no` as the Norwegian language code - https://github.com/woocommerce/google-listings-and-ads/blob/1.4.3/src/GoogleHelper.php#L179

**Comment by layoutd** [comment]
Also > https://linguistics.stackexchange.com/a/36794

Very interesting issue, looks like `no` as a language code is kind of a catch-all, but `nb` is [Bokmål, which is "the preferred written standard of Norwegian for 85% to 90%[5] of the population in Norway"](https://en.wikipedia.org/wiki/Bokm%C3%A5l). In [Google's list of supported languages](https://support.google.com/merchants/answer/160637?hl=en#), it just lists "Norwegian", which I guess should include both standards of Norwegian. So it looks like all three values `no`, `nn`, and `nb` should be added to the list of Merchant Center-supported languages in `GoogleHelper`.

**Comment by dreamtooloud** [comment]
Also reported in zd-4438478

**Comment by ianlin** [comment]
Hey @damiannep and @dreamtooloud, this is fixed in #1091 and it will be included in the next release. Thanks for reporting!
