### ISSUE TITLE
Submit business contact information - after phone verification status is available

### ISSUE THREAD

**Issue by eason9487** [woocommerce/google-listings-and-ads#1033]
#### UPDATE: A new method

The verification status of the phone number can be obtained from the `AccountBusinessInformation->getPhoneVerificationStatus()`. So the following method of getting from an account-level issue would be an alternative.

#### Original method

We implemented the full version of business contact information for phone verification. However, since the phone verification status is not yet available, some planned tasks were pending there.

According to [the phone verification API](https://developers.google.com/shopping-content/guides/phoneverification), it will be able to detect an unverified phone by an account-level issue:

> **Important**: Phone verification is strongly recommended for all new and existing merchants. Your account may otherwise be suspended with the [account status](https://developers.google.com/shopping-content/guides/accountstatuses) issue `PENDING_PHONE_VERIFICATION` until you verify a phone number.

The relevant account issue codes returned from Google API:

- `pending_address_and_phone`: this appears when there is any unfilled address or phone number. Saving an unverified phone number is considered "filled in".
- `pending_phone_verification`: this appears when phone number is unverified

[Previous issue here](https://github.com/woocommerce/google-listings-and-ads/issues/962)

## Technical

[Phone verification API](https://developers.google.com/shopping-content/guides/phoneverification)

### Frontend development tasks

- `<PhoneNumberCard>` component
    - [x] Detect the verification status of the phone number
- `<PhoneNumberCardPreview>` component
    - [x] Show verification status
- `<ContactInformation>` component
    - [x] Recover the initial value of `initEditing` to the auto-detect value `null`

### Backend development tasks

- [x] Add the verification status of the phone number to the API **GET** `mc/contact-information`.
- [x] Add a phone verification status check to the API **GET** `mc/setup`.

## Figma link

eQ9O4m2flzrcAiDMXkOW0m-fi-207%3A6565

## UX changes to be confirmed

Hey @j111q, we have some changes were left in the previous issue:

- Warning icon position - https://github.com/woocommerce/google-listings-and-ads/issues/962#issuecomment-926813119
- Loading placeholder - https://github.com/woocommerce/google-listings-and-ads/issues/962#issuecomment-926844196
- Refresh icon replacement - https://github.com/woocommerce/google-listings-and-ads/issues/962#issuecomment-930546250

## References about phone verification status

- https://github.com/woocommerce/google-listings-and-ads/issues/962#issuecomment-918524625
- https://github.com/woocommerce/google-listings-and-ads/issues/962#issuecomment-923922218

**Comment by j111q** [comment]
Hello @eason9487, thank you so much for the clear summary of outstanding issues! 🙏  And thank you @tomalec for all the great suggestions!! TLDR; 👍 👍 👍 

> Warning icon position: WDYT of moving warning icon to the same line? to make the height of the card closer to the one w/o the message, to make the layout less jumpy as it loads.

I like it! 👍  Agree.

> Loading placeholder: Proposed - IMHO, it gives the user the size and shape of data to anticipate, and is less mesmerizing. Also, it reduces the layout shift.

Agree, great proposal 💯  I think we do have this type of loading pattern elsewhere in Woo as well, so that aligns nicely.

> Refresh icon replacement: I noticed we have "Update" icon in the Gutenberg set.

Yes, let's use that instead!

**Comment by puntope** [comment]
Since after merging https://github.com/woocommerce/google-listings-and-ads/pull/1689 this will become a bug I will label this as a bug in order to be aware of this

**Comment by eason9487** [comment]
> Since after merging #1689 this will become a bug I will label this as a bug in order to be aware of this

Adding some context. The problem was not caused by #1689 but already was there when releasing the business contact information feature. After a phone number is verified, refreshing page or switching to another step and back will reset the verified state.

**Comment by puntope** [comment]
> After a phone number is verified, refreshing page or switching to another step and back will reset the verified state.

Yes. Exactly. Thanks for clarifying. [More info can be found in the issue discussion. ](https://github.com/woocommerce/google-listings-and-ads/pull/1689#issuecomment-1254657431)
