### ISSUE TITLE
WC 5.8 compatibility: Unable to display country name using `useCountryKeyNameMap`

### ISSUE THREAD

**Issue by ecgan** [woocommerce/google-listings-and-ads#1041]
### Describe the bug:

WC version: [5.8.0-rc.1](https://github.com/woocommerce/woocommerce/releases/tag/5.8.0-rc.1)

I was running smoke test on this plugin with the new WooCommerce version. In the Setup MC Step 2 audience page, the SelectControl does not display the country names in the options list and the selected values.

![image](https://user-images.githubusercontent.com/417342/136615966-ce4ad75b-b090-427a-88e7-50c327dbc87f.png)

For comparison, when I downgrade WC to version 5.7.1, and revisit the same page, the values are displayed correctly.

![image](https://user-images.githubusercontent.com/417342/136615985-4e12ef21-0cb4-4718-8279-c7d22a19e287.png)

### Expected behavior:

Selected values and list of options should be visible.

### Actual behavior:

Selected values and list of options are not visible.

### Steps to reproduce:

1. Use WC 5.8.
2. Install GLA plugin.
3. Go through Setup MC flow. In Step 2 choose audience page, you should see the above actual behavior.

### Possible solution:

In case the removal of `countries` from redux store is intentional, one way to fix this issue is to:

1. Figure out the API endpoint to request for the list of countries.
2. Modify the internal of `useCountryKeyNameMap` to call the API endpoint, possibly by using [`useApiFetchEffect`](https://github.com/woocommerce/google-listings-and-ads/blob/996920935e5b61b7a3e9d26dffd6f15c3b825cd6/js/src/hooks/useApiFetchEffect.js) for this.

As long as the `useCountryKeyNameMap` still works the same as prior to WC 5.8, things should continue to work ok.

**Comment by ecgan** [comment]
It seems like this is because in the `wc/admin/settings` redux store, we no longer have the `wc_admin:"countries"` data, so when we try to use `useCountryKeyNameMap` to display the country names, it would return blank.

This affects other places too, like the country code dropdown in phone verification, and store address with country name.

![image](https://user-images.githubusercontent.com/417342/136621106-c6140711-52fd-4bc9-aa4f-1791640de1b0.png)

![image](https://user-images.githubusercontent.com/417342/136621565-768a33fc-4612-4a16-a73b-509cac97bd85.png)

**Comment by ecgan** [comment]
I've added possible solution in the issue description, just in case the removal of `countries` from the redux store is intentional.

**Comment by tomalec** [comment]
Thanks. The other hotfix I was thinking about. Was to simply read it from `window.wcSettings`.

**Comment by eason9487** [comment]
📝  Adding some of my investigations

According to the reply we got from team Isotope (p1633722919407700-slack-CBKK5KM41), eventually the solution will be using `@woocommerce/wc-admin-settings` to get non-mutable settings. However, till now `@woocommerce/wc-admin-settings` has not been published on npm yet. Its former name, [`@woocommerce/settings` **1.0.0**](https://www.npmjs.com/package/@woocommerce/settings), was released two years ago, and its implementation is also obsolete.

If `@woocommerce/wc-admin-settings` 1.1.0 will not be published to npm in the near future, and we still want a more future-compatible solution, we could import it through dependency extraction first for now.

- In the webpack config file, add `'@woocommerce/wc-admin-settings': [ 'wc', 'wcSettings' ]` to the `wcDepMap` object, and add `'@woocommerce/wc-admin-settings': 'wc-settings'` to the `requestToHandle` object.
- At the consumer sides, `import { getSetting } from '@woocommerce/wc-admin-settings';` and then using it as the same way in the [woocommerce-admin/packages/wc-admin-settings](https://github.com/woocommerce/woocommerce-admin/blob/v2.7.2/packages/wc-admin-settings/src/index.js)
- The pros are we can simply remove it from dependency extraction once it gets to be installed from npm, or we don't need to change anything if we still want to use the version injected by dependency extraction.

---

Another alternative is to get countries data located under `dataEndpoints`:

```js
// Original:
// const countries = select( SETTINGS_STORE_NAME ).getSetting('wc_admin', 'countries');
const { countries } = select( SETTINGS_STORE_NAME ).getSetting('wc_admin', 'dataEndpoints');
```

That's how the **woocommerce-admin** gets countries data now, but I haven't look into why `dataEndpoints` and it's kinda a bit weird to me. 😆

**Comment by tomalec** [comment]
> If `@woocommerce/wc-admin-settings` 1.1.0 will not be published to npm in the near future, and we still want a more future-compatible solution, we could import it through dependency extraction first for now.
> …
> - The pros are we can simply remove it from dependency extraction once it gets to be installed from npm, or we don't need to change anything if we still want to use the version injected by dependency extraction.

:rocket: Awesome! I love the idea. The solution works even in WC 5.5, it makes the code more synchronous and shorter.

Before the package will be published we'd need `eslint-disable` exceptions, but that would remind us to check it from time to time.

If the WC will stop using `@woocommerce/wc-admin-settings` internally we would switch to whatever solution that suggests or use in the future.

**Comment by tomalec** [comment]
A bit of archeology, and a suggestion from my past self ;) (8mo. ago)
https://github.com/woocommerce/google-listings-and-ads/commit/6240456b322d8c9c31c4a34d6fb7f424bed45e7c#diff-d9e831e4e3925644df7d65ac6ba2ad3c319537a65b470a5e4e3818cc866ef577R26
> ```js
> // TODO: Consider importing it from something like '@woocommerce/wc-admin-settings'.
> const currency = wcSettings.currency;
> ```
