### ISSUE TITLE
Add a anchor to the Required permissions section in GLA documents on the docs.woocommerce.com

### ISSUE THREAD

**Issue by eason9487** [woocommerce/google-listings-and-ads#1053]
### Description

It's a follow-up of #1000 after asking @j111q , and it's used in #1052 at https://github.com/woocommerce/google-listings-and-ads/blob/92b08874adc1084b2ccde38954e10787355251d5/js/src/components/google-account-card/auth-google-account-card.js#L18-L22

![image](https://user-images.githubusercontent.com/17420811/137724328-48260dcf-a519-4be4-9d0a-f39ebbdb573f.png)

The anchor of "Read more" link when authing the Google account has not been created yet. Please use `required-google-permissions` as the anchor ID.

## Acceptance criteria

* [x] After opening the https://docs.woocommerce.com/document/google-listings-and-ads/#required-google-permissions link, the browser should scroll page to the **Required permissions** section

**Comment by j111q** [comment]
FYI @eason9487 I've added the anchor ID here which can be used for the link: https://woocommerce.com/document/google-listings-and-ads/#required-google-permissions

We're still finalising the copy updates, but I think it's fine to just use this link for now!

**Comment by eason9487** [comment]
Thanks for the updates! @j111q 

Closing this issue due to the link anchor has been added.
