### ISSUE TITLE
Depreciated warning of `should_show_tasks`

### ISSUE THREAD

**Issue by louwie17** [woocommerce/google-listings-and-ads#1054]
### Describe the bug:
There is a depreciated warning of `should_show_tasks` when enabling the Google Listings & Ads plugin

<img width="1808" alt="Screen Shot 2021-10-18 at 9 35 48 AM" src="https://user-images.githubusercontent.com/2240960/137754131-077ae875-5077-41ef-81d3-b62556257510.png">

### Expected behavior:
Should not log the depreciated warning.

### Actual behavior:
A depreciated function is called in the `TaskListTrait` -> https://github.com/woocommerce/google-listings-and-ads/blob/develop/src/TaskList/TaskListTrait.php#L21-L23

### Steps to reproduce:
1. Install WC 5.8 and install the Google Listings & Ads plugin
2. Go to WooCommerce > Home having finished the onboarding wizard
3. If `WP_DEBUG` is enabled, notice the warning in the dashboard, otherwise see the warning in `debug.log`

**Comment by findingsimple** [comment]
Thanks @louwie17
