### ISSUE TITLE
Update product channel visibility styling to match coupons/promos  - pending sync

### ISSUE THREAD

**Issue by findingsimple** [woocommerce/google-listings-and-ads#1062]
### Describe the bug:

Coupon pending sync and product pending sync status currently differs

Products -> 

<img width="314" alt="Screen Shot 2021-10-26 at 5 06 00 pm" src="https://user-images.githubusercontent.com/355014/138822606-91aa27ba-b8ad-4b72-aa72-64ba90502e41.png">

Coupons ->

<img width="306" alt="Screen Shot 2021-10-26 at 5 13 51 pm" src="https://user-images.githubusercontent.com/355014/138822780-b53ca044-c18e-4618-9bb0-1b19470dda84.png">

From @j111q 

> The banner used to show the “status” seems to be always yellow - This is usually used as our warning banner. It would be better for it to be a light grey / no background so it doesn’t seem like it’s always got a warning. 

### Expected behavior:

Consistent treatment of the channel visibility meta boxes

### Steps to reproduce:

* Create and sync a product or coupon
* View the edit product or coupon pages

**Comment by chennyxie** [comment]
Hi, just to confirm this has been fixed in the latest version of the PR
