### ISSUE TITLE
Checking expiring items hits 100% CPU

### ISSUE THREAD

**Issue by kevin25** [woocommerce/google-listings-and-ads#1070]
### Describe the bug:
The query hits 100% CPU for a long time. Looks like it's checking the expiring items.

`SELECT   wp_posts.ID FROM wp_posts  LEFT JOIN wp_term_relationships ON (wp_posts.ID = wp_term_relationships.object_id) LEFT JOIN wp_postmeta ON ( wp_posts.ID = wp_postmeta.post_id AND wp_postmeta.meta_key = '_wc_gla_visibility' )  LEFT JOIN wp_postmeta AS mt1 ON ( wp_posts.ID = mt1.post_id )  LEFT JOIN wp_postmeta AS mt2 ON ( wp_posts.ID = mt2.post_id AND mt2.meta_key = '_wc_gla_errors' )  LEFT JOIN wp_postmeta AS mt3 ON ( wp_posts.ID = mt3.post_id )  LEFT JOIN wp_postmeta AS mt4 ON ( wp_posts.ID = mt4.post_id ) WHERE 1=1  AND (    (      wp_term_relationships.term_taxonomy_id IN (2,4)      OR      NOT EXISTS ( SELECT 1 FROM wp_term_relationships INNER JOIN wp_term_taxonomy ON wp_term_taxonomy.term_taxonomy_id = wp_term_relationships.term_taxonomy_id WHERE wp_term_taxonomy.taxonomy = 'product_type' AND wp_term_relationships.object_id = wp_posts.ID )   ) ) AND (    (      wp_postmeta.post_id IS NULL      OR      ( mt1.meta_key = '_wc_gla_visibility' AND mt1.meta_value != 'dont-sync-and-show' )   )    AND    (      mt2.post_id IS NULL      OR      ( mt3.meta_key = '_wc_gla_errors' AND mt3.meta_value = '' )   )    AND    (      ( mt4.meta_key = '_wc_gla_synced_at' AND mt4.meta_value < '1633321203' )   ) ) AND wp_posts.post_type IN ('product_variation', 'product') AND ((wp_posts.post_status = 'publish' OR wp_posts.post_status = 'draft' OR wp_posts.post_status = 'pending' OR wp_posts.post_status = 'private')) GROUP BY wp_posts.ID  LIMIT 100, 100`

![image](https://user-images.githubusercontent.com/17420811/140849246-64069fe2-c969-417f-b638-cf37b0f33885.png)

### Steps to reproduce:

1.
2.
3.

**Comment by kevin25** [comment]
Can anyone look into it and optimize it please?

**Comment by findingsimple** [comment]
Hi @kevin25 👋 

Thanks for using and getting involved with GLA!

This repository is not intended for support requests. The best place to start the process is with the [WordPress.org Google Listings and Ads forum](https://wordpress.org/support/plugin/google-listings-and-ads/) or if you have a WooCommerce.com account, you can s[tart a chat or open a ticket on WooCommerce.com](https://woocommerce.com/my-account/create-a-ticket/).

The team will help guide you through some problem solving and get some more information to give us a bit more context/background on your concerns/report above.

Taxonomy queries (with lots of joins) can definitely consume resources so I'll keep the issue open until we have more info or can find time to prioritize/investigate.

**Comment by findingsimple** [comment]
Hi @kevin25 we haven't heard anything yet. If/when you open a support ticket - please feel free to reference this issue and include as much additional information/context about your set up as you can. We can reopen once we have some more information to go off.

**Comment by kevin25** [comment]
I chat with your support and they will investigate it. This is really serious issue.
