### ISSUE TITLE
Shipping values flash during the onboarding setup

### ISSUE THREAD

**Issue by eason9487** [woocommerce/google-listings-and-ads#1078]
### Describe the bug:

@layoutd found this issue.

When entering shipping rates/times, sometimes the input values will flash between empty, old value, and new value.

### Expected behavior:

Apart from the currency/number formatting that might change the input value, it should not flash the old/empty value on the `<input>` field after moving out the input cursor.

#### Appear empty value

![Screen Capture on 2021-11-02 at 11-10-04](https://user-images.githubusercontent.com/17420811/140479001-fd26a864-fc07-4314-a988-e4ad08fb2f90.gif)

#### Appear old value

![Kapture 2021-11-05 at 16 29 48](https://user-images.githubusercontent.com/17420811/140481328-2e20d857-6870-4963-99d2-64c2dc49b495.gif)

### Steps to reproduce:

1. Go to step 2 of onboarding setup page.
1. Select "All countries" for audience location.
1. Move to step 3
1. Open browser DevTool and throttle network with "Slow 3G"
    ![image](https://user-images.githubusercontent.com/17420811/140480395-f7d73978-97c9-4684-8e7f-bf9eb7c77beb.png)
1. In step 3, enter values to shipping rates and times quickly, and maybe keep entering values round trip. Then sometimes the flash will happen.

### Additional details:

Eventually the saved values are correct, but it might confuse users.

**Comment by eason9487** [comment]
Reopen this issue as it is not fully resolved. Ref: https://github.com/woocommerce/google-listings-and-ads/pull/1157#issuecomment-998102961

**Comment by puntope** [comment]
I also had it while I was testing for WC6.1.0 the values are not refreshing well when you focus from one to another.

With cursor focus

https://user-images.githubusercontent.com/5908855/147577897-956478a8-480e-473e-81c3-7843f56a7ffe.mov

With tab focus

https://user-images.githubusercontent.com/5908855/147578162-ce7f1d30-a70b-40e2-8fbe-da397c31cd44.mov

**Comment by jorgemd24** [comment]
The root of this issue had deeper implications than expected. See comment about:  [the current implementation](https://github.com/woocommerce/google-listings-and-ads/pull/1157/files/76b976d158e3f0f8ef728e3451f98c6d7e01ef9e#r771529923) and the proposed changes on [#288](https://github.com/woocommerce/google-listings-and-ads/issues/288).

Once the implementations from #288 are accomplished this issue should be resolved.

**Comment by eason9487** [comment]
The last shipping values flash issue only happened on the inputs of shipping time during onboarding setup. With the replacement of using shared shipping time components in #1616, the form state management was isolated from wp-store.

I believe all issues of shipping values flash have been addressed.
