### ISSUE TITLE
WC 5.9 compatibility - migrate should_show_tasks to task list API.

### ISSUE THREAD

**Issue by budzanowski** [woocommerce/google-listings-and-ads#1080]
### Describe the bug:
In WC5.9 the `should_show_tasks` method was deprecated. We should use task list API instead. For reference https://github.com/woocommerce/woocommerce-admin/pull/7577
<figure class="wp-block-table" style="box-sizing: border-box; border: 0px; font-family: inter, -apple-system, system-ui, blinkmacsystemfont, &quot;Segoe UI&quot;, Roboto, Oxygen-Sans, Ubuntu, Cantarell, &quot;Helvetica Neue&quot;, sans-serif; font-style: normal; font-weight: 400; margin: 0px 0px 1.8em; outline: 0px; padding: 0px; vertical-align: baseline; display: block; overflow-x: auto; color: rgb(0, 16, 28); font-size: 16px; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">

Type | File | Line | Notice | Function / Method
-- | -- | -- | -- | --
method_deprecated | src/TaskList/TaskListTrait.php | 22 | Class method \Automattic\WooCommerce\Admin\Features\Onboarding::should_show_tasks() is deprecated woocommerce/packages/woocommerce-admin/src/Features/Onboarding.php line 367 | \Automattic\WooCommerce\Admin\Features\Onboarding::should_show_tasks()

</figure><br class="Apple-interchange-newline">

It looks like a good old version compare will be required.
### Expected behavior:
No deprecation logs.

### Steps to reproduce:

I have not tested this yet. I am just writing what compat checker has found.

### Additional details:
Found during WC5.9 compatibility testing.

**Comment by findingsimple** [comment]
Ncie thanks @budzanowski
