### ISSUE TITLE
JavaScript error in WooCommerce dashboard after Merchant Center onboarding

### ISSUE THREAD

**Issue by layoutd** [woocommerce/google-listings-and-ads#1085]
### Describe the bug:
A JavaScript error appears on the main WooCommerce dashboard page after completing Merchant Center onboarding (tested in WooCommerce 5.8 and WooCommerce 5.9 with the `develop` branch of Google Listings & Ads):

![image](https://user-images.githubusercontent.com/228780/140746395-37888fcc-25d7-4b0c-9a33-40ec093f916d.png)

### Expected behavior:
No error after onboarding.

### Actual behavior:
Error after onboarding.

### Steps to reproduce:
1. Install WooCommerce and Google Listings & Ads
2. Check the WooCommerce dashboard to see the pending Google Listings & Ads task (`Set up Google Listings & Ads`). 
3. Complete the Google Listings & Ads onboarding wizard
4. Return to the WooCommerce dashboard and confirm the JS error in the console.

### Additional details:
- Also note that the _completed_ `Set up Google Listings & Ads` task still links to the "List your products on Google, for free and with ads" Merchant Center onboarding start page.

**Comment by eason9487** [comment]
Thanks for catching this issue! 🙏  It was introduced by #1073. 😭
