### ISSUE TITLE
When setting up Google Listings and Ads, it defaults to a Google Merchant account this is not the one I want to setup.  How do I change it at setup?  I am stuck...please help.

### ISSUE THREAD

**Issue by AGarcia1963a** [woocommerce/google-listings-and-ads#1096]
### Steps to reproduce:

1.
2.
3.

**Comment by AGarcia1963a** [comment]
When setting up Google Listings and Ads, it defaults to a Google Merchant account that is not the one I want to set up.  How do I change it at setup or somewhere else?  I am currently stuck in the setup pages.  Help!

**Comment by layoutd** [comment]
Hi @AGarcia1963a  👋

Thanks for using Google Listings & Ads!

This repository is not intended for support requests. The best place to start the process is with the [WordPress.org Google Listings and Ads forum](https://wordpress.org/support/plugin/google-listings-and-ads/) or if you have a WooCommerce.com account, you can s[tart a chat or open a ticket on WooCommerce.com](https://woocommerce.com/my-account/create-a-ticket/).

The team will help guide you through some problem solving and get some more information to give us a bit more context/background on your concerns/report above.
