### ISSUE TITLE
interrupeted activation

### ISSUE THREAD

**Issue by anto67ba** [woocommerce/google-listings-and-ads#1103]
### Describe the bug:
if you by mistake do insert wrong google account and do interrupt the installation there is no way to insert/change it. i stopped the configuration de-installed the plug in, re-installed it but still i do see the wordpress and google account that i do not want to use

### Expected behavior:
when removed the plug-in should clean all the database info inserted

### Actual behavior:
the information on wordpress google account are still there

### Steps to reproduce:

1. initiate the configuration
2. set the woocommerce account
3. set the google account
4. stop the configuration
5. exit and remove the plug-in
6. if you re-install it info on woocommerce and google account are still there so there is no way to change them if you inserted a wrong account

**Comment by findingsimple** [comment]
Hi @anto67ba thanks for taking the time to post. I'll tag our designer on this as an FYI (@j111q) to keep it on our radar for enhancing but close this out for now as it will require broader considerating/design changes and planning.
