### ISSUE TITLE
Display a checkmark for selected countries in the country dropdown menu

### ISSUE THREAD

**Issue by ecgan** [woocommerce/google-listings-and-ads#112]
This issue is created based on the discussion in https://github.com/woocommerce/google-listings-and-ads/pull/110#issuecomment-754364268 . Currently when we select a country from the dropdown menu in the Step 2 Choose Your Audience in the Setup Merchant Center flow, there is no indicator for the selected countries. There should be some kind of tick or check to show what has been selected, and what hasn't been.

Some figma screenshot references:
https://d.pr/i/AQhnFm
https://d.pr/i/OjOpaU

The first screenshot is preferred because the checkboxes are closer with the labels and hence easier to read; the second screenshot may not work that well for bigger screens as the check marks may be too far apart with the labels.

**Comment by eason9487** [comment]
Close this issue since it's no longer applicable after using the `TreeSelectControl` for all country selectors in #1430.
