### ISSUE TITLE
After Updating plugin "Google listing & ads" plugin stopped working automatically

### ISSUE THREAD

**Issue by arg6063** [woocommerce/google-listings-and-ads#1122]
### Describe the bug:
After Updating plugin "Google listing & ads" plugin stopped working. Completely showing error 
"There was an error loading Google Merchant Center contact information."

### Expected behavior:
It was working fine 2 days ago.

### Steps to reproduce:
1. I just updated extension. it was working fine but without any changes it stopped working completly
2. it showing Errors on dashboard opening "There was an error loading report." & "There was an error loading Google Merchant Center contact information"
3.

### Additional details:
also other facing same issues check support & Review section of "google listings & ads plugin"

Please resolve this issue as soon as possible.
I've also tried unistalling and clearing orphans & reinstalling old version 1.5.1 but still it is not working.

![google listing   ads plugins not working](https://user-images.githubusercontent.com/32302749/143869962-d0e9dc14-cfbb-43e5-8162-200eaf6558f8.JPG)

**Comment by puntope** [comment]
Hey there @arg6063 

Thanks for using Google Listings & Ads!

This repository is not intended for support requests or opening tickets. The best place to start the process is with the WordPress.org Google Listings and Ads forum or if you have a WooCommerce.com account, you can start a chat or open a ticket on WooCommerce.com support.

The support team will help guide you through some problem solving and get some more information to give us a bit more context/background on your concerns/report above.
