### ISSUE TITLE
Fatal error on plugin deactivation.

### ISSUE THREAD

**Issue by budzanowski** [woocommerce/google-listings-and-ads#1141]
### Describe the bug:

Fatal error on plugin deactivation.

### Expected behavior:

The plugin deactivates without errors.
### Steps to reproduce:

1. Set up a new site with WooCommerce installed
2. Install GLA plugin.
3. Make sure that WP debug is set to log and display
4. Go to Plugins page and deactivate the plugin
5. The error:
![image](https://user-images.githubusercontent.com/17271089/144820993-1ba6c01c-ea74-4818-b4cb-c71cb9d21bf6.png)

### Additional details:
Thanks @ilyasfoo for the ping.

**Comment by findingsimple** [comment]
Updated title to "Fatal error on plugin deactivation" and added to a 1.8.1 milestone

**Comment by findingsimple** [comment]
Closed in https://github.com/woocommerce/google-listings-and-ads/pull/1142
