### ISSUE TITLE
Refactor needed in shipping-rate / shipping-time

### ISSUE THREAD

**Issue by puntope** [woocommerce/google-listings-and-ads#1159]
## User story
As a developer I want to have a good development experience and prevent bugs and unpredictable errors created by Duplicated code. As a developer I  want to follow the best coding practices like [DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself)

## Context
Discovered after reviewing this issue https://github.com/woocommerce/google-listings-and-ads/pull/1157#discussion_r771253233

`shipping-rate` and `shipping-time` contains several code duplications. The most clear one is between `/shipping-rate/shipping-rate-setup/add-rate-button/add-rate-modal/useGetRemainingCountryCodes.js` and `/shipping-time/shipping-time-setup/add-time-button/add-time-modal/useGetRemainingCountryCodes.js` which are named the same and the code is 99% the same.

<img width="1321" alt="Screenshot 2021-12-17 at 11 03 57" src="https://user-images.githubusercontent.com/5908855/146527545-0e8e9125-b142-46a3-81d6-dc52c79d6c27.png">

The structure between both of them is also pretty similar, which makes me consider that an abstraction between them is possible and desired..

**Comment by eason9487** [comment]
This is duplicated with #274. Also, there are more relevant follow-up items in #288.

**Comment by findingsimple** [comment]
[Closing as a duplicate](https://github.com/woocommerce/google-listings-and-ads/issues/1159#issuecomment-996827621)
