### ISSUE TITLE
After 30 days all product removed from google ads

### ISSUE THREAD

**Issue by eternal6666** [woocommerce/google-listings-and-ads#1163]
After 30 days all product removed from google ads.
I have free and paid campaign set.
In product feed Automatically synced to Google with today date but on status it shows Not synced. In channel visibility is Sync and show. How can I sync with google again and why its removed all after 30days?

**Comment by findingsimple** [comment]
Hi @eternal6666 

> why its removed all after 30days?

Its how merchant center works

> After 30 days all product removed from google ads.

Sorry for hassle - there is a daily scheduled action that checks for expiring products and resubmits them a few days early. It sounds like this is failing for you somewhere. 

This isn't a support channel so I would recommend heading over to WooCommerce.com and submitting a support ticket so our happiness team can help you problem-solve.
