### ISSUE TITLE
Update Google Ads library

### ISSUE THREAD

**Issue by mikkamp** [woocommerce/google-listings-and-ads#1186]
To be able to use the new [Performance Max Campaigns](https://developers.google.com/google-ads/api/docs/performance-max/create-campaign) we will need to update to at least [v9 of the Google Ads API](https://developers.google.com/google-ads/api/docs/release-notes#v9)

The earliest version that supports v9 is the PHP library version [12.1.0](https://github.com/googleads/google-ads-php/releases/tag/v12.1.0) (currently using 10.0.0).

Note: Version [13.0.0](https://github.com/googleads/google-ads-php/releases/tag/v13.0.0) is also available but that requires the minimum PHP version to be bumped to 7.4 (we still have the minimum as 7.3).

Points to keep an eye on:
- google/protobuf is updated to 3.18.0 this package is shared with dependencies of the Merchant Center libraries
- Confirm all namespace replacements in bin/prefix-vendor-namespace.php still work and we aren't missing any new ones for updated packages (or can remove old replacements no longer needed)
- Remove autoload file for `guzzlehttp/psr7`, see last comment about needing to update Google API library for this
- WCS can be updated to v9 along with the plugin update (see example PR 1807-gh-Automattic/woocommerce-connect-server )
- Confirm we don't get any MISALIGNED_DATE_FOR_FILTER errors when using various date filters for the Ads reports, see [migration details](https://developers.google.com/google-ads/api/docs/version-migration#v8-v9)

**Comment by eason9487** [comment]
After checking through the [Migrating from v8 to v9](https://developers.google.com/google-ads/api/docs/version-migration#v8-v9) document, and [release notes](https://developers.google.com/google-ads/api/docs/release-notes) of v8.1.0 and v9.0. Looks like the change related to GLA implementation only happens on the `GoogleAdsService.Search`. More details of the filtering for `segments` are [here](https://developers.google.com/google-ads/api/docs/release-notes#reporting).

**Comment by mikkamp** [comment]
That's definitely an additional point we need to keep an eye on. It's not clear if we do need to change anything though as we are using the WC Admin function [time_interval_id](https://github.com/woocommerce/woocommerce-admin/blob/main/src/API/Reports/TimeInterval.php#L183), which would convert the date to:

week: 2022-02 (2nd week of 2022)
month: 2021-10 (10th month of 2021)
year: 2022

We use `before` and `after` to filter which results we are interested in. It's not super clear if those must also be set to the start of the range as it mentions before the `MISALIGNED_DATE_FOR_FILTER` error it used to just ignore the filter (which wasn't happening for us). In both versions it's defined the same:
![image](https://user-images.githubusercontent.com/11388669/148914206-cdeb60d9-5494-4a40-b149-332db7f4ec5e.png)

I've added it to the list of points to check.

**Comment by mikkamp** [comment]
Another point to take into consideration is the updates to `guzzlehttp/psr7` which no longer requires (doesn't exist anymore in newer versions) the autoload file. In order to fully remove the dependency on the old version we would also need to update the Google API library #1199
