### ISSUE TITLE
When I am deleting countries on the "Choose your audience section" the dropdown to add countries is displayed

### ISSUE THREAD

**Issue by jorgemd24** [woocommerce/google-listings-and-ads#1195]
### Describe the bug:

When I am deleting countries on the "Choose your audience section" the dropdown to add countries is displayed. This is unnecessary as my intention is to delete countries not to add countries.

### Steps to reproduce:

1. Go to Edit free listings -> Choose your audience.
2. Try to delete a country.
3. The dropdown to add countries is displayed. This is unnecessary as my intention is to delete countries not to add countries. 

### Expected behaviour:
When I am deleting a country the dropdown to add countries should not be displayed. 

### Actual behaviour:
When I am deleting a country the dropdown to add countries is displayed. 

### Additional details:

https://user-images.githubusercontent.com/2488994/149549934-d36864d0-5541-4d00-ac26-16abd8855f32.mp4

**Comment by ianlin** [comment]
Closing this issue based on the conclusion in [this PR](https://github.com/woocommerce/google-listings-and-ads/pull/1200#issuecomment-1017111320). Feel free to reopen it if anything needs to be added.
