### ISSUE TITLE
Disconnect all accounts button's style is not disabled when the checkbox is unchecked

### ISSUE THREAD

**Issue by ianlin** [woocommerce/google-listings-and-ads#1203]
### Describe the bug:

When the user tries to disconnect all accounts a popup modal will appear. There is a button in red called `Disconnect all accounts`  that cannot be clicked unless the checkbox `Yes, I want to disconnect all my accounts` is checked. The colour of the button before the checkbox is clicked is red as well so it is a little bit confusing.

### Steps to reproduce:

1. Have GLA set up.
2. Go to `Marketing` -> `Google listings & Ads` -> `Settings` -> `Disconnect all accounts`.
3. The colour of the button `Disconnect all accounts` is red, which is the confusing part.

### Expected behavior:

The colour of the button `Disconnect all accounts` should be in grey, the disabled style.

### Actual behavior:

The colour of the button `Disconnect all accounts` is red.

### Additional details:

https://user-images.githubusercontent.com/914406/149910408-9c5ff8e9-faa7-4096-b03d-1efec9ed8fbf.mov

**Comment by eason9487** [comment]
This seems to be a duplicate of #1005.

**Comment by ianlin** [comment]
@eason9487 Thanks for pointing this out 😄 Closing this issue.
