### ISSUE TITLE
Ads campaign creation and edit APIs do not respond with errors when parameters are invalid

### ISSUE THREAD

**Issue by eason9487** [woocommerce/google-listings-and-ads#1210]
### Describe the bug:

Ads campaign creation and edit APIs do not respond with errors when parameters are invalid.

### Steps to reproduce:

1. Checkout `0cd7cc9556535559a4bcae409cedd7e02d852518`
1. ~Change store currency to "Japanese yen (¥)" in the WC general settings.~ Change the **Number of decimals** to 3 in WC Settings: `/wp-admin/admin.php?page=wc-settings`.
1. Open browser DevTool.
1. Go to GLA admin page and add or edit a paid campaign.
1. Enter ~0.01~ **0.001** in the daily average cost field.
1. Click on "Launch paid campaign" or "Save changes" button.

https://user-images.githubusercontent.com/17420811/150717012-f78ba7fa-f06b-4172-8ada-380fc148b2b5.mp4

### Expected behavior:

- [x] The APIs should respond with errors when parameters are invalid.
- [x] The UI should show creation/update failure when parameters are invalid.

Remove the client workaround blocks if the APIs are fixed by responding with 40x status code; Or recheck whether they need any adjustments if the APIs are fixed by responding with 20x status code and different error data structures.

- [x] Ads campaign creation
    https://github.com/woocommerce/google-listings-and-ads/blob/6a2bb66ef3787927ef61829b9e7bc4cf282356db/js/src/data/actions.js#L787-L798
- [x] Ads campaign update
    https://github.com/woocommerce/google-listings-and-ads/blob/6a2bb66ef3787927ef61829b9e7bc4cf282356db/js/src/data/actions.js#L834-L845

### Actual behavior:

- The APIs respond HTTP status code 200 response with `message` property only when parameters are invalid.
- The ads campaign creation page shows a "You’ve successfully created a paid campaign!" notification when parameters are invalid.

### Additional details:

The return values of `$e->getCode()` are [Google RPC codes](https://github.com/googleapis/common-protos-php/blob/1.0/src/Rpc/Code.php#L43-L52):
- https://github.com/woocommerce/google-listings-and-ads/blob/0cd7cc9556535559a4bcae409cedd7e02d852518/src/API/Google/AdsCampaign.php#L147-L151
- https://github.com/woocommerce/google-listings-and-ads/blob/0cd7cc9556535559a4bcae409cedd7e02d852518/src/API/Google/AdsCampaign.php#L223-L227

**Comment by eason9487** [comment]
Reopen this due to it's accidentally closed by #1211

**Comment by mikkamp** [comment]
I noticed the same while working on the PMax campaigns. The easiest solution is to just remove the `$e->getCode()` lines which will force the controller to default to a 400 error message. Although it would be nicer to dig a bit deeper in the error messages to get a more descriptive error.

You'll need to actually set the ads account to Japanese Yen, not just the store currency to reproduce it with a value of 0.01. However I can reproduce the same error if I send a value of 0.001 to the API. The full response is:
```json
{
    "message": "Request contains an invalid argument.",
    "code": 3,
    "status": "INVALID_ARGUMENT",
    "details": [
        {
            "@type": 0,
            "data": "type.googleapis.com\/google.ads.googleads.v9.errors.GoogleAdsFailure"
        },
        {
            "@type": 0,
            "data": [
                {
                    "errorCode": {
                        "campaignBudgetError": "MONEY_AMOUNT_LESS_THAN_CURRENCY_MINIMUM_CPC"
                    },
                    "message": "A money amount was less than the minimum CPC for currency.",
                    "trigger": {
                        "int64Value": "1000"
                    },
                    "location": {
                        "fieldPathElements": [
                            {
                                "fieldName": "mutate_operations",
                                "index": 0
                            },
                            {
                                "fieldName": "campaign_budget_operation"
                            },
                            {
                                "fieldName": "update"
                            },
                            {
                                "fieldName": "amount_micros"
                            }
                        ]
                    }
                }
            ]
        },
        {
            "@type": 0,
            "data": "vIkv6gT2mD65BtBN_h1Luw"
        }
    ]
}
```

We currently return the basic error message which is:
> Request contains an invalid argument.

But it would be much more helpful to get the descriptive message:
> A money amount was less than the minimum CPC for currency.

I'd suggest a helper function added to `ApiExceptionTrait` which extracts the errors into an array with the following format:
```php
[
	'MONEY_AMOUNT_LESS_THAN_CURRENCY_MINIMUM_CPC' => 'A money amount was less than the minimum CPC for currency.',
];
```

Although I think in the long run it would be nicer for the UI to handle the minimum amount and prevent the request from being sent, since this can be different depending on which currency is being used.

**Comment by eason9487** [comment]
@mikkamp 

> You'll need to actually set the ads account to Japanese Yen, not just the store currency to reproduce it with a value of 0.01. However I can reproduce the same error if I send a value of 0.001 to the API.

Thanks for noticing this! I updated the replicate steps of this issue.

> Although it would be nicer to dig a bit deeper in the error messages to get a more descriptive error.

> I'd suggest a helper function added to ApiExceptionTrait which extracts the errors into an array with the following format: [...]

Changing the error message to an array will affect response structure in several places on outer layers. I think it might require a more generic error structure design and then refactor both client-side and server-side.

To avoid the wider impact scope, I tended to make the HTTP status codes correspond to actual errors first. I will open another follow-up issue once the #1242 gets merged.

**Comment by mikkamp** [comment]
> Changing the error message to an array will affect response structure in several places on outer layers. I think it might require a more generic error structure design and then refactor both client-side and server-side.

My suggestion was to convert the ApiException to an array of errors, so it would be easier to pick out the right error message. So only the message passed to outer layers would change, which as far as I understand wouldn't affect the client-side. However a followup issue sounds good, since it will work well in combination with mapping the error code.
