### ISSUE TITLE
Spend Match Update - In Product Updates

### ISSUE THREAD

**Issue by findingsimple** [woocommerce/google-listings-and-ads#1214]
Google is changing customer ad credit incentives for Google Listings & Ads from Spend Match $150 to Spend Get $500 on Feb 2, 2022. The fulfillment period will also be changed from 30 days to 60 days.

We need to update various parts of content within the extension as a result

Refer to the messaging update tracker for content updates

Internal link: pcTzPl-eI-p2 (Copy of content below but you might need more context)

---

**Free Listings Submission**

<img width="560" alt="cAELX2" src="https://user-images.githubusercontent.com/355014/150737293-6900125a-ac53-4a09-a454-7a12cda8c74a.png">

> H1 - Spend $500 to get $500 in Google Ads credits.
>
> New to Google Ads? Get $500 in ad credit when you spend $500 within your first 60 days* You can edit or cancel your campaign at any time.
> 
> *Full terms and conditions here (link in doc)

---

**Extension Dashboard**

<img width="889" alt="XyH8K5" src="https://user-images.githubusercontent.com/355014/150737483-dc9e6073-d010-4071-af8f-c7e443546d2a.png">

> Create your first campaign and get $500 in ad credit*
> 
> *Full terms and conditions here. (link in doc)

---

**In Product FAQs**

<img width="884" alt="fD6j9n" src="https://user-images.githubusercontent.com/355014/150737681-876f8059-81f7-4aec-810c-9f7cbf82bef1.png">

Refer to link in tracking doc for copy updates

---

**Free ad credit eligibility box**

Notice the mention of "30 days" which should be changed to "60 days". The green box is shown for sub-account that is newly created within the last 30 days, which should be changed to 60 days too.

![image](https://user-images.githubusercontent.com/417342/151146256-1553d17e-027c-4271-b299-e402e06a99f4.png)

---

**Maximum Credit Modal**

<img width="1076" alt="begBjx" src="https://user-images.githubusercontent.com/355014/150737817-8100f93d-dc03-4cc1-a2e0-71cb4923c6b3.png">

Refer to spreadsheet mention in p2 above for maximum value updates

**Comment by ecgan** [comment]
Note: I have updated the issue description above to include info on fulfillment period and free ad credit eligibility box.

Hat tip to @eason9487 for noticing this. 🎩
