### ISSUE TITLE
Improve error handling when operating ads campaigns

### ISSUE THREAD

**Issue by eason9487** [woocommerce/google-listings-and-ads#1246]
It's a follow-up for https://github.com/woocommerce/google-listings-and-ads/issues/1210#issuecomment-1038760473 and https://github.com/woocommerce/google-listings-and-ads/pull/1242#issuecomment-1039818852.

## User story

- As a merchant, it would be nice to help me enter valid values when creating, editing, and deleting ads campaigns.
- As a merchant, it would be nice to have the exact reason when an error occurs in creating, editing, and deleting ads campaigns.

### Current implementations

Currently, it shows a helpless error message "Unable to update your paid ads campaign. Please try again later." when errors occurred. Merchants may have no idea what's going wrong and how to correct it.

![image](https://user-images.githubusercontent.com/17420811/154198912-159c1b44-e837-41fa-8d13-0f4e0408d465.png)

## How to reproduce the problem

1. Checkout revision `540dfa54ca7e14e32705fa638177fd73b90719cf`.
1. Change the **Number of decimals** to 3 in WC Settings: `/wp-admin/admin.php?page=wc-settings`.
1. Go to GLA admin page and add/edit a campaign.
1. Enter 0.001 in the daily average cost field.
1. Click on "Launch paid campaign" or "Save changes" button.

### Backend

@mikkamp wrote:

> [...] Although it would be nicer to dig a bit deeper in the error messages to get a more descriptive error. [...] The full response is:
> 
> ```json
> {
>     "message": "Request contains an invalid argument.",
>     "code": 3,
>     "status": "INVALID_ARGUMENT",
>     "details": [
>         {
>             "@type": 0,
>             "data": "type.googleapis.com\/google.ads.googleads.v9.errors.GoogleAdsFailure"
>         },
>         {
>             "@type": 0,
>             "data": [
>                 {
>                     "errorCode": {
>                         "campaignBudgetError": "MONEY_AMOUNT_LESS_THAN_CURRENCY_MINIMUM_CPC"
>                     },
>                     "message": "A money amount was less than the minimum CPC for currency.",
>                     "trigger": {
>                         "int64Value": "1000"
>                     },
>                     "location": {
>                         "fieldPathElements": [
>                             {
>                                 "fieldName": "mutate_operations",
>                                 "index": 0
>                             },
>                             {
>                                 "fieldName": "campaign_budget_operation"
>                             },
>                             {
>                                 "fieldName": "update"
>                             },
>                             {
>                                 "fieldName": "amount_micros"
>                             }
>                         ]
>                     }
>                 }
>             ]
>         },
>         {
>             "@type": 0,
>             "data": "vIkv6gT2mD65BtBN_h1Luw"
>         }
>     ]
> }
> ```
> 
> We currently return the basic error message which is:
> 
> > Request contains an invalid argument.
> 
> But it would be much more helpful to get the descriptive message:
> 
> > A money amount was less than the minimum CPC for currency.
> 
> I'd suggest a helper function added to `ApiExceptionTrait` which extracts the errors into an array with the following format:
> 
> ```
> [
> 	'MONEY_AMOUNT_LESS_THAN_CURRENCY_MINIMUM_CPC' => 'A money amount was less than the minimum CPC for currency.',
> ];
> ```
> 
> Although I think in the long run it would be nicer for the UI to handle the minimum amount and prevent the request from being sent, since this can be different depending on which currency is being used.

### Frontend

It would be nicer to
- have error messages in the response body to develop and debug.
- have error codes in the response body to identify known errors for showing i18n error messages to merchants.

### Backend:

* [ ] Provide a more helpful error message and concrete error code for frontend side if it's a known error.

### Frontend:

* [ ] Prevent merchants to enter invalid values if it's possible to check.
* [ ] Show a more helpful error message on UI to merchants if it's a known error.

**Comment by eason9487** [comment]
Added the **on hold** label - It would be more proper to handle this at least after finishing the PMax and multi-country targeting projects.

**Comment by Brianmitchtay** [comment]
Seeing this come up in 42300063-hc, where the UX would be significantly better for this user if they were able to see the reason their campaign can't be launched. 

In the interim before we see this launched, I wanted to share a screenshot that showcases where the detailed error messages can be found in these cases, in case other users or HEs come across this issue before it gets addressed.

In short, have the user open their browsers developer console to the "Network" panel, and inspect the failed HTTP request's response for the error message.

![0aUHoe.png](https://user-images.githubusercontent.com/45057772/229956333-4390dad1-b000-48b7-9872-3a18d404549f.png)

For those who prefer a video:

https://user-images.githubusercontent.com/45057772/229958563-0fbe8aa2-1c0e-4469-94f4-b81bcaf8c5e7.mp4



I hope this helps someone!

**Comment by Brianmitchtay** [comment]
Seeing this again in 6006609-zen

Now that I'm looking for this I see that not having these errors well surfaced to the user in the GLA extension is causing us a lot of otherwise unnecessary back and forth in support.

**Comment by Brianmitchtay** [comment]
Another case in 6133227-zen
