### ISSUE TITLE
Shipping rates UI changes: Navigate away prompt shows up when users edit and change back to original value in Edit Free Listings

### ISSUE THREAD

**Issue by ecgan** [woocommerce/google-listings-and-ads#1290]
- This is a follow up to PR review comment: https://github.com/woocommerce/google-listings-and-ads/pull/1266#pullrequestreview-895997852

> The behavior of alerting user that there is unsaved data is not the same as before. Originally, even if user has edited it, the alert will not pop up if user changes it back to the original value.
> 
> - The shipping rate

https://user-images.githubusercontent.com/17420811/156161814-f3029a2b-b992-4cc7-a3ae-d15184d6a5ba.mp4

> - The free shipping threshold

https://user-images.githubusercontent.com/17420811/156161880-84aa632f-cec4-47ab-a05a-719b1e7cfa1b.mp4

From https://github.com/woocommerce/google-listings-and-ads/pull/1266#issuecomment-1060192535:

> Moreover, the current inconsistencies go beyond the two examples listed. If there is a free shipping threshold in the initial form values, the prompt will not appear when the edited data is the same. At this point, its appearance timing is not due to dirty form again.

https://user-images.githubusercontent.com/17420811/156969616-e9282c3e-d6e7-4ca9-999f-9a6c82c42f07.mp4

**Comment by eason9487** [comment]
📝  Another related comment - https://github.com/woocommerce/google-listings-and-ads/pull/1266#issuecomment-1060192535

**Comment by eason9487** [comment]
After discussing with @ecgan, this issue was transferred to me.

**Comment by eason9487** [comment]
Fixed in #1307
