### ISSUE TITLE
Activating Google Listings & Ads (before WooCommerce) led to a fatal error.

### ISSUE THREAD

**Issue by danielk-am** [woocommerce/google-listings-and-ads#1292]
### Describe the bug:

Fatal error caused when Google Listings and Ads was activated before WooCommerce.

https://user-images.githubusercontent.com/92185881/156963422-3d32890b-5502-412d-8693-031d80ebe663.mov

The short version above where Google Listings & Ads was activated without WooCommerce.

https://user-images.githubusercontent.com/92185881/156963625-d8b51365-2eb3-4756-837b-56e368eef59d.mp4

The full video showed the error and how to correctly activate both Google Listings and Ads and WooCommerce.

### Steps to reproduce:

1. Installed both Google Listings & Ads and WooCommerce (both not activated yet).
2. Activate Google Listings & Ads first. Results in a fatal error.
3. Activate WooCommerce first, and then Google Listings & Ads. All good!

### Expected behavior:

A helpful error message such as "WooCommerce is not yet installed or activated. Would you like to start your WooCommerce store?" instead of a fatal error.

### Actual behavior:

A fatal error message.

### Additional details:

I encountered this while troubleshooting a website by deactivating all plugins and activating the Automattic + WooCommerce plugins in bulk. This possibly led to the plugins being activated in alphabetical order, which meant Google Listing & Ads, before WooCommerce, that led to the fatal error message.

**Comment by mikkamp** [comment]
The error is easy to reproduce by activating Google Listings & Ads with WooCommerce deactivated.

```
Fatal error: Uncaught Automattic\WooCommerce\GoogleListingsAndAds\Vendor\League\Container\Exception\NotFoundException:
Alias (Automattic\WooCommerce\GoogleListingsAndAds\Tracking\Events\ActivatedEvents) is not being managed by the container or delegates in google-listings-and-ads/vendor/league/container/src/Container.php:188

Stack trace:
#0 google-listings-and-ads/src/Container.php(90): Automattic\WooCommerce\GoogleListingsAndAds\Vendor\League\Container\Container->get()
#1 google-listings-and-ads/src/Infrastructure/GoogleListingsAndAdsPlugin.php(61): Automattic\WooCommerce\GoogleListingsAndAds\Container->get()
#2 google-listings-and-ads/google-listings-and-ads.php(49): Automattic\WooCommerce\GoogleListingsAndAds\Infrastructure\GoogleListingsAndAdsPlugin->activate()
#3 wp-includes/class-wp-hook.php(30 in google-listings-and-ads/vendor/league/container/src/Container.php on line 188
```

The error comes from when we try to track the [activation source](https://github.com/woocommerce/google-listings-and-ads/blob/1.11.1/src/Infrastructure/GoogleListingsAndAdsPlugin.php#L61). But since WC is not activated [`maybe_register_services`](https://github.com/woocommerce/google-listings-and-ads/blob/1.11.1/src/Infrastructure/GoogleListingsAndAdsPlugin.php#L114-L118) will stop early without registering services.

We could add another condition before tracking that event (or make the tracking class Activateable and add the tracking code there). But the bigger problem is that if we don't register services we won't call the `activate` functions for any instances of `Activateable`. So for example the cron job for the Notes won't get added. Once WooCommerce does get activated we don't recall the activate functions, so the plugin will continue working but it will have missed all the code it was supposed to run on activate.

Similar story for `Deactivateable` although most of that code is just for cleanup so it won't have as much of a negative impact.

**Comment by rawdreeg** [comment]
> The error is easy to reproduce by activating Google Listings & Ads with WooCommerce deactivated.
> 
> ```
> Fatal error: Uncaught Automattic\WooCommerce\GoogleListingsAndAds\Vendor\League\Container\Exception\NotFoundException:
> Alias (Automattic\WooCommerce\GoogleListingsAndAds\Tracking\Events\ActivatedEvents) is not being managed by the container or delegates in google-listings-and-ads/vendor/league/container/src/Container.php:188
> 
> Stack trace:
> #0 google-listings-and-ads/src/Container.php(90): Automattic\WooCommerce\GoogleListingsAndAds\Vendor\League\Container\Container->get()
> #1 google-listings-and-ads/src/Infrastructure/GoogleListingsAndAdsPlugin.php(61): Automattic\WooCommerce\GoogleListingsAndAds\Container->get()
> #2 google-listings-and-ads/google-listings-and-ads.php(49): Automattic\WooCommerce\GoogleListingsAndAds\Infrastructure\GoogleListingsAndAdsPlugin->activate()
> #3 wp-includes/class-wp-hook.php(30 in google-listings-and-ads/vendor/league/container/src/Container.php on line 188
> ```
> 
> The error comes from when we try to track the [activation source](https://github.com/woocommerce/google-listings-and-ads/blob/1.11.1/src/Infrastructure/GoogleListingsAndAdsPlugin.php#L61). But since WC is not activated [`maybe_register_services`](https://github.com/woocommerce/google-listings-and-ads/blob/1.11.1/src/Infrastructure/GoogleListingsAndAdsPlugin.php#L114-L118) will stop early without registering services.
> 
> We could add another condition before tracking that event (or make the tracking class Activateable and add the tracking code there). But the bigger problem is that if we don't register services we won't call the `activate` functions for any instances of `Activateable`. So for example the cron job for the Notes won't get added. Once WooCommerce does get activated we don't recall the activate functions, so the plugin will continue working but it will have missed all the code it was supposed to run on activate.
> 
> Similar story for `Deactivateable` although most of that code is just for cleanup so it won't have as much of a negative impact.

@mikkamp I see we have a PluginValidator class that provides the validate() method, shouldn't this be able to return false if WooCommerce is not installed?

https://github.com/woocommerce/google-listings-and-ads/blob/develop/src/Internal/Requirements/PluginValidator.php#:~:text=public%20static%20function%20validate()%3A%20bool%20%7B

Maybe we should write a validator class that checks whether WooCommerce is installed or not. Although, I wonder why the WCAdminvalidator isn't catching this.

Let me know your thoughts?

**Comment by mikkamp** [comment]
Discussed it more in Slack. But to follow up here, the WCValidator checks both if WC is active and if it's the right version, see: https://github.com/woocommerce/google-listings-and-ads/blob/1.11.1/src/Internal/Requirements/WCValidator.php#L39

**Comment by rawdreeg** [comment]
@mikkamp explained that:

This line of code is the problem: https://github.com/woocommerce/google-listings-and-ads/blob/1.11.1/src/Infrastructure/GoogleListingsAndAdsPlugin.php#L61

The container didn't register any services, so it returns a fatal that it's not available. Making the ActivatedEvents class Activateable and then adding an activate function that call maybe_track_activation_source could fix the issue but in the case where WooCommerce is activated after GLA, we miss calling the activation code.

MIk suggested that we could store a state of needing a later call to activate as soon as all the dependencies have been met. Or deactivate the plugin automatically. But not sure if we have some examples we can copy.

We'd like to discuss this further with the rest of the team to get more input.

**Comment by rawdreeg** [comment]
@mikkamp Just curious, if we needed to store a state of needing a later call to activate as soon as all the dependencies have been met, this login would run on plugin_loaded, correct?

**Comment by mikkamp** [comment]
Not sure what hook it would run on, but it would have to be after `plugins_loaded` to confirm all the dependencies are met. What I meant with that statement is that we need to somehow detect when all the plugin dependencies have been met, and then re-run this bit of code: 

```php
		foreach ( $this->registered_services as $service ) {
			if ( $service instanceof Activateable ) {
				$service->activate();
			}
		}
```

Because when we first activated Google Listings & Ads, that code was run with `registered_services` as an empty array.

**Comment by mikkamp** [comment]
Based on our discussion we decided to go with a solution where we will prevent the plugin from being activated and show the reason why with the failed dependency. The reason should be shown in all the following circumstances:
- Activate single plugin
- Bulk plugin activation
- Activate through CLI

Preventing the plugin from being activated can be loosely based on the solution [here](https://wordpress.stackexchange.com/a/296278)

**Comment by mikkamp** [comment]
Also wanted to mention that if the PHP version doesn't match (VersionValidator), we don't even register the activation hook. The plugin will still activate, but just do nothing and show a persistent admin notice. If they then update PHP and leave the plugin without reactivating, it will also miss calling the activation hook.

It's a bit of an edge case, but we might want to take it into consideration in case we also want to block activation when the PHP version is too low.
