### ISSUE TITLE
Add blurb to encourage users to connect child Ads account and not a parent MCC

### ISSUE THREAD

**Issue by findingsimple** [woocommerce/google-listings-and-ads#1346]
### Is your feature request related to a problem? 

> Currently, while our plug-in automatically prevents merchants from linking an MCA (multi-client account in merchant center), it currently does not necessarily prevent users from linking an MCC (manager account in Google Ads). We know that
> (1) campaign creation does not happen and (2) the users are not able to access insightful reporting after linking a manager account

#### How to reproduce the problem

Create and connect an an MCC account that has child accounts

### Describe the solution you'd like 

Initial quick solution is to add a "blurb" to the UI to encourage users to only connect child accounts.

We will likely create follow up project/issues to address the underlying problem at a later point.

## Technical

TBC - Initial assumption is this should hopefully be mostly a cosmetic change.

## Figma link

TBC - cc @j111q - to update once we have confirm copy/designs

## Event tracking

Ensure any links in blurb are firing a tracks event to help us gauge interactions.

**Comment by j111q** [comment]
Hi, here's the proposed quick fix:

<img width="2215" alt="image" src="https://user-images.githubusercontent.com/65582817/159864730-e788c9ba-1ca5-4625-ad39-1e87adbb2544.png">

For the `Learn more` link, perhaps we can link to this Google article about manager accounts: https://support.google.com/google-ads/answer/6139186 Open to other suggestions though.

Here's the more ideal / long-term solution I'd propose, where we don't show any additional small text, but instead we just hide any MCC / manager accounts completely:

<img width="2325" alt="image" src="https://user-images.githubusercontent.com/65582817/159864788-e5b68a07-66e4-4407-b6f3-a0cb2116e7fa.png">
