### ISSUE TITLE
Add a helper function to get supported countries of a continent in GoogleHelper

### ISSUE THREAD

**Issue by ianlin** [woocommerce/google-listings-and-ads#1351]
## User story

In this [PR](https://github.com/woocommerce/google-listings-and-ads/pull/1341/files#diff-e5e54e70e3677013fec896bd6a8490847bc64b414e5f573c5945804d85733b95R120) and this [PR](https://github.com/woocommerce/google-listings-and-ads/pull/1344/files#diff-e00da6abb755a70b224c15358214801e8057f047e1ba00ba21f3ba056ce8c480R128-R145), they have similar logic to get only the supported countries for a continent. It would be great to extract the logic as a shared function in GoogleHelper class.

### Is your feature request related to a problem? 

No.

### Describe the solution you'd like 

A a shared helper function in GoogleHelper class to get only the supported countries for a continent, and apply in the code in the above PR.

## Acceptance criteria

- The helper function should be working and shared with both callers.
- Unit tests should be complete and cover the case when removing a continent when there are no supported countries.

**Comment by nima-karimi** [comment]
@ianlin I've moved the method created for the shipping integration into the GoogleHelper class in https://github.com/woocommerce/google-listings-and-ads/pull/1476. Let me know if that looks okay.
