### ISSUE TITLE
Compatibility with the cart and checkout blocks

### ISSUE THREAD

**Issue by mikkamp** [woocommerce/google-listings-and-ads#1368]
Project for investigating compatibility with Cart and Checkout blocks: pdGoBY-wb-p2

GLA has the class `GlobalSiteTag` which has two main functions:

#### 1. Track the conversion on the order received page
From my understanding with the checkout blocks it will still redirect to a new page once the order has completed. So this tracking which is injected into `wp_head` should still run. However I think we should still test that to confirm that there aren't any compatibility issues.

#### 2. Add a Gtag snippet on every page
If the Google Analytics Integration extension is active we will hook into the added snippet and add our conversion ID, if the extension is not active we add a basic Gtag snippet, but as far as I can see this isn't actually used for tracking until we reach the order received page (there are plans and pending PR's to add additional tracking).

The blocks have a custom integration for [Google Analytics](https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/trunk/assets/js/extensions/google-analytics/index.ts). We'll need to determine though if the global Gtag which is output on the page still gets the conversion ID from GLA added.

As mentioned we have plans to add additional tracking, such as PR #1277, which won't work in combination with blocks, so we have to keep that in mind.

**Comment by findingsimple** [comment]
> mikkamp self-assigned this 1 hour ago

Thanks @mikkamp

**Comment by mikkamp** [comment]
#### 1. Track the conversion on the order received page

Confirmed that we are still redirected to a new checkout/order-received page when checkout is done through the Checkout Block. The conversion tracking snippet is added to the head of the page and I can see the event being sent.
We use a `send_to` parameter to send the conversion only to the specific conversion_id/label, so it doesn't send an additional conversion to the property configured by Google Analytics Integration.

#### 2. Add a Gtag snippet on every page
On pages with blocks the conversion ID is still added to the Gtag snippet from Google Analytics Integration.

There is a pending issue which will simplify overriding the snippet: https://github.com/woocommerce/woocommerce-google-analytics-integration/issues/186
If that's implemented we will need to confirm we still hook into the overwritten snippet. Right now the blocks implementation adds a basic configuration snippet, and then Google Analytics Integration adds a more elaborate one, which is the one we hook into.

#### Additional tracking such as PR #1277

This still needs finalisation on how it's going to work, as the `send_to` is still missing a matching `group`. PR #1277 tracks single view pages which are rendered by displaying a new page, so the tracking will function regardless if blocks are being used. However if we want to add tracking for events which are strictly linked to the all-product/cart/checkout blocks, then we will need to find a way to make that compatible.

### Conclusion
All the tracking code we have currently implemented is functioning correctly both with and without the blocks.
For any other tracking code to be implemented, we need to confirm it's compatible with the blocks.

Closing this issue since there are no specific followup points left.
