### ISSUE TITLE
UX Improvements on Get Started Page

### ISSUE THREAD

**Issue by ianlin** [woocommerce/google-listings-and-ads#1392]
### Goal

To better explain the benefits and value of the Google Listings & Ads integration to the merchants, in order to reduce the current drop-off rate of ~31%.

### Overview

1. Highlight more of the benefits of this extension.
    - The current welcome page is underselling the potential value of this extension.
2. Communicate and educate the user about Smart Shopping Campaigns.
    - By failing to mention “Smart Shopping Campaigns” in enough depth at the beginning, users doubt the total value of the extension. This means their expectations are also misled and they miss out on an opportunity to learn about “Smart Shopping Campaigns” (something few knew about)
3. Provide an estimate of how long setup will take.
    - Eg. 15 minutes.
4. Include a place for our marketing video.
    - You can watch the video [here](https://woocommerce.com/products/google-listings-and-ads/)
5. Include a place for case studies / customer quotes.

From the new design, there are several new sections in the get started page:

1. Get started CTA with video.
2. Benefits.
3. Features.
4. Case studies.
5. Get started CTA again.
6. FAQ

<img width="451" alt="Screenshot 2022-04-01 at 12 55 20" src="https://user-images.githubusercontent.com/914406/161197443-58be67f3-35d2-4f77-87d7-7b155425f7e7.png">

### The current state of the system

In our current design, the in-product Get Started page is pretty bare, communicating just a little about the integration. Based on the funnel analysis in Sept 2021, the drop-off here is pretty steep; 31% who view this screen do not proceed with their setup.

There are only three sections in the current get started page:

1. Get started CTA.
2. Features.
3. FAQ.

<img width="888" alt="Screenshot 2022-04-01 at 12 59 48" src="https://user-images.githubusercontent.com/914406/161197840-36433faf-e043-4abc-8f96-cda3a222b64c.png">

## Technical

💡 We will create a shared branch [feature/1392-ux-improvements-on-get-started-page](https://github.com/woocommerce/google-listings-and-ads/tree/feature/1392-ux-improvements-on-get-started-page). All relevant developments should be branched from it and merged back to it. And open a PR to merge the shared branch to develop once the overall feature gets ready to release.
💡 This project is mainly focusing on the UI changes, no backend modification required.

Currently there are two cards, `get-started-card` and `features-card`, and one FAQ section. We need to update it to five cards and one FAQ section according to the new design.

The five cards and the FAQ in the code structure would be:

- `js/src/get-started-page/get-started-with-video-card`
- `js/src/get-started-page/benefits-card`
- `js/src/get-started-page/features-card`
- `js/src/get-started-page/case-studies-card`
- `js/src/get-started-page/get-started-card`
- `js/src/get-started-page/faqs.js`

### Project

pcTzPl-i7-p2

### Figma

[Figma](https://www.figma.com/file/eQ9O4m2flzrcAiDMXkOW0m/Google-Listings-%26-Ads-v1.x?node-id=7253%3A119828)

## Event tracking

TBA.

**Comment by j111q** [comment]
FYI @dominiquevias ☝️ (If there are any design questions, please ping Nikki!)
