### ISSUE TITLE
Fatal error when settings are saved with an invalid value

### ISSUE THREAD

**Issue by mikkamp** [woocommerce/google-listings-and-ads#1396]
### Describe the bug:
We save the `gla_merchant_center` options as an array of values for the Merchant Center settings. However if this is not stored in the database as an array (serialized data) it causes a fatal, preventing the Merchant onboarding steps from being completed.

```
2022-03-30T07:47:41+00:00 CRITICAL Uncaught TypeError: Return value of Automattic\WooCommerce\GoogleListingsAndAds\API\Google\Settings::get_settings() must be of the type array, string returned in wp-content/plugins/google-listings-and-ads/src/API/Google/Settings.php:545
Stack trace:
#0 wp-content/plugins/google-listings-and-ads/src/API/Google/Settings.php(123): Automattic\WooCommerce\GoogleListingsAndAds\API\Google\Settings->get_settings()
#1 wp-content/plugins/google-listings-and-ads/src/API/Google/Settings.php(51): Automattic\WooCommerce\GoogleListingsAndAds\API\Google\Settings->should_sync_shipping()
#2 wp-content/plugins/google-listings-and-ads/src/API/Site/Controllers/MerchantCenter/SettingsSyncController.php(67): Automattic\WooCommerce\GoogleListingsAndAds\API\Google\Settings->sync_shipping()
#3 wp-content/plugins/google-listings-and-ads/src/API/Google/Settings.php on line 545
```

In two of the cases I looked at the `gla_merchant_center` and it appeared to have been saved with the value `1` (could have also been a true value). However I'm not able to track down how the option got saved with this value, in the code there is only one location where we update the value: https://github.com/woocommerce/google-listings-and-ads/blob/develop/src/API/Site/Controllers/MerchantCenter/SettingsController.php#L73
At first glance I wasn't able to find any way to end up with the value of 1 after sending a request to this endpoint. So I'm assuming there was something external which changed this data.

### Steps to reproduce:
1. Save the option `gla_merchant_center` with the value of 1 
2. Try to complete the onboarding steps
3. See the failure at the last step of onboarding
4. Confirm the error is present in the fatal error log

### Expected behavior:
For the merchant settings value to be overwritten during onboarding so we can proceed to syncing the settings without any fatal errors.

### Actual behavior:
Fatal error occurs when settings are being synced to the Merchant Center.

### Additional details:

The error was reported in the following cases:
https://wordpress.org/support/topic/error-when-completing-the-setup/
4907372-zen
4909627-zen
4906550-zen

In two of the cases the log files showed errors with the phone verification endpoint:

```
2022-03-30T09:31:57+00:00 ERROR Automattic\WooCommerce\GoogleListingsAndAds\API\Google\Merchant::request_phone_verification
{
	"error": {
		"code": 500,
		"message": "Internal error",
		"errors": [
			{
				"message": "Internal error",
				"domain": "global",
				"reason": "backendError"
			}
		],
		"status": "INTERNAL",
		"details": [
			{
				"@type": "type.googleapis.com/google.rpc.ErrorInfo",
				"reason": "internalError",
				"domain": "global"
			}
		]
	}
}
```

```
2022-03-31T07:13:26+00:00 ERROR Automattic\WooCommerce\GoogleListingsAndAds\API\Google\Merchant::request_phone_verification {
  "error": {
    "code": 429,
    "message": "Retries quota exceeded.",
    "errors": [
      {
        "message": "Retries quota exceeded.",
        "domain": "global",
        "reason": "rateLimitExceeded"
      }
    ],
    "status": "RESOURCE_EXHAUSTED",
    "details": [
      {
        "@type": "type.googleapis.com/google.rpc.ErrorInfo",
        "reason": "quotaExceeded",
        "domain": "usageLimits"
      }
    ]
  }
}
```

However taking a closer look at the timestamps, this seems to have happened after the first Fatal error with the settings occurred. So I'm assuming this was a side effect of retrying the onboarding (including phone verification step) several times.

In addition to adjusting the `get_settings` function to always return an array. We might also want to refactor [this line](https://github.com/woocommerce/google-listings-and-ads/blob/develop/src/API/Google/Settings.php#L173) to make use of the `get_settings` helper function.

**Comment by mikkamp** [comment]
Temporary workaround to resolve this is to clear up the `gla_merchant_center` value in the `wp_options` table. Or set it to an empty value in the hidden options page `https://domain.com/wp-admin/options.php`.

Once this has been reset the onboarding can be restarted, to resave the shipping and tax settings.

**Comment by mxhassani** [comment]
A similar case in 4923940-zen
The workaround didn't help. Ended up deactivating the plugin.

**Comment by kaushikasomaiya** [comment]
The workaround throws a fatal error and WP Admin is no longer accessible. 

` Fatal error: Uncaught Error: Cannot unset string offsets in /public_html/wp-content/plugins/google-listings-and-ads/src/DB/Migration/Migration20211228T1640692399.php:75`

Is there any other workaround?

**Comment by kaushikasomaiya** [comment]
Another case 4923997-zen

**Comment by kaushikasomaiya** [comment]
Another case 4926752-zen

**Comment by findingsimple** [comment]
@kaushikasomaiya I'm not sure there is any point in adding new case links unless you've confirmed the merchants have updated to the latest version released 13 hours ago which has the fix and they are still seeing the problem  https://github.com/woocommerce/google-listings-and-ads/releases/tag/1.12.4

**Comment by kaushikasomaiya** [comment]
> @kaushikasomaiya I'm not sure there is any point in adding new case links unless you've confirmed the merchants have updated to the latest version released 13 hours ago which has the fix and they are still seeing the problem https://github.com/woocommerce/google-listings-and-ads/releases/tag/1.12.4

@jconroy Apologies, I've let them know that the latest version with the fix is released now.
