### ISSUE TITLE
Edit free listings - change shipping rates and shipping times when audience countries are changed

### ISSUE THREAD

**Issue by ecgan** [woocommerce/google-listings-and-ads#1402]
### Describe the bug:

In Setup MC, when users go through shipping settings, go back to change / delete audience countries and go to shipping settings again, the shipping settings are cleared and users have to set them up again. This is done by using the `useAutoClearShippingEffect`. This ensures that a country that is not a target audience country will not have the corresponding shipping settings.

In Edit Free LIstings however, the logic is different. When users go back to change / delete audience countries and go to shipping settings again, the shipping settings are **not** cleared. As a result, a country that has been deleted in target audience would still show up in shipping rate and shipping times, and users are still able to save the settings successfully. This should be deemed as a bug. (Note that this was discussed / introduced in https://github.com/woocommerce/google-listings-and-ads/pull/444#issue-853572386.)

To fix this issue, the easiest way would be to use the similar `useAutoClearShippingEffect` approach in Edit Free Listings. Alternatively, we can check the deleted country and removed them from shipping rates and shipping times accordingly.

### Steps to reproduce:

1. Go to Edit Free Listings.
2. Remove an existing country in target audience.
3. Go to shipping settings.

### Expected behavior:

The removed country should not be in shipping rates and shipping times.

### Actual behavior:

The removed country is still in shipping rates and shipping times.

**Comment by nima-karimi** [comment]
I think this is similar to this issue: https://github.com/woocommerce/google-listings-and-ads/issues/1387. Maybe we can merge them?

**Comment by ecgan** [comment]
@nima-karimi , thanks, turns out both issues #1387 and #1402 are duplicates of issue #1304 created by @eason9487 😆  (I remember @eason9487 created an issue for it but I couldn't find it before I created issue #1402).

I'll close both issues as duplicates and copy important information into issue #1304, so we just need to look at one issue #1304.

**Comment by ecgan** [comment]
Duplicate of issue #1304, closing this issue.
