### ISSUE TITLE
CES Prompts Showing several times

### ISSUE THREAD

**Issue by puntope** [woocommerce/google-listings-and-ads#1428]
### Describe the bug:

While I was testing other PR I noticed the CES Prompt "How easy was it to create a Google Ad campaign?" (maybe some other Prompts as well) are being shown multiple times.

In my opinion, if the Prompt is already there, we should avoid showing it again. 

https://user-images.githubusercontent.com/5908855/163542330-a2ae0723-7911-4bae-9d3e-8b84de001330.mov

### Steps to reproduce (actual behaviour):

1. WP Admin as well as Analytics Feature should be enabled 
2. Edit a campaign and save
3. You will see the prompt "How easy was it to create a Google Ad campaign?" 
4. Dont do anything and just go to Edit a campaign and save again
5. You will see another prompt "How easy was it to create a Google Ad campaign?" so 2 prompts in total.

### Expected behavior:

1. WP Admin as well as Analytics Feature should be enabled 
2. Edit a campaign and save
3. You will see the prompt "How easy was it to create a Google Ad campaign?" 
4. Dont do anything and just go to Edit a campaign and save again
5. You WONT see another prompt "How easy was it to create a Google Ad campaign?" so 1 prompt in total.

**Comment by findingsimple** [comment]
@jorgemd24 could you pick this one up too please?
