### ISSUE TITLE
Refactor shipping input controls

### ISSUE THREAD

**Issue by ecgan** [woocommerce/google-listings-and-ads#1444]
## User story

This is a follow-up to https://github.com/woocommerce/google-listings-and-ads/pull/1410#issuecomment-1108910285 by @ecgan:

> One thing I would like to point out is that while I was working on the changes (together with the experience in PR #1424), I had a realization that there are duplicated code between `MinimumOrderInputControl`, `ShippingRateInputControl` and `CountriesTimeInput` (the input control for shipping time). All of them has a label, an edit button, and a price/number input, and their layout / CSS is similar. I am thinking to refactor this into a general reusable component like `EditNumberInputControl` (the "Edit" naming is to signify the Edit button), with an `onEditClick` prop. This component should not have any business logic in it, and I think we can replace/remove the three individual custom *InputControl components above by using this new component. I will come out with a separate issue and PR on this.

Below are screenshots of the shipping input controls:

Shipping rate input control:

![image](https://user-images.githubusercontent.com/417342/165301196-8784cf5a-8c51-4be0-995e-6160a652ae8e.png)

Minimum order input control:

![image](https://user-images.githubusercontent.com/417342/165301315-bc36d8d5-1659-46d7-a3aa-01257dfcaf87.png)

Shipping time input control:

![image](https://user-images.githubusercontent.com/417342/165301363-dc459444-ca2f-40ab-9269-d92b2c628d72.png)

The idea of this issue is to refactor the above components into a generic reusable `EditNumberInputControl` component, supporting the following criteria:

- The consumer should be able to specify `label` and `suffix`, and other `InputControl`'s props. These props should be passed into the contained `AppInputNumberControl`.
- The component should contain the "Edit" button, and expose the button click event via `onEditClick` prop. The consumer can then handle the `onEditClick` event and display their own edit modals.
- The component should handle the CSS layout between the contained label, button and input.

With the above `EditNumberInputControl` component, we shall be able to use it to replace the above three individual input control components, reducing duplicated code.

**Comment by ecgan** [comment]
Dev note / update:

> With the above `EditNumberInputControl` component, we shall be able to use it to _replace the above three individual input control components_, reducing duplicated code.

I was looking into this issue, creating `EditNumberInputControl` component and trying to make it replace the existing `ShippingRateInputControl`, but the effort and changes needed are bigger than I thought. `ShippingRateInputControl`'s `value` and `onChange` props work with `ShippingRateGroup` type, while `EditNumberInputControl`'s `value` and `onChange` works with number type. If we want to use `EditNumberInputControl` and replace `ShippingRateInputControl`, this means that we would need to change the related handlers too.

Alternatively, we can consider keeping the `ShippingRateInputControl` component with its props, and change its internal to make use of the `EditNumberInputControl`.

I will continue and evaluate both options later.

**Comment by mikkamp** [comment]
Closing this issue as no longer applicable. We might want to revisit this in the future but at the moment we changed the shipping time inputs to use a stepper component so it's significantly different from the other number input fields.

![Image](https://github.com/user-attachments/assets/ffc18084-71e1-49ae-bc8a-7c492b611314)
