### ISSUE TITLE
Error when connecting some existing Merchant Accounts

### ISSUE THREAD

**Issue by mikkamp** [woocommerce/google-listings-and-ads#1462]
### Describe the bug:
There are several reports of receiving the error "Unable to retrieve Merchant Center account status"
See: [#](https://wordpress.org/support/topic/unable-to-retrieve-merchant-center-account-status/) [#](https://wordpress.org/support/topic/unable-to-retrieve-merchant-center-account-status-2/) [#](https://wordpress.org/support/topic/unable-to-retrieve-merchant-center-account-status-3/) [#](https://wordpress.org/support/topic/unable-to-retrieve-merchant-center-account-status-4/)

The common trend seems to be an existing merchant account, which can be circumvented by creating a new merchant account through the plugin.

One of the reports lists the error as:
```
2022-04-25T23:03:24+00:00 ERROR Automattic\WooCommerce\GoogleListingsAndAds\API\Google\Merchant::get_accountstatus {
  "error": {
    "code": 400,
    "message": "[destinations.destinationName] Invalid destination name: Shopping",
    "errors": [
      {
        "message": "[destinations.destinationName] Invalid destination name: Shopping",
        "domain": "content.ContentErrorDomain",
        "reason": "invalid_destination"
      }
    ]
  }
}
```

Which would indicate that it's related to the change in #1312 

According to the [documentation](https://developers.google.com/shopping-content/reference/rest/v2.1/accountstatuses/get) not providing any destination would default to "Shopping" but it seems this is no longer the case which is why we specifically request "Shopping" as a destination. However this error seems to imply that it's not supported for some Merchant Accounts.

Not sure if it's relevant, but the [documentation](https://developers.google.com/shopping-content/reference/rest/v2.1/accountstatuses/get) mentions destination should be set as an array of strings, we set it to a [single string](https://github.com/woocommerce/google-listings-and-ads/blob/1.12.5/src/API/Google/Merchant.php#L211) in the code, which works fine for Merchants that have been created through the extension.

I have reopened the question for Google to get some additional clarification about this parameter.

**Comment by findingsimple** [comment]
Thanks @mikkamp, i'll mark as high for now as its related to onboarding and you've identified a number of reports

**Comment by wyter** [comment]
5207582-zen, asked them to wait for the fix to be shipped in a coming update.

**Comment by Snaacks** [comment]
Issue also reported in HC-30412511
