### ISSUE TITLE
Confusing properties of `gla_setup_mc` track event

### ISSUE THREAD

**Issue by tomalec** [woocommerce/google-listings-and-ads#1467]
_(This is a follow-up issue from https://github.com/woocommerce/google-listings-and-ads/pull/1408#issuecomment-1090434772)_
### Describe the problem:

When I was moving around the event tracking docs I noticed that `gla_setup_mc` is rather confusing. Its properties are described as:
> - `target` Button ID
> - `trigger` Action (e.g. `click`)

I see a few problems here:
1. `trigger` is always set to `click` - do we really need such a property, that always has a static value?
2. `target` property contains an ID of the button that **triggered** the action, not the target of the merchant's flow. (This may relate to DOM `event.target`, but this is a technical implementation detail, and I'm not sure if that matters for people analyzing data)

So when a merchant clicks a "Continue" button on step 1 and goes to step two, we fire `gla_setup_mc { trigger: 'click', target: 'step1'}`, whereas when I'd be to describe in plain English, what an event just happened I'd say:
> An event in `MC setup` just happened: the merchant `trigger`ed it by clicking/tapping/activating the "Continue" button on `step 1` and is being `target`ted to `step 2`

So, `gla_setup_mc { trigger: 'step1-continue', target 'step2' }` - that is more-or-less what I did in Pinterest in a similar use-case https://github.com/woocommerce/pinterest-for-woocommerce/blob/develop/TRACKING.md#wcadmin_pfw_setup

-----

I guess it may be problematic to change the properties of the already observed events, as that may corrupt the data reports.
However, I doubt `trigger` which was always `click` was used for anything meaningful.
Also, I suppose providing the actual target of user flow, may be a piece of useful information.

//cc @jconroy

**Comment by findingsimple** [comment]
i don't disagree with you @tomalec but can say a lot of the conventions and naming etc. were based off of existing tracks events in core and wc-admin for consistency and then evolved through individual preferences or people implementing them so I can't say for certain why some things are exactly why they are

What's that quote for naming is the hardest thing...

> do we really need such a property, that always has a static value?

My presumption is `gla_setup_mc`  would have been used for more things and potentially not just clicking (you've used a few like clicking/tapping/activating (obviously very similar) but I maybe there could be hover, focus, open ....dunno I'm sure I could come up with more things that could trigger in an onboarding flow. Trigger to me is the action that triggered the event.

> target property contains an ID of the button that triggered the action, 

Definitely get what you saying but I also see the idea that similar to `event.target` you point out that it could be more of a reference to the object which is triggering the event etc.  - the care of multiple events being triggered with the same name it's the specific one doing the triggering.

Loosely held opinions of course, it's just one perspective
