### ISSUE TITLE
Adjust the conversion rate used for budget recommendations

### ISSUE THREAD

**Issue by findingsimple** [woocommerce/google-listings-and-ads#1478]
We currently have budget recommendations [loaded here](https://github.com/woocommerce/google-listings-and-ads/blob/develop/data/budget-recommendations.csv) which are based on a 3.5% conversion rate.

After some analysis (more time and data) a more accurate conversion rate is 1.9%.

We would like to update the recommendations to use this new conversion rate.

We will still keep it at 10 conversions. 

See pcTzPl-zZ-p2 links to the original spreadsheet and which cell can be updated to get new values

**Unknowns / Can't Remember**

@layoutd I believe you worked on this originally - did the Google team provide the csv or did we come up with it from the spreadsheet above?

**Assumptions**

We import the values into a database table. So part of the acceptance criteria for this enhancement will be an upgrade routine to update the values when a user installs the new version.

**Comment by layoutd** [comment]
The original data was provided by the Google team, and we copied it into the CSV.

**Comment by findingsimple** [comment]
Thanks @layoutd
