### ISSUE TITLE
"Create Google Merchant Center Account" for Google Account with existing Google Merchant Center Accounts

### ISSUE THREAD

**Issue by strarsis** [woocommerce/google-listings-and-ads#1490]
### Describe the bug:
The setup assistant only offers a "Create Google Merchant Center Account" action after having connected to a Google Account that already has one or multiple Google Merchant Center Accounts.
I don't want to just try out what happens when I use "Create Google Merchant Center Account", because it may cause issues with the existing accounts...

### Steps to reproduce:

1. Start the setup assistant.
2. Connect to an existing Google account that already has one or multiple Google Merchant Accounts.
3. Note that the assistant now offers the "Create Google Merchant Center Account" action, but no Google Merchant Account selection.

### Expected behavior:
When the Google account already has Google Merchant Accounts, the setup assistant should show a list of these Google Merchant Accounts to select from.

### Actual behavior:
The setup assistant offers a "Create Google Merchant Center Account" action.

### Additional details:
The Google Merchant Account associated with the Google Account is a `multi-client account (MCA)`, 
the setup assistant should support it nonteheless.

**Comment by findingsimple** [comment]
Hi @strarsis GLA [does not currently support MCAs](https://woocommerce.com/document/google-listings-and-ads-faqs/#section-45) - it's on our radar but not prioritized.

Please [head over to our ideas board](https://ideas.woocommerce.com/forums/133476-woocommerce?category_id=403986) and post an idea for us to track popularity - if we get more requests we'll look into it. (excuse the spam in there I need to report it to an admin)

**Comment by strarsis** [comment]
Out of curiosity: What would happen if I connect to a MCA-using Google Account and hit the "Create Google Merchant account" in the setup assistant? 
Would this just cause an error by Google ("Google Merchant account (a MCA one) already exists"? Or would this interfere with the existing Google Merchant MCA account, e.g. somehow unlinking it with the Google account or overwriting it? 

And couldn't I link just one sub-account to an empty Google account somehow and use that with this plugin?

**Comment by mikkamp** [comment]
Hi @strarsis 

If you click "Create Google Merchant account" in the setup assistant it will create a new sub-account, of the WooCommerce MCA. A Google account can be connected to multiple merchant accounts so it will not interfere with any existing MCA's that the same Google account has access to.

As you mentioned the other alternative is to create a sub-account and link it to a Google account. The GLA extension lists all sub-accounts (non MCA) which the Google account has access to, so it will show up in the list of existing accounts. When choosing the existing sub-account in the GLA extension, it will create a new "eCommercePlatform" link to the WooCommerce MCA so it can be managed within the GLA extension (it will leave any existing links in place so it won't interfere with it's link to the original MCA).

**Comment by strarsis** [comment]
@mikkamp: Good to know. Though I already use a MCA Google Merchant Account, I would like to keep this structure.
I hope MCA support is added soon to this plugin!

**Comment by strarsis** [comment]
@mikkamp: I understood correctly that one Google Account can only have one single "normal" Google Merchant Account, right?
When one Google Account should manage multiple Google Merchant Accounts (like an agency for multiple customers), 
a MCA is required, right? Because I created a MCA because I was only able to manage one and only one single Google Merchant Account with my own Google Account, but then the need for multiple other Google Merchant Accounts arose.

**Comment by mikkamp** [comment]
A single Google account can be connected to multiple Merchant accounts. The option to create / connect a new merchant account is not available on the merchants dashboard. But it can be done through the API, for example if you use the Google Listings and Ads extension to create a new account.

**Comment by strarsis** [comment]
It would be great if this plugin adds native support for MCAs!

**Comment by strarsis** [comment]
@mikkamp: Any chances this could be addressed in the near future?

**Comment by mikkamp** [comment]
Hi @strarsis 

MCA support is still on our radar but not prioritized. I noticed there isn't any feature request for it yet here: https://woocommerce.com/feature-requests/google-listings-and-ads/

I would encourage to submit it as a feature request, as that helps us gauge how many people are interested.

**Comment by strarsis** [comment]
@mikkamp: Yes, I will create a feature request.

The main issue for me is that there is already a MCA account that was set up. I can't select that, I can only create a new one, and that one would be a duplicate for the same company and even if it is allowed, needs to be set up again, too.

**Comment by strarsis** [comment]
@mikkamp: So let's say I want to connect another Google Merchant account, but I don't want/can't wait for this plugin to add support for MCA. I would use this plugin which uses the API to create a new Google Merchant account - even if my Google account already has a MCA, right? So what happens with the MCA? Will it be removed? Will it disappear from the Dashboard (which doesn't support multiple accounts) and replaced by the newly created one? Will both Google Merchant account co-exist, but can't both be managed using the Dashboard? I need to follow through an approval and setup process for a Google Merchant account, this cannot be done using the plugin I strongly assume here.

**Comment by mikkamp** [comment]
> I would use this plugin which uses the API to create a new Google Merchant account - even if my Google account already has a MCA, right?

Yes it would create a separate account, which would be a sub-account of the WooCommerce MCA.

> So what happens with the MCA? Will it be removed?

It will stay as is.

> Will it disappear from the Dashboard (which doesn't support multiple accounts) and replaced by the newly created one?

It doesn't make it easy to create multiple accounts through the dashboard, but it does support multiple accounts. At the top left you will have an account selector (similar to how you can switch accounts within your MCA).
![image](https://user-images.githubusercontent.com/11388669/207007613-307ded91-1577-4df1-a2f2-4d588ed339a7.png)

For a scenario like this I would recommend to create another Google account to keep management separate, but that's not strictly required.
