### ISSUE TITLE
Ability to map attributes to Google's attributes

### ISSUE THREAD

**Issue by datapaganism** [woocommerce/google-listings-and-ads#1506]
## User story

It would make this integration extremely powerful to be able to link attributes and variations to Google's standards so products no longer get suspended after importing

### Describe the solution you'd like 

A new menu that would ask the user what attribute they want to link to a drop down of the Google equivalent ones (e.g Colour to g:color).

Set default attributes like MPN and GTIN if applicable, etc.

### Describe alternatives you've considered 

Use of external plugin feed generators however those require subscriptions for features (like not exporting parent products of variations)

**Comment by mikkamp** [comment]
Thanks for the report @datapaganism, although this request is covered by issue #572. We also have issue #15 to cover bulk updating product attributes.

I'm going to close this issue in favour of the linked issues, but feel free to add any points we might be missing there. We currently don't have a specific timeline when either will be implemented but it's on the list.

There is also a matching idea on the [ideas board](https://ideas.woocommerce.com/forums/133476-woocommerce/suggestions/43899639-add-attribute-mapping-to-google-listings-and-ads-s) where you might want to cast your vote.
