### ISSUE TITLE
Expand supported promotion country list for 4 more countries

### ISSUE THREAD

**Issue by chennyxie** [woocommerce/google-listings-and-ads#1509]
The promotion sync on Google surface now is open for in total 5 coutnries:
https://developers.google.com/shopping-content/reference/rest/v2.1/promotions?hl=en

Our promotion sync supported countries can match all the countries by expanding the list here
https://github.com/woocommerce/google-listings-and-ads/blob/e17daaf1526493eeac1febce6b8d60f57b9ffe0f/src/Google/GoogleHelper.php#L1202

## Technical
the country to currency mappings:
CA-> CAD
IN-> INR
AU->AUD
GB->GBP

These countries accept language 'en' ( the locale), which had better to be tested.

**Comment by findingsimple** [comment]
Thanks @chennyxie
