### ISSUE TITLE
PHP Error: ShoppingPerformanceView not found

### ISSUE THREAD

**Issue by rubileandro** [woocommerce/google-listings-and-ads#1519]
### Describe the bug:
From Marketing -> Google Listings & Ads, it doesn't show reports but gives an error:
"We're having trouble loading this data. Try again later, or track your performance in Google Ads."
![image](https://user-images.githubusercontent.com/93342175/169829016-a71f25d0-efdc-46f0-b347-04904d1b69a3.png)
![image](https://user-images.githubusercontent.com/93342175/169829039-2c540373-6cda-44ed-9c70-8bb5996a3cc2.png)

PHP Error:
2022-05-23T12:06:14+00:00 CRITICAL Uncaught Error: Class "Google\Ads\GoogleAds\V9\Resources\ShoppingPerformanceView" not found in /home/username/public_html/wp-content/plugins/google-listings-and-ads/vendor/google/protobuf/src/Google/Protobuf/Internal/Message.php:824

### Steps to reproduce:
On a site with Paid Ads running and connected to Google Listings & Ads version 1.13.0: 
1. Navigate to Marketing -> Google Listings & Ads
2. Select most recent month.

### Expected behavior:
Report shown for dates selected.

### Actual behavior:
From Marketing -> Google Listings & Ads, it doesn't show reports but gives an error:
"We're having trouble loading this data. Try again later, or track your performance in Google Ads."

### Additional details:
Error occurs when using version 1.13.0.
When rolling back to version 1.12.8 it works.

**Comment by mikkamp** [comment]
Thanks for the report, I'm able to reproduce this. It's related to #1495
Working on a fix.
