### ISSUE TITLE
Woo Policy Compliance Checks Links Update

### ISSUE THREAD

**Issue by sukafia** [woocommerce/google-listings-and-ads#1530]
## User story

When setting up the extension, the checklists to ensure merchants meet Google Merchant Center requirements such as "My store is live and accessible to all users", etc, currently link to Google merchant center documentation. 

We recently created a dedicated [Woo doc](https://woocommerce.com/document/google-listings-and-ads/compliance-policy/) for this that provides additional information on how to ensure these requirements are met on the WordPress/woo side.

As such, the links in the documentation need to be updated to reflect the links on this documentation page: https://woocommerce.com/document/google-listings-and-ads/compliance-policy/

(Each section has anchor links to copy and replace the link for the section on the setup page)

**Comment by findingsimple** [comment]
Thanks @sukafia 

FYI @garymurray @j111q

**Comment by j111q** [comment]
👍 @dominiquevias could you make sure the links in Figma are also updated with this new doc article? Thank you!

**Comment by findingsimple** [comment]
@jorgemd24 I'll assign this one to you

**Comment by jorgemd24** [comment]
@jconroy, @sukafia 

Just to double confirm, the links that need to be updated are the ones shown in the following image, and the rest of the "Read more" in the helper sections. 

![image](https://user-images.githubusercontent.com/2488994/171136501-1b08dc47-29b5-4444-9f18-735fe4b554a2.png)

Is this correct?

**Comment by nikivias** [comment]
@jorgemd24 if i could chime in. left link leads to main article. "learn more" jumps to respective section in the main article. (ignore dotted line in image)

<img width="990" alt="Screen Shot 2022-05-31 at 5 12 30 PM" src="https://user-images.githubusercontent.com/99638528/171138968-b692be57-1144-498b-ac45-2e1212e338df.png">

**Comment by jorgemd24** [comment]
Thanks, @dominiquevias, my confusion is: would we like to update the links in the current Pre-launch checklist design (like it shows in my image) or will this only affect to the new design like it is shown in your image? As far as I know, the new design is not developed yet.

I have created a draft PR updating the links using the current design: https://github.com/woocommerce/google-listings-and-ads/pull/1537, I think it is good to provide more information anyway until the new design is ready. 

cc: @jconroy

**Comment by nikivias** [comment]
@jorgemd24 Ah got it. Did we used to have a Read more link to each tooltip before or are we only doing this now?

Looking at the current design (your image) the same links in the newly published article will still be appropriate for the places you highlighted. Agree that it would be good to provide more info.

**Comment by jorgemd24** [comment]
@dominiquevias, 

>Did we used to have a Read more link to each tooltip before or are we only doing this now?

Only the second option "I have a complete and secure checkout process." had a "Read more". I added the "Read more" to the rest of the tooltips in the PR https://github.com/woocommerce/google-listings-and-ads/pull/1537 as I saw that we could link each tooltip to its appropriate link in [Woo Docs](https://woocommerce.com/document/google-listings-and-ads/compliance-policy/). 

![image](https://user-images.githubusercontent.com/2488994/171147919-bcc9221c-2f05-4359-aced-b94706b855fb.png)


>Looking at the current design (your image) the same links in the newly published article will still be appropriate for the places you highlighted

Correct 👍

**Comment by sukafia** [comment]
> @jconroy, @sukafia
> 
> Just to double confirm, the links that need to be updated are the ones shown in the following image, and the rest of the "Read more" in the helper sections.
> 
> ![image](https://user-images.githubusercontent.com/2488994/171136501-1b08dc47-29b5-4444-9f18-735fe4b554a2.png)
> 
> Is this correct?

Yes, your understanding is correct! The links will still be appropriate for the new design and we'll constantly update the doc to reflect any changes. Thank you @dominiquevias for the prompt assistance. 

>Only the second option "I have a complete and secure checkout process." had a "Read more". I added the "Read more" to the rest of the tooltips in the PR https://github.com/woocommerce/google-listings-and-ads/pull/1537 as I saw that we could link each tooltip to its appropriate link in [Woo Docs](https://woocommerce.com/document/google-listings-and-ads/compliance-policy/).

That makes a lot of sense. Thank you so much!
