### ISSUE TITLE
Error getting account review status

### ISSUE THREAD

**Issue by mikkamp** [woocommerce/google-listings-and-ads#1545]
### Describe the bug:
We are getting several reports of users getting the error that they can't retrieve their account review status:
- 5256564-zen
- [Forum post](https://wordpress.org/support/topic/there-was-an-error-loading-your-merchant-center-product-review-request-status/)
- [Forum post](https://wordpress.org/support/topic/there-was-an-error-loading-your-merchant-center-product-review-request-status-2/)

In the UI just a generic message is shown, but the log files show a more specific error:
```
2022-05-31T21:27:51+00:00 ERROR Automattic\WooCommerce\GoogleListingsAndAds\API\Google\Middleware::get_account_review_status
Client error: GET https://api-vipgo.woocommerce.com/google/manager/account-review-status/<accound-id> resulted in a 400 Bad Request response:
{“statusCode”:400,”error”:”Bad Request”,”message”:”User cannot access account <account-id>"}
```

The request for the account review status is a proxied request because the API requires privileged access. However this means that we can only request these for child accounts (accounts created through the extension). Based on the error messages, it looks like these are all standalone accounts which have been linked. Which doesn't provide enough access permissions to perform a proxied request.

### Steps to reproduce:
1. Go through the onboarding using a standalone account
2. Once redirected to the product feed page, observe the error that the account review status can't be retrieved
3. Go to WooCommerce > Status > Logs and view the log file to confirm the detailed error

### Expected behavior:
I'd expect the review status / request to be unavailable for users with a standalone account. I'd expect this to happen silently in the background and it shouldn't affect any followup requests or prevent syncing from happening.

### Additional details:
It seems the error is followed by:
```
2022-05-31T21:43:25+00:00 ERROR Automattic\WooCommerce\GoogleListingsAndAds\Product\ProductSyncer::validate_merchant_center_setup Cannot sync any products before setting up Google Merchant Center.
```

I'm not able to fully reproduce this scenario but since we are getting a 400 error returned, it looks like it's triggering the reconnect code which means their site will not be ready for syncing products.

**Comment by ianlin** [comment]
@mikkamp Thanks for reporting this issue.

> However this means that we can only request these for child accounts (accounts created through the extension). Based on the error messages, it looks like these are all standalone accounts which have been linked. Which doesn't provide enough access permissions to perform a proxied request.

I'm not quite sure what's a "standalone account", does it mean it's an account created outside of the extension, like creating from the Google merchant centre directly?

**Comment by mikkamp** [comment]
> does it mean it's an account created outside of the extension, like creating from the Google merchant centre directly

Yes it's exactly that. We don't have a lot of requests which we proxy through the manager account (Merchant Account), the only other one is "claim website (with override enabled", but that's not possible for users that connected with a "standalone account". So same scenario here, which we seem to have overlooked.

**Comment by mikkamp** [comment]
Summary of our discussion:

There are 2 main issues we are seeing from these reports.

1\. Standalone accounts are unable to retrieve the account review status. The API endpoint needs special permissions, which is enabled on our manager account, but we can only request it for child accounts. This results in the error that the account can't be accessed (should be interpreted as the manager account does not have access to this standalone account).

As a short-term fix we are working on hiding/ignoring this error so it doesn't confuse anyone (it will still show up in the logs).

In the long term we will need to handle stand-alone accounts differently, since they can only request an account review in the Merchant Center dashboard. So we might need to give them a different dialog then showing the request account review button.

2\. The second issue was related to the transient which compares the site URL. If the site was disconnected (before onboarding was completed), it was being saved too early. Which resulted in the product sync only starting 12 hours after onboarding completed.

This has been fixed in #1546

**Comment by ecgan** [comment]
> 1\. Standalone accounts are unable to retrieve the account review status. [...]
> 
> As a short-term fix we are working on hiding/ignoring this error so it doesn't confuse anyone (it will still show up in the logs).

The short-term fix to hide the error notice is ready in PR https://github.com/woocommerce/google-listings-and-ads/pull/1547.

**Comment by felipevelzani** [comment]
Likely related 5266050-zen

**Comment by puntope** [comment]
> Likely related 5266050-zen

@felipelousantos I guess that user is still having problems because is on version 1.13.3 instead of 1.13.4 which implements the fixes.
