### ISSUE TITLE
Create custom labels and add products

### ISSUE THREAD

**Issue by kevin25** [woocommerce/google-listings-and-ads#1568]
It would be perfect if we can Create custom labels right on the backend of WooCommerce and add the products instead of creating rules on Google Merchant Center.

**Comment by findingsimple** [comment]
Hi @kevin25 thanks for taking the time to post.

> It would be perfect if we can Create custom labels right on the backend of WooCommerce and add the products instead of creating rules on Google Merchant Center.

Would you mind heading over to [our ideas board](https://ideas.woocommerce.com/forums/133476-woocommerce?category_id=403986) and posting your suggestion? It'll help us keep better track of the popularity as others can vote.

If possible could you also take the time to clarify there what you mean by "custom labels" - perhaps some links to functionality in the Merchant Center docs.

Thank you!
