### ISSUE TITLE
WC 6.7 compatibility issue: navigation does not work in certain pages

### ISSUE THREAD

**Issue by ecgan** [woocommerce/google-listings-and-ads#1579]
### Describe the bug:

This issue arises from my WooCommerce 6.7 compatibility testing in issue https://github.com/woocommerce/google-listings-and-ads/issues/1577.

In certain pages such as Edit Free Listings, clicking on the "<" back navigation button in the plugin does not do anything. Same with clicking on the browser's back button. Clicking on the "Continue" button in the Edit Free Listings Step 1 does not bring the user to Step 2.

In addition, clicking on some other WC menu items below does not do anything too:

- WooCommerce
- WooCommerce > Home
- WooCommerce > Customers
- Analytics
- Analytics > All menu items.

This might be related: the above URLs share the same URL pattern: `/wp-admin/admin.php?page=wc-admin&path=<...>`. 

Note that this issue only happens in WC 6.7.0 beta 1 and beta 2. If we roll back to version 6.6, it works as expected. WC version switching is done by using [WooCommerce Beta Tester](https://wordpress.org/plugins/woocommerce-beta-tester/). I tested this with https://github.com/woocommerce/google-listings-and-ads/releases/tag/1.13.6.

📹 See demo video below with my voice annotation:

https://user-images.githubusercontent.com/417342/176746047-e89ccafe-3e82-49bc-b0a8-edcb7ad75b5a.mov

### Steps to reproduce:

1. Use WC 6.7 beta 1 or beta 2.
2. Go to Edit Free Listings page. 
3. Click on the back button on the top left corner. Nothing happens.
4. Click on WooCommerce or Analytics pages. Nothing happens.

### Expected behavior:

There should be page navigation when we click on the button or menu items.

### Actual behavior:

Nothing happens when we click on the button or menu items.

**Comment by puntope** [comment]
I was doing some testing and I also cannot click on "continue" button in the plugin 🤔 

<img width="1367" alt="Screenshot 2022-07-01 at 13 20 24" src="https://user-images.githubusercontent.com/5908855/176866360-2ece2b5d-d680-4943-af86-be838296eedb.png">

I'm still investigating

**Comment by puntope** [comment]
Seems like definitely something related with `getHistory().push` function. Its just not working. 

Im still investigating what changed on WC 6..6 Wc 6.7 Regarding that

**Comment by ecgan** [comment]
@puntope , thanks for looking into this. Since we have WC version 6.7.0 beta 1 that is known to have the issue and version 6.6 that works fine, we can make use [git bisect](https://git-scm.com/docs/git-bisect) to find out the exact commit that introduces the bug.

Note that this would require you to have WC development environment setup in your local machine. Also, WC 6.6 was using nx, and WC 6.7 now uses turborepo, which are different development build tools. Something for you to take note of. 😄

**Comment by puntope** [comment]
> @puntope , thanks for looking into this. Since we have WC version 6.7.0 beta 1 that is known to have the issue and version 6.6 that works fine, we can make use [git bisect](https://git-scm.com/docs/git-bisect) to find out the exact commit that introduces the bug.
> 
> Note that this would require you to have WC development environment setup in your local machine. Also, WC 6.6 was using nx, and WC 6.7 now uses turborepo, which are different development build tools. Something for you to take note of. 😄

Hey thanks, Git bisect wont be necessary. I have already localised the root of the problem in `useNavigateAwayPromptEffect` hook. Maybe something changed in WOO Navigation API having a conflict with that.
