### ISSUE TITLE
Implement new E2E environment once its ready in Woo platform

### ISSUE THREAD

**Issue by tomalec** [woocommerce/google-listings-and-ads#1599]
## ~User~developer story
While [trying to add `admin-e2e-tests`](https://github.com/woocommerce/google-listings-and-ads/pull/1593), I encountered some problems with `e2e-environment` while trying to fix them I got notified that [`e2e-environment` is actually deprecated](https://github.com/woocommerce/woocommerce/pull/33828#issuecomment-1184729665), and there is a new solution being baked: https://github.com/woocommerce/woocommerce/tree/trunk/plugins/woocommerce/e2e, but still not ready for extensions yet.

Once, something ready and stable for extension use will appear, we'd better implement it, as probably by that time, our dependencies will get pretty far behind.

### Is your feature request related to a problem? 

We cannot update Jest to `28`, due to `e2e-environment` dependencies problems

#### How to reproduce the problem

See https://github.com/woocommerce/woocommerce/pull/33852, https://github.com/woocommerce/woocommerce/pull/33828, https://github.com/woocommerce/woocommerce/pull/33827

### Describe the solution you'd like 

Wait for an E2E solution with clear setup instructions to be prepared, for the Woo extensions. Then just follow the instructions to implement it.

### Describe alternatives you've considered 

1. Revive `e2e-environment` by trying to push updates and fixes there
2. Try adopting Playwright solution today

## Unknowns

- When the new solution would be released for external use?
- We would have to balance the costs of additional effort for early adopting & contributing to the platform and working with stale, legacy, non-supported `e2e-environment`

**Comment by findingsimple** [comment]
> https://github.com/woocommerce/woocommerce/tree/trunk/plugins/woocommerce/e2e, but still not ready for extensions yet.

I can't find that now

Update - [Found this thought](https://github.com/woocommerce/woocommerce/tree/fddee1a237ae0c79a96513aa8ba24c398a520ed8/plugins/woocommerce/e2e)

~@tomalec is there an internal project you can point me to, I can't seem to find anything~

Ok I think I found some recently closed ones that are likely related

pcr5Cj-3bw-p2

**Comment by tomalec** [comment]
But so far, it's all for `woocommerce/woocommerce` nothing stable for extensions
