### ISSUE TITLE
Add filter to disable event tracking

### ISSUE THREAD

**Issue by alewolf** [woocommerce/google-listings-and-ads#1609]
### Is your feature request related to a problem? 

There are users of the Google Listings and Ads plugin that want to use different plugins for tracking than the integrated one in the Google Listings and Ads plugin. Such a third party tracking plugin is the [Pixel Manager for WooCommerce](https://wordpress.org/plugins/woocommerce-google-adwords-conversion-tracking-tag/) (of which I am the developer of). There are numerous advantages in using a third party plugin like the Pixel Manager for WooCommerce over the integrated tracking. I'll be happy to explain that in more detail if you require me to. 

In order to be able to use the Google Listings and Ads plugin together with the Pixel Manager for WooCommerce it would be great if you could add a filter with which the customer (or the Pixel Manager) could deactivate the integrated tracking in the Google Listings and Ads plugin. 

Could you add such a filter?

**Comment by mikkamp** [comment]
As of now (version 2.0.2) the only tracking included in the plugin is a purchase event which gets sent to the linked Ads account. However there is the "soon to be released" PR #1556 which includes additional tracking including events which are triggered by the WooCommerce Gutenberg blocks. Can you clarify if the built in tracking would be disabled, would it provide equivalent tracking directly to the linked Ads account?

The way it's implemented in the plugin, a conversion action is created automatically so tracking is performed without needing any setup. The built in tracking also uses a `send_to` field to link it to the Ads account and ensure it doesn't conflict with other tracking going to a GA4 property. I see that your plugin also supports tracking to an Ads account (which could potentially conflict). Would you be able to clarify a bit more in which cases you would turn off the built in tracking, and how it conflicts?

**Comment by alewolf** [comment]
> Can you clarify if the built in tracking would be disabled, would it provide equivalent tracking directly to the linked Ads account?

Yes, my plugin would provide equivalent tracking directly to the Google Ads account. The user simply has to add the conversion settings for that specific conversion from Google Ads to my plugin, the Pixel Manager for WooCommerce (PMW). From then on all events will be tracked (add_to_cart, view_item, purchase, etc.)

> The built in tracking also uses a `send_to` field to link it to the Ads account and ensure it doesn't conflict with other tracking going to a GA4 property.

That is great! Not many implementations do the same. My plugin, the Pixel Manager, also uses the `send_to` field for all Google properties (Google Ads, Universal Analytics and GA4). That way it can't pollute other properties if a user chooses to only use Google Ads in my plugin and for Google Analytics the WooCommerce Google Analytics plugin for example. 

> Would you be able to clarify a bit more in which cases you would turn off the built in tracking, and how it conflicts?

Sure. The logic would be the following: If a user of my plugin enables Google Ads in my plugin (using the same conversion ID and conversion label), it would automatically disable the tracking in your plugin (using a the requested filter). 

Does that answer all your questions?

**Comment by puntope** [comment]
Howdy @alewolf For requesting features we use 

https://woocommerce.com/feature-requests/google-listings-and-ads/ and then you can click on "View and submit feature requests" in order to suggest a feature like this. 

We analyse frequently there which features are the most demanded by the marke  in order to analysing costs and investing time on them. 

You can ofc reference this issue there in the feature request :)

**Comment by alewolf** [comment]
@puntope Ok. Done. I hope it will get some attention. Obviously, this is not something that many will upvote. But, it should be simple to implement.

**Comment by mikkamp** [comment]
Thanks for the patience, we've had some internal discussion about the impact of such a filter. The main concern is that the filter isn't just enabled without any replacement solution, as this could result in a negative impact on Google's prediction engine. So the ask is to only enable the filter if replacement tracking has been enabled.
PR should be incoming soon.

**Comment by alewolf** [comment]
> So the ask is to only enable the filter if replacement tracking has been enabled.

Oh yes. Absolutely. I wouldn't do it any other way. 

> PR should be incoming soon.

Wonderful. Thanks !

**Comment by alewolf** [comment]
@mikkamp Thanks for implementing this!

I've already added the new filter to the [Pixel Manager for WooCommerce](https://wordpress.org/plugins/woocommerce-google-adwords-conversion-tracking-tag/) and will release it with the upcoming version.

**Comment by mikkamp** [comment]
👍🏻️ The filter isn't included in a release yet, but it will be included next time we release, most likely version 2.1.1
