### ISSUE TITLE
Change Google-related logos to the generic G logo

### ISSUE THREAD

**Issue by j111q** [woocommerce/google-listings-and-ads#1644]
### Describe the bug:
The Googlers have flagged to us that we should use the generic G logo rather than the Shopping tag logo or the Ads logo. 
We need to change the [wordpress.org plugin page](https://wordpress.org/plugins/google-listings-and-ads/) to the G logo. 

We should also double check our plugin to ensure there are no other Google-related logos anywhere.

### Generic G logo:
Download assets here: https://www.dropbox.com/sh/jiorzn7k2tk01gt/AAC_VevHZhbOHK3YG_iZkhBJa?dl=0

**Comment by puntope** [comment]
Howdy @j111q 

The png files are good. 

However, I see in wordpress_org_assets folder we have discussed the next inconsistencies:

icon.svg -> 128x128 with bakground white 
icon-no-bg.svg -> 128x128 with no background

In the dropbox only a big version with no background was provided

**Comment by j111q** [comment]
I see okay, I've exported two more assets at the [same dropbox link](https://www.dropbox.com/sh/jiorzn7k2tk01gt/AAC_VevHZhbOHK3YG_iZkhBJa?dl=0).

google-icon-with bkground.svg -> 128 x 128 with bkground
google-icon-without bkground.svg -> 128x128 without bkground

Let me know if that works! Thanks @puntope!

**Comment by puntope** [comment]
Thanks @j111q  for the fast changes!  

I added manually thw width and height to the svg. And also croped 1 px in the 128px icon (shomehow it was 129x128) 

I created already a PR
