### ISSUE TITLE
Request Review - Customer stuck in Pending review

### ISSUE THREAD

**Issue by puntope** [woocommerce/google-listings-and-ads#1646]
### Describe the bug:

This is a follow up issue in rgeards a customer who is blocked in PENDING status for a single region. 
The user initially had an issue with NO_OFFERS_UPLOADED that was a bug in Google side and is solved already.
However, after that the IL (Israel) region is stuck in PENDING review. 

### Additional details:

Related Slack thread: p1656394787282569-slack-C7U3Y3VMY
We are syncing with google in order to solve this issue.  And I will post updates here.

**Comment by puntope** [comment]
Update from Google. They say that this customer has not Israel as a target (IL, the region is giving problems)

Can you confirm which targets are being used by the customer?

**Comment by puntope** [comment]
Update from google Eng team:

"We identified this is appearing for us too when we make the same call for this merchant, we are escalating this internally to identify why this is happening. Thanks for flagging!"

**Comment by anant1811** [comment]
Hi team, just an update that the message on customer's site has now changed to `No products added - Add and sync products to Google.`

They have also mentioned:

>All my products are showing as synched and approved under the product feed tab. I have zero clicks from the free listings, which leads me to believe that the products are, in fact, not showing up on search.

**Comment by puntope** [comment]
> All my products are showing as synched and approved under the product feed tab. I have zero clicks from the free listings, which leads me to believe that the products are, in fact, not showing up on search.

Afraid thats true. One think is that the products are synced to google. Hence they show in product feed. With their potential errors at product level.

Other different thing is the account issues. These are the ones the user is suffering. Not because the plugin... also you can see that in Merchant center since is a Google level issue.

Until both account and products are correct he won't see the products listed.

**Comment by puntope** [comment]
I however can get right now the account APPROVED (via API call using the user MCID). So I suggest to check again and otherwise re-sync all the products to see if that solves the problem

**Comment by puntope** [comment]
This seems to be closed for me.
 
explanation about what happened from Google:

_"In summary, the country `IL` was being shown because that country had been targeted by offers within the past 30 days. Since there are no longer any offers targeting `IL` and it has been greater than 30 days, the country should no longer be showing the `PENDING_REVIEW` state. The state for this country was erroneously labeled as "PENDING_REVIEW" even though a review was not pending, due to a recent launch which doesn't require offers to be reviewed before serving impressions. Our team is working to ensure that offer countries don't end up in this state in the future."_
