### ISSUE TITLE
Inconsistencies in frontend Page Struture

### ISSUE THREAD

**Issue by puntope** [woocommerce/google-listings-and-ads#1647]
Checking the frontend code in GLA I can see there is a folder named `pages`. In this folder I see `reports`, `edit-paid-ads-campaign` and `create-paid-ads-campaign`

However other pages like `product-feed` and `get-satrted` have their own directory and are not present in `pages`directory.

This made me think about 2 questions:

1. Which is the convention in order to create new pages? Locate the index in pages or in their own directory?
2. After discussing 1. Should we refactor the current implementation to be consistent?

**Comment by tomalec** [comment]
This is a result of incomplete https://github.com/woocommerce/google-listings-and-ads/issues/195

**Comment by puntope** [comment]
Added low priority & refactor tags
