### ISSUE TITLE
WC 6.9 Compatibility: Cannot update target audience and shipping times when editing free listing

### ISSUE THREAD

**Issue by ianlin** [woocommerce/google-listings-and-ads#1651]
### Describe the bug:

This bug was found when doing WooCommerce `6.9` compatibility test. When editing free listing, the target audience and the shipping times cannot be updated successfully. It works as expected when using WC `6.8.2`.

### Steps to reproduce:

1. Use GLA `2.1.0` and WooCommerce `6.9.0-beta.2`, download from [here](https://developer.woocommerce.com/2022/08/24/woocommerce-6-9-beta-2/).
2. In the onboarding setup, choose two selected countries only, e.g. US and TW.
3. Finish the onboarding setup.
4. In GLA dashboard, click `Edit` of free listings program.
5. Choose `All countries` for the audience.
6. In the shipping times, we cannot add shipping times for countries other than US and TW.
7. Save changes and edit free listings again, the target audience is still US and TW.
8. Using latest stable WC `6.8.2`, both can be updated successfully.

### Expected behavior:

The target audience and the shipping time can be updated when editing free listings.

Video of using WC `6.8.2`:

https://user-images.githubusercontent.com/914406/186616174-07a1b350-7d76-419c-b4e7-bb3d897af945.mov

### Actual behavior:

The target audience and the shipping time cannot be updated.

Video of using WC `6.9.0-beta.2`:

https://user-images.githubusercontent.com/914406/186616769-4216d8ed-0030-47ee-845b-b27dde334177.mov

**Comment by eason9487** [comment]
Reported to WooCommerce repo: https://github.com/woocommerce/woocommerce/issues/34584

**Comment by eason9487** [comment]
This issue has been fixed with https://github.com/woocommerce/woocommerce/pull/34614 and https://github.com/woocommerce/woocommerce/pull/34626 and should be included in the final release of WooCommerce 6.9. We may not need to fix it from GLA.

**Comment by eason9487** [comment]
> This issue has been fixed with [woocommerce/woocommerce#34614](https://github.com/woocommerce/woocommerce/pull/34614) and [woocommerce/woocommerce#34626](https://github.com/woocommerce/woocommerce/pull/34626) and should be included in the final release of WooCommerce 6.9. We may not need to fix it from GLA.

Confirmed these fixes are included in the released WC 6.9.
