### ISSUE TITLE
request_phone_verification rateLimitExceeded

### ISSUE THREAD

**Issue by findingsimple** [woocommerce/google-listings-and-ads#1660]
### Describe the bug:

Merchant in ticket  5498211-zen is seeing a rate limit error when attempting to verify phone number

```
2022-08-22T13:10:19+00:00 ERROR Automattic\WooCommerce\GoogleListingsAndAds\API\Google\Merchant::request_phone_verification {
"error": {
"code": 429,
"message": "Retries quota exceeded.",
"errors": [
{
"message": "Retries quota exceeded.",
"domain": "global",
"reason": "rateLimitExceeded"
}
],
"status": "RESOURCE_EXHAUSTED",
"details": [
{
"@type": "type.googleapis.com/google.rpc.ErrorInfo",
"reason": "quotaExceeded",
"domain": "usageLimits"
}
]
}
}
```

Creating an issue to capture and I will follow up with Google in our Q&A doc - I haven't see this before.

**Comment by eason9487** [comment]
The rate limit is a part of Google's verification API. A maximum of five attempts to verify the same phone number every four hours. If the user exceeds this rate limit, UI will display the relevant error message.

![image](https://user-images.githubusercontent.com/17420811/187586703-228e7892-ce96-446d-849f-867f8bf5349d.png)

Ref: #1022

**Comment by findingsimple** [comment]
aha thank you @eason9487 for educating me!
