### ISSUE TITLE
Consistent URL to redirect to from external location

### ISSUE THREAD

**Issue by mikkamp** [woocommerce/google-listings-and-ads#1668]
## User story

If we want to redirect a user to a page within GLA we currently only have the option of redirecting them to:

- `?page=wc-admin&path=/google/dashboard`
- `?page=wc-admin&path=/google/start`

Which page to redirect them to depends on the state of onboarding, however if we are redirecting form an external source we don't know the onboarding state. This is relevant to cases where we want to provide a landing URL from a [remote inbox notification](https://github.com/woocommerce/woocommerce-admin/tree/main/src/RemoteInboxNotifications#readme).

So we would either need one consistent landing page, or alternatively have the `/google/dashboard` link automatically redirect to `/google/start` if onboarding hasn't completed yet. Currently when you visit the wrong URL you are shown an access denied message:

![image](https://user-images.githubusercontent.com/11388669/188608038-c95d67f7-15f8-482c-b9c5-95fe753223ed.png)

### Describe the solution you'd like 
One consistent URL to link to without getting any error pages.

### Describe alternatives you've considered 
One alternative suggestion was to link to `?page=wc-admin&path=/marketing` but this is less than ideal since it can show many extensions in this list.

**Comment by findingsimple** [comment]
I'll mark this as a big with high priority - I thought in very early implementation we did have a redirect happening.
