### ISSUE TITLE
Login Issue

### ISSUE THREAD

**Issue by haja-rimrubber** [woocommerce/google-listings-and-ads#1676]
Dear Team,

I am Haja from RimRubber.com we are using Google listing & ads plugin for google merchant center. We noticed sometimes google account automatically disconnected which is linked with google listing and ads plugin. Today we try to reconnect again by mistake we connect wrong google account we want login again with correct one, but whenever we choose Google listings and Ads option in WordPress dashboard area there only loading icon displayed we are not able to login or cancel.

Please advise.. Thank you

<img width="1374" alt="sample" src="https://user-images.githubusercontent.com/110378195/190381202-8df924a9-dae8-4b93-a344-3b2bd9e9210a.png">

**Comment by mikkamp** [comment]
Hi Haja,

This repository is not intended for support requests. The best place to start the process is with the [WordPress.org Google Listings and Ads forum](https://wordpress.org/support/plugin/google-listings-and-ads/) or if you have a WooCommerce.com account, you can start a chat or open a ticket on [WooCommerce.com support](https://woocommerce.com/my-account/create-a-ticket/). I'd suggest to include your [system status report](https://woocommerce.com/document/understanding-the-woocommerce-system-status-report/#system-status) as well as additional details to reproduce the issue.

The support team will help guide you through some problem solving and get some more information to give us a bit more context/background on your concerns/report above.
