### ISSUE TITLE
Customize the AccountStatus -> accountLevelIssues for website not claimed title and support link

### ISSUE THREAD

**Issue by dardardardardardar** [woocommerce/google-listings-and-ads#1688]
### Describe the bug:

Google changed how they check website verification on an ongoing basis. Once we identify a website is not verified, google send an email to warn the merchant they need to verify and claim their website. If they don't verify, they get an account issue which appears informing the merchant they need to claim their website. This current account issue directs the merchant to MC to fix, but we want to change it so it is clear to the Woo merchant they can before the verification + claim in the woo platform.

**Before the change:** It was possible for a merchant to successfully verify and claim their site through our onboarding, and then lose that verification (for example, if they've changed their store URL, or[ see other reasons here](https://support.google.com/merchants/answer/7527436)), yet the store would still be claimed.

**After the change:** Google launched a new feature in early August that will periodically check if a store's verification is still valid. Merchants who are found to have invalid verifications will then receive emails telling them to re-verify their sites, and they have up to 60 days before their claims are lost and their products are no longer listed on Google's surfaces.

### Steps to reproduce:

1. Merchant doesn't verify their website, they will get an email from Google merchant center asking to claim their website
2. If merchant doesn't claim their website through the plugin after 60 days, they will get this account suspension (here)
![Screenshot 2022-09-12 1 54 39 PM](https://user-images.githubusercontent.com/114058615/191566323-96bc0f11-4997-4fd8-a93b-5ac83b00fd62.png)

### Expected behavior:

1. We want to change the accountLevelIssues to the following:

- Issue: Website claim is lost, need to re verify and claim your website. Please reference the support link 
- Support link: https://woocommerce.com/document/google-listings-and-ads-faqs/#reverify-website

**Comment by puntope** [comment]
Hello @dardardardardardar 

As far as I know we force to the user to claim the Website on plugin setup

<img width="693" alt="Screenshot 2022-09-22 at 12 58 33" src="https://user-images.githubusercontent.com/5908855/191705109-b559bd85-9dbb-4446-9823-37f3bd7b8000.png">

Besides that, if the user lost it. The account issue is shown as critical in the dashboard.

In regards the title and issue documentation is provided by Google directly. Could you elaborate what is exactly not clear in the current message and documentation link? Or it's just a preference in regards re-verifying from WooCommerce instead of using MC?

**Comment by mikkamp** [comment]
### Additional details
pcTzPl-ZC-p2

**Comment by dardardardardardar** [comment]
@puntope - We want to ensure the user re-verify and claim their website through the plugin if the claim is lost. 

For the current critical account level issue link when the claim is lost, The current [support link](https://support.google.com/merchants/answer/7527436?hl=en) gives more information but doesn't inform how to do this in the plugin. 

The current title account level issue (when claim is lost) is fine but we could add more information to ensure it's clear to do this in the plugin along with the correct [link](https://woocommerce.com/document/google-listings-and-ads-faqs/#reverify-website)
