### ISSUE TITLE
add brand to sync

### ISSUE THREAD

**Issue by davidhefti** [woocommerce/google-listings-and-ads#1709]
I am trying to sync product brand with merchant center.
This piece of code is not working. I will get "false" for brand attribute in Merchant center.

`add_filter( 'woocommerce_gla_product_attribute_values', 'add_yith_brand_to_gla', 10, 3 );

function add_yith_brand_to_gla( $attributes, $product, $adapter ) {
	$id = $product->get_id();
	$brand_names = wp_get_post_terms( $id, 'yith_product_brand', array( 'fields' => 'names' ) );
	$brand = reset( $brand_names );	
	$attributes['brand'] = $brand;
	return $attributes;
}`

Can anyone here help me with that?

**Comment by davidhefti** [comment]
sorry, it is working like that.
So maybe this could be a possible new feature for the future? Option to select the associated brand taxonomy to sync? (because it depends on the brands plugin...)

**Comment by mikkamp** [comment]
Thanks for confirming that the code is working. The functionality of mapping to custom attributes will be part of the [Attribute Mapping](https://github.com/woocommerce/google-listings-and-ads/issues/1648) which we are working on.

So I'll go ahead and close this issue.

**Comment by davidhefti** [comment]
Thank you for your answer and looking forward to the Attribute Mapping.
Unfortunately the above shared code is not fully working. For most of the items I will get brand "false" in the Merchant center... So if you have any idea what to improve in my snippet to get it working, let me know :-)

**Comment by mikkamp** [comment]
Not getting results for some of the brands would be something you would need to troubleshoot from your side. It sounds like the terms aren't assigned to those products like you are expecting. I'd suggest to just run `wp_get_post_terms` for those specific product ID's and see if you are getting the results you are expecting.

**Comment by davidhefti** [comment]
Got it. A brand is only assigned to the parent product and not to the variation. I did it like this.

```
add_filter( 'woocommerce_gla_product_attribute_values', 'add_yith_brand_to_gla2', 10, 3 );
function add_yith_brand_to_gla2( $attributes, $product, $adapter ) {
					if ( $product->is_type( 'simple' ) ) {
						$id = $product->get_id();
					}
					
					if ($product instanceof WC_Product_Variation) {
						$id = $product->get_parent_id();
					}
					
					$brands_taxonomy = YITH_WCBR::$brands_taxonomy;
					$brands          = get_the_terms( $id, $brands_taxonomy );
					if ( ! ! $brands ) {
						$brands_name = $brands[0]->name;
							$attributes['brand'] = $brands_name;
							return $attributes;
					}
}
```

**Comment by mikkamp** [comment]
Glad to hear you resolved it. Just one small comment, when you use `add_filter` you should always make sure to return the original value that is being filtered, otherwise you will be overriding the value with `null` since there is no return statement. In your case that would mean moving the `return $attributes` line outside of the `if` block.
