### ISSUE TITLE
Read more link for "No Google Ads account link" is 404

### ISSUE THREAD

**Issue by ilyasfoo** [woocommerce/google-listings-and-ads#1716]
### Describe the bug:
When clicking on "Read more about the issue", it goes to a 404 link https://support.google.com/merchants/answer/6159060.

<img width="650" alt="image" src="https://user-images.githubusercontent.com/3747241/193982354-010facc6-8360-4bad-9301-8a25c7863245.png">
<br>
<img width="650" alt="image" src="https://user-images.githubusercontent.com/3747241/193982436-0eb56132-85b4-4020-8626-fa54128d2e29.png">

### Steps to reproduce:

1. Connect Google Listing & Ads
2. Under "Issues to resolve", click on read more for "No Google Ads account linked"
3. Observe 404 apge

### Expected behavior:
A proper page linked

### Actual behavior:
404

**Comment by eason9487** [comment]
Hi @ilyasfoo, thanks for reporting this issue.

The link was provided by Google's API. I guess they were doing some migration so the link had been invalid for a while. After testing, I believe Google side has updated the link to https://support.google.com/google-ads/answer/6159060 and the new link works well now.

![Kapture 2022-11-04 at 16 55 17](https://user-images.githubusercontent.com/17420811/199933252-c26e3054-be5e-4c52-ab56-30658fef917f.gif)

I'll be closing this issue.
