### ISSUE TITLE
Plugin google account automatically disconnected

### ISSUE THREAD

**Issue by haja-rimrubber** [woocommerce/google-listings-and-ads#1726]
Hello there,

We recently update Google Listings and Ads v2.1.4. We noticed,
We connect google merchant account using Google Listings and Ads.
After sometime Google merchant account disconnected automatically.
Then we connect again, after sometime same thing happen its disconnected automatically. we don't know what is happen. can you please advise ?

**Comment by mikkamp** [comment]
Hi Haja,

This repository is not intended for support requests. The best place to start the process is with the [WordPress.org Google Listings and Ads forum](https://wordpress.org/support/plugin/google-listings-and-ads/) or if you have a WooCommerce.com account, you can start a chat or open a ticket on [WooCommerce.com support](https://woocommerce.com/my-account/create-a-ticket/). I'd suggest to include your [system status report](https://woocommerce.com/document/understanding-the-woocommerce-system-status-report/#system-status) as well as additional details to reproduce the issue.

The support team will help guide you through some problem solving and get some more information to give us a bit more context/background on your concerns/report above.

**Comment by haja-rimrubber** [comment]
Hello mikkamp,

I though it was bug thats why i mentioned here, sorry for that.

**Comment by haja-rimrubber** [comment]
Hello there,

Can you open this issue please ?  I think its a bug

https://wordpress.org/support/topic/plugin-google-account-automatically-disconnected/#post-16098235

Some others also facing this issue
