### ISSUE TITLE
Shipping rates for 'Product Bundles' are always sent over to Google regardless of the setting "Shipping rates"

### ISSUE THREAD

**Issue by prnvrna** [woocommerce/google-listings-and-ads#1738]
### Describe the bug:
Shipping rates for 'Product Bundles' are always sent over to Google regardless of the setting "Shipping rates". Other product types work as expected.

### Steps to reproduce:

1. Create a Product Bundle with all mandatory sub-products.
2. Now, In Google Listing extension's setting, set "Shipping rates" to "My shipping settings are complex. I will enter my shipping rates and times manually in Google Merchant Center."
3. Let the products sync. Open the product in Google Merchant account; you'll see a message *"You configured the shipping rate for this product by submitting the 'shipping' attribute in your product data. If you configured an account-level shipping rate in your shipping settings, it won't apply to this product."*. The 'shipping price' attribute is being sent in this case, and is overwriting the user's set shipping preferences in the Merchant account.
4. Whereas, for other product types, the shipping price attribute won't be supplied.

*Issue screencast: https://d.pr/v/2xANmR*

### Expected behavior:
Product Bundles should implement shipping functionality similar to other product types.

### Actual behavior:

For product bundles, 'shipping price' attribute is sent over to Google Merchant account overwriting user's main shipping price settings.

*Reference screenshot: https://d.pr/i/ZpLAq5*

### Additional details:

*Issue reported here: 37537703-hc, 5648625-zen (same user)*

### SSR:
<details>
### WordPress Environment ###

WordPress address (URL): https://bhadra.mystagingwebsite.com
Site address (URL): https://bhadra.mystagingwebsite.com
WC Version: 7.0.0
REST API Version: ✔ 7.0.0
WC Blocks Version: ✔ 8.5.1
Action Scheduler Version: ✔ 3.4.0
Log Directory Writable: ✔
WP Version: 6.0.3
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: nginx
PHP Version: 8.0.24
PHP Post Max Size: 2 GB
PHP Time Limit: 1200
PHP Max Input Vars: 6144
cURL Version: 7.85.0
OpenSSL/1.1.1n

SUHOSIN Installed: –
MySQL Version: 10.4.25-MariaDB-log
Max Upload Size: 2 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.0.0
WC Database Prefix: wp_
Total Database Size: 27.41MB
Database Data Size: 16.57MB
Database Index Size: 10.84MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.16MB + Index: 0.16MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 2.47MB + Index: 1.20MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 1.50MB + Index: 0.69MB + Engine InnoDB
wp_automatewoo_abandoned_carts: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_automatewoo_customers: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_automatewoo_customer_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_events: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_guests: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_automatewoo_guest_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_log_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_queue: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_queue_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.09MB + Index: 0.09MB + Engine InnoDB
wp_gla_budget_recommendations: Data: 0.22MB + Index: 0.14MB + Engine InnoDB
wp_gla_merchant_issues: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_gla_shipping_rates: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gla_shipping_times: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_custom_fields: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_dynamic_segment_filters: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_feature_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_forms: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_newsletters: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_newsletter_links: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_mailpoet_newsletter_option: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_option_fields: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_posts: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_segment: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_templates: Data: 2.52MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_scheduled_tasks: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_scheduled_task_subscribers: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_segments: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_sending_queues: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_settings: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_statistics_bounces: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_statistics_clicks: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_mailpoet_statistics_forms: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_statistics_newsletters: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_statistics_opens: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_mailpoet_statistics_unsubscribes: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_mailpoet_statistics_woocommerce_purchases: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_mailpoet_stats_notifications: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_subscribers: Data: 0.02MB + Index: 0.13MB + Engine InnoDB
wp_mailpoet_subscriber_custom_field: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_subscriber_ips: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_subscriber_segment: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_subscriber_tag: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_tags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_user_agents: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_user_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 2.09MB + Index: 0.13MB + Engine InnoDB
wp_postmeta: Data: 1.52MB + Index: 2.98MB + Engine InnoDB
wp_posts: Data: 0.25MB + Index: 0.13MB + Engine InnoDB
wp_redirection_404: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_redirection_groups: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_redirection_items: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_redirection_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_sa_cfw_fbt_temp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_snippets: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_tm_taskmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_tm_tasks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_usermeta: Data: 0.09MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_bookings_availability: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_bookings_availabilitymeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_booking_relationships: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_deposits_payment_plans: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_deposits_payment_plans_schedule: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_bundle_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_order_composite_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_points_rewards_user_points: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_points_rewards_user_points_log: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.05MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wdr_order_discounts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wdr_order_item_discounts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wdr_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wml_entries: Data: 1.52MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_bundled_itemmeta: Data: 0.06MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_bundled_items: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_prl_deploymentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_prl_deployments: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_prl_frequencies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_prl_tracking_conversions: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_shipping_quotes: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_shipping_table_rates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wps_hit: Data: 0.02MB + Index: 0.14MB + Engine InnoDB
wp_wps_index: Data: 1.52MB + Index: 1.28MB + Engine InnoDB
wp_wps_key: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
wp_wps_object_term: Data: 0.08MB + Index: 0.09MB + Engine InnoDB
wp_wps_object_type: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_wps_query: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wps_uri: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wps_user_agent: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_zorem_email_sms_log: Data: 0.02MB + Index: 0.11MB + Engine InnoDB

### Post Type Counts ###

addify_quote: 1
addify_rfq: 1
addify_rfq_fields: 2
af_dis_cart_rule: 1
attachment: 82
aw_workflow: 3
bookable_resource: 2
cart-quote: 7
cbp_zones: 1
cnd_rule: 1
cquote-form-fields: 1
customize_changeset: 24
custom_css: 1
mailpoet_page: 1
page: 14
post: 4
prl_engine: 1
product: 105
product_variation: 133
qts_form_field: 12
revision: 42
shop_coupon: 1
shop_order: 104
shop_order_refund: 1
shop_subscription: 25
wc-quote: 2
wc-quote-rules: 2
wc_booking: 4
wc_membership_plan: 1
wc_user_membership: 1
wp_global_styles: 1
wp_navigation: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (7) ###

Code Snippets: by Code Snippets Pro – 3.2.1
Google Listings and Ads: by WooCommerce – 2.2.0
Jetpack: by Automattic – 11.5-a.9
WooCommerce Payments: by Automattic – 4.9.0
WooCommerce Product Bundles: by WooCommerce – 6.16.0 (update to version 6.17.2 is available)
WooCommerce Subscriptions: by WooCommerce – 4.4.0 (update to version 4.6.0 is available)
WooCommerce: by Automattic – 7.0.0

### Inactive Plugins (52) ###

Akismet Anti-Spam: by Automattic – 5.0.1
AutomateWoo: by WooCommerce – 5.5.17
Bulk Discounts for WooCommerce: by Plugify – 1.0.6
Cart Discounts For Woocommerce: by FME ADDONS – 1.0.3
Cart To Quote: by HighAddons – 1.0.2
Cashier for WooCommerce: by StoreApps – 2.0.1 (update to version 2.1.0 is available)
Cash on Delivery Pro for WooCommerce: by FantasticPlugins – 1.5
Custom Sidebars: by WebFactory Ltd – 3.35
Email Customizer for WooCommerce: by ThemeHigh – 2.5.3
Hide Page And Post Title: by Arjun Thakur – 1.5.6
Loco Translate: by Tim Whitlock – 2.6.2
MailPoet: by MailPoet – 3.99.1
Price By Country: by HighAddons – 1.0.4
Product Dynamic Pricing and Discounts: by Addify – 1.0.5
PublishPress Capabilities: by PublishPress – 2.5.2
Quantity Discounts & Pricing For Woocommerce: by Plugify – 4.0.2
Query Monitor: by John Blackbourn – 3.10.1
Quick Buy Now Button for WooCommerce: by Addify – 1.3.7 (update to version 1.3.8 is available)
Quick Checkout for WooCommerce: by FantasticPlugins – 1.7
Quote for WooCommerce: by WPExperts.io – 2.2
Quote Request for WooCommerce: by FantasticPlugins – 2.2
Redirection: by John Godley – 5.3.2
Request a Quote for WooCommerce: by Addify – 2.4.2
SMS for WooCommerce: by zorem – 2.0.3
User Switching: by John Blackbourn & contributors – 1.7.0
WooCommerce Accommodation Bookings: by WooCommerce – 1.1.33
WooCommerce All Products For Subscriptions: by WooCommerce – 4.0.0 (update to version 4.0.2 is available)
WooCommerce Anti Fraud: by OPMC Australia Pty Ltd – 4.5 (update to version 4.7 is available)
WooCommerce Bookings: by WooCommerce – 1.15.59 (update to version 1.15.63 is available)
WooCommerce Bookings Availability: by WooCommerce – 1.1.22
WooCommerce Composite Products: by WooCommerce – 8.6.0
WooCommerce Conditional Shipping and Payments: by WooCommerce – 1.14.1 (update to version 1.14.2 is available)
WooCommerce Contact for Shipping Quote: by Jeroen Sormani – 1.3.0.1 (update to version 1.4.0 is available)
WooCommerce Deposits: by WooCommerce – 2.0.1 (update to version 2.0.2 is available)
WooCommerce EU VAT Number: by WooCommerce – 2.5.0 (update to version 2.6.0 is available)
WooCommerce Memberships: by SkyVerge – 1.23.0 (update to version 1.23.1 is available)
WooCommerce Min/Max Quantities: by WooCommerce – 4.0.2 (update to version 4.0.4 is available)
WooCommerce Points and Rewards: by WooCommerce – 1.7.13 (update to version 1.7.18 is available)
WooCommerce Product Add-ons: by WooCommerce – 5.0.0
WooCommerce Product Recommendations: by WooCommerce – 2.1.1
WooCommerce Product Search: by itthinx – 4.8.0
WooCommerce Shipping & Tax: by WooCommerce – 1.26.3
WooCommerce Ship to Multiple Addresses: by WooCommerce – 3.7.0 (update to version 3.7.2 is available)
WooCommerce Square: by WooCommerce – 3.1.0 (update to version 3.2.0 is available)
WooCommerce Stripe Gateway: by WooCommerce – 6.6.0
WooCommerce Table Rate Shipping: by WooCommerce – 3.0.41
WooCommerce Twilio SMS Notifications: by SkyVerge – 1.16.3
WooCommerce Xero Integration: by WooCommerce – 1.7.46 (update to version 1.7.49 is available)
Woo Discount Rules: by Flycart – 2.4.5
WP-Optimize - Clean, Compress, Cache: by David Anderson
Ruhani Rabin
Team Updraft – 3.2.7

WP Mail Log: by WPVibes – 1.0
YITH WooCommerce Catalog Mode: by YITH – 2.15.0

### Dropin Plugins (2) ###

advanced-cache.php: advanced-cache.php
object-cache.php: Memcached

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: booking (booking)
bundle (bundle)
composite (composite)
external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔
Enforce Approved Product Download Directories: ✔

### WC Pages ###

Shop base: #5 - /shop/
Cart: #6 - /cart/
Checkout: #7 - /checkout/
My account: #8 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 4.1.3
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Subscriptions ###

WCS_DEBUG: ✔ No
Subscriptions Mode: ✔ Live
Subscriptions Live URL: https://bhadra.mystagingwebsite.com
Subscription Statuses: wc-active: 9
wc-expired: 1
wc-pending: 1
wc-on-hold: 5
wc-cancelled: 9

WooCommerce Account Connected: ✔ Yes
Active Product Key: ❌ No
Report Cache Enabled: ✔ Yes
Cache Update Failures: ✔ 0 failure

### Store Setup ###

Country / State: United States (US) — Florida

### Subscriptions by Payment Gateway ###

WooCommerce Payments: wc-active: 9
wc-cancelled: 9
wc-on-hold: 3
wc-pending: 1

### Payment Gateway Support ###

WooCommerce Payments: products
refunds
multiple_subscriptions
subscription_cancellation
subscription_payment_method_change_admin
subscription_payment_method_change_customer
subscription_payment_method_change
subscription_reactivation
subscription_suspension
subscriptions
subscription_amount_changes
subscription_date_changes
tokenization
add_payment_method

### Product Bundles ###

Database Version: 6.16.0
Loopback Test: ✔
Template Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
experimental-products-task
experimental-import-products-task
experimental-fashion-sample-products
experimental-product-tour
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
multichannel-marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
settings

Daily Cron: ✔ Next scheduled: 2022-10-22 04:12:29 +05:30
Options: ✔
Notes: 66
Onboarding: completed

### WooCommerce Payments ###

Version: 4.9.0
Connected to WPCOM: Yes
Blog ID: 209909531
Account ID: acct_1LZonU2EWJJaTl97

### Action Scheduler ###

Canceled: 24
Oldest: 2022-09-21 05:22:33 +0000
Newest: 2022-10-21 07:50:16 +0000

Complete: 3,851
Oldest: 2022-09-21 05:05:02 +0000
Newest: 2022-10-21 16:33:55 +0000

Failed: 55
Oldest: 2022-08-31 06:52:45 +0000
Newest: 2022-10-21 14:29:47 +0000

Pending: 18
Oldest: 2022-10-21 16:35:55 +0000
Newest: 2024-03-23 06:30:22 +0000

### Status report information ###

Generated at: 2022-10-21 22:05:06 +05:30
</details>

**Comment by gorabd490** [comment]
Any status on this?

**Comment by avantegarde** [comment]
Checking in to see if there are any workarounds for this. Have we tested with previous versions of the extension? 38268390-hc
