### ISSUE TITLE
Blank white screen during setup

### ISSUE THREAD

**Issue by sukafia** [woocommerce/google-listings-and-ads#1741]
### Describe the bug:

Users are reporting seeing a blank white screen during the setup of the Google Listings & Ads extension. The issue happens on the connection page and we're able to replicate it on some sites.

### Steps to reproduce:

1. Access the AT site in 5667661-zen
2. Attempt to setup the extension
3. Notice you're redirected to a blank white page.

### Expected behavior:

The setup flow should continue as expected.

### Additional details:

(The ZD issues have creds so I'd recommend starting with those.)

https://wordpress.org/support/topic/there-was-an-error-loading-your-merchant-center-product-review-request-status-4/

https://wordpress.org/support/topic/can-not-connect-my-site-to-merchant-account/

5665411-zd-woothemes

5664584-zd-woothemes

5641237-zd-woothemes

5666189-zd-woothemes

**Comment by sukafia** [comment]
I'm also seeing reports of blank pages on other extensions (Not sure if they're related)

[FB for WC](https://wordpress.org/support/topic/activate-gives-blank-product-page/), 5664948-zen, 5658333-zen, 5658534-zen

**Comment by jacoswan** [comment]
Also in 5665533-zen 

I could also recreate this on a Jurrasic Ninja site using Google accounts with and without Google Merchant Centre configured. Without goes straight to the blank page. With asks for permissions, then full permission (if not granted), then goes to the blank page.

**Comment by jacoswan** [comment]
5667884-zen

**Comment by jacoswan** [comment]
5667963-zen

User says, in spite of them being Admin on the site: 

> When I activate Google Listings and Ads: by WooCommerce I get redirected to `/wp-admin/admin.php?page=wc-admin&path=googlestart` which shows the error 'Sorry, you are not allowed to access this page.'

The same URL on my test site (not previously connected to GL&A) leads to a blank page.

**Comment by guy01992** [comment]
I am also having the same issue. Does anyone know how to fix?

**Comment by sukafia** [comment]
5668320-zen

**Comment by AmeliaBriscoe** [comment]
37673109-hc and 5668827-zen

**Comment by wyter** [comment]
Also reported in 5669439-zen

**Comment by dsmithweb** [comment]
Also in 5669593-zen

**Comment by Babylon1999** [comment]
Two users reported the same problem here: https://wordpress.org/support/topic/there-was-an-error-loading-your-merchant-center-product-review-request-status-4/#post-16145679

You can find a couple more on the plugin's forum.

**Comment by csmcneill** [comment]
Kinda ran into this with 5670182-zen / 37665613-hc today.

When they tried to authenticate their phone number and store address, they were unable to. The logs showed the following error:

```
2022-10-30T16:43:24+00:00 ERROR Automattic\WooCommerce\GoogleListingsAndAds\Internal\DependencyManagement\GoogleServiceProvider::handle_unauthorized_error Client error: `GET https://api-vipgo.woocommerce.com/google/google-mc/content/v2.1/0/accounts/0` resulted in a `401 Unauthorized` response:
{
  "error": {
    "code": 401,
    "message": "User cannot access account 0",
    "errors": [
      {
        "message" (truncated...)
```

GLA was trying to update the information for an invalid account number—`0`.

When I tried to force a connection to the proper account, I was met with the white screen mentioned in this issue.

**Comment by YuKw** [comment]
When I create a Google Merchant Center account in plugin page, I get an error: Error creating account: Unable to create a merchant account
```
2022-10-30T19:29:25+00:00 ERROR Automattic\WooCommerce\GoogleListingsAndAds\API\Google\Middleware::create_merchant_account_request Client error: `POST https://api-vipgo.woocommerce.com/google/manager/create-merchant` resulted in a `400 Bad Request` response:
{"statusCode":400,"error":"Bad Request","message":"Unable to create a merchant account"}
```

I've tried four or five times, but it still doesn't work, so take the liberty to ask: will this problem be solved, or will you give up on it?
This is a great plugin and I look forward to its solve.

**Comment by theabhig** [comment]
Also reported in 5669626-zen today

**Comment by devvnawaz** [comment]
5671307-zen

**Comment by NateMossp** [comment]
Having the same problem. seems to be when trying to connect and acquire merchant account details.

**Comment by theabhig** [comment]
5666689-zen

**Comment by xuexue28** [comment]
5667920-zen

**Comment by puntope** [comment]
This issue is solved. Was a problem with the connection between Google and the Plugin.

**Comment by guy01992** [comment]
Hi there, Ive noticed its now working again 

Thanks

Guy
