### ISSUE TITLE
URL link wrong for listings 

### ISSUE THREAD

**Issue by netconnectsolutions** [woocommerce/google-listings-and-ads#1757]
Hi,

had to change my permalink for my store but now google is giving me errors because the url on my listings are the old permalinks. 

I have tried deleting the products from google and resyncing them. Also tried uninstalling the google plug in but they are still not updating with the new links which is causing a 404 error when

thanks
Kurtis

**Comment by mikkamp** [comment]
Hi Kurtis,

Generally when you change the URL for your store, the best way to get it up to date is to disconnect all your accounts and go through the onboarding process and reconnect everything. Doing so will ensure the verification process will be completed again for the new URL and it will schedule all the products to be resynced to Google.

You mentioned you deleted and resynced the products, which should also work if only the product URLs change and not the main site URL. When syncing it uses the [get_permalink](https://woocommerce.github.io/code-reference/classes/WC-Product.html#method_get_permalink) function directly from the WooCommerce product, so the plugin doesn't really handle the URL. Maybe you can check if there is some caching in place which prevents the right permalink from being retrieved.

Having said that, I'd like to mention that this repository is not intended for support requests. The best place to start the process is with the [WordPress.org Google Listings and Ads forum](https://wordpress.org/support/plugin/google-listings-and-ads/) or if you have a WooCommerce.com account, you can start a chat or open a ticket on [WooCommerce.com support](https://woocommerce.com/my-account/create-a-ticket/). I'd suggest to include your [system status report](https://woocommerce.com/document/understanding-the-woocommerce-system-status-report/#system-status) as well as additional details to reproduce the issue.

The support team will help guide you through some problem solving and get some more information to give us a bit more context/background on your concerns/report above.
