### ISSUE TITLE
Missing gtin in woo variable products

### ISSUE THREAD

**Issue by webwit** [woocommerce/google-listings-and-ads#1763]
### Describe the bug:
Hi, in admin under Marketing -> Google Listings & Ads -> Product Feed I’m getting lots of Product Issues with the message “Limited performance due to missing identifiers [gtin, mpn, brand]”. Same list in Google Merchant center.

The problem is it can’t find the gtin13. I’m only getting this with variable products. In each of the affected variable products, I’ve the Google Listings & Ads GTIN setting set to “From Yoast WooCommerce SEO”, which I have defined in the variable product settings under “Yoast SEO options” as GTIN13/EAN.

This works fine with simple products, but apparently it doesn’t pick it up for variable products. It used to work.

I use the latest WP/WOO and plugin versions with PHP 8.1.

### Steps to reproduce:
1. Create product with variations
2. Add GTIN13 in variation in the Yoast field
3. Set GTIN in the variation Google field to “From Yoast WooCommerce SEO” (see screenshot below)

### Expected behavior:
GTIN of variable products to be fed to Google

### Actual behavior:
Google Merchant center gives errors that GTIN of variable products isn't fed to them

### Additional details:
Bug should be somewhere here: src/Integration/YoastWooCommerceSeo.php
I reported this bug earlier here: https://wordpress.org/support/topic/missing-gtin-in-woo-variable-products/
But I met no intelligence.
Yoast also investigated the problem, they said the problem is at your end as I suspected.

Product issues:
![gla1](https://user-images.githubusercontent.com/3962955/201383076-365c28c0-01cd-4ebc-90e9-5ece66918b4e.png)

Entered the GTIN in Yoast, selected "From Yoast WooCommerce SEO" in GL&A:
![gla2](https://user-images.githubusercontent.com/3962955/201383117-d5b00956-e5dc-4c17-96ec-28029ef91dc7.png)

**Comment by webwit** [comment]
The problem seems to be here in src/Integration/YoastWooCommerceSeo.php?

`        protected function get_identifier_value( string $key, WC_Product $product ) {
                $product_id = $product->get_id();

                if ( ! isset( $this->yoast_global_identifiers[ $product_id ] ) ) {
                        $product = $product instanceof WC_Product_Variation ? wc_get_product( $product->get_parent_id() ) : $product;

                        $this->yoast_global_identifiers[ $product_id ] = $product->get_meta( 'wpseo_global_identifier_values', true );
                }

                return ! empty( $this->yoast_global_identifiers[ $product_id ][ $key ] ) ? $this->yoast_global_identifiers[ $product_id ][ $key ] : null;
        }
`

I'm looking at this line:
$product = $product instanceof WC_Product_Variation ? wc_get_product( $product->get_parent_id() ) : $product;

It tries to get the GTIN from the variable product's parent instead of the variable product. This is wrong. If I have a product with three variations, it has three GTINs set in each variation set under Yoast settings, not a single GTIN in the parent. There is no GTIN in the parent.

**Comment by mikkamp** [comment]
Thanks for the report @webwit 

I was just looking at the code and was going to ask you to confirm whether meta `wpseo_global_identifier_values` was being saved per variation (but you beat me to it). As you mentioned it is indeed trying to load it from the variable product instead of the variation.

I can confirm that this is indeed a problem, we'll need to get that fixed.

### Additional details

Post meta fields used to store identifiers:
```
Single and parent variable products: wpseo_global_identifier_values
Variations:                          wpseo_variation_global_identifiers_values
```

For variable products we'll need to check for the variation identifiers first, and fallback to the parent variable product identifiers if it's not set.

Tested by installing:
- https://wordpress.org/plugins/wordpress-seo/
- https://github.com/Yoast/wpseo-woocommerce/releases/tag/15.3

**Comment by webwit** [comment]
Cheers, thanks for your help.

**Comment by webwit** [comment]
Hi, I tried this fix:

Old:
$product = $product instanceof WC_Product_Variation ? wc_get_product( $product->get_parent_id() ) : $product;

New:
if ($product instanceof WC_Product_Variation && !$product->get_meta( 'wpseo_global_identifier_values', true )) {
    $product = wc_get_product( $product->get_parent_id() );
}

The idea is it only takes the GTIN from the parent when the variation has no GTIN set. This should work for both scenarios, i.e. a variation having a single GTIN in the parent or separate GTIN in the variation.

I'm not entirely versed with WOO or this plugin so I might be wrong and I leave that to you guys. But I edited a variable product to give it a resync kick, and the product no longer gives that error.

**Comment by mikkamp** [comment]
@webwit Can you confirm whether you have set those identifier values through the Yoast plugin or an importer and which versions of the Yoast plugins you are using.

When I save it through the plugin I can only find the data from the variations saved in `wpseo_variation_global_identifiers_values` as mentioned above, which wouldn't work with the fix you described.

**Comment by webwit** [comment]
Yeah I saw that wpseo_variation_global_identifiers_values a little too late, already removed my comment after it started showing the errors a little while later anyway.

It should probably be more like this, although I guess I shouldn't be doing this and leave it up to you as I don't know the fine details ;)

`        protected function get_identifier_value( string $key, WC_Product $product ) {
                $product_id = $product->get_id();
                $meta_field = 'wpseo_global_identifier_values';

                if ( ! isset( $this->yoast_global_identifiers[ $product_id ] ) ) {
                        if ( $product instanceof WC_Product_Variation ) {
                                if ( $product->get_meta( 'wpseo_variation_global_identifiers_values', true ) ) {
                                        $meta_field = 'wpseo_variation_global_identifiers_values';
                                } else {
                                        $product = wc_get_product( $product->get_parent_id() );
                                }
                        }
                        $this->yoast_global_identifiers[ $product_id ] = $product->get_meta( $meta_field, true );
                }
                return ! empty( $this->yoast_global_identifiers[ $product_id ][ $key ] ) ? $this->yoast_global_identifiers[ $product_id ][ $key ] : null;
        }
`
