### ISSUE TITLE
Improve setup flow policy compliance checks

### ISSUE THREAD

**Issue by sukafia** [woocommerce/google-listings-and-ads#1781]
### Describe the bug:

We introduced [policy compliance checks](https://github.com/woocommerce/google-listings-and-ads/issues/1446) to automatically detect compliance issues and prompt merchants to fix them during the onboarding process. This was to help prevent account rejection after the onboarding. As far as I know, the checks appear to be performed for all the Pre-Launch Checklist items. 

However, there's no clear notice when a site fails one of the checks, the continue button is just not clickable and merchants aren't clear on the blocker. 

The setup flow checks should be improved to prompt users on the failed policy compliance check that's preventing them from continuing the setup. This will help reduce dropoff on the setup flow.

### Steps to reproduce:

1. Setup the extension on a fresh installation
2. Ensure no refunds/returns policy page or payment method is set up on the site (Intentionally fail one of the policy compliance checks)
3. Attempt the extension setup and select the Pre-Launch Checklist
4. Notice that the continue button isn't clickable but it's not clear what check the store failed

### Expected behavior:

The user should be prompted about the failed policy compliance check

### Actual behavior:

No prompt is shown. However, if you refresh the page you'll find the pre-launch checklist related to the failed test will be unselected, while the passed checks will remain selected. This suggests the extension is correctly detecting the failed checks but just not prompting users which was the goal of implementing the checks.

### Additional details:

![5GbtTL.png](https://user-images.githubusercontent.com/60121732/202565278-7c4ae027-c612-4a5d-ba7e-880f0dc81de9.png)

**Comment by mikkamp** [comment]
Thanks for the report. I think this falls in line with other issues where we don't clearly highlight which step failed during onboarding. See #1415

**Comment by mikkamp** [comment]
As described in the comment here: https://github.com/woocommerce/google-listings-and-ads/issues/1782#issuecomment-1359215798
Policy Compliance checks don't block the continue button if they are checked manually, so their must be something else on the page which is preventing the continue button from being disabled, such as the store address or the phone number.

Closing this issue in favour of: https://github.com/woocommerce/google-listings-and-ads/issues/634
