### ISSUE TITLE
WC 7.2-beta.2: Styling issues

### ISSUE THREAD

**Issue by jorgemd24** [woocommerce/google-listings-and-ads#1802]
### Describe the bug:

These are some styling issues that I found when I was running the compatibility tests of WC 7.2-beta.2. See: https://github.com/woocommerce/google-listings-and-ads/issues/1801

### Attribute Mapping

**WC 7.2-beta.2** | **WC 7.1**
-- | --
![image](https://user-images.githubusercontent.com/2488994/205102203-e337d3ec-2665-471f-b2bd-a43e36f5bcad.png) | ![image](https://user-images.githubusercontent.com/2488994/205102392-2db832eb-4da1-4379-b5c1-dfda98d06938.png)

**Create attribute modal: Affects both versions WC 7.2-beta.2 & WC 7.1**

![image](https://user-images.githubusercontent.com/2488994/205102913-8b22c492-d1ad-4929-8bfa-eafdaa129a01.png)

### FAQ Section

I believe that the below texts should be aligned to the left:

![image](https://user-images.githubusercontent.com/2488994/205105340-f8741b4b-37b3-47b6-bdcc-0f86311fc1d2.png)

![image](https://user-images.githubusercontent.com/2488994/205105870-3e44c650-e231-4516-894d-824d7f8ef1bd.png)

See PRs:
https://github.com/woocommerce/google-listings-and-ads/pull/506
https://github.com/woocommerce/google-listings-and-ads/pull/1217

### Steps to reproduce:
1. Install the [WC 7.2-beta.2](https://globalstepp2.wordpress.com/2022/11/28/woocommerce-7-2-beta-2-globalstep-smoke-testing-to-be-done-on-november-28-2022/#:~:text=2%2Dsmoke%2D1-,Download,-GlobalStep%20team%3A)
2. Navigate to the screens mentioned before.

### Additional details:
I used the branch `dev/align-wp-wc-packages-with-react-17` to  run the compatibility tests.

**Comment by eason9487** [comment]
Apart from the modal overflow issue, others have been fixed along with #1779.
- https://github.com/woocommerce/google-listings-and-ads/pull/1779#issuecomment-1335623267
- https://github.com/woocommerce/google-listings-and-ads/pull/1779#issuecomment-1336135119
- https://github.com/woocommerce/google-listings-and-ads/pull/1779#pullrequestreview-1206909575

**Comment by puntope** [comment]
I created a [separated issue](https://github.com/woocommerce/google-listings-and-ads/issues/1811) for the modal. Since I think it comes for previous versions. So I'm closing this one.
