### ISSUE TITLE
Ho to add Custom label 0–4?

### ISSUE THREAD

**Issue by mycoinber** [woocommerce/google-listings-and-ads#1838]
Hi! How tp add [Custom label 0–4](https://support.google.com/merchants/answer/6324473?hl=en)

**Comment by jorgemd24** [comment]
Hi there! 

Currently, we are not supporting this feature, would you mind heading over to [our feature request board](https://woocommerce.com/feature-requests/google-listings-and-ads) and posting your suggestion? It'll help us keep better track of the popularity as others can vote.

Thanks!
