### ISSUE TITLE
Linked accounts do not load in Google listings and ads plugin settings

### ISSUE THREAD

**Issue by andrada91** [woocommerce/google-listings-and-ads#1900]
My linked accounts would not load in the plugin settings. It used to work until 2 weeks ago. Please help
![Screenshot 2023-02-23 at 08 03 43](https://user-images.githubusercontent.com/126141568/220833187-f122a29d-5439-43c9-9797-44f9ee1191e0.jpg)

**Comment by jorgemd24** [comment]
Hi @andrada91,

Thanks for contacting us, can you try the following steps:

- Go to `https:://yourdomain.com/wp-admin/admin.php?page=connection-test-admin-page`
- Disconnect all your accounts (Google Account, Ads, Jetpack)
- Go back to Google Listings & Ads and follow the onboarding steps. 
- Check if all your accounts are loading correctly.

If the issue persists, I'd suggest contacting the support team, as this repository is not intended for support requests. The best place to start the process is with the [WordPress.org Google Listings and Ads forum](https://wordpress.org/support/plugin/google-listings-and-ads/) or if you have a WooCommerce.com account, you can start a chat or open a ticket on [WooCommerce.com support](https://woocommerce.com/my-account/create-a-ticket/). I'd suggest including your [system status report](https://woocommerce.com/document/understanding-the-woocommerce-system-status-report/#system-status) as well as additional details to reproduce the issue.
