### ISSUE TITLE
Gax Library - ApiException Fatal error.

### ISSUE THREAD

**Issue by jorgemd24** [woocommerce/google-listings-and-ads#1902]
### Describe the bug:

The [Google Ads library](https://github.com/googleads/google-ads-php) uses the [gax library](https://github.com/googleapis/gax-php/tree/v1.19.0) to handle requests and API exceptions, and it is expecting that the exceptions are formatted with a specific format used for Ads API. **To be more specific is expecting the property `error` to contain a `message` property.**

The problem comes when there is an error in our Proxy (WooCommerce Connect Server) not from the Ads API, the exception thrown from the proxy does not have the format that the Ads API library is expecting. 

See more context about this issue here: https://github.com/woocommerce/google-listings-and-ads/pull/1896#pullrequestreview-1307797410

#### Process:
`Client -> WCS -> Ads API (throws an exception) `

#### Exception format:
```
"{
  "error": {
    "code": 400,
    "message": "Request contains an invalid argument.",
    "status": "INVALID_ARGUMENT",
    "details": [
        ....
    ]
  }
}
"
```

#### Process:
`Client -> WCS (throws an exception and the Ads API  is not reached) `

#### Exception format:
```
{
  "statusCode":413,
  "error":"Request Entity Too Large",
  "message":"Payload content length greater than maximum allowed: 1048576"
}
```
Notice the difference between the error format between both exceptions.

### Updating `gax` from v1.13.0 to v1.19.0

In the process to update the Ads API versions from 11 to 12 the below libraries were updated:

- PHP Google Ads library from v16 to v17.1 
- `gax` library was updated from v1.13.0 to v1.19.0. 

This new version of `gax` introduces some changes to how the API Exceptions are handled and the strict typing. 

In v1.19.0, if the error does not contain a `message` property it will create a fatal error because the `message` is null and it is not of the type of `string`.

Error Message:

`PHP Fatal error:  Uncaught TypeError: Google\ApiCore\ApiException::create(): Argument #1 ($basicMessage) must be of type string, null given, called in google-listings-and-ads/vendor/google/gax/src/ApiException.php on line 194 and defined in google-listings-and-ads/vendor/google/gax/src/ApiException.php:242`

```
....
$basicMessage = isset($error['message']) ? $error['message'] : null;
....

    private static function create(
        string $basicMessage,
        int $rpcCode,
        $metadata,
        array $decodedMetadata,
        Exception $previous = null
    ) {


```
See the code [here](https://github.com/googleapis/gax-php/blob/d537fd00dcdb1b5599386c1253ccb79e69d5d9f2/src/ApiException.php#L310).

Although setting the `$basicMessage` to `null` does not seem the right fix here ( I created an [issue](https://github.com/googleapis/gax-php/issues/446) in the gax library), we need to be able to avoid this fatal error in our code.

### Possible solution:

- As far as I can see, the only requests using the proxy and using `APIExceptions` from the `gax` library, is the Ads Library. The Merchant Center does not seem to use these types of exceptions.
- The Ads API responses always contain the header [request-id](https://developers.google.com/google-ads/api/rest/auth#request_id), so we could use this header to identify whether the response comes from the Ads API.
- We need to identify which requests are expected to have the header `request-id`, this could be done by checking the request path, for example: `/google/google-ads/`

If my assumptions are correct, we could do the following:

We can use the [custom error_handler](https://github.com/woocommerce/google-listings-and-ads/blob/2.3.10/src/Internal/DependencyManagement/GoogleServiceProvider.php#L196) and add a conditional statement, some like: 

```
 if ( $this->is_ads_proxy_exception( $request, $response ) ) {
	throw ProxyError::proxy_error( $response->getReasonPhrase(), $code );
 }
```

And `is_ads_proxy_exception` will check:

- if the request path contains `/google/google-ads/`
- if it contains the header `request-id`

In case the request contains the path  `/google/google-ads/`  and does not have a `request-id` would mean that the error was caused in the Proxy.

### Steps to reproduce:

1. In your Local WCS, force throwing an error on `lib/google-proxy/index.js`, for example: `throw new Error( 'Not implemented' );`
2. Do the following request `GET /gla/ads/campaigns/123456`
3. A fatal error will be thrown.

### Expected behavior:
Not fatal errors should be displayed.

### Actual behavior:
A fatal errors should be displayed.

### Additional details:
This issue was found in the following PR: https://github.com/woocommerce/google-listings-and-ads/pull/1896#pullrequestreview-1307797410

**Comment by mikkamp** [comment]
Just to add some additional context, in the WCS the unauthorized error is formatted specifically for Ads requests, see: https://github.com/Automattic/woocommerce-connect-server/blob/woogle/lib/google-proxy/index.js#L46-L51

Although apparently there are lots of other errors that can be returned which aren't formatted. I guess another possible solution would be to catch other errors for the proxy handler and convert the error message. This would still miss other cases where an error is returned from the additional proxy we have in the tests folder (but at least worth weighing out the pros/cons of each solution).

**Comment by jorgemd24** [comment]
@mikkamp, thanks for adding some additional context. I explored the possible solutions and I think  the below code could do the job: 

```
module.exports = {
	id: 'google-proxy',
	handler: function( request, h ) {
	 .........
	},
	.........     
	ext: {
		onPreResponse: {
			method: ( request, h ) => {
			       const service = request.params.service;
				if ( request.response.isBoom && 'google-ads' === service ) {
					request.response.output.payload = {
						...request.response.output.payload,
						error: {
							message: request.response.output.payload.message,
						},
					};
				}
				return h.continue;
			},
		},
	},
```

All Boom errors ( server errors and client errors such as entity too large ) would be formatted in the `ApiException` style. Errors from the Ads API will be just forwarded to the client.

This solution is more specific and we ensure that all errors coming from the service `google-ads` will follow one specific format. Besides that,  we could add some tests in the GL&A plugin to ensure that the `ApiException` continues handling the error with that specific format.

In my opinion, the first solution, updating [custom error_handler](https://github.com/woocommerce/google-listings-and-ads/blob/2.3.10/src/Internal/DependencyManagement/GoogleServiceProvider.php#L196) would be a  "workaround" for something that should be done in the proxy.

**Comment by mikkamp** [comment]
Makes sense to resolve it in the proxy. Eventually the fatal should get fixed in the Gax library anyway. I haven't tested the code you suggested, but at initial glance it looks good so we can get a PR up for that so it can be tested and reviewed.

**Comment by jorgemd24** [comment]
The issue has been resolved, see: https://github.com/Automattic/woocommerce-connect-server/pull/2048 however is not deployed yet until this issue is closed: [2055](https://github.com/Automattic/woocommerce-connect-server/issues/2055)

**Comment by eason9487** [comment]
https://github.com/Automattic/woocommerce-connect-server/pull/2048 has been deployed along with https://github.com/Automattic/woocommerce-connect-server/pull/2160 on May 17, 2023. This issue is ready to check if it has been solved.

**Comment by mikkamp** [comment]
I can confirm that this issue is resolved with both the following fixes:

- Update in [WCS PR](https://github.com/Automattic/woocommerce-connect-server/pull/2048)
- Update the google/gax package to [1.20.2](https://github.com/googleapis/gax-php/releases/tag/v1.20.2) (`composer update google/gax --with-all-dependencies`)

For now we can leave the fix for the WCS in place. Updating google/gax can be completed as part of the project to update the Ads API to v13: pcTzPl-1w2-p2
