### ISSUE TITLE
Base price export

### ISSUE THREAD

**Issue by hoppelAG** [woocommerce/google-listings-and-ads#1917]
## User story

In certain countries you need to indicate the base price of a certain unit for the offered products (e.g. beverages, parfums, food,...) 
It would be great to export the base price of the offered goods. Google therfore requests the values [unit_pricing_measure] and [unit_pricing_base_measure]. [Link](https://support.google.com/merchants/answer/6324455?hl=en#zippy=%2Cgetr%C3%A4nke%2Cbodenbel%C3%A4ge%2Cvisitenkarten%2Cparf%C3%BCm%2Cvarianten).
It would be great to have these attributes implemented into the plugin for quick and easy handling.

Keep going with your great work. I am looking forward to the implementation of this featur :)

**Comment by puntope** [comment]
Hello @hoppelAG thanks for opening an issue and giving us feedback.

For your case I think it would be useful to look at this filter. 

`woocommerce_gla_product_attribute_values`

You can see usage [here](https://github.com/woocommerce/google-listings-and-ads/blob/develop/src/Product/WCProductAdapter.php#L167)

It allows you to override/add manually the attributes you need.

I'm closing this issue for now, [if you need further assistance](https://woocommerce.com/document/how-to-get-help/),  then [opening a ticket in WooCommerce support ](https://woocommerce.com/my-account/create-a-ticket/) is the preferred method. 

Thanks for contacting us.
