### ISSUE TITLE
Return the URL to setup ads account in MCM dashboard if it is not already set up

### ISSUE THREAD

**Issue by nima-karimi** [woocommerce/google-listings-and-ads#1922]
Based on the discussion here: https://github.com/woocommerce/woocommerce/pull/37044#discussion_r1129068032

Currently, return the following static URL to WooCommerce's Multichannel Marketing dashboard to allow users to create a new campaign: `admin.php?page=wc-admin&path=/google/dashboard&subpath=/campaigns/create`

This URL will be used on the marketing dashboard in the following section (PR https://github.com/woocommerce/woocommerce/pull/37044):

<img width="1035" alt="image" src="https://user-images.githubusercontent.com/73110514/224313190-4e5378fb-6704-44eb-867c-cb2065c370c3.png">

However, if the ads account has not been set up in GLA, the user cannot visit that URL. This means that we are returning a broken URL.

To resolve this, we can a check in the `MultichannelMarketing\GLAChannel::generate_campaign_types` method to see if the ads account has been set up and connected before returning the URL to create a campaign page. If it is not set up, we need to return the URL to the ads setup page.

**Comment by martynmjones** [comment]
Resolved in #1926 as any attempt to access `/google/dashboard` will be redirected to onboarding if the account isn't set up.
