### ISSUE TITLE
Php errors

### ISSUE THREAD

**Issue by betayazilim** [woocommerce/google-listings-and-ads#1935]
Hi there,
I have wordpress and woocommerce latest versions.
Php 8.1

Keep seeing below errors.

`Warning: foreach() argument must be of type array|object, null given in /srv/htdocs/wp-content/plugins/google-listings-and-ads/src/MerchantCenter/MerchantStatuses.php on line 472`

```
WordPress database error You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '' at line 11 for query
SELECT wp_posts.ID
FROM wp_posts LEFT JOIN wp_term_relationships ON (wp_posts.ID = wp_term_relationships.object_id) INNER JOIN wp_postmeta ON ( wp_posts.ID = wp_postmeta.post_id ) INNER JOIN wp_postmeta AS mt1 ON ( wp_posts.ID = mt1.post_id ) INNER JOIN wp_postmeta awcmso_pm_ss ON (wp_posts.ID = awcmso_pm_ss.post_id)
WHERE 1=1 AND awcmso_pm_ss.meta_key = '_stock_status' AND awcmso_pm_ss.meta_value <> '' AND (
wp_term_relationships.term_taxonomy_id IN (32294,2,4)
) AND (
( wp_postmeta.meta_key = '_wc_gla_sync_status' AND wp_postmeta.meta_value != 'synced' )
AND
( mt1.meta_key = '_wc_gla_visibility' AND mt1.meta_value = 'sync-and-show' )
) AND wp_posts.post_type = 'product' AND ((wp_posts.post_status = 'publish'))
GROUP BY wp_posts.ID
ORDER BY awcmso_pm_ss.meta_value ASC,

made by do_action_ref_array('woocommerce_tracker_send_event'), WP_Hook->do_action, WP_Hook->apply_filters, WC_Tracker::send_tracking_data, WC_Tracker::get_tracking_data, apply_filters('woocommerce_tracker_data'), WP_Hook->apply_filters, Automattic\WooCommerce\GoogleListingsAndAds\Tracking\TrackerSnapshot->Automattic\WooCommerce\GoogleListingsAndAds\Tracking\{closure}, Automattic\WooCommerce\GoogleListingsAndAds\Tracking\TrackerSnapshot->include_snapshot_data, Automattic\WooCommerce\GoogleListingsAndAds\Tracking\TrackerSnapshot->get_settings, Automattic\WooCommerce\GoogleListingsAndAds\MerchantCenter\MerchantCenterService->has_account_issues, Automattic\WooCommerce\GoogleListingsAndAds\MerchantCenter\MerchantStatuses->get_issues, Automattic\WooCommerce\GoogleListingsAndAds\MerchantCenter\MerchantStatuses->maybe_refresh_status_data, Automattic\WooCommerce\GoogleListingsAndAds\MerchantCenter\MerchantStatuses->update_mc_statuses, Automattic\WooCommerce\GoogleListingsAndAds\Product\ProductRepository->find_mc_not_synced_product_ids, Automattic\WooCommerce\GoogleListingsAndAds\Product\ProductRepository->find_ids, Automattic\WooCommerce\GoogleListingsAndAds\Product\ProductRepository->execute_woocommerce_query, wc_get_products, WC_Product_Query->get_products, WC_Data_Store->__call, WC_Product_Data_Store_CPT->query, WP_Query->__construct, WP_Query->query, WP_Query->get_posts

```

**Comment by puntope** [comment]
Hey there @bsahins. Thanks for contacting  us. 

It seems for me like a plugin you're using is creating  some malformation in the database query (see how `awcmso_pm_ss` is altering the query). Since the DB query has a malformation, it fails making the next line in the code to generate a Warning. 

I would advise you to [contact WooCommerce support](https://woocommerce.com/my-account/create-a-ticket/) for further help and investigation.  Or you can also get [some tips about how to deal with conflicts here](https://woocommerce.com/document/how-to-get-help/)

**Comment by betayazilim** [comment]
how about this?

`Warning: foreach() argument must be of type array|object, null given in /srv/htdocs/wp-content/plugins/google-listings-and-ads/src/MerchantCenter/MerchantStatuses.php on line 472`

**Comment by puntope** [comment]
> how about this?

> Warning: foreach() argument must be of type array|object, null given in /srv/htdocs/wp-content/plugins/google-listings-and-ads/src/MerchantCenter/MerchantStatuses.php on line 472

Hello again @bsahins. Since the DB query has a malformation, it fails making the next line in the code to generate a Warning, so that warning is a happening because of the failing DB query.
