### ISSUE TITLE
Please namespace the `psr/container` dependency

### ISSUE THREAD

**Issue by ecaron** [woocommerce/google-listings-and-ads#1938]
### Describe the bug:
On WordPress 6.1.1, installing 2.4.2 (both as an upgrade and from scratch) trigger a post-install error.

The fatal error shown is:
> Fatal error: Declaration of Automattic\WooCommerce\GoogleListingsAndAds\Container::has($id) must be compatible with Psr\Container\ContainerInterface::has(string $id): bool in /code/wp-content/plugins/google-listings-and-ads/src/Container.php on line 104 Notice: Function is_embed was called incorrectly. Conditional query tags do not work before the query is run. Before then, they always return false. Please see Debugging in WordPress for more information. (This message was added in version 3.1.0.) in /code/wp-includes/functions.php on line 5835 Notice: Function is_search was called incorrectly. Conditional query tags do not work before the query is run. Before then, they always return false. Please see Debugging in WordPress for more information. (This message was added in version 3.1.0.) in /code/wp-includes/functions.php on line 5835

### Steps to reproduce:
1. Install 2.4.2 via /wp-admin/ alongside another plugin using `psr/container` > 2.0.0 (such as https://github.com/publishpress/PublishPress-Revisions/releases/tag/v3.1.13)

### Expected behavior:
Plugin update runs smoothly.

### Actual behavior:
Depending on plugin load order, a fatal error prevents site from being used.

### Additional details:
As @mikkamp noted below, this problem is caused by multiple plugins loading `psr/container` without namespacing them, and the breaking change of `psr/container` 2.0 causes this crit error.

**Comment by mikkamp** [comment]
Hi @ecaron 
I checked the zip files from both 2.4.2 and 2.4.1 and the `ContainerInterface::has` it bundles in `vendor/src/psr/container/src/ContainerInterface.php` both have the function declaration as:

```php
public function has(string $id);
```

The return type of `bool` was added in version [2.0.0 of the `psr/container` package](https://github.com/php-fig/container/releases/tag/2.0.0) but that's not the version we have bundled yet. Is there any other plugin that could be loading a newer version of this package before that time?

I'd find it odd that only the downgrade of 2.4.2 > 2.4.1 resolved the error, there must have been some other factors in play which prevented a newer version of the `psr/container` package from loading.

Could you search the site for copies of `ContainerInterface.php` using the namespace `Psr\Container` to help track down if there is a newer version of the library, and where it's coming from?

Ideally if there is a conflict then we would add it to the list of packages which should be "namespaced".

**Comment by ecaron** [comment]
@mikkamp, you're right that the problem is with package conflicts for `psr/container`.

The plugin creating the conflict is the @publishpress Revisions plugin, which as of v3.1.13 loads `pimple/pimple` v3.5.0 and that offers dual support for `psr/container` 1.1 and 2.0 (causing the inconsistent critical errors depending on plugin load order). I'll also open an issue with them requesting them to namespace their library.

I adjusted the subject of this issue (to avoid scaring people from 2.4.2) and altered the body of the main issue to reorient this ticket towards the request of namespacing `psr/container`
