### ISSUE TITLE
Erro na Configuração Inicial do Google

### ISSUE THREAD

**Issue by lojaportela21** [woocommerce/google-listings-and-ads#1942]
Alguém pode me ajudar, por favor.

O plugin Google Listings & Ads está apresentando erro de conexão com o Google no primeiro dia de configuração.

Já no segundo dia está apresentando a seguinte mensagem de erro: Ocorreu um erro ao carregar o status de configuração do Merchant Center.

Não sei mas o que fazer. Já fiz vários testes, como abrir em uma janela anônima, já desinstalei e instalei o plugin e nada de resolver o problema.

Agradeço a ajuda, atenção e compreensão.

Atenciosamente.
Hávila Portela

**Comment by puntope** [comment]
Hello @lojaportela21. Thanks for contacting us.

I would advise you to [contact WooCommerce support](https://woocommerce.com/my-account/create-a-ticket/) for further help and investigation in your specific case. Or you can also get [some tips about how to deal with conflicts here](https://woocommerce.com/document/how-to-get-help/)
