### ISSUE TITLE
Php error

### ISSUE THREAD

**Issue by betayazilim** [woocommerce/google-listings-and-ads#1943]
Hi there,

I use latest WP and Woo.
Php 8.1

Keep getting this error message.
`Warning: Undefined array key 0 in /srv/htdocs/wp-content/plugins/google-listings-and-ads/src/Product/WCProductAdapter.php on line 1026`

**Comment by puntope** [comment]
Hello @bsahins. Thanks for contacting us.

I wasn't able to reproduce the mentioned error. Potentially it could be some conflicts with other plugins as happened [here](https://github.com/woocommerce/google-listings-and-ads/issues/1935). 

I would advise you to [contact WooCommerce support](https://woocommerce.com/my-account/create-a-ticket/) for further help and investigation. Or you can also get [some tips about how to deal with conflicts here](https://woocommerce.com/document/how-to-get-help/)
