### ISSUE TITLE
on product page :Issues detected  Issues  [description] This value should not be blank. The description values are not blank yet this shows?

### ISSUE THREAD

**Issue by infokingsandqueens** [woocommerce/google-listings-and-ads#1949]
![google sync issue](https://user-images.githubusercontent.com/130659397/231763308-c71cdbc2-2eee-4a47-b9ea-e58836a7fa93.jpg)
### Steps to reproduce:

1. 
2. 
3.

**Comment by infokingsandqueens** [comment]
Please assist

**Comment by puntope** [comment]
Hello @infokingsandqueens. That description field in your screenshot seems like an external SEO plugin meta-description field. The description in GLA is supposed to be taken from the description or the short description field in the WooCommerce product. 

If you cannot do so, there are some filters/actions you might want to use to load that field manually in the description. But that would require a custom  code snippet and we cannot offer support for that.

If you need more help I would advise you to [contact WooCommerce support](https://woocommerce.com/my-account/create-a-ticket/) for further help and investigation.
