### ISSUE TITLE
Reorganize front-end files, to have a dedicated pages folder

### ISSUE THREAD

**Issue by tomalec** [woocommerce/google-listings-and-ads#195]
_This is an issue to continue a discussion on pages folder started at https://github.com/woocommerce/google-listings-and-ads/pull/192#issuecomment-773084286_

@eason9487 [wrote](https://github.com/woocommerce/google-listings-and-ads/pull/192#issuecomment-773084286):
> Since we did not create a dedicated folder for pages, we can still have the alias for the js/src directory. And add a `pages` alias if we adjust the file structure for putting these pages together in the future.

@ecgan [wrote](https://github.com/woocommerce/google-listings-and-ads/pull/192#issuecomment-773108174):
> Yeah I agree that we should have a dedicated folder for pages, it would be easier to tell which ones are the entry point / components at the highest level. 😄

-----

Personally, I totally upvote this idea as well.

I think we can have a folder for pages that matches the navigation, like:

```
/js/src/
├── components/
├── css/
├── hooks/
├── pages/
│   ├── getting-started
│   ├── dashboard
│   ├── reports
│   │   ├── programs
│   │   └── products
│   ├── product-feed
│   └── settings
├── utils/
├── tasks/
└── wcdl/
```

It would help to:
- identify highest-level components and a relationship between individual components
- make folders smaller

## Doubts

- Should we put `setup-*` pages inside "Getting started", as they do not have their own menu entry after the plugin is set up?
- Shouldn't we have `hooks` per-component, or move them to utils?

## Additional comments

I think it would be good to move all the files with one PR, instead of adapting gradually.

//cc @haszari maybe you would like to comment on that as well.

**Comment by eason9487** [comment]
@puntope wrote in https://github.com/woocommerce/google-listings-and-ads/pull/1374#issuecomment-1084429913:

> 💅 Not related to this PR but after seeing your nice work in refactoring the cards to the components I was wondering if it would be even nicer to organize the components folder.
> 
> * Cards -> All the cards
> * Icons -> Icons
> * Controls -> Inputs / user interaction elements like inputs, selects, etc
> * Rest in the root...

I think it's also a good thought for this follow-up issue.
