### ISSUE TITLE
Add new products with rules to custom lable

### ISSUE THREAD

**Issue by kevin25** [woocommerce/google-listings-and-ads#1963]
## User story

New products will make the Google ads mess up. To avoid it, we need to add new products to a custom label for a new campaign. But now, there is no way to make it happen. Please add the rule for this

**Comment by mikkamp** [comment]
Hi Kevin,

Could you clarify what you mean by "New products will make the Google ads mess up". When a campaign is created it will be created for all products which have been synced to your Merchant Center account. When new products are added they will also be synced (unless you enable Do Not Sync & Show), and included in the campaign. Is that not the behaviour you are expecting.

If you would like to create a campaign for only a specific set of products such as a product category (or product tag), you can do so by selecting a product category page as the final URL in the step "Boost your Campaign". You can then define any specific assets relative to the campaign you are intending to create. Would that help prevent your campaigns from messing up when new products are added?

You are correct that we don't support any custom labels for campaigns. If you would like to see this added then the best place to request this is on the [Features Request page](https://woocommerce.com/feature-requests/google-listings-and-ads/), as that allows us to gauge interest, before choosing which features to develop.

I have added such a feature request here where you can add your vote: https://woocommerce.com/feature-request/limit-products-included-in-a-campaign/
Please also add any details to the request if you have a specific scenario which should be covered.

As such I'm going to close this issue as this repo is not intended for support requests.
