### ISSUE TITLE
Extend Target attribute

### ISSUE THREAD

**Issue by alexlii1971** [woocommerce/google-listings-and-ads#1969]
Hello,

I am quite confused why there is only 15 Target attribute in this plugin, and please check the screenshot to understand what I mean:

https://prnt.sc/Z1gofv46KjnP

Any way to extend the feature and enable more Target attributes? 

For example: 

Product highlight [product_highlight]

https://support.google.com/merchants/answer/9216100?hl=en

Thanks

**Comment by mikkamp** [comment]
Hi there,

The target attributes in the Attribute Mapping features are constant (based on the Google Listings & Ads attributes which can be set per product). However if you want to sync over additional product attributes to the Google Merchant center then you can use the filter [`woocommerce_gla_product_attribute_values`](https://github.com/woocommerce/google-listings-and-ads/blob/2.4.6/src/Hooks/README.md#woocommerce_gla_product_attribute_values). Additional key / value pairs can be added to the list of attributes using this filter.

In your case that would be a key value of `productHighlights` and an array of strings for the value, see [here](https://developers.google.com/shopping-content/reference/rest/v2.1/products#Product).

Although this repository is not intended for support requests. The best place to get help is with the [WordPress.org Google Listings and Ads forum](https://wordpress.org/support/plugin/google-listings-and-ads/) or if you have a WooCommerce.com account, you can start a chat or open a ticket on [WooCommerce.com support](https://woocommerce.com/my-account/create-a-ticket/). So I'll go ahead and close this issue now.
