### ISSUE TITLE
code snippet for adding More Google attribute ?

### ISSUE THREAD

**Issue by alexlii1971** [woocommerce/google-listings-and-ads#1973]
Hello,
I went through all of your official document, but I did not find a way to resolve the problem.

**there are only minimum 15 built-in Google Attribute in this plugin**: Adult, Age group, Brand, Color, Condition, Gender, GTIN, is Bundle, Material, MPN, Multipack, Pattern, Size, Size System, Size Type.

But,  Some of essential attributes are missing, and it is really a problem in practice,  for example, the following attributes are all used **by product-widely, but not site-widely.**

**1#  Capacity [capacity]**, it is essential attribute.
that is a must-use attribute for variety products.
https://support.google.com/manufacturers/answer/7495963?hl=en#:~:text=The%20capacity%20%5Bcapacity%5D%20attribute%20defines,1TB%20and%202TB%20storage%20sizes

**2# Sale price effective date [sale_price_effective_date]**
Again, it is essential attribute for sales promotion and campaign, you know there are always lots of season sales activity, especially, if target multiple countries.

https://support.google.com/merchants/answer/6324460?hl=en

**3# [custom_label]**
It is essential attribute to narrow down a group of attributes, and try to bid on different budget:
https://support.google.com/merchants/answer/6324473?hl=en

Here is a screenshot to show it is used:
https://prnt.sc/PyBA4TbuWKZU

Actually, there are other essential attributes are missing, like

 **4# [transit time label]**,

Because different product need different shipping method and shipped by different shipping carrier, the transit time vary a lot. If the transit time not reflect as the estimated delivery time, that will appeal as untrustworthy seller.

**5 # Product highlight [product_highlight]**
There are always different sales points and we spend lots of time to write Product highlight for each products, and usually, it works fine by other feed plugin, but there is no product_highlight attribute in this plugin.

   - rationale
Essential attributes are missing in list of Built-in Google attribute in the option of Target attribute

   - screenshots
   https://prnt.sc/IgwJnGqVn11L

   - examples
https://support.google.com/manufacturers/answer/7495963?hl=en#:~:text=The%20capacity%20%5Bcapacity%5D%20attribute%20defines,1TB%20and%202TB%20storage%20sizes

It would be great if you can add a full Google attribute list by Build-in. 

But if not.....alternative solutions would be **code snippet**, and **code snippet would be a fast way to achieve the purpose.**

Much appreciated.

**Comment by ianlin** [comment]
Thanks for reporting this issue. As in [README](https://github.com/woocommerce/google-listings-and-ads#support) this repo is not a place for support questions, the best place to get support is the [WordPress.org Google Listings and Ads forum](https://wordpress.org/support/plugin/google-listings-and-ads/) and I can see you've already [asked in the forum](https://wordpress.org/support/topic/how-to-extend-target-attributes). For feature request please visit https://woocommerce.com/feature-requests/google-listings-and-ads/.
