### ISSUE TITLE
New Feature Suggestion: "Unsync & Visible" Action for Google Listings & Ads Plugin

### ISSUE THREAD

**Issue by loaishar** [woocommerce/google-listings-and-ads#1992]
Dear WooCommerce Team,

I am writing to suggest a new feature that could potentially enhance the flexibility and user experience of the Google Listings & Ads plugin. This suggestion arises from a specific requirement we have encountered in our e-commerce operation, which we believe might be beneficial to other WooCommerce users as well.

Our requirement revolves around the use of product images in Google Ads. Currently, we use variant swatch images for our products, but we wish to utilize more attractive, "fancy" images for our Google Ads. We understand the importance of schema markup data consistency, but we also see an opportunity for flexibility here.

To this end, we suggest adding a new action in the product synchronization process, which we would like to call "Unsync & Visible." This action would allow products to unsync from future changes after they are initially synced, enabling users to make changes on the Merchant Center listing without these changes being overridden. Importantly, the products would remain visible on the website throughout this process.

We believe this feature would provide the right balance between data consistency for Google and the operational flexibility required by WooCommerce store owners. It could significantly enhance the control we have over our product listings and their presentation in Google Ads.

Please consider this suggestion for a future update of the Google Listings & Ads plugin. I have added this feature request to the plugin's GitHub page for further community discussion and potential consideration by the plugin developers.

Thank you for your time and consideration.

Best regards,
Loai

**Comment by martynmjones** [comment]
Hey @loaishar,

Many thanks for your contribution and for sharing your thoughts on feature improvements in Google Listings and Ads.

The extension needs to ensure there is consistency between the listing on the website and the data held by Google for any product listings so an option to prevent product updates from being sent to Google could lead to a number of issues and potentially lead to listings being refused depending on how it was used.

However, I appreciate that it would be beneficial to have more control over what images are used in listings on Google and we have opened an issue for that: [More control over product images #1991](https://github.com/woocommerce/google-listings-and-ads/issues/1991). I'm not able to say if/ when features may be implemented in that area but please do subscribe to the issue if you'd like to receive updates via email whenever any updates are made on it.

To avoid duplication I'm closing this issue but thank you again for the suggestion!
