### ISSUE TITLE
Unable to get the exact error reason for the failed phone number verification request

### ISSUE THREAD

**Issue by eason9487** [woocommerce/google-listings-and-ads#1998]
### Describe the bug:

It's a follow-up for us to occasionally revisit if the exact error reason is returned in the future.

Originally, if a phone number verification request fails, the `reason` field in the response body provides a clear code. For example, `"rateLimitExceeded"`.

However, currently, Google's [Content API for Shopping](https://developers.google.com/shopping-content/reference/rest/v2.1/accounts/requestphoneverification) returns unclear reason, making it impossible to distinguish the actual cause of the error.

![1](https://github.com/woocommerce/google-listings-and-ads/assets/17420811/4fa6ced9-df22-45b3-9e96-7c32fbb39a03)

On GLA side, the response body of API results in:

```json
{
  "message": "Internal error",
  "reason":  "backendError"
}
```

### Steps to reproduce:

1. Go to the phone number editing page: `/wp-admin/admin.php?page=wc-admin&subpath=%2Fedit-phone-number&path=%2Fgoogle%2Fsettings`
2. Open the Network tab of browser DevTool.
3. Trigger an API failure by one of these methods
   - Request verification with an invalid phone number: +31 111111111
   - Request verification with the same phone number within an hour six times.
4. Inspect the result of `gla/mc/phone-verification/request` on the Network tab.

If someday the `reason` value is "rateLimitExceeded" or "badRequest" and the `message` is clearer, maybe then this issue can be solved.

### Expected behavior:

Show the exact error reason for the failed phone number verification request.

### Actual behavior:

Unable to get the exact error reason for the failed phone number verification request.

### Additional details:

Found this issue while working on #1101

**Comment by mikkamp** [comment]
Phone number verification is being removed in #2653 so I'm closing this issue as no longer applicable.
