### ISSUE TITLE
Current Deprecated warnings as of version 2.5.0

### ISSUE THREAD

**Issue by kaushikasomaiya** [woocommerce/google-listings-and-ads#2021]
6566329-zen

Just reporting these here so that we can consider fixing them in the future.

> Deprecated: Using ${var} in strings is deprecated, use {$var} instead in /Applications/MAMP/htdocs/woogenerator/sites/wp-5373570/wp-content/plugins/google-listings-and-ads/src/Admin/Product/Attributes/AttributesTab.php on line 105

> Deprecated: Using ${var} in strings is deprecated, use {$var} instead in /Applications/MAMP/htdocs/woogenerator/sites/wp-5373570/wp-content/plugins/google-listings-and-ads/src/Admin/Product/Attributes/AttributesTab.php on line 112

> Deprecated: Using ${var} in strings is deprecated, use {$var} instead in /Applications/MAMP/htdocs/woogenerator/sites/wp-5373570/wp-content/plugins/google-listings-and-ads/src/Admin/MetaBox/ChannelVisibilityMetaBox.php on line 108

> Deprecated: Using ${var} in strings is deprecated, use {$var} instead in /Applications/MAMP/htdocs/woogenerator/sites/wp-5373570/wp-content/plugins/google-listings-and-ads/src/Admin/MetaBox/ChannelVisibilityMetaBox.php on line 115

> Deprecated: Using ${var} in strings is deprecated, use {$var} instead in /Applications/MAMP/htdocs/woogenerator/sites/wp-5373570/wp-content/plugins/google-listings-and-ads/src/Admin/MetaBox/CouponChannelVisibilityMetaBox.php on line 113

> Deprecated: Using ${var} in strings is deprecated, use {$var} instead in /Applications/MAMP/htdocs/woogenerator/sites/wp-5373570/wp-content/plugins/google-listings-and-ads/src/Admin/MetaBox/CouponChannelVisibilityMetaBox.php on line 120

> Deprecated: Creation of dynamic property Automattic\WooCommerce\GoogleListingsAndAds\Proxies\WC::$allowed_countries is deprecated in /Applications/MAMP/htdocs/woogenerator/sites/wp-5373570/wp-content/plugins/google-listings-and-ads/src/Proxies/WC.php on line 55

**Comment by mikkamp** [comment]
Thanks for the report. Just wanted to add that these are PHP 8.2 deprecation warnings.
