### ISSUE TITLE
Deprecation warning from onboarding task

### ISSUE THREAD

**Issue by mikkamp** [woocommerce/google-listings-and-ads#2024]
### Describe the bug:
With PHP 8.2 I get the following deprecation warning:

```
[25-Jul-2023 10:11:59 UTC] PHP Deprecated:  Creation of dynamic property Automattic\WooCommerce\Admin\Features\OnboardingTasks\DeprecatedExtendedTask::$title is deprecated in wp-content/plugins/woocommerce/src/Admin/Features/OnboardingTasks/DeprecatedExtendedTask.php on line 66
```

It seems the creation of the dynamic property is already being resolved in PR https://github.com/woocommerce/woocommerce/pull/38774

However it makes me wonder why we are triggering the DeprecatedExtendedTask class to be used. I initially thought it could be related to the Onboarding Wizard which was introduced in WooCommerce 7.9: p6q7sZ-e5D-p2
It seems the DeprecatedExtendedTask has been around longer than that.

We add the onboarding task here: https://github.com/woocommerce/google-listings-and-ads/blob/2.5.0/js/src/tasks/complete-setup/index.js#L17

So my question is whether that filter is still valid or if we need to be using a different method not to trigger any deprecated classes?

### Steps to reproduce:
1. Run the plugin on a site with PHP 8.2 and debug logging enabled 
2. Notice the deprecation message when loading the Google Listings and Ads page

**Comment by tomalec** [comment]
After a brief investigation it seems the `woocommerce_admin_onboarding_task_list` filter was [deprecated](https://github.com/woocommerce/woocommerce/blob/trunk/packages/js/data/src/onboarding/deprecated-tasks.ts#L47-L50) in https://github.com/woocommerce/woocommerce-admin/pull/7918
in favor of [`TaskLists::add_task`](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce-admin/docs/features/onboarding-tasks.md)

Even though the filter is still the recommended way by the docs in https://developer.woocommerce.com/extension-developer-guide/handling-merchant-onboarding/#. Docs issue reported at https://github.com/woocommerce/woocommerce/issues/33293

I think we can move completely to PHP-based task and remove the need for https://github.com/woocommerce/google-listings-and-ads/blob/trunk/src/TaskList/CompleteSetup.php#L71:L71
