### ISSUE TITLE
Item ID by SKU number

### ISSUE THREAD

**Issue by kaoopro** [woocommerce/google-listings-and-ads#2029]
pls change Item ID to SKU number. don't like "gla_27364". it will issue don't match with SEO product and conversion for google ads

**Comment by jorgemd24** [comment]
Hey, @kaoopro, thanks for getting in touch!

We are looking into this option, but implementing it is not a straightforward task, as it could have an impact on any running Ads campaigns and reporting.

If you happen to be a developer, you can make changes to the product offer ID using the below filter:

https://github.com/woocommerce/google-listings-and-ads/blob/de3a88952bebf5c2c708c7b0e6efa3f83f88fce8/src/Product/WCProductAdapter.php#L280

Moreover, you have the option to customize how the plugin maps with the correct product ID (in your case, the SKU) using the filter mentioned here:

https://github.com/woocommerce/google-listings-and-ads/blob/a185cf952e21a8a622eac12df1769aacb0912a5a/src/Product/ProductHelper.php#L278

But please note that these changes will only affect new products.

It would be fantastic if you could suggest this new feature in the [Google Listings and Ads Requests](https://woocommerce.com/feature-requests/google-listings-and-ads/). This way, other merchants can vote for it, allowing us to prioritize this task accordingly.

Thanks!
