### ISSUE TITLE
Delete products are not deleted in Google Merchant Center

### ISSUE THREAD

**Issue by kevin25** [woocommerce/google-listings-and-ads#2032]
### Describe the bug:

I delete products are no deleted in Google Merchant Center. I tried to delete them on Google Shopping either. But for no reason, they came back to Google Merchant Center again and again. 

We got the disapproval then with follow issues:

Mismatched value (page crawl) [price]
Unavailable mobile landing page
Unavailable Desktop landing page

### Steps to reproduce:

1. Delete the product
2. Check Google Merchant Center and not removed. Checked schedule action and process it. (I also had issue with this and some of the actions were failed) 
3. The deleted products returned to Google Merchant Center

`2023-08-01T04:05:23+00:00 ERROR Automattic\WooCommerce\GoogleListingsAndAds\Product\ProductSyncer::handle_delete_errors Attempted to delete product "online:en:US:gla_1631825" (WooCommerce Product ID: 1631825) but it did not exist in Google Merchant Center, removing the synced product ID from database.
2023-08-01T04:05:23+00:00 ERROR Automattic\WooCommerce\GoogleListingsAndAds\Product\ProductSyncer::handle_delete_errors Attempted to delete product "online:en:US:gla_1631826" (WooCommerce Product ID: 1631826) but it did not exist in Google Merchant Center, removing the synced product ID from database.
2023-08-01T04:05:23+00:00 ERROR Automattic\WooCommerce\GoogleListingsAndAds\Product\ProductSyncer::handle_delete_errors Attempted to delete product "online:en:US:gla_1631827" (WooCommerce Product ID: 1631827) but it did not exist in Google Merchant Center, removing the synced product ID from database.
2023-08-01T04:05:23+00:00 ERROR Automattic\WooCommerce\GoogleListingsAndAds\Product\ProductSyncer::handle_delete_errors Attempted to delete product "online:en:US:gla_1631828" (WooCommerce Product ID: 1631828) but it did not exist in Google Merchant Center, removing the synced product ID from database.
2023-08-01T04:05:23+00:00 ERROR Automattic\WooCommerce\GoogleListingsAndAds\Product\ProductSyncer::handle_delete_errors Attempted to delete product "online:en:US:gla_1631829" (WooCommerce Product ID: 1631829) but it did not exist in Google Merchant Center, removing the synced product ID from database.
2023-08-01T04:05:23+00:00 ERROR Automattic\WooCommerce\GoogleListingsAndAds\Product\ProductSyncer::handle_delete_errors Attempted to delete product "online:en:US:gla_1631830" (WooCommerce Product ID: 1631830) but it did not exist in Google Merchant Center, removing the synced product ID from database.
2023-08-01T04:05:23+00:00 ERROR Automattic\WooCommerce\GoogleListingsAndAds\Product\ProductSyncer::handle_delete_errors Attempted to delete product "online:en:US:gla_1631831" (WooCommerce Product ID: 1631831) but it did not exist in Google Merchant Center, removing the synced product ID from database.
2023-08-01T04:05:23+00:00 ERROR Automattic\WooCommerce\GoogleListingsAndAds\Product\ProductSyncer::handle_delete_errors Attempted to delete product "online:en:US:gla_1631832" (WooCommerce Product ID: 1631832) but it did not exist in Google Merchant Center, removing the synced product ID from database.
2023-08-01T03:33:22+00:00 DEBUG Automattic\WooCommerce\GoogleListingsAndAds\MerchantCenter\MerchantStatuses::filter_valid_statuses A Google ID was not found in Merchant Center.
2023-08-01T03:33:22+00:00 DEBUG Automattic\WooCommerce\GoogleListingsAndAds\MerchantCenter\MerchantStatuses::filter_valid_statuses A Google ID was not found in Merchant Center.
2023-08-01T03:33:22+00:00 DEBUG Automattic\WooCommerce\GoogleListingsAndAds\MerchantCenter\MerchantStatuses::filter_valid_statuses A Google ID was not found in Merchant Center.
2023-08-01T03:33:22+00:00 DEBUG Automattic\WooCommerce\GoogleListingsAndAds\MerchantCenter\MerchantStatuses::filter_valid_statuses A Google ID was not found in Merchant Center.
2023-08-01T03:33:22+00:00 DEBUG Automattic\WooCommerce\GoogleListingsAndAds\MerchantCenter\MerchantStatuses::filter_valid_statuses A Google ID was not found in Merchant Center.
2023-08-01T03:33:22+00:00 DEBUG Automattic\WooCommerce\GoogleListingsAndAds\MerchantCenter\MerchantStatuses::filter_valid_statuses A Google ID was not found in Merchant Center.
2023-08-01T03:33:22+00:00 DEBUG Automattic\WooCommerce\GoogleListingsAndAds\MerchantCenter\MerchantStatuses::filter_valid_statuses A Google ID was not found in Merchant Center.
2023-08-01T03:33:22+00:00 DEBUG Automattic\WooCommerce\GoogleListingsAndAds\MerchantCenter\MerchantStatuses::filter_valid_statuses A Google ID was not found in Merchant Center.
2023-08-01T03:33:22+00:00 DEBUG Automattic\WooCommerce\GoogleListingsAndAds\MerchantCenter\MerchantStatuses::filter_valid_statuses A Google ID was not found in Merchant Center.
2023-08-01T03:33:22+00:00 DEBUG Automattic\WooCommerce\GoogleListingsAndAds\MerchantCenter\MerchantStatuses::filter_valid_statuses A Google ID was not found in Merchant Center.
2023-08-01T03:33:22+00:00 DEBUG Automattic\WooCommerce\GoogleListingsAndAds\MerchantCenter\MerchantStatuses::filter_valid_statuses A Google ID was not found in Merchant Center.`

### Expected behavior:

The deleted products should have been removed permanently. 

### Actual behavior:

The deleted products returned back to Google Merchant Center. I tried to remove them from Google Merchant Center again and again. 

### Additional details:

`
### WordPress Environment ###

WordPress address (URL): https://www.domain.com
Site address (URL): https://www.domain.com
WC Version: 7.9.0
REST API Version: ✔ 7.9.0
WC Blocks Version: ✔ 10.4.6
Action Scheduler Version: ✔ 3.6.1
Log Directory Writable: ✔
WP Version: 6.2.2
WP Multisite: –
WP Memory Limit: 6 GB
WP Debug Mode: ✔
WP Cron: –
Language: en_US
External object cache: –

### Server Environment ###

Server Info: nginx/1.24.0
PHP Version: 7.4.33
PHP Post Max Size: 128 MB
PHP Time Limit: 300000
PHP Max Input Vars: 3000
cURL Version: 7.74.0
OpenSSL/1.1.1n

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.9.7-MariaDB-1:10.9.7+maria~deb11
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.9.0
WC Database Prefix: wp_
Total Database Size: 3142.40MB
Database Data Size: 1652.74MB
Database Index Size: 1489.66MB
wp_woocommerce_sessions: Data: 24.06MB + Index: 9.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 2.52MB + Index: 1.52MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 25.56MB + Index: 23.08MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 4.14MB + Index: 3.16MB + Engine InnoDB
wp_actionscheduler_claims: Data: 1.36MB + Index: 0.27MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 205.73MB + Index: 111.20MB + Engine InnoDB
wp_automatewoo_abandoned_carts: Data: 1.02MB + Index: 0.08MB + Engine InnoDB
wp_automatewoo_customers: Data: 1.52MB + Index: 2.70MB + Engine InnoDB
wp_automatewoo_customer_meta: Data: 0.09MB + Index: 0.09MB + Engine InnoDB
wp_automatewoo_guests: Data: 1.52MB + Index: 2.16MB + Engine InnoDB
wp_automatewoo_guest_meta: Data: 3.52MB + Index: 4.03MB + Engine InnoDB
wp_automatewoo_logs: Data: 9.52MB + Index: 13.42MB + Engine InnoDB
wp_automatewoo_log_meta: Data: 52.59MB + Index: 45.84MB + Engine InnoDB
wp_automatewoo_queue: Data: 1.02MB + Index: 0.20MB + Engine InnoDB
wp_automatewoo_queue_meta: Data: 1.02MB + Index: 2.03MB + Engine InnoDB
wp_cfw_acr_carts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_cky_banners: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_cky_cookies: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_cky_cookie_categories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_commentmeta: Data: 0.06MB + Index: 0.14MB + Engine InnoDB
wp_comments: Data: 8.52MB + Index: 15.61MB + Engine InnoDB
wp_ewwwio_queue: Data: 1.52MB + Index: 0.28MB + Engine InnoDB
wp_e_events: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_e_submissions: Data: 0.02MB + Index: 0.27MB + Engine InnoDB
wp_e_submissions_actions_log: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_e_submissions_values: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gla_attribute_mapping_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gla_budget_recommendations: Data: 0.20MB + Index: 0.11MB + Engine InnoDB
wp_gla_merchant_issues: Data: 1.02MB + Index: 0.00MB + Engine InnoDB
wp_gla_shipping_rates: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_gla_shipping_times: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_iconic_woo_linked_variations: Data: 0.19MB + Index: 0.00MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_litespeed_avatar: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_litespeed_img_optming: Data: 0.44MB + Index: 1.72MB + Engine InnoDB
wp_litespeed_url: Data: 0.41MB + Index: 0.56MB + Engine InnoDB
wp_litespeed_url_file: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_nf3_actions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_nf3_action_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_nf3_chunks: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_nf3_fields: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_nf3_field_meta: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_nf3_forms: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_nf3_form_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_nf3_objects: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_nf3_object_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_nf3_relationships: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_nf3_upgrades: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 220.53MB + Index: 22.16MB + Engine InnoDB
wp_oses_attachments: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_oses_clicks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_oses_emails: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_oses_email_attachments: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_oses_failures: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_oses_jobs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_pinterest_automatic: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_postmeta: Data: 680.47MB + Index: 949.25MB + Engine InnoDB
wp_posts: Data: 173.61MB + Index: 62.72MB + Engine InnoDB
wp_pys_stat_landing: Data: 0.19MB + Index: 0.00MB + Engine InnoDB
wp_pys_stat_order: Data: 0.19MB + Index: 0.00MB + Engine InnoDB
wp_pys_stat_product_order: Data: 0.47MB + Index: 0.00MB + Engine InnoDB
wp_pys_stat_traffic: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_pys_stat_utm_campaing: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_pys_stat_utm_content: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_pys_stat_utm_medium: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_pys_stat_utm_source: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_pys_stat_utm_term: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_rank_math_404_logs: Data: 0.06MB + Index: 0.05MB + Engine InnoDB
wp_rank_math_analytics_ga: Data: 10.02MB + Index: 10.16MB + Engine InnoDB
wp_rank_math_analytics_gsc: Data: 101.14MB + Index: 132.92MB + Engine InnoDB
wp_rank_math_analytics_inspections: Data: 41.58MB + Index: 3.47MB + Engine InnoDB
wp_rank_math_analytics_keyword_manager: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_rank_math_analytics_objects: Data: 4.16MB + Index: 1.22MB + Engine InnoDB
wp_rank_math_internal_links: Data: 4.52MB + Index: 2.52MB + Engine InnoDB
wp_rank_math_internal_meta: Data: 1.52MB + Index: 0.00MB + Engine InnoDB
wp_rank_math_redirections: Data: 1.52MB + Index: 0.02MB + Engine InnoDB
wp_rank_math_redirections_cache: Data: 1.52MB + Index: 0.23MB + Engine InnoDB
wp_revslider_css: Data: 0.13MB + Index: 0.02MB + Engine InnoDB
wp_revslider_css_bkp: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_revslider_layer_animations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_revslider_layer_animations_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_revslider_navigations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_revslider_navigations_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_revslider_sliders: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_revslider_sliders_bkp: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_revslider_slides: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_revslider_slides_bkp: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_revslider_static_slides: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_revslider_static_slides_bkp: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_shopmagic_automation_outcome: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_shopmagic_automation_outcome_logs: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_shopmagic_cart: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_shopmagic_guest: Data: 0.34MB + Index: 0.00MB + Engine InnoDB
wp_shopmagic_guest_meta: Data: 3.52MB + Index: 1.52MB + Engine InnoDB
wp_shopmagic_marketing_lists: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_shopmagic_optin_email: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_termmeta: Data: 0.13MB + Index: 0.28MB + Engine InnoDB
wp_terms: Data: 0.06MB + Index: 0.09MB + Engine InnoDB
wp_term_relationships: Data: 10.19MB + Index: 6.19MB + Engine InnoDB
wp_term_taxonomy: Data: 0.09MB + Index: 0.06MB + Engine InnoDB
wp_usermeta: Data: 5.47MB + Index: 11.45MB + Engine InnoDB
wp_users: Data: 0.28MB + Index: 0.38MB + Engine InnoDB
wp_viwec_clicked: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_vi_woo_orders_tracking_track_info: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wcpdf_invoice_number: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 1.52MB + Index: 1.70MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.06MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 2.50MB + Index: 1.44MB + Engine InnoDB
wp_wc_order_stats: Data: 2.52MB + Index: 0.97MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 1.52MB + Index: 0.52MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 7.17MB + Index: 5.14MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 17.55MB + Index: 28.05MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_product_tags: Data: 1.52MB + Index: 0.88MB + Engine InnoDB
wp_woocommerce_tags: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woof_query_cache: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wotv_woo_track_info: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpmailsmtp_debug_events: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_wpmailsmtp_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpmelon_advbedit_temp: Data: 0.20MB + Index: 0.00MB + Engine InnoDB
wp_wpr_rocket_cache: Data: 3.28MB + Index: 3.55MB + Engine InnoDB
wp_wpr_rucss_used_css: Data: 3.48MB + Index: 3.92MB + Engine InnoDB
wp_wt_iew_action_history: Data: 0.17MB + Index: 0.00MB + Engine InnoDB
wp_wt_iew_mapping_template: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_yith_wcwl: Data: 0.08MB + Index: 0.02MB + Engine InnoDB
wp_yith_wcwl_lists: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
_mig_wpmdb_alter_statements: Data: 0.02MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

attachment: 89675
aw_workflow: 48
awdp_pt_rules: 1
cpt_iconic_wlv: 955
ct_size_guide: 59
custom_css: 1
elementor_library: 1
hl_highlight_product: 4
intro_introduction: 2
nav_menu_item: 66
oembed_cache: 7
page: 42
post: 23
product: 11092
product_variation: 88736
rank_math_schema: 1
revision: 3
saswp: 4
shop_coupon: 3201
shop_order: 10431
shop_order_refund: 488
shopmagic_automation: 1
size-chart: 11
viwec_template: 18
viwec_template_block: 2
wallet_withdrawal: 1
wcpa_pt_forms: 1
wpcf7_contact_form: 2
wpclv: 1136
yaymail_template: 76
yith_wcan_preset: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (47) ###

Advanced Database Cleaner PRO: by Younes JFR. – 3.2.2
AutomateWoo: by WooCommerce – 6.0.0
Contact Form 7: by Takayuki Miyoshi – 5.7.7
createIT Size Guide Plugin: by createIT – 4.0
YayMail Premium Addon for  AutomateWoo: by YayCommerce – 1.7.1
Instant Indexing: by Rank Math – 1.1.17
Stuff for Gecko Theme Offical: by Kevin – 1.3
Google Listings and Ads: by WooCommerce – 2.5.0
Goya Core: by Everthemes – 1.0.8.1
Highlight Product: by Henry – 1.0
Index WP MySQL For Speed: by Oliver Jones
Rick James – 1.4.13

Introduction: by Henry – 1.0.0
WPBakery Page Builder: by Michael M - WPBakery.com – 6.13.0
Kirki Customizer Framework: by Themeum – 4.2.0
Meta Box: by MetaBox.io – 5.7.4
PayPal for WooCommerce: by Angell EYE – 4.0.15
PixelYourSite Microsoft UET (Bing): by PixelYourSite – 3.1.4
PixelYourSite PRO: by PixelYourSite – 9.7.1
Product Catalog Feed Pro by PixelYourSite: by PixelYourSite – 5.3.3
Product Import Export for WooCommerce: by WebToffee – 2.3.2
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 3.1.5
SalesGen - Change Product Title on payment Paypal & Stripe: by salesgen.io – 0.9.3
Rank Math SEO PRO: by Rank Math – 3.0.40
Rank Math SEO: by Rank Math – 1.0.119.1
Tawk.to Live Chat: by Tawkto – 0.8.0
Trustpilot-reviews: by Trustpilot – 2.5.914
User Role Editor: by Vladimir Garagulya – 4.63.3
WebP Express: by Bjørn Rosell – 0.25.6
Woocommerce Custom Product Addons (5.x.x): by Acowebs – 5.0.14
Variation Swatches for WooCommerce: by Emran Ahmed – 2.0.24
WooCommerce Advanced Bulk Edit: by George Iron & Yas G. – 5.1
WooCommerce Custom Indexes: by WooCommerce – 1.0.0
WooCommerce Stripe Gateway: by WooCommerce – 7.4.1
Advanced Order Export For WooCommerce (Pro): by AlgolPlus – 3.3.2
WooCommerce Orders Tracking Premium: by VillaTheme – 1.1.7
PDF Invoices & Packing Slips for WooCommerce: by WP Overnight – 3.5.6
WooCommerce Photo Reviews Premium: by VillaTheme – 1.3.10
WooCommerce Table Rate Shipping: by Bolder Elements – 4.2.1
WooCommerce: by Automattic – 7.9.0
WordPress Importer: by wordpressdotorg – 0.8.1
WP Mail SMTP Pro: by WP Mail SMTP – 3.8.1
WP Rocket | Deactivate WooCommerce Refresh Cart Fragments Cache: by WP Rocket Support Team –
WP Rocket: by WP Media – 3.14
WPC Linked Variation for WooCommerce: by WPClever – 4.1.0
Related Products for WooCommerce: by WebToffee – 1.4.9
YayMail - WooCommerce Email Customizer: by YayCommerce – 3.3
YITH WooCommerce Wishlist: by YITH – 3.23.0

### Inactive Plugins (38) ###

Acowebs Woocommerce Dynamic Pricing Pro: by Acowebs – 5.1.1
Action Scheduler High Volume: by Prospress Inc. – 1.1.0
Asset CleanUp Pro: Page Speed Booster: by Gabe Livan – 1.2.3.1
Autocomplete Google Address: by Md Nishath Khandakar – 1.9.5
AutomateWoo - Birthdays Add-on: by WooCommerce – 1.3.9
BEAF - Ultimate Before After Image Slider & Gallery: by Themefic – 4.3.22
bunny.net: by bunny.net – 1.0.8
CheckoutWC: by Objectiv – 8.2.0
CookieYes | GDPR Cookie Consent: by CookieYes – 3.1.1
DISABLE WP-Bakery: by Kevin – 1.0
Estimated Delivery Date Plugin For WooCommerce: by PluginHive – 2.1.3
Flying Analytics: by WP Speed Matters – 1.2.2
Google Authenticator: by Ivan Kruchkoff – 0.54
Google Autocomplete Pro Smart: by Nishath – 2.0.6
LiteSpeed Cache: by LiteSpeed Technologies – 5.5
Microsoft Clarity: by Microsoft – 0.9.2
Mobile Featured Image: by ryanshoover – 0.1
MultiStep Checkout for WooCommerce: by ThemeHigh – 2.2.2
Object Cache 4 everyone: by fpuenteonline – 1.2
Pinterest for WooCommerce: by WooCommerce – 1.3.5 (update to version 1.3.6 is available)
PixelYourSite Pinterest: by PixelYourSite – 4.2.1
PixelYourSite Super Pack: by PixelYourSite – 3.2.0
Product Feed PRO for WooCommerce: by AdTribes.io – 12.7.8
Product Size Charts Plugin for WooCommerce: by theDotstore – 2.4.3.1
Proxy Cache Purge: by Mika Epstein – 5.1.3
Purge Varnish: by Dsingh <dev.firoza@gmail.com> – 2.5
Query Monitor: by John Blackbourn – 3.13.1
Redis Object Cache: by Till Krüss – 2.4.3
Sale Count: by Kevin – 1.0
SEO Image Optimizer: by XfinitySoft – 2.0.5
Slider Revolution: by ThemePunch – 6.6.14
Stripe Payment Plugin for WooCommerce: by WebToffee – 3.7.8
WC Ajax Product Filters: by Shamim Al Mamun – 4.2.0
WooCommerce Linked Variations by Iconic: by Iconic <info@iconicwp.com> – 1.3.0
WOOF - WooCommerce Products Filter: by realmag777 – 2.2.6.4
Woo Product Tags: by Kevin Nguyen – 1.5
WP Offload SES: by Delicious Brains – 1.5.6
WP Rocket | Disable Cache Clearing: by WP Rocket Support Team –

### Dropin Plugins (1) ###

advanced-cache.php: advanced-cache.php

### Must Use Plugins (1) ###

Index WP MySQL For Speed Upgrade Filter for mu-plugins.: by  – 1.4.10

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: –
HPOS feature screen enabled: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### WC Pages ###

Shop base: #6 - /shop/
Cart: #7 - /cart/
Checkout: #8 - /checkout/
My account: #9 - /my-account/
Terms and conditions: #135 - /terms-of-service/

### Theme ###

Name: Goya Child Theme
Version: 1.0
Author URL: http://themeforest.net/user/luisvelaz
Child Theme: ✔
Parent Theme Name: Goya
Parent Theme Version: 1.0.8.7
Parent Theme Author URL: https://themeforest.net/user/everthemess
WooCommerce Support: ✔

### Templates ###

Overrides: goya/woocommerce/archive-product.php
goya/woocommerce/cart/cart-empty.php
goya/woocommerce/cart/cart-shipping.php
goya/woocommerce/cart/cart.php
goya/woocommerce/cart/mini-cart.php
goya/woocommerce/cart/shipping-calculator.php
goya/woocommerce/checkout/form-checkout.php
goya/woocommerce/checkout/form-coupon.php
goya/woocommerce/checkout/form-login.php
goya/woocommerce/checkout/review-order.php
goya/woocommerce/content-product.php
goya/woocommerce/content-single-product.php
goya/woocommerce/global/form-login.php
goya/woocommerce/global/quantity-input.php
goya/woocommerce/global/wrapper-end.php
goya/woocommerce/global/wrapper-start.php
goya/woocommerce/loop/add-to-cart.php
goya/woocommerce/loop/loop-start.php
goya/woocommerce/loop/pagination.php
goya/woocommerce/myaccount/form-login.php
goya/woocommerce/myaccount/navigation.php
goya/woocommerce/order/tracking.php
goya/woocommerce/product-searchform.php
goya/woocommerce/single-product/photoswipe.php
goya/woocommerce/single-product/related.php
goya/woocommerce/single-product/tabs/tabs.php
goya/woocommerce/single-product/up-sells.php
goya/woocommerce/single-product-reviews.php
goya/woocommerce/content-product_cat.php

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
product-variation-management
settings
async-product-editor-category-field

Daily Cron: ❌ Not scheduled
Options: ✔
Notes: 67
Onboarding: completed

### Action Scheduler ###

Complete: 7,173
Oldest: 2023-07-29 08:50:48 +0000
Newest: 2023-08-01 04:38:03 +0000

Failed: 38
Oldest: 2023-07-29 18:12:15 +0000
Newest: 2023-08-01 00:38:13 +0000

Pending: 17
Oldest: 2023-08-01 04:39:02 +0000
Newest: 2023-08-04 06:22:04 +0000

### Status report information ###

Generated at: 2023-07-31 21:38:55 -07:00
`

**Comment by jorgemd24** [comment]
Hey, @kevin25, thanks for bringing this up!

Do you have any staging pages that might be re-uploading the products? 

Related to the errors that you provided, I noticed that the plugin is attempting to delete products in the merchant center, but it seems these products no longer exist there, hence the logged error.

```
"online:en:US:gla_1631825" (WooCommerce Product ID: 1631825) but it did not exist in Google Merchant Center, removing the synced product ID from database.
```

If you see in the code, every time a product is deleted the plugin make a request to delete the product in the Merchant center:

https://github.com/woocommerce/google-listings-and-ads/blob/de3a88952bebf5c2c708c7b0e6efa3f83f88fce8/src/Product/SyncerHooks.php#L141

https://github.com/woocommerce/google-listings-and-ads/blob/de3a88952bebf5c2c708c7b0e6efa3f83f88fce8/src/Product/SyncerHooks.php#L237-L244

This situation makes me wonder if the product is not actually deleted and might have a special status, could you check it?

Additionally, I want to mention that this repository isn't meant for support requests. For addressing such issues, the best approach is to seek assistance through the [WordPress.org Google Listings and Ads forum](https://wordpress.org/support/plugin/google-listings-and-ads/). Alternatively, if you have a WooCommerce.com account, you can initiate a [chat or open a support ticket on WooCommerce.com](https://woocommerce.com/my-account/create-a-ticket/).

To help the support team understand the issue better, consider including your system status report and providing additional details to reproduce the problem.

**Comment by kevin25** [comment]
All of them were removed completely. I can confirm that. But they just returned to Google Merchant Center again and again. I tried to delete them in Google Merchant Center and they keep returning back. This should be a bug.

**Comment by kevin25** [comment]
@jorgemd24  jorgemd24 This should be bug and need to be investigated. I deleted all those products. I disconnected my Merchant Account, deleted the API feed and re-connected it again. However, those products were returned to my Merchant center again and again. It should be still stored somewhere.
