### ISSUE TITLE
Option to connect Google Ads account after disconnection.

### ISSUE THREAD

**Issue by johndcoy** [woocommerce/google-listings-and-ads#2048]
### Is your feature request related to a problem? 

The expectation is for there to be an option within Marketing > GL&A > Settings to connect to an Google Ads. Currently, you have to initiate a new "Add paid campaign" to see an option to connect to a Google Ads account

#### How to reproduce the problem

1. Disconnect Google Ads account from Marketing > Google Listing & Ads > Settings
2. Attempt to reconnect Google Ads account.

### Describe the solution you'd like 

I think an option to connect an ads account from the settings page would be ideal. Currently, you have to ticket "Add paid campaign" to initiate a connection:

![Screenshot](https://d.pr/i/Ks56tB+)
Screenshot link: https://d.pr/i/Ks56tB

### Describe alternatives you've considered 

Alternatively, users can connect from the admin connection page:

/wp-admin/admin.php?page=connection-test-admin-page

Or they can start the new paid campaign process and abort after initiating a connection.

**Comment by jorgemd24** [comment]
Hello @johndcoy, thanks for reaching out!

I share your perspective on the user's convenience in being able to link their account without having to create a new campaign. [This subject has been discussed internally](p1652072876319049-slack-CK365S85V), but no steps have been implemented yet. Additionally, I've noticed that some merchants are also showing [support for this feature on the requests board](https://woocommerce.com/feature-request/option-to-sync-existing-smart-shopping-campaigns/).

For now, I'll close this issue in GitHub, as we monitor new feature requests through the [Google Listings and Ads Requests Dashboard](https://woocommerce.com/feature-request/option-to-sync-existing-smart-shopping-campaigns/). It would be fantastic if you could cast your vote for this new feature, as it would aid us in determining its priority, 

Thank you once more!
