### ISSUE TITLE
Product tags not working with Google attributes on variable products

### ISSUE THREAD

**Issue by sukafia** [woocommerce/google-listings-and-ads#2071]
### Describe the bug:

The attribute mapper supports mapping tags to Google product attributes. For instance, mapping tags as brand attributes. However, mapping tags to product attributes only works with simple products, the tags' taxonomy data isn't passed for variable products.

### Steps to reproduce:

1. Create a variable product with multiple variants and use tags to specify the brand (e.g. Woo)
2. Create a brand attribute rule and assign product tags

![ACDMVt.png](https://github.com/woocommerce/google-listings-and-ads/assets/60121732/91ef0455-dd25-47a1-bc00-ceb5b0be1712)

3. Allow the product to sync to Google Merchant Center and notice the brand isn't synced. (This causes the product to be flagged as missing brand attribute)
4. Repeat the above step for a simple product and notice the brand attribute is correctly synced.

### Expected behavior:

Mapping tags to Google product attributes should work for both simple and variable products.

### Actual behavior:

It only works for simple products. 

### Affected users

6632964-zd-a8c
6666355-zd-a8c

**Comment by eason9487** [comment]
Thanks for reporting this issue!

I can reproduce it with the given steps.

After a brief investigation, it's suspected the processing of the following code fragment may need adjustment.

https://github.com/woocommerce/google-listings-and-ads/blob/75f5d3c09897601134183e38dd8ff298d9ddba77/src/Product/WCProductAdapter.php#L1037-L1048

Both results of `$product->get_attribute( $taxonomy )` and `$parent->get_attribute( $taxonomy )` don't have associated product tags.

**Comment by eason9487** [comment]
Set to high priority as all taxonomies have the same issue with variable products.

![image](https://github.com/woocommerce/google-listings-and-ads/assets/17420811/e43a49a4-828e-446c-a3cc-f047bd40a04b)
