### ISSUE TITLE
E2E Tests failing with WooCommerce 8.1.0

### ISSUE THREAD

**Issue by martynmjones** [woocommerce/google-listings-and-ads#2095]
### Describe the bug:
A few of the E2E tests are failing when run against WooCommerce `8.1.0`. There is not an issue with any previous version.

![Screenshot 2023-09-14 at 12 49 39](https://github.com/woocommerce/google-listings-and-ads/assets/40762232/21ce4bfa-6f63-4f6c-b0ad-1c0250481f18)

### Steps to reproduce:
1. Checkout develop
2. `npm run wp-env:up`
3. `npm run test:e2e`
4. See errors

**Comment by puntope** [comment]
Checking

**Comment by puntope** [comment]
I tested the events in the store itself GLA 2.5.5 + WC 8.1.0 + TT2 and it tracking seems working. 

Seems like problem is the class "added" which is not anymore there

**Comment by puntope** [comment]
Another issue I'm still investigating is that sometimes GLA Id is undefined. THis also happens in the Shop. Not only in the tests

**Comment by puntope** [comment]
Hi @martynmjones 

I created a PR for this https://github.com/woocommerce/google-listings-and-ads/pull/2096
