### ISSUE TITLE
Promotions are not supported for all destinations in non US countries

### ISSUE THREAD

**Issue by mikkamp** [woocommerce/google-listings-and-ads#2113]
### Describe the bug:
Coupons (Promotions) can be synced to Google for the following list of countries: AU, CA, DE, FR, GB, IN, and US

The [API documentation](https://developers.google.com/shopping-content/reference/rest/v2.1/promotions?hl=en) shows there are more countries supported but we haven't enabled them yet in the extension, see: #1536 

However when trying to sync for another country (other than US) the following error is given:

```
Automattic\WooCommerce\GoogleListingsAndAds\Coupon\CouponSyncer::update Promotion failed to sync with Merchant Center:
```

```json
{
  "woocommerce_id": 1457,
  "errors": {
    "400": {
      "error": {
        "code": 400,
        "message": "[promotionDestinationIds] The given destination: surfaces_across_google is not supported in the chosen country.",
        "errors": [
          {
            "message": "[promotionDestinationIds] The given destination: surfaces_across_google is not supported in the chosen country.",
            "domain": "global",
            "reason": "badRequest"
          }
        ],
        "status": "INVALID_ARGUMENT",
        "details": [
          {
            "@type": "type.googleapis.com\/google.rpc.ErrorInfo",
            "reason": "invalid",
            "domain": "global"
          }
        ]
      }
    }
  },
  "google_target_country": "GB"
}
```

We don't actually set the `promotionDestinationIds` in the request so we expect it to apply for all destinations. Which according to the error is `surfaces_across_google`.

If I go to the Merchant Center and manually create a promotion I can see that for US the following destinations are supported:
![image](https://github.com/woocommerce/google-listings-and-ads/assets/11388669/06ca9502-57ba-4cd1-bf97-9d4a48efd491)

Whereas other countries only support Shopping Ads:
![image](https://github.com/woocommerce/google-listings-and-ads/assets/11388669/0e0aed41-f9b8-4e10-9876-5bfb44d74211)

I tested this out by setting only Shopping Ads when syncing a coupon through the following code:
```php
$this->setPromotionDestinationIds(
	[
		'Shopping_ads',
	]
);
```

Which allowed me to successfully sync a coupon for the United Kingdom. So it seems we need to explicitly set the destinations based on the promotion country. 

Based on the Google Merchant Center dashboard, only the following countries support Free Listings as destination:
- Brazil
- Italy
- Japan
- Netherlands
- South Korea
- Spain
- United States

### Steps to reproduce:
1. Set the store base country to United Kingdom and Currency to British Pounds 
2. Include United Kingdom in the list of target countries (Marketing > Google Listings & Ads, edit button for Free listings)
3. Edit / Update a coupon and wait for the sync to complete
4. Check the GLA logs and confirm there is an error with syncing the coupon

**Comment by darcie** [comment]
Ticket ref: 7084840-zen

**Comment by puntope** [comment]
7096472-zd-a8c

Also affected by this

**Comment by bunny-ug** [comment]
To whom this issue is assigned?
@puntope @mikkamp

**Comment by puntope** [comment]
> To whom this issue is assigned? @puntope @mikkamp

Hi @bunny-ug we are still discussing this with the Google team, that's why it's not assigned yet.

**Comment by puntope** [comment]
Adding Google Response about the coupons countries config:

```
Country Language Destination
Australia en Shopping_ads
Brazil pt, en Shopping_ads, Free_listings
Canada en, fr Shopping_ads
France en, fr Shopping_ads
Germany en, de Shopping_ads
India en Shopping_ads
Italy en, it Shopping_ads, Free_listings
Japan en, jp Shopping_ads, Free_listings
Netherlands en, nl Shopping_ads, Free_listings
South Korea en, kr Shopping_ads, Free_listings
Spain en, es Shopping Ads, Free Listings
GB en Shopping Ads
US en Shopping Ads, Free Listings, Local Inventory Ads
```

**Comment by bunny-ug** [comment]
@puntope Please release this, We are facing the issue.

**Comment by bunny-ug** [comment]
@mikkamp Please release the changes, It already been more than a week

**Comment by puntope** [comment]
Hello, @bunny-ug The releases are normally done on Tuesdays/Wednesdays but this is not necessarily happening every week. Also, we don't usually release the extension by request. 

In any case,[ the new version 2.5.10 ](https://github.com/woocommerce/google-listings-and-ads/releases/tag/2.5.10) is adding the enhancement you were waiting for.

**Comment by bunny-ug** [comment]
I believe Bug fixes should not have to be released on any request, they have to be released once they are resolved. As they are affecting thousands of users. @puntope

**Comment by bunny-ug** [comment]
> Hello, @bunny-ug The releases are normally done on Tuesdays/Wednesdays but this is not necessarily happening every week. Also, we don't usually release the extension by request.
> 
> In any case,[ the new version 2.5.10 ](https://github.com/woocommerce/google-listings-and-ads/releases/tag/2.5.10) is adding the enhancement you were waiting for.

Thanks

**Comment by puntope** [comment]
> I believe Bug fixes should not have to be released on any request, they have to be released once they are resolved. As they are affecting thousands of users. @puntope

Hi @bunny-ug , thanks for the feedback. Yes we do have a policy to release security bugs or any other critical bugs as soon as they are fixed. But that doesn't necessarily apply to all the enhancements, tweaks (or even bugs) in the extension. I understand this certainly has a big impact on your business needs, but in our registers, this was not having a massive impact on the users yet. Just for context, this issue was more of an enhancement than a bug as Google released support for some new countries and a strict Destination policy just recently. 

The release process can be on hold sometimes because of the following reasons:

- Not enough amount of changes, fixes, or enhancements.
- Excessive workload.
- Some other internal reason. 

For the next time, we politely ask you to patiently wait for the releases. (You can follow the releases [here](https://github.com/woocommerce/google-listings-and-ads/releases)) and avoid pinging the development team as we already acknowledged the issue. 

Thanks for your understanding and we hope this release solves the issue you were facing. We will be happy if you can confirm that.
