### ISSUE TITLE
Add Tracking for Onboarding Setup

### ISSUE THREAD

**Issue by puntope** [woocommerce/google-listings-and-ads#2168]
## User story

As a data analyst, I want to know about the data being sent when the Onboarding is completed to have metrics and improve my knowledge about merchants' trends.

### Is your feature request related to a problem? 
Data is not being tracked in Onboarding setup

### Describe the solution you'd like 
- When completing the Onboarding setup we can send info like the budget, audiences, shipping information...etc

## Event tracking

To be discussed and defined in the PR

**Comment by mikkamp** [comment]
This is completed in #2207 so closing this issue.
