### ISSUE TITLE
Test data plugin is sometimes missing from test environment and error is displayed reading "The plugin does not have a valid header"

### ISSUE THREAD

**Issue by martynmjones** [woocommerce/google-listings-and-ads#2175]
### Describe the bug:
`npm run wp-env:up` will setup an environment including the [test-data.php](https://github.com/woocommerce/google-listings-and-ads/blob/676d64944157e10105cf1e47e6a53bf5dcceb35d/tests/e2e/bin/test-data.php) plugin which is required for the E2E tests to run.

Occasionally, an error will be triggered on the test site reading `The plugin test-data.php has been deactivated due to an error: The plugin does not have a valid header.`. On more than one occasion I've checked the Docker container after that error was triggered and the `test-data.php` file doesn't exist.

![Screenshot 2023-12-06 at 12 19 37](https://github.com/woocommerce/google-listings-and-ads/assets/40762232/6c039b75-1897-4b39-a0c4-9748c0323ba0)

### Steps to reproduce:
1. Setup local environment with `npm run wp-env:up`
2. Run e2e tests

I've not yet come up with reliable reproduction steps as the issue appears to be intermittent.

### Expected behavior:
We should be able to rely on the environment being used for e2e testing.

**Comment by mikkamp** [comment]
Just linking [a previous suggestion](https://github.com/woocommerce/google-listings-and-ads/pull/2080#issuecomment-1698679989) to try:

> Another suggestion would be to clear cache. As `get_plugins` caches the list of plugins and if it's missing from the list it outputs the message that the header is missing. Maybe running `wp cache delete plugins plugins` before activating the plugin. Or alternatively `wp cache flush-group plugins`

**Comment by eason9487** [comment]
After a few rounds of testing, it seems to be fixed by mounting the *test-data.php* file to docker within a dedicated directory rather than placing it under the *plugins* directory. But I need more time to validate it.
