### ISSUE TITLE
item price is incorrect in purchase event

### ISSUE THREAD

**Issue by phamhung77** [woocommerce/google-listings-and-ads#2181]
### Steps to reproduce:

Assuming that there is a connection between GA4 and WooCommerce already.

1. Open GA4 Debug View.
2. Place an order with one (or multiple products). Each product has quantity > 1.
3. Complete the order. 
4. in GA4 Debug View, a purchase event should appear, and we can check the item price

### Expected behavior:

the price of one unit of each product.

### Actual behavior:

the returned price is subtotal, which is multiplied by the quantity already.

### Additional details:

By using subtotal for item price, the GA4 revenue report will be wrong. Because the revenue = item price of one unit * quantity.

**Comment by jorgemd24** [comment]
Hi @phamhung77! Thanks for flagging this issue!

I've replicated it, and we're working on a fix! It should be released in the coming weeks.
