### ISSUE TITLE
Feedback System

### ISSUE THREAD

**Issue by jconroy** [woocommerce/google-listings-and-ads#22]
**User story:**

As a product manager
I want to receive feedback from our customers about their experience with the extension
So that we can improve the customer experience

**Description:**

* Leverage the new/in-development feedback system

**Acceptance criteria:**

* [ ] TBC

**Event tracking:**

* Assuming there will be some form of event tracking built into the feedback system

**Comment by findingsimple** [comment]
Closing in favor of https://github.com/woocommerce/google-listings-and-ads/issues/882
