### ISSUE TITLE
Merchant request: enable GTIN from 3pd plugin

### ISSUE THREAD

**Issue by sophiegyo** [woocommerce/google-listings-and-ads#2317]
## User story

Reference 7873440-zen

* The merchant uses a 3pd plugin to insert GTIN: https://wordpress.org/plugins/woo-add-gtin/
* They are aware this plugin has not been updated in a while
* They would like Google Listings & Ads to be able to pick up the GTIN from this plugin
* They do not wish to use the prescribed method in the Google Listings & Ads docs:
https://woo.com/document/google-listings-and-ads/#global-attribute-mapping

I let them know I'd pass the request on but did not guarantee it would be implemented. 

### Is your feature request related to a problem? 

* They find the GLA prescribed method isn't convenient for managing individual GTINs for each product

#### How to reproduce the problem

1. Site with WooCommerce, Google Listings & Ads, and the above 3pd plugin
2. Add GTIN using the 3pd plugin
3. Try to use attribute mapping in GLA
4. GTIN field from 3pd plugin is not detected

### Describe the solution you'd like 

The merchant would like GLA to be able to use the GTIN as detailed here:
https://wordpress.org/support/topic/where-the-woocommerce-gtin-value-is-stored/

### Describe alternatives you've considered 

* I did suggest testing out the GTIN method from the GLA docs.
* I also let the merchant know about the Yoast option:
https://woo.com/document/google-listings-and-ads/attribute-mapping-use-cases/#section-4

## Technical

* I'm aware this is a 3pd plugin with their own custom implementation of how they add the GTIN and that we can't account for every 3pd plugin out there.

## Out of bounds/rabbit holes

See above!

**Comment by eason9487** [comment]
Looks like their could try [this filter](https://github.com/woocommerce/google-listings-and-ads/blob/2.6.4/src/Product/WCProductAdapter.php#L888-L909) to set the GTIN.

For example:

```php
add_filter(
	'woocommerce_gla_product_attribute_value_gtin',
	function ( $value, WC_Product $product ) {
		$gtin = 'Get the GTIN from another plugin';
		return $gtin;
	},
	10,
	2
);
```

**Comment by mikkamp** [comment]
Moving forward we are going to be focusing on the GTIN field that has been added to WooCommerce directly, [see here ](https://github.com/woocommerce/google-listings-and-ads/issues/2614).

This means we won't be adding additional support for other extensions, if a different source is needed for the GTIN then the snippet [can be used as described above](https://github.com/woocommerce/google-listings-and-ads/issues/2317#issuecomment-2021863039).

Closing this issue.
