### ISSUE TITLE
GH Action: PHP Unit Tests / Get WP and WC version matrix failed

### ISSUE THREAD

**Issue by ianlin** [woocommerce/google-listings-and-ads#2374]
### Describe the bug:

When I was releasing [2.6.7](https://github.com/woocommerce/google-listings-and-ads/releases/tag/2.6.7), one of the checks in the final step [merge trunk to develop](https://github.com/woocommerce/google-listings-and-ads/pull/2373) failed. The check is the preprocessor of PHP unit tests which it would [get WP and WC version matrix](https://github.com/woocommerce/google-listings-and-ads/actions/runs/8701663168?pr=2373).

The error message is:

> [Get WP and WC version Matrix](https://github.com/woocommerce/google-listings-and-ads/actions/runs/8701663168/job/23864136334#step:3:15)
Action failed with error: FetchError - Invalid response body while trying to fetch https://api.wordpress.org/plugins/info/1.0/woocommerce.json: Premature close

However, the URL https://api.wordpress.org/plugins/info/1.0/woocommerce.json is accessible. I also tested it locally using [node-fetch to fetch the URL](https://github.com/woocommerce/grow/blob/7ebb15c145e65fa95ab93e7ba0b9b3eba7faa2de/packages/github-actions/actions/get-plugin-releases/src/get-plugin-releases.js#L16) and it worked. I haven't dug deeper but just a bold guess it would possibly because of https://github.com/node-fetch/node-fetch/issues/1576 in node-fetch package?

Strangely that the same check passed in [the 2.6.7 release branch PR](https://github.com/woocommerce/google-listings-and-ads/actions/runs/8701471190/job/23863537892).

### Steps to reproduce:

1. Re-run [this failed job](https://github.com/woocommerce/google-listings-and-ads/actions/runs/8701663168?pr=2373)
2. Or, create a test PR and check the same job in that PR.

### Expected behavior:

The job should complete successfully.

### Actual behavior:

The job failed.

**Comment by eason9487** [comment]
A new retry attempt passed - https://github.com/woocommerce/google-listings-and-ads/actions/runs/8701663168?pr=2373.

Probably the https://api.wordpress.org/plugins/info/1.0/woocommerce.json randomly fails for now.

**Comment by ianlin** [comment]
Thanks for testing, I will close it as it seems to be the URL https://api.wordpress.org/plugins/info/1.0/woocommerce.json is unstable for now.
