### ISSUE TITLE
Move FAQ below action buttons in onboarding

### ISSUE THREAD

**Issue by mikkamp** [woocommerce/google-listings-and-ads#2382]
## User story
As part of the User Flow Review session we received some feedback on various issues which could be improved. Not all the suggestions have been decided on, and some needed some additional data to backup whether it was a blocker for many people. However I'm logging the issues here so we can determine how we would like to resolve them.

### Describe the solution you'd like 
Onboarding flow takes up quite a bit of screen space and a lot of scrolling is needed to get to the continue / action buttons at the bottom of the screen. The FAQ is not a primary section which the user is required to interact with to complete the onboarding, so the suggestion is to move it below the action buttons.

This can be changed on the first step of onboarding:
![image](https://github.com/woocommerce/google-listings-and-ads/assets/11388669/79de7b53-9664-4f3b-bbaf-d04efc20f40c)

And also on the last (fourth) step of onboarding:
![image](https://github.com/woocommerce/google-listings-and-ads/assets/11388669/277adfd9-6ef3-4a67-a892-54ae6335c777)

#### Ads Onboarding
To remain consistent this should also be switched within the Ads onboarding flow where we once again see the FAQ show up on the second step of the onboarding flow:
![image](https://github.com/woocommerce/google-listings-and-ads/assets/11388669/3d3cf949-808b-49b2-b646-c672ad787c61)

**Comment by joemcgill** [comment]
Closing this in favor of #2488.
