### ISSUE TITLE
Present campaign creation directly on fourth step of onboarding

### ISSUE THREAD

**Issue by mikkamp** [woocommerce/google-listings-and-ads#2383]
## User story
As part of the User Flow Review session we received some feedback on various issues which could be improved. Not all the suggestions have been decided on, and some needed some additional data to backup whether it was a blocker for many people. However I'm logging the issues here so we can determine how we would like to resolve them.

### Describe the solution you'd like 
When we reach the fourth step of onboarding we are initially presented with the option to connect an Ads account:
![gla-step-4](https://github.com/woocommerce/google-listings-and-ads/assets/11388669/ac8273c9-cced-454c-bf74-b860e0373495)

> [!Note]
> Connecting an Ads account will be moving to step one as part of #2215 
> With that change implemented any of the screenshots in this issue would no longer show the Google Ads card, the rest of the screen would remain the same.

Once we've connected the Ads account we move on to the next state where the user is now asked whether they want to create the campaign or skip:
![gla-step-4-2](https://github.com/woocommerce/google-listings-and-ads/assets/11388669/147787db-577c-4362-b4b2-87a7d9e23eb1)

If we click on the option to create the campaign it will load the next state where they can enter campaign details, and then once again either create the campaign or skip:
![gla-step-4-3](https://github.com/woocommerce/google-listings-and-ads/assets/11388669/97ba5fa5-ab2b-46bf-87e5-5442f5148d9c)

#### Feedback
The feedback that was given on this multistep process was two fold. Firstly the users need to go through an additional step to be able to start campaign creation. There is no direct need for this to happen, so we could directly present them with the option to fill in the campaign details after connecting the Ads account. Also if the Ads account has been moved to step 2 then there seems to be even less purpose of requiring this intermediate step, so the recommendation was to skip it.

Secondly there was some feedback that the buttons were shown within the section, which isn't consistent with the other onboarding steps (where the action / next buttons were at the bottom of the screen). One comment was that they were initially stuck on the screen as they didn't find the action buttons at the bottom and it wasn't clear enough that the section "Boost product listings with Ads" was a required section to interact with. This could either be resolved by placing the action buttons in the same location as other screens, or the intermediate status could be skipped since that would resolve both feedback comments.

**Comment by mikkamp** [comment]
Just updating this issue as after moving the Ads account connection to step 1, the fourth step looks slightly different and it makes it even more obvious that the extra step is not necessary to start with campaign creation:

![image](https://github.com/woocommerce/google-listings-and-ads/assets/11388669/e292a5b6-7b52-4753-bacc-b2ddf00873f2)

The expectation would be to directly jump to the screen after "create campaign" has been clicked:
![image](https://github.com/woocommerce/google-listings-and-ads/assets/11388669/22adfddd-cbc7-4cac-845c-2d7408bf6c5f)
The merchant will still be presented with the option to skip campaign creation at the bottom of the screen.

Related issue would be to [move the FAQ section lower](https://github.com/woocommerce/google-listings-and-ads/issues/2382) so the buttons to create / skip are more visible.

**Comment by joemcgill** [comment]
Closing in favor of #2459.
