### ISSUE TITLE
Required sections on step 2 of onboarding

### ISSUE THREAD

**Issue by mikkamp** [woocommerce/google-listings-and-ads#2384]
## User story
As part of the User Flow Review session we received some feedback on various issues which could be improved. Not all the suggestions have been decided on, and some needed some additional data to backup whether it was a blocker for many people. However I'm logging the issues here so we can determine how we would like to resolve them.

### Describe the solution you'd like 
When I initially reach step 2 all the sections are pre-populated with settings we fetch with from the store:
![gla-step-2](https://github.com/woocommerce/google-listings-and-ads/assets/11388669/b9eeaf00-eb59-48a1-837e-f2d068a2d5cd)

The shipping time and the taxes (only if US is included in target countries), must be interacted with. But at initial glance there is no indication that these sections are required, and the continue button is not disabled. Once we do click on the continue button we are made aware which sections are required:
![gla-step-2-2](https://github.com/woocommerce/google-listings-and-ads/assets/11388669/1af05fa1-b6d5-44a3-afcf-68b25251f21f)

#### Feedback
A decision on how this should be changed would need to be backed by some tracking data to determine if merchants are getting stuck on this step. The initial feedback was that anyone that's scanning through this quickly could just click the continue button right away, and expect the defaults to apply.

**Comment by joemcgill** [comment]
Closing this in favor of #2458, which includes these improvements.
