### ISSUE TITLE
[HC] - Google Listings & Ads not syncing weight when the measure in WooCommerce is set to "lbs" 

### ISSUE THREAD

**Issue by OmarFPG** [woocommerce/google-listings-and-ads#2388]
### Describe the bug:
The weight measurement units in WooCommerce → Settings → Products → Measurements → Weight units are:
- kg
- g
- lbs
- oz
![image](https://github.com/woocommerce/google-listings-and-ads/assets/122303439/5a15be0e-4ac5-4ab8-a4e7-4c366b233ae4)

While the available units on Google Merchant Center are:
- g
- kg
- lb
- oz
![image](https://github.com/woocommerce/google-listings-and-ads/assets/122303439/88acb611-8e85-4995-8167-5191a9154fee)

The discrepancy between "lbs" (plural) on WooCommerce and "lb" (singular) on GMC is causing items to show up with an error:

![image](https://github.com/woocommerce/google-listings-and-ads/assets/122303439/c34e7353-67cf-4d12-83af-63d8245d8668)

### Workaround:
Set up a [rule on GMC](https://support.google.com/merchants/answer/7450276?hl=en) to remove "lbs" from shipping weight and append "lb", as confirmed [here](https://wordpress.org/support/topic/woo-lbs-not-lb/#post-17731181).

## References:
- 7859394-zd
- 8080559-zd
- 8138600-zd

**Comment by ianlin** [comment]
@OmarFPG Thanks for reporting the issue, it has been fixed in #2389, the fix would be included in next Tuesday release.

**Comment by OmarFPG** [comment]
That was quick! Thank you so much! Looking forward to sharing the good news with merchants next week!
