### ISSUE TITLE
Onboarding Improvements Overview

### ISSUE THREAD

**Issue by eclarke1** [woocommerce/google-listings-and-ads#2458]
## Objective
Currently, only about half of users make it past the onboarding process to successfully set up and configure their WooCommerce store to integrate with Google Ads and Merchant Center. Simplifying and streamlining this process will lead to greater customer success.

## Background
The first step of the current onboarding process requires a store administrator to successfully create and connect four separate accounts/services

![Image](https://github.com/user-attachments/assets/c39252ce-ec1b-4f5b-82e6-396b0a5816a5)

- WordPress.com
- Google Account
- Google Merchant Center
- Google Ads

Setting up each of these accounts creates opportunities for confusion or uncertainty for users, which can be reduced by consolidating this step into a simpler process. Additionally, there are several places during the configuration and confirming store requirements steps where we can remove redundant or unnecessary actions to create a more streamlined experience for users.

## Overview
To streamline the onboarding process, we’re proposing the following adjustments to the onboarding flow steps.

### Account Creation
To simplify this screen, we will consolidate account creation from the current four steps, to two:

![Image](https://github.com/user-attachments/assets/585c26bd-fbf5-434f-9e73-acf46aeca9eb)

### Connect to WordPress.com
This will only be shown if the store is not already connected. Otherwise, this UI will not be displayed.

### Connect to Google
This step will consolidate all of the current steps for connecting to a Google account and creating/connecting to Google services into a single unified flow. Users will be prompted to connect a Google account, accept all necessary permissions scopes, and accept any necessary terms & conditions before either automatically connecting to the most applicable Ads and Merchant Center accounts, or creating new ones if they don’t already exist.

In addition, the FAQ list will be moved below the main “Continue” button to make the next step more obvious.

### Configure Product Listings
In this step, we can remove the “Language” settings. This is something that we know, and cannot be edited by merchants so there’s no point of showing it.

![Image](https://github.com/user-attachments/assets/950890e2-cef4-4094-8fd5-c03b9842fd43)

Additionally, this step includes selecting whether the store uses destination based tax rates. This does not need to be chosen during initial onboarding, so we’ll remove this step and default to destination-based tax rates and allow this setting to be adjusted after onboarding.

![Image](https://github.com/user-attachments/assets/e94ff0e1-4303-462c-b1bb-07d9f6e40b56)

### Confirm Store requirements
Currently, merchants have to do three things in this page:

1. Verify phone number
2. Edit store address if they haven’t done it already on Woo core product
3. Confirm pre-launch checklist

Phone verification and Store Address will remain the same:

![Image](https://github.com/user-attachments/assets/c2ae69d7-31d1-4ba0-bc8d-6a9ae95e0210)

However, we will remove the Pre-Launch checklist:

![Image](https://github.com/user-attachments/assets/32d28f0e-0ef0-4344-946f-c3255fbcaced)

We can check these things post onboarding and surface to merchants if they’re missing something, like we currently do with MC issues.

![Image](https://github.com/user-attachments/assets/cb3df7f0-5047-4df7-9390-56f956a63dbc)

In some cases, we may already have a verified phone number and address set up in the MC account, in which case we can skip this step of the onboarding entirely and move right to the Campaign Creation step of the onboarding process.

### Complete Your Campaign

Changes to the campaign creation are out of scope of this initial project and will be handled in a follow-up project.

## Requirements
🔗[See the Requirements Section of the PRD](https://docs.google.com/document/d/1G1kkC-jEhI65QdvdT5sOi7ibke1Mq8G-Qm1MA5YQKlI/edit?resourcekey=0-xRKLbc13_Cf8UyyG2UoHBQ#bookmark=id.v6v9omy8wmjd)

## Technical Design
The Onboarding Improvements work will be implemented by completing the following set of tasks:

### Account Creation
- [x] #2487
- [x] #2509
- [x] #2488

### Configure Product Listings
- [x] #2489
- [x] #2490
- [x] #2491

### Confirm Store requirements
- [x] #2492
- [x] #2494
- [x] #2493

**Comment by mikkamp** [comment]
Closing this as completed since it was part of the [2.9 release](https://github.com/woocommerce/google-listings-and-ads/releases/tag/2.9.0).
