### ISSUE TITLE
Campaign Creation Overview

### ISSUE THREAD

**Issue by eclarke1** [woocommerce/google-listings-and-ads#2459]
## Objective
The current onboarding flow does not result in many people successfully creating their first campaign. In order to help users successfully complete this step, we can better communicate the value of setting up a campaign and streamline the process to make it easier to complete during onboarding.

## Background

![Image](https://github.com/user-attachments/assets/fdb0ee2d-7c88-4ece-9146-efabf9c52149)

Currently, during onboarding, when a user gets to the final “Create a campaign” step, they are presented with a card that promotes setting up PMax campaigns, and gives them the option to either create a campaign or skip. 

This flow creates unnecessary friction. Instead, we can show the fields for creating a campaign immediately when the user starts this step and streamline the form to reduce confusion and make it simpler for someone to set up their first campaign during this step.

We will apply these same simplifications to the Ads Setup Flow that can be used to set up campaigns after onboarding, but that work will be handled as part of the Post Onboarding epic.

## Overview
In order to streamline the campaign creation step during onboarding, we will remove the CTAs that are initially shown before the setup form fields are displayed, and allow a user to immediately set up their first campaign. This will be supported  by better communication about the value of creating a campaign and by simplifying the form to reduce the number of steps it takes to successfully set up your first campaign. 

Users will still be able to complete onboarding without creating a campaign, and we will make that clear by moving the Skip/Continue buttons up above the FAQ section so these actions are easier to find.

See the following mockup of what the page might look like:

![Image](https://github.com/user-attachments/assets/270773b4-cbd2-4535-a1fb-e915b1d12e4f)

### Streamline post onboarding campaign creation
We’ll update this setup flow using the same UI used on the final step of the Onboarding flow. The current first step (setup accounts) will be removed entirely. The second step will now use the same form UI as the last step of the onboarding flow, which includes several improvements, like:

* [Remove Ads Audience field](https://github.com/woocommerce/google-listings-and-ads/issues/2501)  
* [Update Budget Setup Card](https://github.com/woocommerce/google-listings-and-ads/issues/2502)  
* [Add minimum budget limit](https://github.com/woocommerce/google-listings-and-ads/issues/2503)

The flow on the onboarding page also includes the ability to set up billing if needed, so we can use the same UI and eliminate the third step of the Ads setup flow.

![Image](https://github.com/user-attachments/assets/de13f21e-80c0-441c-b2c3-c2841eda0f15)

## Requirements
🔗 [See the requirements in the PRD](https://docs.google.com/document/d/1G1kkC-jEhI65QdvdT5sOi7ibke1Mq8G-Qm1MA5YQKlI/edit?resourcekey=0-xRKLbc13_Cf8UyyG2UoHBQ#bookmark=id.8orjha9xzhrx)

## Technical Design
- [x] #2499
- [x] #2500
- [x] #2501
- [x] #2502
- [x] #2503
- [x] #2488
- [x] #2504

### Streamline post onboarding campaign creation
The following issues have been moved from the Post Onboarding epic, #2460 to simplify the delivery of the shared components being modified in both epics.

- [x] #2534
- [x] #2535
- [x] #2536
- [x] #2578
- [x] #2579

**Comment by mikkamp** [comment]
Closing this as completed since it was part of the [2.9 release](https://github.com/woocommerce/google-listings-and-ads/releases/tag/2.9.0).
