### ISSUE TITLE
Post Onboarding Overview

### ISSUE THREAD

**Issue by eclarke1** [woocommerce/google-listings-and-ads#2460]
## Objective

In order to help merchants enhance product visibility and attract potential customers, we will improve the user experience for working with Ads after finishing the onboarding process.

## Background

Currently, during the initial onboarding flow, merchants can complete the onboarding process without setting up billing and adding any Ads campaigns. In those cases, merchants must go through another multi-step user flow to set up Ads for the first time. Similar to the Onboarding Improvements project, we can streamline this flow to make creating a campaign easier and avoid unnecessary steps:

**Step 1: Shows connected accounts**. Now that setting up an Ads account is a requirement of onboarding, this is unnecessary and can be removed.

![Image](https://github.com/user-attachments/assets/ddb11926-dedb-40a9-8e9c-999c164be1af)

**Step 2: Create a campaign.** This page is similar to the final page of the onboarding flow, but by using the exact same UI we can provide the same streamlined experience regardless of whether the user is setting up a campaign during onboarding or after.

**Step 3: Set up billing.** This is always shown, even if the user has already set up billing on their ads account. This is unnecessary and can be removed if not needed.

![Image](https://github.com/user-attachments/assets/9d98dd06-5ac5-473d-bd58-7bb6e202c98e)

In addition to streamlining campaign creation after onboarding, there is a general lack of information about the value of setting up ads or about the current status of the ads account or previously added campaigns on the dashboard.

![Image](https://github.com/user-attachments/assets/bad7744a-feec-407e-9cac-af792c9bc59d)

## Overview

To improve the user experience of working with Ads campaigns after initial onboarding we can make the following improvements.

### Streamline the Setup Ads flow

> [!Warning]
> This section has been implemented as part of #2459 instead.

### **Communicate the value of Google Ads after onboarding**

There are three tabs that are part of the Google for WooCommerce settings page where we will can highlight the value proposition for setting up ads:

* the dashboard tab  
* the reports tab  
* the product feed tab (the first tab a new user sees after onboarding)

On the dashboard tab, we will swap the position of the performance cards for free listings and paid campaigns and rename these to “Google Ads” and “Free Listings (Limited Visibility)”. If no paid ads campaigns have been set up, we will show a similar value proposition as is shown during onboarding, including promoting the $500 Google Ads credit.

![Image](https://github.com/user-attachments/assets/4b4410f8-0787-451b-894f-53a09101f068)
*Current Paid campaigns card*

![Image](https://github.com/user-attachments/assets/5df13c75-93e7-4ba2-80ea-e7cc598576d4)
*Improved design of the value proposition shown during onboarding.*

On the Reports and Product Feed tabs, if the merchant hasn’t set up any Google Ads campaigns, we’ll add some UI to the top of the page that explains the value prop including the $500 credit offer and suggests setting up their first campaign (designs TBD)..

### Improve communication of Google Ads status after onboarding

Today, the dashboard doesn’t provide any information about the Google Ads account status. If the connected Ads account is suspended, the campaigns listed will still appear as active, but they will not actually be running. We need to surface a banner showing if the Google Ads account is suspended. “Your Google Ads account has been suspended. Please click here to resolve issues.” And the “click here” takes them to their account on Google Ads frontend where they’ll find more information about the problem and be able to correct it.

## Requirements

🔗 [See the requirements in the PRD](https://docs.google.com/document/d/1G1kkC-jEhI65QdvdT5sOi7ibke1Mq8G-Qm1MA5YQKlI/edit?resourcekey=0-xRKLbc13\_Cf8UyyG2UoHBQ\#bookmark=id.jlbv7kvfmv0w)

## Technical Design

This work will be completed by the following tasks, further defined in individual GH issues:

### Streamline Set up paid ads flow
Update: This set of work has been moved to the Campaign Creation epic in #2459.

### Communicate the value of Google Ads after onboarding
The following will be merged into the [feature/2460-google-ads-value-prop](https://github.com/woocommerce/google-listings-and-ads/tree/feature/2460-google-ads-value-prop) branch.

- [x] #2537
- [x] #2538
- [x] #2539

### Improve communication of Google Ads status after onboarding

- [ ] #2540

### Misc

- [x] #2541

**Comment by kt-12** [comment]
Note for future: 
Check button display condition for AdCampaing.js page (https://github.com/woocommerce/google-listings-and-ads/pull/2577/files/1833363260aea805ca6380cf3af501a5ef48d673#r1766944395)

We need to ensure the button is enabled only when billing is available. This component is used in 3 locations, but all related to paid ad campaign cc: @joemcgill @asvinb

**Comment by mikkamp** [comment]
Closing this as completed since it was part of the [2.9 release](https://github.com/woocommerce/google-listings-and-ads/releases/tag/2.9.0).
