### ISSUE TITLE
Disable the gtag conversion and purchase tracking

### ISSUE THREAD

**Issue by nayaabkhan** [woocommerce/google-listings-and-ads#2465]
## User story
As a merchant, I can disable the gtag tracking when using another plugin like GTM4WP.

### Is your feature request related to a problem? 
We use GTM4WP to send ecommerce events to GA4. We noticed that this plugin also adds a `purchase` event which causes double purchases in the GA reports.

### Describe the solution you'd like 
A setting to disable the tracking, which by default could be enabled for backwards compatibility.

## Technical
Source in question is:
https://github.com/woocommerce/google-listings-and-ads/blob/develop/src/Google/GlobalSiteTag.php#L410

**Comment by mikkamp** [comment]
Hi @nayaabkhan 

Is your request any different then the solution implemented in PR #1633 

If not then you can use the provided filter:
```php
add_filter( 'woocommerce_gla_disable_gtag_tracking', '__return_true' );
```

If that works for you we can go ahead and close this issue. We decided specifically not to go with a setting as we want to ensure that there is an alternative tracking solution in place, so the filter can be used by plugins to override the tracking.

**Comment by nayaabkhan** [comment]
Sure let me take a look and I'll close this if the filter is enough.

**Comment by ZenDevMaster** [comment]
A note for anyone trying to get this to work and banging their head on the wall like I was. 

If you've added this to your functions.php and it's not working:

`add_filter( 'woocommerce_gla_disable_gtag_tracking', '__return_true' );`

Note that Wordpress loads all plugins prior to running functions.php, and it appears the plugin needs the filter to be set prior to loading. So you need to get this filter to fire first, which can be done by creating a file in your mu-plugins (must use plugins) folder.

Create the following file:

`/wp-content/mu-plugins/disable-gla-globalsitetag.php`

Content:

```
<?php
/** Plugin Name: Disable the GlobalSiteTag features from Google for WooCommerce for mu-plugins.
 *  Description: Activates the filter woocommerce_gla_disable_gtag_tracking prior to the plugin loading
 *  Version: 1.0.0
 *  License: GPL v2 or later
 */


namespace Automattic\WooCommerce\GoogleListingsAndAds\Google;

if ( ! defined( 'ABSPATH' ) ) {
  die( 'We\'re sorry, but you can not directly access this file.' );
}

/* this filter needs to be called before the Google for Woocommerce plugin loads */
add_filter( 'woocommerce_gla_disable_gtag_tracking', '__return_true' );

```

I'm not a WordPress or WooCommerce developer so YMMV. Works for me though!

**Comment by mikkamp** [comment]
> Note that Wordpress loads all plugins prior to running functions.php, and it appears the plugin needs the filter to be set prior to loading.

That's a good point. The services classes are loaded using the hook [`plugins_loaded`](https://github.com/woocommerce/google-listings-and-ads/blob/2.8.5/src/Infrastructure/GoogleListingsAndAdsPlugin.php#L23) (priority 20), which is triggered before the theme / functions.php is loaded. However that means it can be placed in any custom plugin, it doesn't specifically have to be in a must use plugin.

Or using a code snippet plugin will work as well.

**Comment by andrew-dixon** [comment]
I really don't understand the resistance to adding this as an option. I've just wasted several hours trying to figure out why my e-commerce tracking was all messed up, as Google for WooCommerce doesn't even really mention that it is outputting the GA code.

If this option had been there in the "settings" I would have seen it straightaway and known that it was the problem. Thanks to @ZenDevMaster for the code snippet, as that has worked for me, but I would strongly recommend that this is added as a simple on/off tick box option on the settings page, or at a minimum, mention that the plugin does GA e-commerce tracking and maybe link to this ticket for anyone wanting to turn it off.

**Comment by tobyhage** [comment]
Here also wasted several hours. Thank you @ZenDevMaster !!

**Comment by betterlifewithlorin** [comment]
Also wasted a lot of time trying to figure out what was going on with my setup. I think the on/off tick box would be a great feature.
