### ISSUE TITLE
Campaign Creation: Show campaign setup fields immediately during onboarding

### ISSUE THREAD

**Issue by joemcgill** [woocommerce/google-listings-and-ads#2500]
Part of https://github.com/woocommerce/google-listings-and-ads/issues/2459

Currently, the first time someone gets to the Create a Campaign step of the onboarding flow, they are presented with a promotion for PMax campaigns with the option either skip or create a campaign. Choosing to Create a Campaign reveals the forms fields needed to set up your first campaign. This adds unnecessary friction since this step is much simpler than it was when originally introduced. 

![Image](https://github.com/user-attachments/assets/6606f849-23ee-4ea1-b7d5-e72c2818e19d)

Instead of showing the Skip/Create buttons in the `PaidAdsFeaturesSection` and hiding `PaidAdsSetupSections` components, we will always show the `PaidAdsSetupSections`.

## Acceptance Criteria

When reaching the Create a Campaign step of the onboarding flow:
- [ ] The PMax Campaign Promo (`PaidAdsSetupSections`) no longer show footer buttons.
- [ ] The Ads setup fields (`PaidAdsSetupSections`) are always visible.
- [ ] Unused code related to showing the Paid Ads setup is removed from the `SetupPaidAds` components.

## Implementation Brief
Whether the footer buttons are shown in the `PaidAdsFeaturesSection` or not is based on the `hideFooterButtons` prop of that component, which currently passes `! hasGoogleAdsConnection || showPaidAdsSetup`. This entire prop can be removed and the footer buttons removed from the component itself and all the related logic be removed from `js/src/setup-mc/setup-stepper/setup-paid-ads/setup-paid-ads.js` where this component is being used.

Likewise, the `PaidAdsSetupSections` and `StepContentFooter` are only shown if `showPaidAdsSetup` is true. Now that we always want to show that component, we can remove all the logic related to `showPaidAdsSetup`, which is set via a `useState()` hook. This includes removing remove the `clientSession.setShowPaidAdsSetup` and `clientSession.getShowPaidAdsSetup` methods in `js/src/setup-mc/setup-stepper/setup-paid-ads/clientSession.js`. The rest of that file should remain since it is also referenced by the `PaidAdsSetupSections` component.

## Test Coverage
Update E2E tests in tests/e2e/specs/setup-mc/step-4-complete-campaign.test.js to match expected behavior and remove unused helpers.

**Comment by eason9487** [comment]
> This includes removing and cleaning up the `clientSession` helper in `js/src/setup-mc/setup-stepper/setup-paid-ads/clientSession.js` that is also referenced in the `PaidAdsSetupSections` component.

Does it mean the uses of `clientSession.getCampaign()` and `clientSession.setCampaign( nextPaidAds )` are planned to remove?

**Comment by joemcgill** [comment]
> Does it mean the uses of clientSession.getCampaign() and clientSession.setCampaign( nextPaidAds ) are planned to remove?

No, I don't think there is any reason to remove those methods. We should just remove the `clientSession.setShowPaidAdsSetup` and `clientSession.getShowPaidAdsSetup` methods. I'll clarify in the Implementation Brief. Thanks!

**Comment by eclarke1** [comment]
Engineering complete and approved, moving to UAT for @fblascogarma final approval

**Comment by eclarke1** [comment]
Just tagging @joemcgill and @asvinb  to advise this needs to be merged please

**Comment by asvinb** [comment]
Merge conflicts fixed and assigning to @fblascogarma for final approval.

**Comment by mikkamp** [comment]
Closing this as completed since it was part of the [2.9 release](https://github.com/woocommerce/google-listings-and-ads/releases/tag/2.9.0).
