### ISSUE TITLE
Campaign Creation: Remove Ads Audience field

### ISSUE THREAD

**Issue by joemcgill** [woocommerce/google-listings-and-ads#2501]
Part of https://github.com/woocommerce/google-listings-and-ads/issues/2459

![Image](https://github.com/user-attachments/assets/5b2b937c-e0ae-4871-ab6e-5cff7cd3cab5)

Today we show “Ads audience” (see screenshot below) but instead, we can remove it and target all countries selected during product feed configuration (step 2).

## Acceptance Criteria

- [ ] The campaign creation step no longer shows the audience section during onboarding.
- [ ] When a new campaign is created, the values selected during step 2 are used for the campaign.

## Implementation Brief
The `AudienceSection` component can be removed from the `PaidAdsSetupSections` component. Update the `PaidAdsSetupSections` component so that it initializes the `paidAds` state with targetAudience data that was saved in step 2. We can probably use the `getTargetAudience` selector to get this data, but will need to make sure that it then gets formatted in a way that is expected when the form is submitted.

## Test Coverage
Update the E2E tests for `tests/e2e/specs/setup-mc/step-4-complete-campaign.test.js` to remove tests related to the audience field.

**Comment by eason9487** [comment]
> 1. Are there any side effects that we would need to be aware of when using target audience data from MC for the Ads campaign?

I think there shouldn't be any side effects because the target audiences from MC are originally the default value when the starting campaign creation.

**Comment by eason9487** [comment]
There is a code conflict so I moved this ticket to the **In Progress** status. I believe the PR won't need another round of code reviews after resolving the code conflict.

**Comment by asvinb** [comment]
Thanks @eason9487 . Merge conflicts fixed. As per your comment, assigning task to @fblascogarma for UAT.

**Comment by mikkamp** [comment]
Closing this as completed since it was part of the [2.9 release](https://github.com/woocommerce/google-listings-and-ads/releases/tag/2.9.0).
