### ISSUE TITLE
Campaign Creation: Add minimum budget limit

### ISSUE THREAD

**Issue by joemcgill** [woocommerce/google-listings-and-ads#2503]
Part of https://github.com/woocommerce/google-listings-and-ads/issues/2459

As a follow-up to #2502, even when we initialize the `BudgetSection` component with the recommended daily budget amount, merchants can edit the value to a lower value. For example, a merchant could set a campaign for 1 cent per day. 

We already have budget recommendations for each country, so we could take a % of that recommendation and set it up as a minimum. For example, if the budget recommendation for US is $15/day, the minimum possible budget should be $5/day (~30% of recommended budget).

If a user tries to input a number lower than the minimum, we should display a validation error with an explanation of what needs to change.

_Example mockup_

<img width="315" alt="image" src="https://github.com/user-attachments/assets/2f853bd6-4268-4620-b0ae-09461d583edb">

## Acceptance Criteria

- [ ] A minimum possible value for the Daily Average Cost will be 30% of the recommended daily budget
- [ ] If the Daily Average Cost input is set to a value lower than the minimum possible budget, a validation warning is shown reading "Please make sure daily average cost is greater than %d." where %d is replaced with the minimum.
- [ ] If the Daily Average Cost input is set to a value lower than the minimum possible budget, the validation error is shown
- [ ] If the Daily Average Cost input is set to a value lower than the minimum possible budget, the "Complete setup" button is disabled.

## Implementation Brief
The component where this is displayed is the `BudgetSection` component, but the validation logic will need to be applied in the `CampaignAssetsForm` component by updating the validation logic of the `validateCampaign` function ([ref](https://github.com/woocommerce/google-listings-and-ads/blob/a55258332f0c46faaf1834d28e30a6a44a691d49/js/src/components/paid-ads/validateCampaign.js)).

## Test Coverage
E2E tests for step 4 of the setup process is updated to cover examples where the minimum value is set and when a value less than the minimum is set.

**Comment by joemcgill** [comment]
Consolidating into #2502.

**Comment by joemcgill** [comment]
Actually, no, setting a minimum budget limit will be a separate task from setting the initial value, which is what will be handled in #2502. Reopening this to define requirements for setting the minimum limit.

**Comment by eclarke1** [comment]
Adding back the custom labels as this was not appearing in our 'Detailed Epic View'

**Comment by eclarke1** [comment]
@joemcgill  please could you re-add the size and Eng Focus labels (once the AC/IB has been added of course)

**Comment by joemcgill** [comment]
@fblascogarma and @MatthiasReinholz, we'll need to confirm how we want to calculate the minimum value and better define the UX for when a merchant enters a value lower than the minimum.

**Comment by joemcgill** [comment]
@fblascogarma confirmed in Slack that we should use 30% of the recommended budget as the minimum for now. I think we can try to show a similar validation logic when the field value changes to an empty or zero value...


![Image](https://github.com/user-attachments/assets/c2fc3888-dd29-40b9-980b-9efdc3454756)

Instead of "Please make sure daily average cost is greater than 0." the text can be "Please make sure daily average cost is greater than %d." where %d is replaced with the minimum. When the value is less than the minimum the "Complete setup" button will remain disabled.

**Comment by fblascogarma** [comment]
Correct, let's use 30%, see how it goes with that, and adjust if needed.

The default value should be the recommended budget. If users set up a budget below the recommended, we show them the message we have today in production. If users set up budget below the %d (minimum budget allowed) we can use with red font saying that the minimum is %d to avoid poor performance for very low budgets. 

What do you think?

**Comment by fblascogarma** [comment]
30% and rounding up for a nicer number. For example, $28,000 instead of $27,547

**Comment by joemcgill** [comment]
@eason9487 I'm going to go ahead and take a swing at implementing this, but would appreciate any feedback you have about the approach to applying the validation logic/styles when you have a chance.

**Comment by eason9487** [comment]
Will this change be applied to campaign editing? If so, I would suggest adjusting the issue title and describing how it change campaign editing, e.g. whether to apply this limit to campaigns that already exist and are below the minimum budget.

**Comment by dsawardekar** [comment]
@asvinb Assigning this to you for the styling updates, please send back to me once complete, as I need to implement the e2e tests.

**Comment by asvinb** [comment]
@dsawardekar PR has been updated to add the style updates. Let me know if i've missed anything.

**Comment by asvinb** [comment]
@dsawardekar Can you kindly fix the merge conflicts please, then I'll review the PR. Just FYI, we removed the Audience section from the paid ads setup:
https://github.com/woocommerce/google-listings-and-ads/pull/2551

**Comment by dsawardekar** [comment]
@asvinb Updated. And also remove the unused import.

**Comment by asvinb** [comment]
@joemcgill I made a few tweaks to @dsawardekar 's PR. Can you kindly review please?
Thanks!

**Comment by eason9487** [comment]
Assigned to @dsawardekar and @asvinb because I'm not sure who is working on this ticket for now.

**Comment by mikkamp** [comment]
Closing this as completed since it was part of the [2.9 release](https://github.com/woocommerce/google-listings-and-ads/releases/tag/2.9.0).
