### ISSUE TITLE
Swap and rename dashboard performance cards

### ISSUE THREAD

**Issue by joemcgill** [woocommerce/google-listings-and-ads#2537]
Part of https://github.com/woocommerce/google-listings-and-ads/issues/2460

The current dashboard includes two `SummaryCard` components for "Performance (Free Listing)" (free listings) and "Performance (Paid Campaigns)" (paid campaigns). See current screenshot:

![Image](https://github.com/user-attachments/assets/a5f8248c-a41c-405e-bdb8-124369b83827)

In order to better highlight the value of setting up paid ads, we'll swap these two cards and rename them to “Google Ads” (paid campaigns) and “Free Listings (Limited Visibility)” (free-listings)

## Acceptance Criteria

On the dashboard:

- [ ] The first `SummaryCard` should be titled "Google Ads" and show the `PaidPerformanceCard` when the ads setup is complete, or `PaidCampaignPromotionCard` when not.
- [ ] The second `SummaryCard` should be titled "Free Listings (Limited Visibility)" and show the `FreePerformanceCard` component.

## Implementation Brief
This PR should be merged into the [feature/2460-google-ads-value-prop](https://github.com/woocommerce/google-listings-and-ads/tree/feature/2460-google-ads-value-prop) branch.

The file where these can be swapped and renamed [is found here](https://github.com/woocommerce/google-listings-and-ads/blob/develop/js/src/dashboard/summary-section/index.js#L113-L132).

## Test Coverage
- Jest tests in `js/src/dashboard/summary-section/summary-section.test.js` should still pass.
- E2E tests that rely on the "Add paid campaign" button in the `PaidCampaignPromotionCard` component should still pass after swapping positions. If not, update the tests so they aren't dependent on the position of the `SummaryCard`.

**Comment by eason9487** [comment]
This looks good for the Definition phase.

**Comment by mikkamp** [comment]
Closing this as completed since it was part of the [2.9 release](https://github.com/woocommerce/google-listings-and-ads/releases/tag/2.9.0).
