### ISSUE TITLE
Show Ads value prop in Paid Campaign performance card

### ISSUE THREAD

**Issue by joemcgill** [woocommerce/google-listings-and-ads#2538]
Part of https://github.com/woocommerce/google-listings-and-ads/issues/2460

In order to better explain why someone should set up their first PMax campaign, we'll update the Paid Campaign card in the dashboard to show a similar value prop as the one shown during onboarding.

<img width="556" alt="image" src="https://github.com/user-attachments/assets/3c2e63d9-bcb2-4cd8-a747-78960c0c4341">

## Acceptance Criteria

- [ ] Display the Paid Ads features value prop card when:
  - [ ] the connected Ads account has not completed the setup flow ([see discussion](https://github.com/woocommerce/google-listings-and-ads/pull/2641#issuecomment-2438579282)), or
  - [ ] if the Ads account does not have any existing campaigns
- [ ] If the account is eligible to see the $500 ads credit (see: #2599), include the banner.
- [ ] Clicking the Create Campaign button should open the same Create Campaign flow as the current Paid Campaign card.
- [ ] Once a campaign has been created, the Paid Campaign card should show performance metrics from the current card.

## Implementation Brief
* Create `js/src/dashboard/summary-section/paid-features.js` which will house the `PaidFeatures` component.
	* Render the component as per the ticket description.
	* The paid features are also found in `js/src/setup-mc/setup-stepper/setup-paid-ads/paid-ads-features-section.js`
		* Extract the features into a common component which can be used for both, `PaidAdsFeaturesSection` and `PaidFeatures`.
	* For the $500 as credit implementation, implementation details can be taken from `js/src/setup-mc/setup-stepper/setup-paid-ads/paid-ads-features-section.js`
	* Button for "Create campaign" should possibly reuse `js/src/components/paid-ads/add-paid-campaign-button.js`.
		* Necessary updates should be make to the componen so that it can be used across different components.
		* Possibly mode the component to `js/src/component`
* Using `js/src/dashboard/summary-section/index.js`,
	* Add `PaidFeatures` to `SummarySection` if
		* `adsSetupComplete` is `true`
		* and there are no campaign.
			* To check whether there are no campaigns, use the `useAdsCampaigns`
* We will deprecate the `useFreeAdCredit()` while implementing this, see #2599. Instead of any places where that hook is currently in use should be updated so that the Ads Credit banner is always shown when there are no existing campaigns. 

## Test Coverage
* Appropriate E2E tests should be added to test for `PaidFeatures` to be displayed/hidden.

## Definition Questions
* What is the condition to replace the `useFreeAdCredit` hook?

**Comment by joemcgill** [comment]
As part of this issue, we'll deprecate and remove the `useFreeAdCredit` hook based on the discussion related to #2599.

**Comment by asvinb** [comment]
@joemcgill I've added the IB. Can you kindly take a look please? Left a question about the `useFreeAdCredit`.

**Comment by joemcgill** [comment]
@asvinb I've tried to clarify the part about deprecating the `useFreeAdCredit` hook in the IB. I think everything else looks good.

**Comment by mikkamp** [comment]
Closing this as completed since it was part of the [2.9 release](https://github.com/woocommerce/google-listings-and-ads/releases/tag/2.9.0).
