### ISSUE TITLE
Phone Number Verification error doesn't show correctly in the UI

### ISSUE THREAD

**Issue by puntope** [woocommerce/google-listings-and-ads#2553]
### Describe the bug:
While testing the Phone Number verification I noticed that when there is an error sending SMS it doesn't show as expected in the UI

https://github.com/user-attachments/assets/12853da3-f40d-4dc9-8112-ee4fdb8399cb

### Steps to reproduce:

1.  Go to Settings - Edit Phone Number
2. Set a non-valid country number for example Georgia -- 551144555
3. See the error in the UI empty

### Expected behavior:
The error is shown in the UI or if is empty we don't show the error notice.

### Actual behavior:
An error is shown at the bottom but the error notice is empty.

**Comment by mikkamp** [comment]
Phone number verification is being removed in #2653 so I'm closing this issue as no longer applicable.
