### ISSUE TITLE
Onboarding: Clean up unused MC settings data

### ISSUE THREAD

**Issue by joemcgill** [woocommerce/google-listings-and-ads#2572]
This is a follow-up to #2494. Once the MC settings related to the pre-launch policy check is removed from the API, those settings can be removed from other places that they are referenced.

The `SettingsData` type definition in `/src/data/actions.js`

https://github.com/woocommerce/google-listings-and-ads/blob/007190f26e4851e5350b8aab64cc0a2bf0f40c96/js/src/data/actions.js#L87-L91

The `SetupFreeListings` component.

https://github.com/woocommerce/google-listings-and-ads/blob/dd73ec687205a94d34399c890803f58cf5900a83/js/src/components/free-listings/setup-free-listings/index.js#L38-L42

and

https://github.com/woocommerce/google-listings-and-ads/blob/feature/2494-remove-pre-launch-checklist-items/js/src/components/free-listings/setup-free-listings/index.js#L217-L221

The relevant settings are:

- 'website_live'
- 'checkout_process_secure'
- 'payment_methods_visible'
- 'refund_tos_visible'
- 'contact_info_visible'

## Acceptance criteria

- [ ] The settings references identified above are removed from the codebase.
- [ ] Setting up free listings during onboarding (step 2) or editing free listings after onboarding still work as expected (no regressions).

**Comment by joemcgill** [comment]
@mikkamp we noticed this additional cleanup after #2494. Can you confirm that this looks right?

**Comment by mikkamp** [comment]
Yes that looks alright, in [#2494](https://github.com/woocommerce/google-listings-and-ads/issues/2494#issuecomment-2270898229) I mainly mentioned the PolicyCompliance classes which are part of the PHP side. The js parts which reference these same settings/endpoints can be removed as well, which you have listed above.

If you search for `mc/policy_check` you might find a few more references that could be removed, like: https://github.com/woocommerce/google-listings-and-ads/blob/2.8.4/js/src/data/resolvers.js#L173-L195

**Comment by joemcgill** [comment]
Thanks @mikkamp. I'm unsure if the resolver for the `mc/policy_check` endpoint can be removed, because we haven't removed that endpoint. We'll go ahead and remove the settings that we identified and if there are additional things to clean up, they could be handled in follow-up PRs.

**Comment by eclarke1** [comment]
@joemcgill discussion ongoing here as to whether this ticket can be closed. Please advise.

**Comment by joemcgill** [comment]
Yep, looks like this was handled in a follow-up during code review. See: https://github.com/woocommerce/google-listings-and-ads/pull/2584#pullrequestreview-2285249553. Closing as complete.
