### ISSUE TITLE
Optionally connect Ads account during campaign creation

### ISSUE THREAD

**Issue by joemcgill** [woocommerce/google-listings-and-ads#2578]
As a follow-up to #2534 and #2535, once the component responsible for creating campaigns during onboarding is consolidated with the one used for creating and editing a campaign after onboarding, there is a need for that screen to handle cases where the Ads account has been disconnected from the settings screen.

To handle connecting an Ads account during campaign creation, we will optionally show the Google Ads account card on the campaign creation page if no account is connected (see [related conversation](https://github.com/woocommerce/google-listings-and-ads/issues/2534#issuecomment-2306716676)).

![Image](https://github.com/user-attachments/assets/61a48b58-625a-460f-a38c-b35064e6a133)

## Acceptance Criteria

- [ ] If an Ads account is already connected when entering the campaign creation form, no Google Ads account card should be shown.
- [ ] When no Google Ads account is connected, the Google Accounts card is shown in its unconnected state and all other form fields are disabled.
- [ ] The merchant can use the Ads card to connect an existing account or create a new account.
- [ ] If a new account is created from this flow, the merchant can complete the claim account flow.
- [ ] Once connected, the Google Ads card will show in a connected state.

## Implementation details
This should be based from the work in this feature branch: [feature/2460-simplify-paid-ads-setup](https://github.com/woocommerce/google-listings-and-ads/tree/feature/2460-simplify-paid-ads-setup)

## Definition Questions

**Comment by joemcgill** [comment]
@fblascogarma and @MatthiasReinholz, I've started to stub out a ticket to handle the concerns @eason9487 raised in https://github.com/woocommerce/google-listings-and-ads/issues/2534#issuecomment-2306716676.

Optionally adding some UI to this page to handle connecting an Ads account that was disconnected via the settings screen is an elegant solution and would allow the whole flow to remain consolidated to a single step. However, this does add a lot of additional complexity to this UI, so I wanted to confirm that we want to move forward with this approach rather than just keeping the first step in this flow (being removed in #2534) and instead optionally show that step if the Ads account is disconnected.

**Comment by fblascogarma** [comment]
Thank you for the question @joemcgill ! Fine by me on having that additional first step if we identify there isn't an Ads account connected yet.

**Comment by joemcgill** [comment]
Great, thanks @fblascogarma. I'm going to close this issue as not planned for now, and we'll update #2534 to allow the original step to remain shown if no account is connected.
