### ISSUE TITLE
Add AppSelectOrTextControl component

### ISSUE THREAD

**Issue by joemcgill** [woocommerce/google-listings-and-ads#2592]
# Issue Template

As part of the consolidated account connection UI (https://github.com/woocommerce/google-listings-and-ads/issues/2509), there is a need for a new type of control for to show a list of existing accounts for Ads and Merchant accounts. It should render an Text control when there is only one existing account, and a Select (option) control when there are multiple to choose from:

**Text Control**
<img width="728" alt="image" src="https://github.com/user-attachments/assets/5327cae8-1315-410e-9088-b6711163c866">

**Select Control**
<img width="600" alt="image" src="https://github.com/user-attachments/assets/697e19fa-00ff-4603-a876-04094a7587ca">

🔗 [Figma designs](https://www.figma.com/design/fqR0EHi63lWahRcVTKCcba/Google-Listings-%26-Ads-v2.x?node-id=7176-108902&t=DKSHdhVrxv09BKOp-1)

## Acceptance Criteria

- [ ] Accepts the same props as `AppSelectControl` ([ref](https://github.com/woocommerce/google-listings-and-ads/blob/c2d385858258a97a78a3640e439dcee2a5873f0b/js/src/components/app-select-control/index.js#L21)).
- [ ] Renders an `AppSelectControl` when more than 1 option is passed.
  - [ ] Changing the selected option triggers the onChange event with the selected value.
- [ ] Renders a text component styled to match the designs when only 1 option is passed
  - [ ] If the value is undefined and there is only 1 option, the onChange event is triggered to set the value.

## Implementation Brief
This component should be created `js/src/components/app-select-or-text-control/index.js`. 

For the text component, the `AppText` component could be reused from `js/src/components/app-text/index.js` with a custom variant or `AppInputControl` if it can be made readonly.

## Test Coverage
- Jest Tests to confirm that the correct subcomponent is rendered depending on option length isa nice to have.

**Comment by joemcgill** [comment]
@eason9487 and @asvinb could you both review and provide feedback? I'm curious if there is a preferred component to use for the text variation when only one option is found? Alternately, we can implement this now in the new UI with the AppSelectControl even when there is only 1 option.

**Comment by eason9487** [comment]
> I'm curious if there is a preferred component to use for the text variation when only one option is found? Alternately, we can implement this now in the new UI with the AppSelectControl even when there is only 1 option.

The `SelectControl` used in `AppSelectControl` should be able to present the needed variation:

```jsx
<SelectControl
	suffix=" "
	readOnly
	tabIndex="-1"
	style={ { pointerEvents: 'none' } }
	{ ...rest }
/>
```

![image](https://github.com/user-attachments/assets/af682daf-3217-44a8-ba15-a79763da4e4a)

And I think the switch logic of this ticket could be implemented within `AppSelectControl` and controlled by a prop, since it currently does nothing but add a wrapper layer. Therefore, it's also possible to consider not to add a new `AppSelectOrTextControl` component.

**Comment by joemcgill** [comment]
Thanks, @eason9487. That's a much cleaner solution. I'll update #2593 to reflect this approach and close this as not planned.
