### ISSUE TITLE
[GTIN] Prioritise core WooCommerce GTIN field when syncing  

### ISSUE THREAD

**Issue by martynmjones** [woocommerce/google-listings-and-ads#2614]
WooCommerce 9.2 introduced a global unique ID field to products that will replace the `GTIN` field included in Google for WooCommerce. To support the existing data being migrated to the core field we will first need to update our product adapter to prioritise the core field and then fallback to existing Google for WooCommerce data.

<img width="1257" alt="Screenshot 2024-09-17 at 20 33 45" src="https://github.com/user-attachments/assets/279cd70b-4e0f-461b-92cb-3742039f4bd2">

## Acceptance criteria
GTIN is automatically populated when syncing products using the following priority:

1. WC Core field
1. Mapping Rule
1. Fallback to GLA value

## Additional

pcTzPl-2p2-p2

**Comment by puntope** [comment]
Closed - https://github.com/woocommerce/google-listings-and-ads/pull/2621
