### ISSUE TITLE
[GTIN] Hide the Global Trade Item Number field for new users and make read-only for existing users

### ISSUE THREAD

**Issue by martynmjones** [woocommerce/google-listings-and-ads#2615]
As we will be prioritising the global unique ID field in core (See #2614) when syncing product data, the `GTIN` field in Google for WooCommerce will need to be hidden for new users of the extension and made read-only for existing users. The tooltip will also need to be updated to direct existing users to the core `Inventory` tab to popular the field.

<img width="1252" alt="Screenshot 2024-09-17 at 20 54 30" src="https://github.com/user-attachments/assets/6b7a7a41-1f7d-4bf4-98c1-2f28d9b6cfb8">

## Acceptance criteria

1. For new merchants, the `GTIN` field is automatically hidden in both the classic and new product editor
2. For existing merchants, the `GTIN` field is made read-only and the tooltip directs them to the `Inventory` tab

## Additional

pcTzPl-2p2-p2

**Comment by puntope** [comment]
Closed - https://github.com/woocommerce/google-listings-and-ads/pull/2622
