### ISSUE TITLE
[GTIN] Migrate existing GLA Global Trade Item Number data to core

### ISSUE THREAD

**Issue by martynmjones** [woocommerce/google-listings-and-ads#2616]
The `GTIN` field in Google for WooCommerce will be retired in favour of the new global unique ID field available in core. To support this change we will need to add a migration tool to populate the core field from data available in Google for WooCommerce. Merchants will be prompted to run the migration tool rather than it running automatically.

## Acceptance criteria

1. The migration will happen using batched scheduled actions
1. Existing merchants of Google for WooCommerce will be prompted via a banner to run a migration tool
1. Existing merchants will see a prompt next to the `GTIN` field in Google for WooCommerce to run a migration tool
1. The data migrated by the tool will respect mapping rules and filters to ensure that the most relevant source of information is used
1. The migration tool will only populate the core global unique ID field if it is empty
    - Action scheduler logs should state if a product was skipped due to the core field being populated
1. The migration tool will be available via CLI
    - This is secondary to the rest of the functionality and may be added as a follow-up

## Additional

pcTzPl-2p2-p2

**Comment by puntope** [comment]
Closed - https://github.com/woocommerce/google-listings-and-ads/pull/2662 https://github.com/woocommerce/google-listings-and-ads/pull/2656 https://github.com/woocommerce/google-listings-and-ads/pull/2655
