### ISSUE TITLE
Google Ads do not Create Account

### ISSUE THREAD

**Issue by Bunker889** [woocommerce/google-listings-and-ads#2620]
In the Set up your accounts tab, I can't verify my google ads account. I have it set up separately but the plugin doesn't see it. After clicking create Account, the plugin shows an error at the bottom left: Unable to create Google Ads account. Please try again later.

### Steps to reproduce:

1. Sell more on google button
2. Create Google ads
3. Unable to create Google Ads account. Please try again later

### Additional details:

![Bez tytułu](https://github.com/user-attachments/assets/258add55-5965-4a8a-8a35-64e4165b5f97)

**Comment by puntope** [comment]
Hey there @Bunker889, thanks for contacting us!

This repository is not suitable for support. Please don't use our issue tracker for support requests.

For self help, start with our [user documentation](https://woocommerce.com/document/google-for-woocommerce/).

The best place to get support is the [WordPress.org Google for WooCommerce forum](https://wordpress.org/support/plugin/google-listings-and-ads/).

If you have a WooCommerce.com account, you can [start a chat or open a ticket on WooCommerce.com](https://woocommerce.com/my-account/contact-support/).
