### ISSUE TITLE
Loading Loop 

### ISSUE THREAD

**Issue by DerErzengel** [woocommerce/google-listings-and-ads#2628]
### Describe the bug:
I can no longer access the settings or change anything in the plugin. A loading symbol is permanently displayed.

### Steps to reproduce:
1. complete the setup in Google for Wocommerce and create a merchant account.
2. have the Merchant Center account deleted
3. after deletion, the plugin can no longer access the account and loads forever.

### Expected behavior:
I don't know

### Actual behavior:
I don't know

### Additional details:
I use the latest version of the plugin. Deleting and re-adding the Plugin did not work. The error has already occurred on 2 different websites.

**Comment by tomalec** [comment]
Hi @GWE767, thanks for reaching out!

I tried reproducing this scenario locally, and it works well for me. Could you check your logs, the PHP log, and the browser console? Are you running Google for WooCommerce alone? 
You can also reach out to https://wordpress.org/support/plugin/google-listings-and-ads/. Our Support Engineers are monitoring the forum and could help you debug it.

**Comment by DerErzengel** [comment]
Thanks for the quick reply! Under Marketing the options “Overview” and “Coupons” are callable, as soon as I go to the option “google for Wocommerce” then it displays a constant loading screen. Here is a screenshot of what the plugin looks like in my case:

![Screenshot 2024-10-02 132349](https://github.com/user-attachments/assets/500649a2-f7b9-4a29-93b6-31789f362d4f)

and this is the error message in the logs under Wocommerce -> Status -> Logs:


`2024-10-02T08:11:30+00:00 ERROR Automattic\WooCommerce\GoogleListingsAndAds\Internal\DependencyManagement\GoogleServiceProvider::handle_unauthorized_error Client error: `POST https://api.woocommerce.com/google/google-mc/content/v2.1/5442787946/reports/search` resulted in a `401 Unauthorized` response:
{
  "error": {
    "code": 401,
    "message": "User cannot access account 5442787946",
    "errors": [
      {
         (truncated...)
2024-10-02T08:11:30+00:00 ERROR Automattic\WooCommerce\GoogleListingsAndAds\Notes\NoteInitializer::add_notes Please reconnect your Google account.
2024-10-02T11:23:39+00:00 ERROR Automattic\WooCommerce\GoogleListingsAndAds\Internal\DependencyManagement\GoogleServiceProvider::handle_unauthorized_error Client error: `POST https://api.woocommerce.com/google/google-mc/content/v2.1/5442787946/reports/search` resulted in a `401 Unauthorized` response:
{
  "error": {
    "code": 401,
    "message": "User cannot access account 5442787946",
    "errors": [
      {
         (truncated...)
2024-10-02T11:23:39+00:00 ERROR Automattic\WooCommerce\GoogleListingsAndAds\Internal\DependencyManagement\GoogleServiceProvider::handle_unauthorized_error Client error: `POST https://api.woocommerce.com/google/google-mc/content/v2.1/5442787946/reports/search` resulted in a `401 Unauthorized` response:
{
  "error": {
    "code": 401,
    "message": "User cannot access account 5442787946",
    "errors": [
      {
         (truncated...)
2024-10-02T11:23:40+00:00 ERROR Automattic\WooCommerce\GoogleListingsAndAds\Internal\DependencyManagement\GoogleServiceProvider::handle_unauthorized_error Client error: `GET https://api.woocommerce.com/google/google-mc/content/v2.1/5442787946/accounts/5442787946` resulted in a `401 Unauthorized` response:
{
  "error": {
    "code": 401,
    "message": "User cannot access account 5442787946",
    "errors": [
      {
         (truncated...)
`

 This is what it says in the browser console:


`Failed to load resource: net::ERR_BLOCKED_BY_CLIENTUnderstand this error
contact-information:1 
        
        
       Failed to load resource: the server responded with a status of 401 ()Understand this error
index.js?ver=816555e1438122e9c8da:25 {message: 'Please reconnect your Google account.', status: 401, code: 'GOOGLE_DISCONNECTED', statusCode: 401}
E @ index.js?ver=816555e1438122e9c8da:25
Tt @ index.js?ver=816555e1438122e9c8da:25
(anonymous) @ redux-routine.min.js?ver=a0a172871afaeb261566:2Understand this error
api-fetch.min.js?ver=4c185334c5ec26e149cc:2 
        
        
       GET https://eu.******.com/wp-json/wc/gla/google/reconnected?_locale=user 401 (Unauthorized)
O @ api-fetch.min.js?ver=4c185334c5ec26e149cc:2
h @ api-fetch.min.js?ver=4c185334c5ec26e149cc:2
(anonymous) @ api-fetch.min.js?ver=4c185334c5ec26e149cc:2
P @ api-fetch.min.js?ver=4c185334c5ec26e149cc:2
(anonymous) @ api-fetch.min.js?ver=4c185334c5ec26e149cc:2
o @ api-fetch.min.js?ver=4c185334c5ec26e149cc:2
(anonymous) @ api-fetch.min.js?ver=4c185334c5ec26e149cc:2
P.method.r @ api-fetch.min.js?ver=4c185334c5ec26e149cc:2
(anonymous) @ api-fetch.min.js?ver=4c185334c5ec26e149cc:2
(anonymous) @ api-fetch.min.js?ver=4c185334c5ec26e149cc:2
o @ api-fetch.min.js?ver=4c185334c5ec26e149cc:2
(anonymous) @ api-fetch.min.js?ver=4c185334c5ec26e149cc:2
(anonymous) @ api-fetch.min.js?ver=4c185334c5ec26e149cc:2
t @ api-fetch.min.js?ver=4c185334c5ec26e149cc:2
(anonymous) @ api-fetch.min.js?ver=4c185334c5ec26e149cc:2
g @ api-fetch.min.js?ver=4c185334c5ec26e149cc:2
(anonymous) @ api-fetch.min.js?ver=4c185334c5ec26e149cc:2
c.use.call.then.e.message @ index.js?ver=816555e1438122e9c8da:25
(anonymous) @ api-fetch.min.js?ver=4c185334c5ec26e149cc:2
j @ api-fetch.min.js?ver=4c185334c5ec26e149cc:2
API_FETCH @ data-controls.min.js?ver=49f5587e8b90f9e7cc7e:2
(anonymous) @ redux-routine.min.js?ver=a0a172871afaeb261566:9
(anonymous) @ redux-routine.min.js?ver=a0a172871afaeb261566:2
t @ redux-routine.min.js?ver=a0a172871afaeb261566:2
(anonymous) @ redux-routine.min.js?ver=a0a172871afaeb261566:2
e @ redux-routine.min.js?ver=a0a172871afaeb261566:2
(anonymous) @ redux-routine.min.js?ver=a0a172871afaeb261566:9
(anonymous) @ redux-routine.min.js?ver=a0a172871afaeb261566:9
(anonymous) @ redux-routine.min.js?ver=a0a172871afaeb261566:9
(anonymous) @ data.min.js?ver=7c62e39de0308c73d50c:2
(anonymous) @ data.min.js?ver=7c62e39de0308c73d50c:2
(anonymous) @ data.min.js?ver=7c62e39de0308c73d50c:2
setTimeout
s @ data.min.js?ver=7c62e39de0308c73d50c:2
i @ data.min.js?ver=7c62e39de0308c73d50c:2
(anonymous) @ commons.js?ver=2ae22dd912b5e1944bb9:90
(anonymous) @ data.min.js?ver=7c62e39de0308c73d50c:9
__unstableMarkListeningStores @ data.min.js?ver=7c62e39de0308c73d50c:2
(anonymous) @ data.min.js?ver=7c62e39de0308c73d50c:2
p @ data.min.js?ver=7c62e39de0308c73d50c:9
(anonymous) @ data.min.js?ver=7c62e39de0308c73d50c:9
Qe @ data.min.js?ver=7c62e39de0308c73d50c:9
Ye @ data.min.js?ver=7c62e39de0308c73d50c:9
i @ commons.js?ver=2ae22dd912b5e1944bb9:90
B @ settings.js?ver=750a7a935467818d824b:1
hu @ react-dom.min.js?ver=18.3.1:2
xi @ react-dom.min.js?ver=18.3.1:2
bs @ react-dom.min.js?ver=18.3.1:2
vs @ react-dom.min.js?ver=18.3.1:2
gs @ react-dom.min.js?ver=18.3.1:2
is @ react-dom.min.js?ver=18.3.1:2
Hl @ react-dom.min.js?ver=18.3.1:2
ts @ react-dom.min.js?ver=18.3.1:2
Ku @ react-dom.min.js?ver=18.3.1:2
(anonymous) @ index.js?ver=be0e43c052ae1fedfc26:1
(anonymous) @ index.js?ver=be0e43c052ae1fedfc26:1
call @ index.js?ver=be0e43c052ae1fedfc26:1
O @ index.js?ver=be0e43c052ae1fedfc26:1
e @ index.js?ver=be0e43c052ae1fedfc26:1
(anonymous) @ index.js?ver=816555e1438122e9c8da:25
Promise.then
(anonymous) @ index.js?ver=816555e1438122e9c8da:25Understand this error
index.js?ver=816555e1438122e9c8da:25 {message: 'Please reconnect your Google account.', status: 401, code: 'GOOGLE_DISCONNECTED', statusCode: 401}`

**Comment by DerErzengel** [comment]
clicked the wrong button, unfortunately the problem persists

**Comment by DerErzengel** [comment]
I hadn't written that so clearly before: I create the Merchant Center account using the plugin so that it is a subaccount of Wocommerce. I then have to ask customer service to delete the Merchant Center account and then I get the errors (I have the same problem on two different websites)

**Comment by DerErzengel** [comment]
Is there anything i can do?

**Comment by mikkamp** [comment]
Thanks for the report @GWE767 

Could you clarify the expectation for Google for WooCommerce after deleting the Merchant Account?

You mentioned:
> after deletion, the plugin can no longer access the account and loads forever

I can understand the expectation that it will properly recover from such a scenario, in fact the last error message you mentioned:
> {message: 'Please reconnect your Google account.', status: 401, code: 'GOOGLE_DISCONNECTED', statusCode: 401}

This should trigger a redirect to a reconnect Google account page, in my case that's what is happening when I no longer have access to the connected account.
But if that continues to be a problem then you can use the technique described here to manually disconnect, so you can reconnect a new account: https://woocommerce.com/document/google-for-woocommerce/faq/#blank-page-when-trying-to-set-up

What I don't understand though, is why you are requesting to delete the account, and then expect to continue using the extension? The Google for WooCommerce extension can't do anything without a Merchant Center account connected.

**Comment by DerErzengel** [comment]
> Thanks for the report [@GWE767](https://github.com/GWE767)
> 
> Could you clarify the expectation for Google for WooCommerce after deleting the Merchant Account?
> 
> You mentioned:
> 
> > after deletion, the plugin can no longer access the account and loads forever
> 
> I can understand the expectation that it will properly recover from such a scenario, in fact the last error message you mentioned:
> 
> > {message: 'Please reconnect your Google account.', status: 401, code: 'GOOGLE_DISCONNECTED', statusCode: 401}
> 
> This should trigger a redirect to a reconnect Google account page, in my case that's what is happening when I no longer have access to the connected account. But if that continues to be a problem then you can use the technique described here to manually disconnect, so you can reconnect a new account: https://woocommerce.com/document/google-for-woocommerce/faq/#blank-page-when-trying-to-set-up
> 
> What I don't understand though, is why you are requesting to delete the account, and then expect to continue using the extension? The Google for WooCommerce extension can't do anything without a Merchant Center account connected.

Thanks for your link, that instantly fixed my Problem! 
I needed to Delete the MC because i wanted to create a Advanced MC Account with Subaccounts and connect the Subaccounts to each of my Subdomains.
