### ISSUE TITLE
Remove the word "Paid" associated with campaign creation

### ISSUE THREAD

**Issue by joemcgill** [woocommerce/google-listings-and-ads#2664]
## Acceptance Criteria
- [ ] Remove the “Paid” in “Paid Performance Max campaigns are automatically optimized for you by Google.” in the sub-title
- [ ] In the CTA to create campaign that says “Launch paid campaign” say “Create Campaign”
- [ ] In the button on the Programs card that says “Add paid campaign” replace for “Add Campaign”
- [ ] Remove the word "Paid" associated with Ads campaigns found in other creation flows

**Comment by mikkamp** [comment]
Closing this as completed since it was part of the [2.9 release](https://github.com/woocommerce/google-listings-and-ads/releases/tag/2.9.0).
