### ISSUE TITLE
Coupon restrictions by brand are not supported

### ISSUE THREAD

**Issue by nicdwilson** [woocommerce/google-listings-and-ads#2693]
### Describe the bug:
While coupon restrictions by brand were previously only available to merchants running a brands plugin, this situation now changes with the introduction of brands to core WooCommerce. In 9069070-zd-a8c the merchant reached out to understand why brand restrictions were not being honored in the coupon field.

We map coupon restrictions [here](https://github.com/woocommerce/google-listings-and-ads/blob/0d356b7f1bd20ee45030876ab59d52b9652e217c/src/Coupon/WCCouponAdapter.php#L220) with no mention of brands.

Not sure if this is a bug or a feature request :)

I lean to bug since this was the user experience.

**Comment by ianlin** [comment]
@nicdwilson Thanks for reporting this issue, it has been fixed in #2697 and will be released in 2.9.2 (scheduled next Tuesday 10 Dec).
