### ISSUE TITLE
Replace `cloneDeep` within reducer by another way

### ISSUE THREAD

**Issue by eason9487** [woocommerce/google-listings-and-ads#270]
### Describe the issue:

This issue was sourced from [here](https://github.com/woocommerce/google-listings-and-ads/pull/264/files/4db418d544da8b70e7f9087677477297d3af65a9#diff-8e875e4932c094a7da6eac9322edf0cb70fbf56fc555137bd686aa9e265a76cf)

It's a potential performance issue to use `cloneDeep` to update nested objects within a redux store. It would make all unchanged objects and arrays within the store's subtree be different references. Then causing all selectors and components to be forced to evaluate re-render.
```js
case TYPES.RECEIVE_SHIPPING_TIMES: {
	const { shippingTimes } = action;
	const newState = cloneDeep( state );
	newState.mc.shipping.times = shippingTimes;
	return newState;
}
```

### Solution options

1. Copy all levels of nested data
```js
case TYPES.RECEIVE_SHIPPING_TIMES: {
	const { shippingTimes } = action;
	const newState = {
		...state,
		mc: {
			...state.mc,
			shipping: {
				...state.mc.shipping,
				times: shippingTimes,
			},
		},
	};
	return newState;
}
```
2. Implement a util function to simplify the option 1 method.
```js
// A util function similar to lodash.set without mutating the input object
// but return a new object with the same subtree references,
// and only change the value at the specified path
function set( object, paths, value ) {
	const [ key, ...restPaths ] = Array.isArray( paths )
		? paths
		: paths.split( '.' );

	if ( restPaths.length === 0 ) {
		return { ...object, [ key ]: value };
	}

	return {
		...object,
		[ key ]: set( object[ key ], restPaths, value ),
	};
}

// Usage example
case TYPES.RECEIVE_SHIPPING_TIMES: {
	return set( state, 'mc.shipping.times', action.shippingTimes );
}
```
3. Use [combineReducers](https://github.com/WordPress/gutenberg/blob/9111ad51e3f123b0b60cc75666412991e834a46b/packages/data/README.md#combineReducers) to cut the store to flatter slices (but raise the complexity)
4. Introduce [Immer](https://immerjs.github.io/immer/docs/introduction) or [Redux Toolkit](https://redux-toolkit.js.org/)
5. Flat the nested object and give a normalized naming rule
5. Any other practice?

### Additional details:

https://redux.js.org/recipes/structuring-reducers/immutable-update-patterns

**Comment by eason9487** [comment]
> FWIW, Personally, I'd vote for Solutions 1 or 2, as they look like a quite minimalistic change and still leaves the flexibility of object structure.

Same to @tomalec 's thoughts. And I'm thinking we can address this by solution 2. And solution 1 can still be used when the path depth is shallow.

@ecgan, what do you think if we take solution 2?

**Comment by ecgan** [comment]
My opinion is that, since we have a bit of time luxury right now, we might as well use it to do this whole wp-data (not limited to this reducer issue) nicely once and for all, based on the experience we have got so far from the project.

A question that I often use to ask myself and other people is this: if we were to build this project from scratch again, how would we implement this wp-data? I think we should come out with a solution based on this question.

So with the above said, here's my comment on the solution options / answer to your question. 

Option 1: I don't quite like it, it looks too verbose and tedious.

Option 2: it looks ok. I was having question with the `set` function and after some googling, I found https://github.com/lodash/lodash/issues/1696#issuecomment-328335502:

```js
const newState = _.setWith(_.clone(state), 'users.user01.name.first', 'John Doe', _.clone);
```

I think this code snippet might be helpful and better than our custom `set` function? 🤔 

For options 3, 4 and 5, yeah we should keep the store state flat. I don't have much opinions on the tools like combineReducer, Immer, or Redux Toolkit. I only have experience with combineReducer from a few years back.

Ultimately, I think we should implement the best solution that we can come up with now, so that we don't need to worry about it so much in the future. (And yes that would mean possible changes to other wp-data files too, not just reducer.)

---

Related to my "build from scratch scenario" question and wp-data, I also think that we should figure out a way to store API errors into the state tree and not swallow API error with `handleFetchError`. For example, maybe the state tree should be something like this:

```
// initial default state.
{
	mc_issues: null	
}

// successful API call.
{
	mc_issues: {
		data: [] // array of mc_issues from API successful result.
	}
}

// error scenario.
{
	mc_issues: {
		error: {} // error object from API error.
	}
}
```

**Comment by eason9487** [comment]
> A question that I often use to ask myself and other people is this: if we were to build this project from scratch again, how would we implement this wp-data? I think we should come out with a solution based on this question.
> 

That's a nice perspective to think about 👍 

> Option 2: it looks ok. I was having question with the `set` function and after some googling, I found [lodash/lodash#1696 (comment)](https://github.com/lodash/lodash/issues/1696#issuecomment-328335502):
> 
> ```js
> const newState = _.setWith(_.clone(state), 'users.user01.name.first', 'John Doe', _.clone);
> ```
> 
> I think this code snippet might be helpful and better than our custom `set` function? 🤔

Surely that's better than implementing by ourselves, but only if we are not going to follow the idea of removing lodash dependency - https://github.com/woocommerce/google-listings-and-ads/pull/462#discussion_r612374627

> For options 3, 4 and 5, yeah we should keep the store state flat. I don't have much opinions on the tools like combineReducer, Immer, or Redux Toolkit. I only have experience with combineReducer from a few years back.

After more thought, I'd say solution 5 is also worth to take if we agree to constraint the state structure by flat naming convention like:

```js
const DEFAULT_STATE = {
	// To be replaced
	mc: {
		target_audience: null,
		countries: null,
		shipping: {
			rates: [],
			times: [],
		},
		settings: null,
		accounts: {
			jetpack: null,
			google: null,
			mc: null,
			ads: null,
			existing_mc: null,
			existing_ads: null,
			ads_billing_status: null,
		},
	},

	// Replace above by
	mc_target_audience: null,
	mc_countries: null,
	mc_shipping_rates: [],
	mc_shipping_times: [],
	mc_settings: null,

	account_jetpack: null,
	account_google: null,
	account_mc: null,
	account_existing_mc: null,
	account_ads: null,
	account_existing_ads: null,
	account_ads_billing_status: null,

	// ... omitted
};
```

The change scope would be a bit wider but still good to me. And the mainly pros are

1. we don't need to create a custom `set` function nor have deeper dependence on lodash
2. it's simple 😆 

> Related to my "build from scratch scenario" question and wp-data, I also think that we should figure out a way to store API errors into the state tree and not swallow API error with `handleFetchError`.

I had drafted a proposal https://github.com/woocommerce/google-listings-and-ads/issues/489#issuecomment-821102756 to store and retrieve errors as well. It's a universal API similar to buit-in methods of `isResolving`, `hasFinishedResolution`, and it would not need to consider other data structures in the state tree. I think it could benefit us to reduce scope and conflict as well when refactoring.

**Comment by ecgan** [comment]
> Surely that's better than implementing by ourselves, but only if we are not going to follow the idea of removing lodash dependency - [#462 (comment)](https://github.com/woocommerce/google-listings-and-ads/pull/462#discussion_r612374627)

Gotcha. From the links given, it seems like it is specific to the Calypso project, not so sure about WooCommerce or WordPress in general. 🤔 

> I had drafted a proposal [#489 (comment)](https://github.com/woocommerce/google-listings-and-ads/issues/489#issuecomment-821102756) to store and retrieve errors as well. It's a universal API similar to buit-in methods of `isResolving`, `hasFinishedResolution`, and it would not need to consider other data structures in the state tree. I think it could benefit us to reduce scope and conflict as well when refactoring.

I followed the links and found your proposal commit https://github.com/woocommerce/google-listings-and-ads/commit/71bece8908c3108dc4d0ed6b9ca96d607927709f. Looking back at it again and giving it a bit more thoughts, I'm not sure if that is a solid approach. Specifically, the `error` is a dedicated state tree node and is separated apart from other business domain state tree, which means when we are looking at one piece of business domain data, we might overlook the `error`. Please see my illustration below:

```
// Your proposal commit:
{
	// when mc_issues API is successful, we will have the array data in here.
	mc_issues: [ ... ], 

	// long list of other nodes.
	...,

	// dedicated `error` node.
	error: {
		// when mc_issues API has error, we store the error here, with a key 'mc_issues' here for example.
		mc_issues: { ... }
	}
}
```

The above means that when we look at mc_issues, we would need to be mindful to look at two places.

Compared the above with my suggestion earlier:

```
// My suggestion from my comment earlier:
{
	mc_issues: {
		data: [ ... ], // array of mc_issues from API successful result.
		error: { ... } // error object when API failed.
		// note that we can (and possibly should) choose to always have either data or error only (not both), 
		// and this can be done in reducer. 
	},
	// long list of other nodes.
	...,
}
```

With this approach, when we look at `mc_issues`, we only need to focus on one sub tree. Also, because it is contained within one subtree, it would work well with `combineReducer` if we want to use that too.

On the resolver side with action dispatch, we can probably do something like this too: (just a quick example off the top of my head)

```js
export function* getMCIssues( query ) {
	try {
		const data = yield apiFetch( {
			path: addQueryArgs( `${ API_NAMESPACE }/mc/issues`, query ),
		} );

		// RECEIVE_MC_ISSUES with positive result as `data`.
		yield {
			type: TYPES.RECEIVE_MC_ISSUES,
			data,
		};
	} catch ( error ) {
		// RECEIVE_MC_ISSUES with negative result as `error`.
		yield {
			type: TYPES.RECEIVE_MC_ISSUES,
			error,
		};
	}
}
```

This means we don't need to have dedicated action type to store errors. We just use `RECEIVE_MC_ISSUES` for receiving both positive and negative result, and reducer would have the logic to handle that. 

I also just happened to find this redux recommended best practice: [Write Actions Using the Flux Standard Action Convention](https://redux.js.org/style-guide/style-guide#write-actions-using-the-flux-standard-action-convention)

> The FSA convention says that actions:
> 
> - Should always put their data into a `payload` field
> - May have a `meta` field for additional info
> - May have an `error` field to indicate the action represents a failure of some kind

Let me know what you think. 🤔

**Comment by eason9487** [comment]
> This means we don't need to have dedicated action type to store errors. We just use RECEIVE_MC_ISSUES for receiving both positive and negative result, and reducer would have the logic to handle that.

If we're using a state management library closer to redux, the FSA format and putting data and error together might be a good way. But with wp-data, perhaps not as good as it may seem at first.

As I understand, although wp-data contains redux, its design concept of connecting with `GET` APIs is to match the corresponding **selector** and **resolver** with the query parameters as the primary key to handle the resolving state management. And uses **actions** to connecting `POST`, `DELETE`, etc. APIs when mutating data. The benefit is that developers don't need to manage concurrent queries, and let wp-data internally manage whether or not to trigger API requests when those queries are triggered in multiple places at the same time.

Compare to redux, no matter read or mutate data, they're triggered by **actions** when using redux, and the data resolving state corresponding to the query parameters and multiple places concurrent queries are managed by developers.

Since `GET` query triggers are managed by wp-data, error handling is more limited, but it also gives a solution, such as the way `isResloving` is designed. Based on the implementations in this project, here list some categories to summarize the differences in error management if we put data and error together.

### Type A - For read-only data without pagination, such as `mc_setup`

Current `mc_setup`:

https://github.com/woocommerce/google-listings-and-ads/blob/4c27b1fc45c215c67ddc4d2e8b9ee9249aed4125/js/src/data/reducer.js#L265-L271

Possible method:

```js
const newState = {
	...state,
	mc_setup: {
		data: action.mcSetup,
		error: action.error,
	},
};
```

Looks good. It's very easy to handle.

### Type B - For read-only data with pagination, such as `mc_issues` and `report`

The errors are corresponding to query parameters, so errors probably need to be set at their query parameters specific position, but not at the first subtree node of `mc_issues`. For example, if the error occurs when loading page 2, how do we store the error of page 2 and even more query parameters?

1. Current `mc_issues`:
    https://github.com/woocommerce/google-listings-and-ads/blob/4c27b1fc45c215c67ddc4d2e8b9ee9249aed4125/js/src/data/reducer.js#L281-L303
    Possible method:
    ```js
    const { query, data, error } = action;

    const newState = {
    	...state,
    	mc_issues: {
    		...state.mc_issues,
    		issues: [ ...state.mc_issues.issues ],
    		// use an object to hold different page errors
    		errors: {
    			...state.mc_issues.errors,
    			[ query.page ]: error,
    		},
    	},
    };

    newState.mc_issues.issues.splice(
    	( query.page - 1 ) * query.per_page,
    	query.per_page,
    	...data.issues
    );
    ```
2. Current `report`:
    https://github.com/woocommerce/google-listings-and-ads/blob/4c27b1fc45c215c67ddc4d2e8b9ee9249aed4125/js/src/data/reducer.js#L335-L344
    Possible method:
    ```js
    const { reportKey, data, error } = action;
    return {
    	...state,
    	report: {
    		...state.report,
    		[ reportKey ]: {
    			data,
    			// use one more layer to put error with corresponding data
    			error,
    		},
    	},
    };
    ```

### Type C - For mutable data without pagination, such as `mc.shipping.rates`

Current **RECEIVE** of `mc.shipping.rates`:

https://github.com/woocommerce/google-listings-and-ads/blob/4c27b1fc45c215c67ddc4d2e8b9ee9249aed4125/js/src/data/reducer.js#L52-L62

Current **UPSERT** of `mc.shipping.rates`:

https://github.com/woocommerce/google-listings-and-ads/blob/4c27b1fc45c215c67ddc4d2e8b9ee9249aed4125/js/src/data/reducer.js#L64-L84

Current **DELETE** of `mc.shipping.rates`:

https://github.com/woocommerce/google-listings-and-ads/blob/4c27b1fc45c215c67ddc4d2e8b9ee9249aed4125/js/src/data/reducer.js#L86-L95

Possible method:
```js
const newState = getNextStateForShipping( state );
newState.mc.shipping.rates = {
	// processed data for each read/upsert/delete implementations
	data: nextShippingRates,
	errors: {
		[ `${ action.type }` ]: action.error,
	},
};
```

### Type D - For mutable data with pagination, such as `mc_product_feed`

Current `mc_product_feed`:

https://github.com/woocommerce/google-listings-and-ads/blob/4c27b1fc45c215c67ddc4d2e8b9ee9249aed4125/js/src/data/reducer.js#L305-L333

Possible method:

```js
const { query, data, error } = action;
const newState = {
	...state,
	mc_product_feed: {
		...state.mc_product_feed,
		pages: {
			...state.mc_product_feed.pages,
			[ `${ action.type }:${ query.page }` ]: {
				products: data.products,
				// use one more layer to put error with corresponding data
				error,
			},
		},
	},
};
```

---

We do have workable solutions to handle these categories of data structures. But apart from *Type A*, I'd say the rest methods look not that good and need to take different considerations against how data are organized, and the overall **reducer** starts getting complicated. Not to mention that all **selectors** would have to make substantial changes respectively.

Look further at their patterns, we could see most of them have to use query parameters and maybe plus `action.type` to generate a primary key for storing data and errors, regardless of where they're stored. And if abstract these patterns, the solution I concluded was that universal API, which is able to cover all practical usages we have. Thus, the pros are:

- Separation of concerns. The data and errors are handled separately to make each can be focused on a smaller scope.
- One method for all cases and it's simpler than all different considerations above
- Easier to modify and expand
- Easier for unit tests
- Easy to understand because it has the similar concept and interface to `isResolving`
- It would not create more nested layers within each subtree, so we can still have the chance to consider solution 5 for the original issue

For me, this brings more benefits than seeing data and errors within one subtree node.

**Comment by ecgan** [comment]
@eason9487 , that's a pretty good analysis and comparison, good stuff! 🙂 👍 

> Compare to redux, no matter read or mutate data, they're triggered by **actions** when using redux

In redux, we read data by using [`useSelector`](https://react-redux.js.org/api/hooks#useselector), there are no action involved, no? 🤔 

> Based on the implementations in this project, here list some categories to summarize the differences in error management if we put data and error together.

I must say Type C is really the trickiest and the most difficult one. I don't have an idea right now on how to better handle it. 

For Type B and Type D, I think I'd probably use the parameters as keys, and put `data` and `error` under the key, maybe something like this:

```
{
    mc_product_feed: {
		...state.mc_product_feed,
        [ `${ action.type }:${ query.page }` ]: {
            data: data.products,
            error,
        },
	},
}
```

---

> * Easy to understand because it has the similar concept and interface to `isResolving`

I think this is a really good point if we want to go with your suggested "universal API". 💯  It is a good answer to why we want to store the `error` that way: to be consistent with `isResolving`.

> For me, this brings more benefits than seeing data and errors within one subtree node.

So, relating this back to my earlier question, "if we were to build this project from scratch again", would you go with the universal API? 

If the answer is yes, I guess feel free to go ahead. 😄  Also cc @tomalec in case he has opinions on the `error` things too.

**Comment by eason9487** [comment]
@ecgan 

> In redux, we read data by using [`useSelector`](https://react-redux.js.org/api/hooks#useselector), there are no action involved, no?

I didn't write clearly. I wanted to compare the entry point of fetching data from server APIs:

- redux: dispatch an action such as `fetchPost( id )` in some of component's lifecycle
- wp-data: call a selector such as `getPost( id )` in component's render phase, and wp-call will call the relevant resolver if the post is not yet resolved

> So, relating this back to my earlier question, "if we were to build this project from scratch again", would you go with the universal API?

To me, the proposed error handling was almost like starting from scratch because we don't have other implementation yet and I kept thinking that for a while. When I tried to figure out a solution for #438, my first thought was also to put the error and data together. But after the report pages and ads programs table developments, I switched to the similar approach to `isResolving`. Till now the solution and thoughts are the same as it was then.

And there are some references take the similar concept:

- https://github.com/woocommerce/woocommerce-admin/blob/v2.1.2/packages/data/src/reports/reducer.js
- https://github.com/google/site-kit-wp/blob/1.34.1/assets/js/googlesitekit/data/create-error-store.js

---

Back to the primary topic of this issue, I think the lodash way you found is really solid.

> Option 2: it looks ok. I was having question with the `set` function and after some googling, I found [lodash/lodash#1696 (comment)](https://github.com/lodash/lodash/issues/1696#issuecomment-328335502):
> 
> ```js
> const newState = _.setWith(_.clone(state), 'users.user01.name.first', 'John Doe', _.clone);
> ```

I'm thinking that even in the longer term, the deprecating of lodash isn't a priority in this project and that we can adopt it to solve this issue in a minimal change scope. When lodash is phased out one day, we only need to implement the same interface function to replace it and don't need to reconsider another solution then.

**Comment by ecgan** [comment]
@eason9487 ,

> When I tried to figure out a solution for #438, my first thought was also to put the error and data together. But after the report pages and ads programs table developments, I switched to the similar approach to `isResolving`. Till now the solution and thoughts are the same as it was then.

Thanks for the explanation, that's a good and interesting background context 🙂  👍 

> I'm thinking that even in the longer term, the deprecating of lodash isn't a priority in this project and that we can adopt it to solve this issue in a minimal change scope. When lodash is phased out one day, we only need to implement the same interface function to replace it and don't need to reconsider another solution then.

Agree 💯 🙂

**Comment by tomalec** [comment]
Sorry, I didn't comment earlier, I mostly agree with what you stated here, and don't have much constructive input, other than my high-level comments

1. In general I like [the idea of keeping errors close](https://github.com/woocommerce/google-listings-and-ads/issues/270#issuecomment-863412160) to the state nodes they refer to. Thanks to that, as a consumer, in the view, I don't need to think where in the partial state tree am I? I just check: do I have data? Yes: cool, go and render it; No: do something with the error. 

    However, to really not think about "where am I?", would mean to have `{data, error}` at **every** node, which looks like too much bloat. So, with [the extensive list of other pros](https://github.com/woocommerce/google-listings-and-ads/issues/270#issuecomment-863934991) mentioned by @eason9487, I'm totally for the `getError` approach

    We can alternatively think of diverging from plain, serializable JSON, and explore more complicated solutions like putting to the specific node an instance of `ErrorObject` instead of expected data, or optionally adding a `[ Symbol( "error" ) ]` property to every node, to store errors there. Then on the consuming side, we should always look it up. However, as @eason9487  [referenced similar appraochec](https://github.com/woocommerce/google-listings-and-ads/issues/270#issuecomment-864708881) `getError` looks more convenient, and consistent with existing features.

2. > "if we were to build this project from scratch again", would you go with the universal API?

	Yes :)
3. When I think about state management problems we face, I cannot stop thinking on 
    1. Why isn't it solved on WP/Woo/wp-data platform level, and we need to handcraft it here?

        Said that I find it another reason to go with a "universal solution" which maybe someday could be upstreamed :)

    2. (definitely out of scope of this issue) Why do we stick to the old-school XHR/REST, instead of for example Web Socket?
        1. Do we really keep the server completely stateless, and do not have state/session already for logged-in inside woo-admin?
        2. With current REST we to lots of translations. PHP end: database JSON state → JS end: action → JSON change → client-side JSON state.  
        Maybe we could reduce it a little. PHP end: database JSON  state → Service Worker/regular JS/stateful PHP: (given it is already aware of local user state)  JSON change (patch) → client-side JSON state. 
        That way we reduce the number of translations, simplify the flow, don't need to cater for `isResolving`, pending, concurrent requests, etc. as we are prepared for receiving a message at any time

**Comment by tomalec** [comment]
Speaking of `lodash.set` `setWith`

Personally, besides even of Calypso approach, I like to limit the number of dependencies, to keep the code more lightweight, flexible, explicit, as it allows new/3PD folks to jump in easier, reduces technical debt, bugs & security investigation time, etc.

Calypso team [already stated few other good reasons](https://calypsop2.wordpress.com/2021/02/24/the-path-to-deprecating-lodash/) not to keep lodash around, and I think they are valid here as well. So, in the long term, I think we should remove lodash from GLA.

However, given we already have it in our repo, and the scope of this issue is complicated anyway, I think it's good to start with using its methods to focus on solving our state management problem.

We could address lodash as a separate effort afterward. Maybe in the process of solving this here, we could come up with some more strict or relaxed requirements in regards to `set` function so we could implement our own profiled util (similar to Calypso approach [https://github.com/Automattic/wp-calypso/tree/trunk/packages/js-utils](https://github.com/Automattic/wp-calypso/tree/trunk/packages/js-utils))
