### ISSUE TITLE
Duplicate reporting due to incorrect meta value comparison

### ISSUE THREAD

**Issue by ridings3d** [woocommerce/google-listings-and-ads#2733]
### Describe the bug:
I had noticed that a few of the websites I manage was having issues double reporting and it seemed to be from people that were revisiting their thank you page across multiple days. I have nailed the issue down to the file “GlobalSiteTag.php” located in the src > Google folder. The issue resides on line 358 and has to do with the strict checking of the returned meta key value. The function “get_meta” will return a string and not an integer in this case because the database for meta values is set as text. To fix this issue, Line 358 – 360 in the file “GlobalSiteTag.php” should change from:
```
if ( ! $order || 1 === $order->get_meta( self::ORDER_CONVERSION_META_KEY, true ) ) {
    return;
}
```
TO:
```
if ( ! $order || '1' === $order->get_meta( self::ORDER_CONVERSION_META_KEY, true ) ) {
    return;
}
```

To stay consistent, the line 363 should also be changed to a string instead of a integer.

### Steps to reproduce:
1. Complete a checkout and on the thank you page, inspect the page code and look for the gtag conversion event.
2. Verify in the database for this order that the meta value for "_gla_tracked" is set to 1.
3. Refresh the thank you page and the gtag conversion event is still there even with the meta value set to 1

### Expected behavior:
The gtag conversion event should not fire after the thank you page loads for the first time.

### Actual behavior:
The gtag conversion event is firing on every page refresh.

### Additional details:
We are currently running version 2.9.2 and I have been testing this fix for the past month or so and our double reporting has stopped happening.

**Comment by mikkamp** [comment]
Thanks for the suggested fix and uncovering this issue @ridings3d 

That is indeed correct that the types don't match. It seems like it was originally implemented as a non-strict comparison, and then later adjusted to conform to PHPCS rules: https://github.com/woocommerce/google-listings-and-ads/commit/45bff6f6d9d628a8a3eb100aeaf0e2b8b7034ff1

Unfortunate that it didn't get caught all this time. While it is correct that `get_meta` will return a string. It's a bit inconsistent with the type if it's called directly after setting the meta field, where it would still have it's original type. That won't happen in this case but just to be safe I think it would be best to use a type cast before comparison:

```php
if ( ! $order || 1 === (int) $order->get_meta( self::ORDER_CONVERSION_META_KEY, true ) ) {
    return;
}
```

We'll work on getting this fixed, and hopefully it can be included in a release soon.

**Comment by ridings3d** [comment]
Awesome! Thank you for the quick response @mikkamp
