### ISSUE TITLE
Refactor useGetRemainingCountryCodes

### ISSUE THREAD

**Issue by ecgan** [woocommerce/google-listings-and-ads#274]
This is a follow up from https://github.com/woocommerce/google-listings-and-ads/pull/264#discussion_r585243370.

Currently we have two similar copies of `useGetRemainingCountryCodes` hook, one for shipping rate and one for shipping time. There is just a bit of difference between both.

This issue is aimed to refactor the code to reduce the duplication.

**Comment by eason9487** [comment]
There are no `useGetRemainingCountryCodes` hooks after merging #1616.
