### ISSUE TITLE
Investigate if we can reduce the Google Client Library bundle size (and verdor directory size in general)

### ISSUE THREAD

**Issue by jconroy** [woocommerce/google-listings-and-ads#314]
Currently, the Google Ads client library weighs in at ~96 MB with support for 4 different versions of the API

This is an issue to investigate ways we can minimize this - presumable we can drop the older version support which looks like adds up to ~48mb

**Comment by findingsimple** [comment]
Just noting that I believe we're still seeing issues as a result of size of the extension e.g. "Auto install fails, manual upload also fails."

**Comment by mikkamp** [comment]
Linking a [branch](https://github.com/woocommerce/google-listings-and-ads/tree/cleanup-google-ads-services) that I created a while back. What that does is it removes unused Services in the Google Ads library, which results in about 10MB of files less. Now that we completed all the unit testing for classes that use the Ads library I feel more comfortable pushing that across the line. Are we adding a higher priority to this issue?

**Comment by findingsimple** [comment]
> Are we adding a higher priority to this issue?

I'd like to yep

**Comment by mikkamp** [comment]
We've implemented several steps to reduce the library sizes:
- Script for cleaning up vendor files #516
- Script for removing unused Google Ads Services #1495

We've consistently stayed around the 7MB mark for the final release zip. Which is an acceptable plugin size. Closing this issue for now but it can be reopened if we come across additional issues where the size becomes a problem.
