### ISSUE TITLE
Handle Google account disconnect and prompt user to reconnect

### ISSUE THREAD

**Issue by mikkamp** [woocommerce/google-listings-and-ads#486]
### Describe the issue:
Even though the server handles the token and renews it with the refresh token. There are still scenarios where a refresh token could be revoked, which results in the Google account no longer being connected.
This can mainly happen in scenarios where the connection to the app is revoked, or possibly a limit is hit. [Full list of reasons](https://blog.timekit.io/google-oauth-invalid-grant-nightmare-and-how-to-fix-it-9f4efaf1da35) why it might no longer be valid.

When this happens, at the moment we just get failed requests to the API, but we don't catch this explicitly to prompt the user to reconnect. Even when we move to the settings page we can't see the proper status and correct the error:

![image](https://user-images.githubusercontent.com/11388669/114862680-ba62ad00-9de6-11eb-986f-bcf220ada814.png)

### Expected behavior:

We should get a clear error message in the UI that prompts the user to reconnect.

When sending a request we do get the right response:
```
2021-04-15T11:34:27+00:00 DEBUG Automattic\WooCommerce\GoogleListingsAndAds\API\Google\MerchantReport::get_report_data {"statusCode":400,"error":"Bad Request","message":"Site is not connected to Google account for google-mc"}
```

Maybe we need to add a generic handler to pass this on to the UI. In the UI we see the error:
```
Unable to retrieve report data.
```

It seems to work. And I think it might have some details need to confirm:

1. When a user reconnects a no access Google account (above step 4.ii), and if they browse to other pages in this status, would the HTTP status code still being 401? Thus we can bring user back to the reconnection page again.
2. Inherited from above, in this status, whether the frontend requests `DELETE` to the same API `/wc/gla/google/connect` to disconnect the wrong Google account as well when they click on the "Try another Google account" button? Or requests to the new endpoint?

#### 💡  Google account reconnection flow (added on June 8)

When GLA doesn't have valid credentials available for the Google account, the reconnection flow would be:

1. When the client receives any 401 response from APIs, redirect the user to the reconnection page: `/wp-admin/admin.php?page=wc-admin&path=/google/settings&subpath=/reconnect-accounts`.
2. In the reconnection page, fetch account connection status from a new API (#823) `/wc/gla/google/reconnected`. At this moment, the API response should be:
    ```json
    {
      "active": "no",
    }
    ````
    And the UI status should be:
    ![image](https://user-images.githubusercontent.com/17420811/123081295-66acb980-d450-11eb-854f-094e10c9bf03.png)
3. The "Connect" button redirects the user to Google's authorization page. After proceeding with authorization, Google redirects the user back to the reconnection page.
4. The reconnection page requests to account connection status from the API `/wc/gla/google/reconnected` again to get the accessibility of currently connected Google MC and/or Ads accounts.
    1. No: go to step 5.
    2. Yes: go to step 6.
5. User connected to a Google account that doesn't have accessibility of current MC/Ads. The API response should be:
    ```json
    {
      "active": "yes",
      "email": "test@gmail.com",
      "merchant_account": 1234567890,
      "merchant_access": "no",
      "ads_account": 5678901234,
      "ads_access": "no"
    }
    ```
    Adn display the fault-tolerant process UI:
    ![image](https://user-images.githubusercontent.com/17420811/123081362-73c9a880-d450-11eb-8f2a-914ffbf66ef1.png)
    1. When clicking on "Disconnect all accounts ", popup the confirm modal. Redirects to the Get Started page If the user proceeds with all accounts disconnecting process.
    2. When clicking on "Try another Google account", disconnect Google account and go to step 2 again.
6. Reconnected successfully. Redirect to the dashboard page.

### Steps to reproduce:
1. Connect all the accounts
2. Use the connection test page to disconnect only the Google account
3. Go back to the UI and notice that requests fail and the settings page is not viewable.

**Comment by aheckler** [comment]
4065218-zen ran into this. The workaround I devised:

1. Go to `https://www.example.com/wp-admin/options.php`.
2. Set `gla_redirect_to_onboarding` to `yes`.
3. Set `gla_mc_setup_completed_at` to be empty.
4. Scroll to bottom, click Save Changes.
5. Go to `https://www.example.com/wp-admin/admin.php?page=wc-admin&path=%2Fgoogle%2Fstart`.

Not sure if that's the "proper" way or what, but it worked for the user. ¯\\_(ツ)_/¯

**Comment by nima-karimi** [comment]
I had a brief discussion about this with @mikkamp on internal Slack (p1623910263056500-slack-C01E9LB4X61) and we decided the following:

- Send either an email or an admin notification to the user once we detect that their Google account is disconnected and they need to reconnect it manually before the product can function (syncing, etc. will not work unless they reconnect)
- Check if the user has access to the Merchant Center ID we've stored when they reconnect their Google account. This might need some UI changes to warn the user if we detect that they don't have access to the Merchant Center on file
- Check if the user has access to the Google Ads account we have on file (we store the ID) and warn them if they don't

**Comment by j111q** [comment]
☝️  This makes sense to me. 
 
I did a quick mock of the flow, do take a look:

![disconnected0001](https://user-images.githubusercontent.com/65582817/122354022-2e563880-cf83-11eb-9d15-f61080797bf0.gif)

Figma link: https://www.figma.com/file/eQ9O4m2flzrcAiDMXkOW0m/?node-id=9%3A1115

**Comment by eason9487** [comment]
Hey @j111q ,

![image](https://user-images.githubusercontent.com/17420811/122729721-0bda5d00-d2ac-11eb-8996-f00b45850ba2.png)

I'm thinking would it better to display a **⚠️ Unable to proceed** or some proper tip instead of **✅  Connected**? Because of

- The user is unable to recover currently connected GLA if they reconnect with another Google account
- The user need to disconnect all currently connected accounts if they confirm to set up from the beginning
- I'm a bit worried that users might feel confused when seeing **✅  Connected**, but they cannot proceed. Use another status and tip within the Google account card to make it more consistent with error messages below, and let them know actually they run into a fault-tolerant process to help them resume to correct ways.

**Comment by j111q** [comment]
Yeah that's a really good point, thanks for flagging!! 😅 

I tried some other alternatives but I think it's best if we just remove "Connected", and I improved the wording in the error message as well.

See the updated gif here:

![disconnected0001c](https://user-images.githubusercontent.com/65582817/122741052-28c85d80-d2b7-11eb-866c-0552e7483fb0.gif)

Improved copy for the error message:

```
This Google account, mypersonalemail@gmail.com, was not the Google account previously connected to this integration.

Thus, it doesn't have access to the Google Merchant Center and/or Google Ads account currently connected to this WooCommerce store. 

Try connecting with a different Google account, or completely disconnect all your connected accounts.
```

Let me know if that works!

**Comment by eason9487** [comment]
I assigned myself for the frontend dev and will work on the UI parts first.

There might be a configuration that needs to dig out. After user accept the authorization at Google end, it will be redirected back to the MC setup flow path `/wp-admin/admin.php?page=wc-admin&path=%2Fgoogle%2Fsetup-mc&google-mc=connected`. Does anyone know where to specify the redirect URL settings?

**Comment by mikkamp** [comment]
> Does anyone know where to specify the redirect URL settings?

That would be done here: https://github.com/woocommerce/google-listings-and-ads/blob/1.0.0/src/API/Site/Controllers/Google/AccountController.php#L79
The `<service>=connected` gets added to the URL by the WCS.

**Comment by eason9487** [comment]
Technical questions for backend dev:

1. After completing the onboarding process, the client will use `/wc/gla/google/connected` API to check the status of connected Google account when entering all pages. And when a user selects a different Google account to reconnect, does backend side plan to add the new status at the same API for the client to enter the process as shown in the screenshot below? Or it would be another (new) API?
2. The client has to check Google account status every time when any page loaded, so this check flow and API request will happen frequently, will there be any concern at the backend side?

![image](https://user-images.githubusercontent.com/17420811/123027327-3ba27580-d410-11eb-99ee-c233e8cf9e6d.png)

**Comment by mikkamp** [comment]
For question 1: We still haven't decided exactly when that will be done. I don't think it should be done all the time since it requires a request to both MC and Ads accounts, so it will be relatively "expensive" to do it on each status check.
Would it make sense to add a `/wc/gla/google/reconnected` endpoint, or do you think it's better for the backend to detect when a reconnect happened? In theory the backend could detect a recent reconnect but it might be hard to know the full UI status in case the page was reloaded after a reconnect.

For question 2: The idea was not to check the status on each page load. Mainly because we don't store the connected email address, so it sends a request to the Google API to retrieve the connected email address.
In the backend we have a global handler for any request that is sent to WCS: https://github.com/woocommerce/google-listings-and-ads/blob/1.0.0/src/Internal/DependencyManagement/GoogleServiceProvider.php#L191-L193
Which means that in the frontend if you ever receive a 401 response to any request you can know the Google account is no longer connected. Is it possible for this response code to trigger a reconnect procedure?

**Comment by eason9487** [comment]
Thanks for the explanation!

> Which means that in the frontend if you ever receive a 401 response to any request you can know the Google account is no longer connected. Is it possible for this response code to trigger a reconnect procedure?

Detect if receive a 401 response is a more robust way. However, since the `wordpress@api-fetch` library discards the HTTP status code by default, it's possible to add the HTTP status code to the response body together? For example,

Current 401 response:

```json
{
  "message": "Unable to retrieve report data."
}
```

Still returning 401 response, and change the response body to:

```json
{
  "code": 401,
  "message": "Unable to retrieve report data."
}
```

In this way, the frontend side could do the global processing more elegantly, or it'd need to have a workaround.

---

> Would it make sense to add a `/wc/gla/google/reconnected` endpoint, or do you think it's better for the backend to detect when a reconnect happened?

To align the flow between frontend and backend sides. With a new `/wc/gla/google/reconnected` endpoint, I assumed that when user reconnecting Google account, the page flow would be:

1. Happened a 401 error and then redirecting user to the reconnect page.
2. Fetch account connection status from the API `/wc/gla/google/reconnected` to display the UI.
    ![image](https://user-images.githubusercontent.com/17420811/123081295-66acb980-d450-11eb-854f-094e10c9bf03.png)
3. Click on the "Connect" button and be redirected to Google's authorization page.
4. Google redirects user back to the reconnection page. And the page requests to account connection status from the API `/wc/gla/google/reconnected` again to get the accessibility of currently connected Google MC and/or Ads accounts.
    1. Yes: redirect to dashboard
    2. No: display the fault-tolerant process UI
        ![image](https://user-images.githubusercontent.com/17420811/123081362-73c9a880-d450-11eb-8f2a-914ffbf66ef1.png)

It seems to work. And I think it might have some details need to confirm:

1. When a user reconnects a no access Google account (above step 4.ii), and if they browse to other pages in this status, would the HTTP status code still being 401? Thus we can bring user back to the reconnection page again.
2. Inherited from above, in this status, whether the frontend requests `DELETE` to the same API `/wc/gla/google/connect` to disconnect the wrong Google account as well when they click on the "Try another Google account" button? Or requests to the new endpoint?

**Comment by mikkamp** [comment]
> Detect if receive a 401 response is a more robust way. However, since the wordpress@api-fetch library discards the HTTP status code by default, it's possible to add the HTTP status code to the response body together?

We don't have a global response/error handler so we'll have to find a workaround or refactor some of the code to always add in the status code in the response.

> 1\. When a user reconnects a no access Google account (above step 4.ii), and if they browse to other pages in this status, would the HTTP status code still being 401? Thus we can bring user back to the reconnection page again.

That would depend on the request that's sent or which page they view. WCS specifically returns the 401 error when we don't have valid credentials available for the account. In this scenario it does have valid access credentials available, so it would return an error about the resources it's trying to access, which won't necessarily be a 401 error.

> 2\. Inherited from above, in this status, whether the frontend requests DELETE to the same API /wc/gla/google/connect to disconnect the wrong Google account as well when they click on the "Try another Google account" button? Or requests to the new endpoint?

A disconnect request would include sending a request to the Google API to revoke the token and removes the stored token from WCS. Issuing a connect directly (even if we are already connected), will overwrite the token on WCS and leave the old Google token as is. So technically both will work, although the delete + connect would probably be better.

**Comment by eason9487** [comment]
> We don't have a global response/error handler so we'll have to find a workaround or refactor some of the code to always add in the status code in the response.

It only needs a little modification in one place from the frontend, so If this requires more effort or time at backend side, I think we could have that workaround to get the HTTP status code from the frontend side. After all, there's already a [code fragment](https://github.com/woocommerce/google-listings-and-ads/blob/14d73c1ef089af6a51e95c4e07ea92562e2cc9d0/js/src/hooks/useApiFetchCallback.js#L135-L149) that used a similar approach.

Adding error codes to response body could still be placed in the backlog. In the long run, if it needs to handle errors in a more detailed way, it'd be easier to determine what happened by custom error codes.

> That would depend on the request that's sent or which page they view. WCS specifically returns the 401 error when we don't have valid credentials available for the account. In this scenario it does have valid access credentials available, so it would return an error about the resources it's trying to access, which won't necessarily be a 401 error.

Got it. 📝  As a dev note, we will have to watch out for any unintended effects in this path.
