### ISSUE TITLE
Incompatibility with `@wordpress/components` `RadioControl` component version 13.0.0 - 13.0.2

### ISSUE THREAD

**Issue by ecgan** [woocommerce/google-listings-and-ads#497]
### Describe the bug:

Our use of RadioControl is not compatible with `@wordpress/components` version 13.0.0 - 13.0.2. In those versions, the RadioControls would get checked as per the following screenshot:

![](https://user-images.githubusercontent.com/417342/115151546-e52b5a80-a09f-11eb-94b4-1a82155eef87.png)

We would need to investigate whether this is due to breaking change in `@wordpress/components`. Currently we are using version 12.0.8 and it is working fine.

### Expected behavior:

The RadioControl should work as per normal, only one RadioControl should be checked at one time. 

### Actual behavior:

Both RadioControls are checked.

### Steps to reproduce:

1. Open https://gla1.test/wp-admin/admin.php?page=wc-admin&path=%2Fgoogle%2Fsetup-mc
2. Proceed to Step 2. 
3. In the Location settings, only one of "All countries" or "Selected countries only" should be selected, not both.

**Comment by eason9487** [comment]
Closing this issue as the `@wordpress/components` version 19.17.0 has been used for over 9 months, it's larger than the problematic version range, and no the same issue has been reported.
