### ISSUE TITLE
Don't bundle SVG Images in JS build

### ISSUE THREAD

**Issue by ecgan** [woocommerce/google-listings-and-ads#498]
## User story

Currently we have a number of SVG images that are bundled together in JS build output. This causes the JS build output significantly and unnecessarily large.

One way to fix it is to move those SVG images into a separate "public" / "assets" folder and don't include them in the JS build, and then we can display those images like below:

```
<img
	className="wc-admin-shipping-banner-illustration"
	src={ wcAdminAssetUrl + 'shippingillustration.svg' }
	alt={ __( 'Shipping ', 'woocommerce-admin' ) }
/>
```

Reference: https://github.com/woocommerce/woocommerce-admin/blob/5ebba741eaca7f73137db408996aa3c25d16612a/client/wp-admin-scripts/print-shipping-label-banner/shipping-banner/index.js#L400-L404

For more reference and implementations, checkout the WC-Admin repo and do a global search with the keyword ".svg".

Related slack thread: https://a8c.slack.com/archives/CK365S85V/p1618576095270200

**Comment by tomalec** [comment]
(FWIW, this is another reason to consider using Web Components more ;) - you can deliver the entire scaffold as plain, cheap HTML, with inlined SVGs that compress efficiently and do not put much stress on CPUs.)

**Comment by tomalec** [comment]
Unfortunately, my [PR](https://github.com/woocommerce/google-listings-and-ads/pull/897) introduced a bug, as it removed SVGs not only from JS bundle but also from `.zip`. See https://github.com/woocommerce/google-listings-and-ads/pull/897#issuecomment-888246189
