### ISSUE TITLE
Put in .nvmrc with LTS (v14) when next wp-env is released

### ISSUE THREAD

**Issue by ecgan** [woocommerce/google-listings-and-ads#50]
wp-env is supposed to work with node LTS but right now it doesn't work: https://github.com/WordPress/gutenberg/issues/26660. 

[The fix](https://github.com/WordPress/gutenberg/pull/26712) is scheduled to be in [Gutenberg 9.4](https://github.com/WordPress/gutenberg/milestone/135), "due by November 26, 2020".

**Comment by eason9487** [comment]
Looks like we could close this because the current e2e doesn't use wp-env, and .wp-env.json was removed from #801.

**Comment by ecgan** [comment]
@eason9487 , thanks for spotting this. I'm closing this issue.
