### ISSUE TITLE
Multi User Management

### ISSUE THREAD

**Issue by jconroy** [woocommerce/google-listings-and-ads#51]
Our [current test connection code](https://github.com/woocommerce/google-listings-and-ads/pull/49) requires each user to connect a jetpack account to get to the next step.

WCPay doesn't appear to do the same thing (I can continue setup using a different account) - we'll need to investigate a similar approach and see if it will work for us.

**Comment by mikkamp** [comment]
This is quite similar to #931 which was resolved for the Connection test page in #947
For the UI we logged the issue in #624 which was resolved in #893

For the multi step setup process we check the Jetpack connection status with the endpoint `wc/gla/jetpack/connected`, this returns the connected account regardless of which site account is being used, so the setup can be continued where it was left off.

Closing this as it's fully resolved.
