### ISSUE TITLE
Account connection issues in beta test

### ISSUE THREAD

**Issue by j111q** [woocommerce/google-listings-and-ads#514]
### Describe the bug:

Our beta tester installed the .zip file and tried to setup and this happened:

![Screen Capture on 2021-04-23 at 15-56-09](https://user-images.githubusercontent.com/65582817/115856724-6ba8b900-a45f-11eb-869e-d3e685f22a2e.gif)

Through a follow-up email, he said:

> First I disabled my wordfence 2FA to make sure it has nothing to do with it. Didnt make a difference.
> Then I installed jetpack and tried to login. Same fail it seems. So I uninstalled it again.
> Then I went to wordpress.com and logged in with my PV account. https://wordpress.com/me/account
> This seemed to work.
> (I was confused that on the .org domain my account is different https://nl.wordpress.org/plugins/ and uses my private email address)
> Now I went back to the google link plugin and it seemed I was able to login :)
> However it redirected me back and I got the error: “There was an error loading Google Account Info”.
> See also the screenshot.

![image](https://user-images.githubusercontent.com/65582817/115856445-14a2e400-a45f-11eb-9238-3d34cd9235c9.png)

### Additional details:

His domain is: pv-productions.com

**Comment by findingsimple** [comment]
Closing - can reopen if needed
