### ISSUE TITLE
Allow globally mapping attributes to existing product fields or taxonomy values

### ISSUE THREAD

**Issue by nima-karimi** [woocommerce/google-listings-and-ads#572]
Split from #428 

We need to implement a way for the user to set up global mappings that map each product attribute to another product field. A similar method is done by the Google Product Feeds extension and, As @mikkamp mentioned in https://github.com/woocommerce/google-listings-and-ads/pull/428#issuecomment-814128796, has proved to be very useful:

> I know this is a work in progress, but I had some initial questions on how we can simplify this for a store owner. A while back I was pretty intensely involved in helping store owners get their product feeds setup with the [Google Product Feed](https://woocommerce.com/products/google-product-feed/) extension.
> 
> While it does offer the option to set/override a GTIN / MPN or brand per product, most store owners weren't using this (especially the ones with a substantial set of products). Mostly products were created using some kind of importer, and additional data that doesn't fit in the WooCommerce fields, is saved as either a custom taxonomy or a custom field.
> 
> The [Google Product Feed](https://woocommerce.com/products/google-product-feed/) extension, offers the ability to setup a mapping between each of it's fields. Like here where we can choose to retrieve the GTIN from the WooCommerce SKU field, or optionally any other custom field/taxonomy:
> 
> ![image](https://user-images.githubusercontent.com/11388669/113718070-31f85400-96e4-11eb-85cd-fd427130b781.png)
> 
> This allows the store to use a fully automated process, when importing/updating products so they don't need to do manual data entry. It also makes it quite flexible when retrieving data from other extensions such as Yoast SEO or our own [Brands](https://woocommerce.com/products/brands/) extension.

**Comment by gmangesh** [comment]
This feature will also be useful for mapping product_shipping_class attribute to the shipping_label attribute used within Google Merchant for setting up shipping cost tables. This is very first issue I encountered when trying to use this plugin and is preventing any of my products for becoming active. The only easy workaround is to setup a flat shipping rate, but this does not work for my catalog as the shipping rates vary significantly between items based on the shipping class.

**Comment by melek** [comment]
Another customer also wants to be able to set the `shipping_label` field manually, and I believe this feature would be a great way to provide that option. 4153913-zen

**Comment by a-danae** [comment]
There was another request for this. 4237559-zen (from forums).

I instructed the user to leave a vote [here](https://ideas.woocommerce.com/forums/133476-woocommerce/suggestions/43899639-add-attribute-mapping-to-google-listings-and-ads-s) and [here](https://ideas.woocommerce.com/forums/133476-woocommerce/suggestions/43736268-ability-to-map-product-attributes-to-google-conten) in our Woo ideas forums. Looks like we're keeping track of requests here as well, so dropping this here just in case.

**Comment by kevin25** [comment]
Please add this feature. It's really important

**Comment by Parentivincent** [comment]
Hello, I confirm this fields mapping feature would really be a must to properly use this great plugin. Thanks in advance for the upgrade ;)

**Comment by stephentripco** [comment]
Hi. This seems to me to be an essential feature. The SKU is the GTIN (and this would seem to be a common practice, why come up an entirely separate identification system when one already exists) but I have no way of telling Google that with this plugin.

Is there a workaround until this feature is added? Currently I have 14K products with missing GTINs on Google when in fact I have that data already (and was working under the other plugin mentioned in the OP)

**Comment by findingsimple** [comment]
> SKU is the GTIN

@stephenptem alas, that is [not always the case](https://squareup.com/help/au/en/article/7175-square-for-retail-sku-vs-gtin).

If you are a developer then you can [create your own filter](https://github.com/woocommerce/google-listings-and-ads/blob/e77d8060f1604cd9068fc5bfaaa60aae34375c12/src/Product/WCProductAdapter.php#L134).

**Comment by xuexue28** [comment]
Another request here: https://wordpress.org/support/topic/mapping-gtin-ean-field/

**Comment by mikkamp** [comment]
Global attribute mapping was implemented and released in version [2.3.1](https://github.com/woocommerce/google-listings-and-ads/releases/tag/2.3.1).
Closing this issue as there hasn't been any additional reports here since the release.
