### ISSUE TITLE
`[websiteUrl]` in MCA connection error is not resolved

### ISSUE THREAD

**Issue by tomalec** [woocommerce/google-listings-and-ads#611]
### Describe the bug:
When I tried to connect to MCaccount from the local environment and domain `gla1.test`, the creation of MCA failed with an error that has `[websiteUrl]` placeholder, which I believe could be resolved to the actual URL given.

### Expected behavior:
```
Error creating account: <code>https://gla1.test/</code> URL ends with an invalid top-level domain name
```
### Actual behavior:
```
Error creating account: [websiteUrl] URL ends with an invalid top-level domain name
```
![Screenshoot of the above error](https://user-images.githubusercontent.com/17435/118362260-21fb4c00-b58f-11eb-86af-49a846aabbd3.png)

### Steps to reproduce:

0. [Disconnect](https://gla1.test/wp-admin/admin.php?page=connection-test-admin-page) your MC account
1. Go to Setup MC page on you **local** domain [`gla1.test/wp-admin/admin.php?page=wc-admin&path=%2Fgoogle%2Fsetup-mc`](https://gla1.test/wp-admin/admin.php?page=wc-admin&path=%2Fgoogle%2Fsetup-mc)
2. Click "Create Account"
3. Wait for error

### Additional details:
I found the issue during the review of https://github.com/woocommerce/google-listings-and-ads/pull/610

**Comment by rawdreeg** [comment]
I haven't been able to reproduce this issue locally. I get:

`{"message": "Unable to insert site verification." "id":#id_number}`

Instead of the error described on the issue. Not sure I am missing something. Can anyone reproduce this still? or confirm this is still an issue?
