### ISSUE TITLE
Report tabs lose active state when changing chart

### ISSUE THREAD

**Issue by findingsimple** [woocommerce/google-listings-and-ads#621]
### Describe the bug:

The report page tabs / submenu items (Program or Product) lose active state when changing chart - here is a demo video

https://user-images.githubusercontent.com/355014/118592448-1bfea880-b7e5-11eb-9ec1-5fd42d23ef42.mov

The sidebar menu item also loses the active state. I think from memory I was discussing this with someone and it's possibly an upstream issue.

Could possibly get picked up with[ the new Navigation support](https://github.com/woocommerce/google-listings-and-ads/issues/285). 

Marking as low priority for now

### Expected behavior:
The submenu items stay active.

**Comment by tomalec** [comment]
Fixed in https://github.com/woocommerce/google-listings-and-ads/pull/1038
