### ISSUE TITLE
Expose errors to allow setup to complete

### ISSUE THREAD

**Issue by mikkamp** [woocommerce/google-listings-and-ads#634]
### Describe the bug:

Followup from https://github.com/woocommerce/google-listings-and-ads/issues/530#issuecomment-829222356

We have error messages for validating the form, see: https://github.com/woocommerce/google-listings-and-ads/blob/0.5.6/js/src/setup-mc/setup-stepper/setup-free-listings/checkErrors.js#L29

But we only disable the Complete Setup button if there is at least one error: https://github.com/woocommerce/google-listings-and-ads/blob/0.5.6/js/src/setup-mc/setup-stepper/setup-free-listings/index.js#L128

I don't see the actual error messages being shown anywhere, so I have to guess that I'm missing a country to add a shipping rate. Can we add some kind of indication why the "Complete Setup" button is disabled to guide them to completing the setup.

### Expected behavior:
To be shown the error why the "Complete Setup" button is disabled, so I can know what to fix.

### Actual behavior:
"Complete Setup" button is disabled without showing errors.

### Steps to reproduce:
1. Go through the onboarding
2. At step 3 setup shipping for all countries except one
3. Notice that the "Complete Setup" button is disabled but we aren't shown what step to take to resolve it

**Comment by tijosh** [comment]
35355092-hc could benefit from this error logging

**Comment by mikkamp** [comment]
Some additional details from a scenario where the error message would be helpful to indicate that the store address is missing street.

![image](https://user-images.githubusercontent.com/11388669/208656067-4a2e9c0b-d850-41d0-ab38-fd09fc2b9414.png)

Especially since the user has to manually confirm policy compliance checks it looks like the disabled continue button is related to the policy compliance checks, but in this case it's because of the store address. Highlighting the exact error would prevent confusion.

**Comment by Brianmitchtay** [comment]
7973235-hc could be benefitted from this error message displaying as well

**Comment by sukafia** [comment]
6192158-zen didn't enter the store address fully and so couldn't complete the setup. (They had no way of knowing that was the issue)

**Comment by sukafia** [comment]
6350049-zen

**Comment by sukafia** [comment]
6350049-zen

**Comment by Brianmitchtay** [comment]
Seeing another case of this in 6485161-zen

I'm not sure if we even have a list of the specific requirements available to HEs or users to know what is required here? Can we add this to the documentation? It's pretty frustrating for the user and for the HE to not have an easy way to solve this.

![MvIjoL.png](https://github.com/woocommerce/google-listings-and-ads/assets/45057772/fd66c6ff-6b81-480e-99b8-d327de2c0840)

Edit: I see I had just missed the section about this in the FAQ on the documentation. Thanks for the heads up @sukafia. I wonder if it's worth highlighting the requirements more clearly in section 1.4 of setup and configuration? That's where I was looking.

**Comment by sukafia** [comment]
> Seeing another case of this in 6485161-zen
> 
> I'm not sure if we even have a list of the specific requirements available to HEs or users to know what is required here? Can we add this to the documentation? It's pretty frustrating for the user and for the HE to not have an easy way to solve this.

I agree this is frustrating. I'll be reminding the product team of this issue and recommending they prioritize it (It's already on my Q2 feedback). By the way, the issue is documented [here](https://woocommerce.com/document/google-listings-and-ads/#continue-button) - it looks like you missed it.
