### ISSUE TITLE
"Error retrieving status: Invalid token" when viewing onboarding connection page

### ISSUE THREAD

**Issue by jconroy** [woocommerce/google-listings-and-ads#736]
### Describe the bug:

Internal reference pbIy4N-1yo-p2 discussing feedback from the beta customer and some investigation

```
after installing and activating the extension and clicking get started – we hit an error almost immediately on the Setup your accounts step – before anything loaded he got the following error: 
```

Console error received 

```
load-scripts.php?c=1&load[chunk_0]=jquery-core,jquery-migrate,utils,moxiejs,plupload,jquery-ui-core,jquery-ui-tooltip&ver=5.7.2:5 JQMIGRATE: Migrate is installed, version 3.3.2
admin.php?page=wc-admin&path=%2Fgoogle%2Fsetup-mc:2562 `woocommerce_shared_settings` filter in Blocks is deprecated. See https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/trunk/docs/contributors/block-assets.md
(anonymous) @ admin.php?page=wc-admin&path=%2Fgoogle%2Fsetup-mc:2562
/wp-json/jetpack/v4/scan:1 Failed to load resource: the server responded with a status of 400 ()
/wp-json/wc/gla/google/connected?_locale=user:1 Failed to load resource: the server responded with a status of 400 ()
index.js?ver=f2bd3895a25dfa0d87bc8beae53b83e1:1 Objectmessage: "Error retrieving status: Invalid token"__proto__: constructor: ƒ Object()hasOwnProperty: ƒ hasOwnProperty()isPrototypeOf: ƒ isPrototypeOf()propertyIsEnumerable: ƒ propertyIsEnumerable()toLocaleString: ƒ toLocaleString()toString: ƒ toString()valueOf: ƒ valueOf()__defineGetter__: ƒ __defineGetter__()__defineSetter__: ƒ __defineSetter__()__lookupGetter__: ƒ __lookupGetter__()__lookupSetter__: ƒ __lookupSetter__()get __proto__: ƒ __proto__()set __proto__: ƒ __proto__()
```

Note the reference to "Error retrieving status: Invalid token""

I did some digging (noted in the internal p2) - the site appears to have Jetpback installed but debugger is shower a number of errors e.g.

https://jptools.wordpress.com/debug/

```
Failed
error: test authenticated xmlrpc request for jetpack passes connection test
error: test authenticated xmlrpc with blog token
error: test local testing suite
error: test get heartbeat data
error: plugin jetpack test site has jetpack features available
error: plugin jetpack test site has jetpack features enabled
```

My first suspicion is something is not working properly in with their jetpack installation or it is being blocked/disabled for security/performance reasons.

The beta tester is not willing to give us access to their site to check things but is happy to answer questions / dig up more information. I've asked:
* If they have any security or performance related extensions that might be affecting Jetpacks ability to communicate with the site
* If there are any PHP errors generated when viewing the page

### Expected behavior:
Gracefully handle errors like this

### Actual behavior:
Doesn't handle the error well

### Steps to reproduce:
TBC

**Comment by findingsimple** [comment]
Related to https://github.com/woocommerce/google-listings-and-ads/issues/775 so closing in favor of detecting the connecting is lost/broken and handling that better
