### ISSUE TITLE
[GlobalStep] Database Errors are triggered upon installing and activating "Google Listing and Ads" plugin.

### ISSUE THREAD

**Issue by gglobalstep** [woocommerce/google-listings-and-ads#746]
## Bug Description:
Database Errors are triggered upon installing and activating "Google Listing and Ads" plugin.

## Environment:
Woocommerce Version : WooCommerce 5.4 RC1
WordPress version: (v5.7)

PC:
Windows 10, Mac 10.14.6
Chrome(Version 90.0.4430.93) 
Firefox(Version 88.0)
Safari: v13.1.1

## Steps To Reproduce:
1. Create any test site using JN site.
1. Install and activate all the required plugins.
1. Complete the onboarding setup wizard with Google Listing and Ads extension checked on Buisness details step.
1. Observe that database rrror messages are triggered on query monitor.

## Actual Result:
Database Errors are triggered upon installing and activating "Google Listing and Ads" plugin.

## Expected Result:
Google Listing and Ads plugin should get install and activate without any errors

## Video:

![#30021](https://user-images.githubusercontent.com/41110392/120512372-ebc02800-c3e8-11eb-82bd-f73a978f038b.png)

*Isolating the problem (mark completed items with an [x]):*
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

<details>

### WordPress Environment ###

WordPress address (URL): https://narrow-crested.jurassic.ninja
Site address (URL): https://narrow-crested.jurassic.ninja
WC Version: 5.4.0
REST API Version: ✔ 5.4.0
WC Blocks Version: ✔ 5.1.0
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 2.3.1
Log Directory Writable: ✔
WP Version: 5.8-alpha-51055
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.46 (Unix) OpenSSL/1.0.2g
PHP Version: 7.4.18
PHP Post Max Size: 1 GB
PHP Time Limit: 30
PHP Max Input Vars: 5000
cURL Version: 7.47.0
OpenSSL/1.0.2g

SUHOSIN Installed: –
MySQL Version: 5.7.33-0ubuntu0.16.04.1-log
Max Upload Size: 512 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 5.4.0
WC Database Prefix: wp_
Total Database Size: 10.10MB
Database Data Size: 7.46MB
Database Index Size: 2.64MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_ce4wp_abandoned_checkout: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_gla_budget_recommendations: Data: 0.22MB + Index: 0.14MB + Engine InnoDB
wp_gla_merchant_issues: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_gla_shipping_rates: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gla_shipping_times: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailchimp_carts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailchimp_jobs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_custom_fields: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_dynamic_segment_filters: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_feature_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_forms: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_mapping_to_external_entities: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletters: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_newsletter_links: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_mailpoet_newsletter_option: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_option_fields: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_posts: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_segment: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_templates: Data: 2.52MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_scheduled_tasks: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_scheduled_task_subscribers: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_segments: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_sending_queues: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_settings: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_statistics_clicks: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_mailpoet_statistics_forms: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_statistics_newsletters: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_statistics_opens: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_mailpoet_statistics_unsubscribes: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_mailpoet_statistics_woocommerce_purchases: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_mailpoet_stats_notifications: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_subscribers: Data: 0.02MB + Index: 0.13MB + Engine InnoDB
wp_mailpoet_subscriber_custom_field: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_subscriber_ips: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_subscriber_segment: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_user_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 3.03MB + Index: 0.09MB + Engine InnoDB
wp_postmeta: Data: 0.13MB + Index: 0.09MB + Engine InnoDB
wp_posts: Data: 0.06MB + Index: 0.06MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 25
mailpoet_page: 1
page: 8
post: 2
product: 23
product_variation: 11
revision: 4
shop_order: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (14) ###

Query Monitor: by John Blackbourn – 3.7.1
Companion Plugin: by Osk – 1.18
Creative Mail by Constant Contact: by Constant Contact – 1.3.9
Facebook for WooCommerce: by Facebook – 2.5.1
Google Listings and Ads: by WooCommerce – 0.6.0
Gutenberg: by Gutenberg Team – 10.7.1
Jetpack: by Automattic – 9.8
Mailchimp for WooCommerce: by Mailchimp – 2.5.1
MailPoet 3 (New): by MailPoet – 3.62.1
WooCommerce Beta Tester: by WooCommerce – 2.0.2
WooCommerce Payments: by Automattic – 2.4.0 (update to version 2.5.0 is available)
WooCommerce: by Automattic – 5.4.0-rc.1
WordPress Beta Tester: by Peter Westwood
Andy Fragen – 3.1.0

Test jQuery Updates: by The WordPress Team – 2.0.0

### Inactive Plugins (2) ###

Akismet Anti-Spam: by Automattic – 4.1.9
Hello Dolly: by Matt Mullenweg – 1.7.2

### Dropin Plugins (1) ###

db.php: Query Monitor Database Class

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 0
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: woocommerce/woocommerce#6 - /shop/
Cart: woocommerce/woocommerce#7 - /cart/
Checkout: woocommerce/woocommerce#8 - /checkout/
My account: woocommerce/woocommerce#9 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 3.7.0
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 21
Oldest: 2021-06-02 07:16:29 +0000
Newest: 2021-06-02 14:17:27 +0000

### Status report information ###

Generated at: 2021-06-02 15:19:37 +00:00
`

</details>

**Comment by peterfabian** [comment]
Not totally sure if this is the same problem, but in 4616326-zen, it seems like this has actually brought the site down for a customer (they're not using Query Monitor). 

Error:
```
Fatal error: Uncaught mysqli_sql_exception: Table 'dbs2450657.sgKTLnPZgla_budget_recommendations' doesn't exist in /homepages/15/d875422767/htdocs/sheetmarket/wp-includes/wp-db.php:2056 

Stack trace: 
#0 /homepages/15/d875422767/htdocs/sheetmarket/wp-includes/wp-db.php(2056): mysqli_query(Object(mysqli), 'DESCRIBE sgKTLn...') 
#1 /homepages/15/d875422767/htdocs/sheetmarket/wp-includes/wp-db.php(1945): wpdb->_do_query('DESCRIBE sgKTLn...') 
#2 /homepages/15/d875422767/htdocs/sheetmarket/wp-includes/wp-db.php(2695): wpdb->query('DESCRIBE sgKTLn...') 
#3 /homepages/15/d875422767/htdocs/sheetmarket/wp-admin/includes/upgrade.php(2749): wpdb->get_results('DESCRIBE sgKTLn...') 
#4 /homepages/15/d875422767/htdocs/sheetmarket/wp-content/plugins/google-listings-and-ads/src/Proxies/WP.php(88): dbDelta(Array) 
#5 /homepages/15/d875422767/htdocs/sheetmarket/wp-content/plugins/google-listings-and-ads/src/DB/Table.php(45): Automattic\WooCommerce\GoogleListingsAndAds\Proxies\WP->db_delta('CREATE TABLE `s...') 
#6 /homepages/15/d875422767/htdocs/sheetmarket/wp-content/plugins/google-listings-and-ads/src/DB/Table/BudgetRecommendationTable.php(45): Automattic\WooCommerce\GoogleListingsAndAds\DB\Table->install() 
#7 /homepages/15/d875422767/htdocs/sheetmarket/wp-content/plugins/google-listings-and-ads/src/DB/Installer.php(49): Automattic\WooCommerce\GoogleListingsAndAds\DB\Table\BudgetRecommendationTable->install() 
#8 /homepages/15/d875422767/htdocs/sheetmarket/wp-content/plugins/google-listings-and-ads/src/Installer.php(100): Automattic\WooCommerce\GoogleListingsAndAds\DB\Installer->install('', '1.9.0') 
#9 /homepages/15/d875422767/htdocs/sheetmarket/wp-content/plugins/google-listings-and-ads/src/Installer.php(80): Automattic\WooCommerce\GoogleListingsAndAds\Installer->install() 
#10 /homepages/15/d875422767/htdocs/sheetmarket/wp-content/plugins/google-listings-and-ads/src/Installer.php(63): Automattic\WooCommerce\GoogleListingsAndAds\Installer->admin_init() 
#11 /homepages/15/d875422767/htdocs/sheetmarket/wp-includes/class-wp-hook.php(303): Automattic\WooCommerce\GoogleListingsAndAds\Installer->Automattic\WooCommerce\GoogleListingsAndAds\{closure}('') 
#12 /homepages/15/d875422767/htdocs/sheetmarket/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters(NULL, Array) 
#13 /homepages/15/d875422767/htdocs/sheetmarket/wp-includes/plugin.php(470): WP_Hook->do_action(Array) 
#14 /homepages/15/d875422767/htdocs/sheetmarket/wp-admin/admin.php(175): do_action('admin_init') 
#15 /homepages/15/d875422767/htdocs/sheetmarket/wp-admin/index.php(10): require_once('/homepages/15/d...') 
#16 {main} thrown in /homepages/15/d875422767/htdocs/sheetmarket/wp-includes/wp-db.php on line 2056

```

SSR:
```

### WordPress Environment ###

WordPress address (URL): https://sheetmarket.com
Site address (URL): https://sheetmarket.com
WC Version: 5.6.0
REST API Version: ✔ 5.6.0
WC Blocks Version: ✔ 5.5.1
Action Scheduler Version: ✔ 3.2.1
WC Admin Version: ✔ 2.5.1
Log Directory Writable: ✔
WP Version: 5.8
WP Multisite: –
WP Memory Limit: ❌ 40 MB - We recommend setting memory to at least 64MB. See: Increasing memory allocated to PHP
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.4.22
PHP Post Max Size: 6 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.64.0
OpenSSL/1.1.1d

SUHOSIN Installed: –
MySQL Version: 5.7.32-log
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 5.6.0
WC Database Prefix: sgKTLnPZ
Total Database Size: 105.01MB
Database Data Size: 84.93MB
Database Index Size: 20.08MB
sgKTLnPZwoocommerce_sessions: Data: 22.06MB + Index: 2.28MB + Engine InnoDB
sgKTLnPZwoocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
sgKTLnPZwoocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
sgKTLnPZwoocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
sgKTLnPZwoocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
sgKTLnPZwoocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
sgKTLnPZwoocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
sgKTLnPZwoocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
sgKTLnPZwoocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
sgKTLnPZwoocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
sgKTLnPZwoocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
sgKTLnPZwoocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
sgKTLnPZwoocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
sgKTLnPZwoocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
sgKTLnPZ410_links: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
sgKTLnPZactionscheduler_actions: Data: 1.33MB + Index: 0.61MB + Engine InnoDB
sgKTLnPZactionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
sgKTLnPZactionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
sgKTLnPZactionscheduler_logs: Data: 11.52MB + Index: 7.03MB + Engine InnoDB
sgKTLnPZaioseo_notifications: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
sgKTLnPZaioseo_posts: Data: 4.52MB + Index: 0.06MB + Engine InnoDB
sgKTLnPZce4wp_abandoned_checkout: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
sgKTLnPZcommentmeta: Data: 1.05MB + Index: 0.03MB + Engine InnoDB
sgKTLnPZcomments: Data: 0.08MB + Index: 0.09MB + Engine InnoDB
sgKTLnPZcss_js_manager: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
sgKTLnPZewwwio_images: Data: 2.52MB + Index: 1.80MB + Engine InnoDB
sgKTLnPZewwwio_queue: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
sgKTLnPZlinks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
sgKTLnPZmailchimp_carts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
sgKTLnPZmailchimp_jobs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
sgKTLnPZmailpoet_custom_fields: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
sgKTLnPZmailpoet_dynamic_segment_filters: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
sgKTLnPZmailpoet_feature_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
sgKTLnPZmailpoet_forms: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
sgKTLnPZmailpoet_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
sgKTLnPZmailpoet_mapping_to_external_entities: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
sgKTLnPZmailpoet_newsletters: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
sgKTLnPZmailpoet_newsletter_links: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
sgKTLnPZmailpoet_newsletter_option: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
sgKTLnPZmailpoet_newsletter_option_fields: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
sgKTLnPZmailpoet_newsletter_posts: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
sgKTLnPZmailpoet_newsletter_segment: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
sgKTLnPZmailpoet_newsletter_templates: Data: 2.52MB + Index: 0.00MB + Engine InnoDB
sgKTLnPZmailpoet_scheduled_tasks: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
sgKTLnPZmailpoet_scheduled_task_subscribers: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
sgKTLnPZmailpoet_segments: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
sgKTLnPZmailpoet_sending_queues: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
sgKTLnPZmailpoet_settings: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
sgKTLnPZmailpoet_statistics_clicks: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
sgKTLnPZmailpoet_statistics_forms: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
sgKTLnPZmailpoet_statistics_newsletters: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
sgKTLnPZmailpoet_statistics_opens: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
sgKTLnPZmailpoet_statistics_unsubscribes: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
sgKTLnPZmailpoet_statistics_woocommerce_purchases: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
sgKTLnPZmailpoet_stats_notifications: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
sgKTLnPZmailpoet_subscribers: Data: 0.02MB + Index: 0.13MB + Engine InnoDB
sgKTLnPZmailpoet_subscriber_custom_field: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
sgKTLnPZmailpoet_subscriber_ips: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
sgKTLnPZmailpoet_subscriber_segment: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
sgKTLnPZmailpoet_user_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
sgKTLnPZms_snippets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
sgKTLnPZoptions: Data: 4.13MB + Index: 0.23MB + Engine InnoDB
sgKTLnPZpostmeta: Data: 6.52MB + Index: 3.94MB + Engine InnoDB
sgKTLnPZposts: Data: 26.22MB + Index: 0.56MB + Engine InnoDB
sgKTLnPZprli_clicks: Data: 0.45MB + Index: 1.05MB + Engine InnoDB
sgKTLnPZprli_links: Data: 0.02MB + Index: 0.17MB + Engine InnoDB
sgKTLnPZprli_link_metas: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
sgKTLnPZsnippets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
sgKTLnPZtermmeta: Data: 0.09MB + Index: 0.08MB + Engine InnoDB
sgKTLnPZterms: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
sgKTLnPZterm_relationships: Data: 0.09MB + Index: 0.08MB + Engine InnoDB
sgKTLnPZterm_taxonomy: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
sgKTLnPZusermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
sgKTLnPZusers: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
sgKTLnPZwc_admin_notes: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
sgKTLnPZwc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
sgKTLnPZwc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
sgKTLnPZwc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
sgKTLnPZwc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
sgKTLnPZwc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
sgKTLnPZwc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
sgKTLnPZwc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
sgKTLnPZwc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
sgKTLnPZwc_product_meta_lookup: Data: 0.11MB + Index: 0.13MB + Engine InnoDB
sgKTLnPZwc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
sgKTLnPZwc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
sgKTLnPZwc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
sgKTLnPZwoo_shippment_provider: Data: 0.08MB + Index: 0.00MB + Engine InnoDB
sgKTLnPZwpf_filters: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
sgKTLnPZwpf_modules: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
sgKTLnPZwpf_modules_type: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
sgKTLnPZwpf_usage_stat: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 1451
elementor_library: 3
jetpack_migration: 2
mailpoet_page: 1
ml-slide: 1
ml-slider: 1
nav_menu_item: 14
oembed_cache: 1
page: 10
post: 139
pretty-link: 11
product: 78
product_variation: 624
revision: 656
shop_coupon: 2
shop_order: 12
shop_order_refund: 3
tt_font_control: 1
wpcf7_contact_form: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (28) ###

Akismet Anti-Spam: by Automattic – 4.1.11
All in One SEO: by All in One SEO Team – 4.1.3.3
Autoptimize: by Frank Goossens (futtta) – 2.9.1
Breadcrumb NavXT: by John Havlik – 6.6.0
Classic Editor: by WordPress Contributors – 1.6.2
Code Snippets: by Code Snippets Pro – 2.14.1
Contact Form 7: by Takayuki Miyoshi – 5.4.2
Elementor: by Elementor.com – 3.4.2
EWWW Image Optimizer: by Exactly WWW – 6.2.3
Facebook for WooCommerce: by Facebook – 2.6.1
Find and Replace TEXT: by jesse Lau – 2.0
Hide featured image on all single page/post: by TylerTork – 1.0
Insert Headers and Footers: by WPBeginner – 1.6.0
Jetpack: by Automattic – 10.0
MetaSlider: by MetaSlider – 3.23.0
Perfmatters: by forgemedia – 1.7.7
Pretty Links: by Pretty Links – 3.2.3
Really Simple SSL: by Really Simple Plugins – 5.0.10
Advanced Editor Tools (previously TinyMCE Advanced): by Automattic – 5.6.0
Title and Nofollow For Links: by WPKube – 1.11
Use Any Font: by Dnesscarkey – 6.1.4
Advanced Shipment Tracking for WooCommerce: by zorem – 3.2.9
WooCommerce Stripe Gateway: by WooCommerce – 5.4.0
WooCommerce Payments: by Automattic – 2.9.0
WooCommerce Shipping & Tax: by WooCommerce – 1.25.18
WooCommerce: by Automattic – 5.6.0
StoreCustomizer: by Kaira – 2.3.2
410 for WordPress: by Samir Shah – 0.8.7

### Inactive Plugins (9) ###

AMB Variable Affiliate Products for WooCommerce: by WP Guild – 1.0.1
Creative Mail by Constant Contact: by Constant Contact – 1.4.4
Facebook for WordPress: by Facebook – 3.0.5
Google Ads & Marketing by Kliken: by Kliken – 1.0.7
Mailchimp for WooCommerce: by Mailchimp – 2.5.2
MailPoet 3 (New): by MailPoet – 3.67.1
OneSignal Push Notifications: by OneSignal – 2.2.2
Specify Missing Image Dimensions: by WPHowKnow – 1.0.2
WooCommerce Product Filter by WooBeWoo: by WooBeWoo – 1.5.6

### Must Use Plugins (1) ###

1&1 Product Subdomain: by 1&1 – 1.1.0

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Shop base: #2417 - /shop
Cart: #2418 - /cart
Checkout: #2419 - /checkout
My account: #2420 - /my-account
Terms and conditions: ❌ Page not set

### Theme ###

Name: Vogue
Version: 10.8.8
Author URL: https://kairaweb.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 1,637
Oldest: 2021-07-28 16:23:47 -0700
Newest: 2021-08-27 14:31:44 -0700

Failed: 1
Oldest: 2021-08-09 14:35:38 -0700
Newest: 2021-08-09 14:35:38 -0700

Pending: 9
Oldest: 2021-08-27 14:46:44 -0700
Newest: 2021-11-15 19:44:40 -0800


### Status report information ###

Generated at: 2021-08-27 14:46:19 -07:00

```

**Comment by mikkamp** [comment]
If we look at that stack trace it's throwing an exception when it reaches the code `DESCRIBE {$tablename}`. That's the way the `dbDelta` function checks to see if the table already exists.

If we look at WP it uses the function `mysqli_error` to retrieve the error, and if `suppress_errors` is set it will silently continue. However PHP allows you to change the way MySQL errors are reported using the [`mysqli_report`](https://www.php.net/manual/en/function.mysqli-report.php) function. The documentation there shows that if the mode is set to `MYSQLI_REPORT_STRICT` it will throw a `mysqli_sql_exception` (which is what the stack trace mentions).

So I'd suggest for them to check their site for any plugins / code which calls `mysqli_report` or check their PHP configuration (with the help of their hosting provider).

Although not applicable for the user in this report, something to take into consideration is the note:
> As of PHP 8.1.0, the default setting is MYSQLI_REPORT_ERROR | MYSQLI_REPORT_STRICT. Previously, it was MYSQLI_REPORT_OFF.

It seems like this has already been addressed [here](https://core.trac.wordpress.org/ticket/52825) for WP 5.9
