### ISSUE TITLE
Limit the accounts.link services to just “shoppingAdsProductManagement” 

### ISSUE THREAD

**Issue by findingsimple** [woocommerce/google-listings-and-ads#770]
### Describe the bug:
Limit the accounts.link services to just “shoppingAdsProductManagement” -- [reference page](https://developers.google.com/shopping-content/reference/rest/v2.1/accounts/link)

### Expected behavior:
Limit the accounts.link services to ones we use.

### Actual behavior:
We've defined a few different Services, including some related to Buy on Google. Since this integration isn’t explicitly supporting Buy on Google - we should limit the accounts.link services.

**Comment by mikkamp** [comment]
The account gets linked in WCS as part of a two stage "request" and "approve":

```js
{
	action: 'request',
	linkedAccountId: accountId,
	linkType: 'eCommercePlatform',
	services: [ 'shoppingAdsProductManagement', 'shoppingActionsProductManagement', 'shoppingActionsOrderManagement' ],
}
```

```js
{
	action: 'approve',
	linkedAccountId: mcaId,
	linkType: 'eCommercePlatform',
	services: [ 'shoppingAdsProductManagement', 'shoppingActionsProductManagement', 'shoppingActionsOrderManagement' ],
}
```

So if I understand correctly, we want to remove both `shoppingActionsProductManagement` and `shoppingActionsOrderManagement`? The original slides shows we needed all three.

**Comment by findingsimple** [comment]
> So if I understand correctly, we want to remove both shoppingActionsProductManagement and shoppingActionsOrderManagement? 

That was my understanding from the call today. 

> The original slides shows we needed all three.

I was trying to find the original mention for this but my search foo clearly failed - this issue was actually a direct request from Ben in our Q&A doc - maybe just tag him in the doc to confirm just in case.

**Comment by mikkamp** [comment]
The Q&A doc mentions why we shouldn't include those last two:

> shoppingActionsProductManagement suggests you’re syncing Buy on Googles-specific attributes. shoppingActionsOrderManagement suggests you’ve integrated with our Orders API.

**Comment by findingsimple** [comment]
Gotcha, I guess my point around confirmation was more to double-check (given it was in the original slides) if we weren't certain. But seems like it should be a-ok to remove

**Comment by mikkamp** [comment]
Resolved in Automattic/woocommerce-connect-server#1794 and merged to vipgo
