### ISSUE TITLE
Incompatibility notice with Google Product Feed extension

### ISSUE THREAD

**Issue by nima-karimi** [woocommerce/google-listings-and-ads#774]
We need to display a notice to the user if they have the [Google Product Feed](https://woocommerce.com/products/google-product-feed/) extension activated on their website. Google suggests that only one method (either API or Data Feed) be used to submit products to the Merchant Center and using both methods might lead to unexpected results. We could display a notice when a conflict is detected and add this to our docs.

https://developers.google.com/shopping-content/guides/best-practices#do-not-use-api-and-feeds
![image](https://user-images.githubusercontent.com/73110514/121339311-67f9c480-c92f-11eb-99b7-f30175399156.png)

**Comment by findingsimple** [comment]
Good call out @nima-karimi 

Definitely worth adding to docs in the short term

**Comment by findingsimple** [comment]
@j111q for visibility

**Comment by j111q** [comment]
Ooo. Good call out. What about Kliken's integration? Should we warn if they have that too?

**Comment by findingsimple** [comment]
We’d need to test running them both but off the top of my head - GLA would hijack/override the claim to the domain and want the Merchant to setup an account on their own rather than going via their service

**Comment by j111q** [comment]
Okay 👍 

How about let's:
1. Add a section in Docs about this
2. Add a warning message in "Issues to Resolve" like this:

![Markup 2021-06-10 at 13 47 00](https://user-images.githubusercontent.com/65582817/121471575-8379d380-c9f2-11eb-8ed3-fd6355213b5c.png)
