### ISSUE TITLE
Make the Reclaim URL flow a little more alarming

### ISSUE THREAD

**Issue by j111q** [woocommerce/google-listings-and-ads#781]
Currently, this is what the user will see:
![image](https://user-images.githubusercontent.com/65582817/121870888-12aa2280-cd36-11eb-8426-d794b1ae6859.png)

However, it is quite a destructive action as it removes all existing shipping and tax configurations as well. 

**Proposed UI and copy tweaks:**

![image](https://user-images.githubusercontent.com/65582817/121871038-3cfbe000-cd36-11eb-9496-c6949d71a8cd.png)

## Figma link
https://www.figma.com/file/jZUpa8eTrnrK1Lwt2ry7zk/?node-id=9933%3A0

Open to feedback on this!

**Comment by ecgan** [comment]
@j111q , do we want to have some sort of "double check" with the user, just in case users accidentally click on the button? Maybe a checkbox to say "I understand this will cause my existing product listings or ads to stop running, and my existing shipping or tax configurations will be lost."?

**Comment by j111q** [comment]
Oh, I like that idea to make users a little more careful. How about something like this:

![image](https://user-images.githubusercontent.com/65582817/121986837-dcb67e00-cdc9-11eb-90de-0e0dadeb4926.png)

"Reclaim my URL" only is active after they check the box.

**Comment by ecgan** [comment]
@j111q , that looks good to me 👍  Should I implement that now, or will you run through that design with Google or others first? 🤔

**Comment by j111q** [comment]
Will be chatting with them about it tomorrow morning (7am our time) - you can wait till then!

**Comment by findingsimple** [comment]
@j111q We didn't chat about this today

@ecgan if/when implementing can we add an event when the checkbox is ticked and one to the reclaim button click

**Comment by j111q** [comment]
Oh yes 😅 Ran out of time. I dropped a link to this issue for visibility to the Googlers. I think we can go ahead with this small tweak first and iterate again if there’s any feedback.

**Comment by ecgan** [comment]
> if/when implementing can we add an event when the checkbox is ticked and one to the reclaim button click

Okay gotcha. 

> I think we can go ahead with this small tweak first and iterate again if there’s any feedback.

Okay I'll work on this.
