### ISSUE TITLE
Ad campaign currency confusion

### ISSUE THREAD

**Issue by findingsimple** [woocommerce/google-listings-and-ads#786]
### Describe the bug:

>Problem with currency conversion while creating an AD campaign. I’ve set $10 a day through your plugin and within the google ads page my manager seeing this as 10 Roubles

Basically, ads campaign creation flow indicates $ but ads account is in a different currency.

### Expected behavior:

Currency when creating an ads campaign should align with account currency.

### Actual behavior:

Currency when creating an ads campaign may not match the ads account currency.

### Steps to reproduce:

(Needs confirmation of exact steps / causes)

1.
2.
3.

**Comment by ecgan** [comment]
Just dropping some notes here. In the UI, the currency shown is based on the WooCommerce store currency, which can be set in https://gla1.test/wp-admin/admin.php?page=wc-settings. 

![image](https://user-images.githubusercontent.com/417342/122040911-f62bea00-ce0a-11eb-8a27-a0f066010e96.png)

When we create an ads campaign, we call the ads campaign API like this: (from PR https://github.com/woocommerce/google-listings-and-ads/pull/141 by @mikkamp)

```
POST https://domain.test/wp-json/wc/gla/ads/campaigns
{
    "name": "Ad Campaign 2021-01-21",
    "amount": 10.00,
    "country": "US"
}
```

We probably need a way to cross check WooCommerce store currency and Google Ads account currency settings, and decide on which one to use.

**Comment by mikkamp** [comment]
We decided to just use the store currency for v1, we still have the pending point here: https://github.com/woocommerce/google-listings-and-ads/issues/363#issuecomment-844008794

**Comment by findingsimple** [comment]
Will close this in favor of the existing #363 issue
