### ISSUE TITLE
Global Offers

### ISSUE THREAD

**Issue by findingsimple** [woocommerce/google-listings-and-ads#790]
Currently GLA [syncs all product all target countries ](https://github.com/woocommerce/google-listings-and-ads/pull/319)

This approach works but creates a lot of overhead/resource consumption such as API requests, product counts & a real risk we'll keep hitting our quotas quickly (a small number of merchants can use up the quota if they have a large number of products and select to target all countries).

The alternative approach is to move to "Global Offers" - Global Offers makes it easy to list products in multiple countries without needing to upload the products to each country (this was beta when initially discussing the project and there was some disconnect/confusion about using this as the go-to/default approach when working on https://github.com/woocommerce/google-listings-and-ads/pull/399).

The change we need to make is essentially

* We no longer need to submit products for each country
* We only need to submit the list of shipping countries (an enhancement to https://github.com/woocommerce/google-listings-and-ads/pull/399)
* The product will be displayed in all of the Shipping countries regardless of the target country that it is submitted to

At face value - it seems simple enough - but I know we are doing are a lot of juggling under the hood.

Some of the questions that came to mind when discussing internally for reference

> Will the target country still be relevant after these changes? I mean what is the difference of a product submitted in all countries vs. a product that’s submitted in one country but SHIPS to all countries?

Based on discussions this morning my understanding is we can actually think of the "target country" more as the country of sale with shipping to multiple countries.

In the UI target country will be mapped to "Country of Sale" then in the Program and Status columns will see multiple rows for each shipping country.

<img width="1242" alt="Markup 2021-06-16 at 13 04 00" src="https://user-images.githubusercontent.com/355014/122154142-74d46600-cea3-11eb-98ab-b3846de0a5df.png">

> I assume that after this change we will only submit a product once for the shop’s current country (set in Woo settings) and then set the shipping based on the target country settings. This will mean that if their API doesn’t change, we will have only one ID and one synced product to deal with.

Correct, the Google team confirmed it would make sense to use the store location for the "target country" product attribute then set shipping based all the "target countries" the merchant selects during onboarding.

> We could store the target countries as a separate meta and assume that they all have the same ID.
> Or we can just store the same ID for each target country and continue using the same structure that we have now.
> I would go with the first method to separate the concepts of target countries and shipping countries.

At the moment we have `_wc_gla_google_ids` meta which is a serialized array of Ids e.g. for a single target country it looks like `a:1:{s:2:"AU";s:19:"online:en:AU:gla_85";}`

Thinking outside the box - the current structure may still offer some benefitts if we add multi-lingual / currency / country support to a single site - open to some brain cycles on this though - I just like to avoid backtracking too much if we avoid it. 

Otherwise an un-educated thought - we could probably move to something simple like `_wc_gla_google_id` (singular) and `online:en:AU:gla_85` - so yes same/single ID for the product being uploaded (we won't have multiple IDs to track anymore - at the moment).

**Notes**
* variations are still handled individually - that hasn't changed.
* I am assuming there are going to flow on changes for the product feed summary, issues, and table as a result of this - but this might help reduce some of the performance impacts cc @layoutd 
* impact on existing offers - we might need to look at running a migration job to clean up products that have been pushed up - but I'll wait to hear the teams thoughts.

**Reference pull requests**

* [Sync products for all target countries](https://github.com/woocommerce/google-listings-and-ads/pull/319)
* [Set Product Shipping Information Based on Target Country](https://github.com/woocommerce/google-listings-and-ads/pull/399)

**Comment by mikkamp** [comment]
My vote goes towards switching to the singular `_wc_gla_google_id`. It would make the migration job easier as we could just search for products with the meta `_wc_gla_google_ids` and then handle the conversion.

**Comment by nima-karimi** [comment]
Reopening this issue because we also need to change some of the docs, [FAQ](https://docs.woocommerce.com/document/google-listings-and-ads/google-listings-and-ads-faqs/), etc. to reflect this change.

**Comment by findingsimple** [comment]
Do we need to do anything for the product feed page? (I recall possibly doing extra juggling there to account for multiple products in MC) - but maybe I'm getting a bit mixed up

**Comment by mikkamp** [comment]
There is some merging / sorting that gets done for similar issues that occur for multiple countries. But it already supported just one country, so it will continue working the same whether it's for one country or for multiple countries. From what we discussed in the dev chat I understood from @layoutd that we didn't need to change anything there.

**Comment by layoutd** [comment]
> Do we need to do anything for the product feed page? (I recall possibly doing extra juggling there to account for multiple products in MC) - but maybe I'm getting a bit mixed up

The issues and statuses all account for multiple countries per product, so if that's reduced to just one country, it should still work as currently. There may be some places where the cache generation can be optimized (no need to alphabetize affected countries in the issues table, for example, or try to combine identical issues for one product in multiple countries).

**Comment by mikkamp** [comment]
The issues are still for multiple countries but Google will just have them already merged for us (and I assume alphabetized).

Before and after:
![image](https://user-images.githubusercontent.com/11388669/122382179-93993200-cf61-11eb-98cb-155421e4a44f.png)

**Comment by nima-karimi** [comment]
Closing this as we have the docs already published on https://docs.woocommerce.com/document/google-listings-and-ads/google-listings-and-ads-faqs/ and v1.1 released.
