### ISSUE TITLE
Site verification uses site_url() which appears to be causing issues during site verification

### ISSUE THREAD

**Issue by findingsimple** [woocommerce/google-listings-and-ads#796]
### Describe the bug:

The site verification process uses [site_url()](https://developer.wordpress.org/reference/functions/site_url/)  

https://github.com/woocommerce/google-listings-and-ads/blob/trunk/src/API/Site/Controllers/MerchantCenter/AccountController.php#L482

which retrieves the URL for the current site where WordPress application files (e.g. wp-blog-header.php or the wp-admin/ folder) are accessible.

It is quite common for WordPress files to be in a subdirectory e.g. https://findingsimple.com/wordpress/ while the front end is accessible from the top level domain e.g. https://findingsimple.com/

This appears to be creating issues during site verification because Google is attempting to verify http://findingsimple.com/wordpress/ instead of http://findingsimple.com/

[get_home_url()](https://developer.wordpress.org/reference/functions/get_home_url/)  is probably better to use here - i.e. retrieves the URL for a given site where the front end is accessible.

**Comment by igotdes** [comment]
Noting that this may be related to the user's issue in #4076397-zen.
