### ISSUE TITLE
Minimum supported WP and WC versions

### ISSUE THREAD

**Issue by mikkamp** [woocommerce/google-listings-and-ads#799]
### Describe the bug:
We currently have the minimum supported versions set to:

```
Requires at least: 5.3
WC requires at least: 4.5
```

Although the Jetpack connection package we use, calls the function `wp_get_environment_type`, which was introduced in WordPress 5.5. In older versions it used to check if this function exists, but since we [updated the Jetpack connect package](https://github.com/woocommerce/google-listings-and-ads/pull/336), that's no longer the case.

So this causes a fatal error on any site installing on a version older then 5.5. Do we need to bump any of these versions or create some compatibility if we want to support older versions?

### Steps to reproduce:
1. Setup a site on WordPress 5.4 and an older version of WooCommerce
2. Install and activate the GLA extension
3. Observe the fatal error

### Additional details:
Originally reported in https://wordpress.org/support/topic/fatal-error-3893/

**Comment by nima-karimi** [comment]
I think following the [L2 support policy](https://developer.woocommerce.com/what-we-support/) we have, we should drop support for 5.3 and ask everyone to update to 5.5. For WooCommerce that should be set to a minimum version 5.2.

There was a similar discussion on another issue too: https://github.com/woocommerce/google-listings-and-ads/issues/794

**Comment by mikkamp** [comment]
L2 support sounds good. Bumping the versions isn't very hard, but my main question is whether we should handle lower versions gracefully.

We currently have the following requirement checks, with admin notices:
- PHP is 7.3 or higher
- WC Admin is active (no specific version)
- Bookings is not active (will be removed by PR #788)

Should we add two checks to require the minimum WP and WC versions?

**Comment by findingsimple** [comment]
> Should we add two checks to require the minimum WP and WC versions?

Yes please - I think graceful is a good rule of thumb

AW I think has/had an ok approach
