### ISSUE TITLE
Ask users to leave a review on WordPress.org

### ISSUE THREAD

**Issue by nima-karimi** [woocommerce/google-listings-and-ads#831]
As of today we have roughly 20,000 active installs and only [9 reviews on our WordPress.org page](https://wordpress.org/support/plugin/google-listings-and-ads/reviews/). Some of them are support requests.

It's highly likely that only people with a bad experience leave a review and people who had a good experience with the product just don't.

I suggest to add an admin notice or some other form of notification asking the happy user for their feedback (and hopefully a five-star rating) after they have used the product for a while (say, one week). This method is used a lot in mobile apps.

I realize that this notice might come off as annoying to some (I personally hate it when mobile apps do this) but on the other hand it may help us get some really valuable reviews based on real user experiences. I have seen some plugins do this too and it's usually a tiny admin notice with a simple action button that goes straight to the ["Add your own review" section](https://wordpress.org/support/plugin/google-listings-and-ads/reviews/#new-post).

Related to https://github.com/woocommerce/google-listings-and-ads/issues/22

FYI, current state of reviews:

![image](https://user-images.githubusercontent.com/73110514/123484021-bfc74980-d618-11eb-98d0-71c01f45a917.png)

**Comment by j111q** [comment]
Thank you for creating this issue Nima! I just wrote a [P2 post](https://wp.me/pbIy4N-1Jn) about this too. 

Thinking of using certain milestones to prompt for reviews, here's an example:

![image](https://user-images.githubusercontent.com/65582817/123505451-c47c1400-d691-11eb-8bc6-17517478a731.png)

Will align with Gary and Jason next week about what type of milestones we want to use. Do suggest as well if you have any thoughts!

**Comment by nima-karimi** [comment]
Closing this in favor of https://github.com/woocommerce/google-listings-and-ads/issues/860
