### ISSUE TITLE
Google Listings & ads Malfunctioning

### ISSUE THREAD

**Issue by AtomicRange** [woocommerce/google-listings-and-ads#844]
Loading Errors
The listing dashboard loads errors: Displays, account loading errors, Product feed error, Analytics errors, Google merchant centre connection errors. 

Please see:
[WP-Admin Dashboard](https://vimeo.com/568634516/94808464f2)

I was hoping to have no complications with the plugin. But it seems they are either many errors with the plugin itself or my hosting environment. I had to upload the plugin via sftp protocol after it caused fatal errors at installation point. 

I cannot access any functions at all on the plugin. I even ended up disabling all plugins, deactivating and activating the it. And it worked for some while until the 1.10 update was released and immediately after uploading it it started with the loading errors problem. 

The upload error detail:
Error Details
=============
An error of type E_ERROR was caused in line 47 of the file /var/www/wp-content/plugins/google-listings-and-ads/vendor/jetpack-autoloader/class-plugin-locator.php. Error message: Uncaught RuntimeException: Failed to locate plugin /var/www/wp-content/plugins/google-listings-and-ads in /var/www/wp-content/plugins/google-listings-and-ads/vendor/jetpack-autoloader/class-plugin-locator.php:47
Stack trace:
#0 /var/www/wp-content/plugins/google-listings-and-ads/vendor/jetpack-autoloader/class-autoloader.php(46): Automattic\Jetpack\Autoloader\jp7d0b9b05c61170bf7b752103749920e3\Plugin_Locator->find_current_plugin()
#1 /var/www/wp-content/plugins/google-listings-and-ads/vendor/autoload_packages.php(13): Automattic\Jetpack\Autoloader\jp7d0b9b05c61170bf7b752103749920e3\Autoloader::init()
#2 /var/www/wp-content/plugins/google-listings-and-ads/src/Autoloader.php(37): require('/var/www/wp-con...')
#3 /var/www/wp-content/plugins/google-listings-and-ads/google-listings-and-ads.php(35): Automattic\WooCommerce\GoogleListingsAndAds\Autoloader::init()
#4 /var/www/wp-settings.php(391): include_once('/var/www/wp-con...')
#5 /var/www/wp-config.php(96): require_once('/var/www/wp-set...')
#6 /var/www/wp-load.p

Fatal Error Log
2021-06-28T21:28:02+00:00 CRITICAL Uncaught Error: Call to undefined function Automattic\WooCommerce\GoogleListingsAndAds\Vendor\GuzzleHttp\Psr7\stream_for() in /var/www/wp-content/plugins/google-listings-and-ads/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:400
Stack trace:
#0 /var/www/wp-content/plugins/google-listings-and-ads/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(59): Automattic\WooCommerce\GoogleListingsAndAds\Vendor\GuzzleHttp\Handler\CurlFactory->applyHandlerOptions(Object(Automattic\WooCommerce\GoogleListingsAndAds\Vendor\GuzzleHttp\Handler\EasyHandle), Array)
#1 /var/www/wp-content/plugins/google-listings-and-ads/vendor/guzzlehttp/guzzle/src/Handler/CurlHandler.php(43): Automattic\WooCommerce\GoogleListingsAndAds\Vendor\GuzzleHttp\Handler\CurlFactory->create(Object(Automattic\WooCommerce\GoogleListingsAndAds\Vendor\GuzzleHttp\Psr7\Request), Array)
#2 /var/www/wp-content/plugins/google-listings-and-ads/vendor/guzzlehttp/guzzle/src/Handler/Proxy.php(28): Automattic\WooCommerce\GoogleListingsAndAds\Vendor\GuzzleHttp\ in /var/www/wp-content/plugins/google-listings-and-ads/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php on line 400

Scheduled Action Error:
<html>
<body>

gla/jobs/update_products/process_item | Failed | 0 => array ( 0 => 2800, ) | gla | Non-repeating | 2021-06-26 07:20:48 +0000(3 days 10 hours ago) | 2021-06-26 07:20:49 +0000action created2021-06-26 07:21:58 +0000action started via Async Request2021-06-26 07:21:58 +0000unexpected shutdown: PHP Fatal error Uncaught Error: Call to undefined function Automattic\WooCommerce\GoogleListingsAndAds\Vendor\GuzzleHttp\Psr7\stream_for() in /var/www/wp-
/var/www/wp-content/plugins/google-listings-and-ads/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:400 Stack trace: #0 /var/www/wp-content/plugins/google-listings-and-ads/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(59): Automattic\WooCommerce\GoogleListingsAndAds\Vendor\GuzzleHttp\Handler\CurlFactory->applyHandlerOptions(Object(Automattic\WoAutomattic\WooCommerce\GoogleListingsAndAds\Vendor\GuzzleHttp\Handler\EasyHandle), Array) #1 /var/www/wp-content/plugins/google-listings-and-ads/vendor/guzzlehttp/guzzle/src/Handler/CurlHandler.php(43): Automattic\WooCommerce\GoogleListingsAndAds\Vendor\GuzzleHttp\Handler\CurlFactory->create(Object(Automattic\WooCommerce\GoogleListingsAndAds\Vendor\GAds\Vendor\GuzzleHttp\Psr7\Request), Array) #2 /var/www/wp-content/plugins/google-listings-and-ads/vendor/guzzlehttp/guzzle/src/Handler/Proxy.php(28): Automattic\WooCommerce\GoogleListingsAndAds\Vendor\GuzzleHttp\ in /var/www/wp-content/plugins/google-listings-and-ads/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php on line 400
-- | -- | -- | -- | -- | -- | --

I don't know if this helps with the problem. If possible please assist. 

Warm Regards

**Comment by mikkamp** [comment]
Hi there,

This repository is not intended for support requests.

The best place to get support is the [WordPress.org Google Listings and Ads forum.](https://wordpress.org/support/plugin/google-listings-and-ads/)

If you have a WooCommerce.com account, you can [start a chat or open a ticket on WooCommerce.com](https://woocommerce.com/my-account/create-a-ticket/).

It seems you already have a support request [open on the forum](https://wordpress.org/support/topic/google-listings-ads-plugin-problem/), so we'd ask you to continue with the support request there. As mentioned in the last reply, the errors you posted look like the plugin is not fully installed or is missing some files. I'd suggest to completely remove the old version through SFTP before uploading the new version.
