### ISSUE TITLE
Star Review Showing in Search Results but Not on the Product Page

### ISSUE THREAD

**Issue by mavoelke** [woocommerce/google-listings-and-ads#848]
### Describe the bug:
A customer flagged that Google search results for the Xero extension includes ratings/reviews https://d.pr/i/IropWO however, they are not shown on the product page https://d.pr/i/Y6tnvy is there a way to also keep the data from popping up in search results for products that haven't hit the 10-rating/review threshold?

### Expected behavior:
If the product doesn't have 10 reviews it shouldn't populate a rating in Google search results because reviews will not be live on site.

### Actual behavior:
When the product pops up in search results, it says it has a star rating of 2.2 based on 8 reviews in search snippet, but when you go to the PDP the reviews do not appear.

### Steps to reproduce:
1. Search for "Xero WooCommerce"
2. View the search result for Xero WooCommerce and notice the star rating.
3. Visit the page and scroll to the bottom to the reviews section.

### Additional details:
Matty suggested in an earlier conversation about this that a possible fix may be "removing Google’s structured data tags for reviews if below the review threshold."

**Comment by mikkamp** [comment]
Moved over to the the woocommerce.com repo: 10632-gh-Automattic/woocommerce.com
