### ISSUE TITLE
WP.com account card is empty when Jetpack is active but not connected.

### ISSUE THREAD

**Issue by tomalec** [woocommerce/google-listings-and-ads#853]
_This issue was discovered while debugging support ticket 4086698-zd-woothemes_

### Describe the bug:
When Jetpack is installed, activated but not connected to WP.com account, the WP account card in the onboarding setup is rendered empty and unusable. Does not render the status of connection, or button to connect.

![Jetpack dashboard page asking to connect to WP.com account](https://user-images.githubusercontent.com/17435/124145482-20c5a600-da8d-11eb-8bde-7ef5f63715e8.png)

This is probably due to an overly simplified condition/assumption that active means connected at https://github.com/woocommerce/google-listings-and-ads/blob/trunk/js/src/setup-mc/setup-stepper/setup-accounts/wordpressdotcom-account/card-content.js#L32

### Actual behavior:

![Empty card](https://user-images.githubusercontent.com/17435/124145504-258a5a00-da8d-11eb-8d6c-ae0c83eb0943.png)

### Steps to reproduce:
(I haven't reproduced it from scratch on my local env, but it's reproducible every time on merchants env)
1. Install and activate Jetpack and GLA (do not connect Jetpack)
2. Somewhat activate Jetpack plugin without connecting WP.com account (not sure how?)
2. Go to the onboarding [**Marketing > GLA > Get started**](https://www.tsquarelifestyle.nl/wp-admin/admin.php?page=wc-admin&path=%2Fgoogle%2Fsetup-mc)
3.check the card

### Technical details

At the customer's env `jetpack` variable at https://github.com/woocommerce/google-listings-and-ads/blob/trunk/js/src/setup-mc/setup-stepper/setup-accounts/wordpressdotcom-account/card-content.js#L15
is equal to 
```js
{
	  active: "yes"
	  displayName: ""
	  email: ""
	  owner: "no"
}
```

### Additional details:
I guess we should update the condition to allow connecting Jetpack to Wp, or at least show a message.

//cc @jconroy 
(I'm marking as `priority: high`, as it blocks the onboarding)

**Comment by findingsimple** [comment]
I believe this is the same or very similar to https://github.com/woocommerce/google-listings-and-ads/issues/624

@tomalec was Jetpack connected to the site using a different account?

**Comment by tomalec** [comment]
Yes, it was.
Closing as duplicate of #624
