### ISSUE TITLE
Add 2 inbox notifications to prompt for public reviews

### ISSUE THREAD

**Issue by j111q** [woocommerce/google-listings-and-ads#860]
## Message 1
**Message 1 should be sent to:** 
Stores that
1. **Have not** set up any paid ads, AND
2. **Have** more than 100 clicks on their free listings. 

_Sidenote: It could be a little awkward for stores which have MUCH more than 100 clicks, eg. they already have 2000 clicks, and then they read that we're congratulating them on 100 clicks. But that's a temporary awkwardness just for now, since moving forward with new accounts, they would reach the milestone and immediate receive the inbox notification. IMO it's an acceptable awkwardness but open to discussion if anyone has a different perspective!_

**Title:** 
`You’ve gotten 100+ clicks on your free listings! 🎉`

**Body:** 
`Congratulations! Tell us what you think about Google Listings & Ads by leaving a review. Your feedback will help us make WooCommerce even better for you.`

**Button:** 
`Leave a review` 
which links to `https://woocommerce.com/products/google-listings-and-ads/#reviews`

**Image:**
![Prompt reviews-FL](https://user-images.githubusercontent.com/65582817/124579854-1e46c000-de82-11eb-87a1-8b514a3c99ab.png)

## Message 2
**Message 2 should be sent to:** 
Stores that
1. **Have** set up at least 1 paid ad campaign, AND
2. **Have** more than 10 conversions total

_Sidenote: Same at the above - It could be a little awkward for stores which have MUCH more than 10 conversions, eg. they already have 200 conversions, and then they read that we're congratulating them on 10 conversions. But that's a temporary awkwardness just for now, since moving forward with new accounts, they would reach the milestone and immediate receive the inbox notification. IMO it's an acceptable awkwardness but open to discussion if anyone has a different perspective!_

**Title:** 
`You’ve gotten 10+ conversions through Google Ads! 🎉`

**Body:** 
`Congratulations! Tell us what you think about Google Listings & Ads by leaving a review. Your feedback will help us make WooCommerce even better for you.`

**Button:** 
`Leave a review` 
which links to `https://woocommerce.com/products/google-listings-and-ads/#reviews`

**Image:**
![Prompt reviews-PA](https://user-images.githubusercontent.com/65582817/124581140-69ad9e00-de83-11eb-88dd-15259a905e68.png)

## Event tracking
Can we tracking for 2 events:
1. Click on the button for Message 1
2. Click on the button for Message 2

## Figma link
[URL](https://mc.a8c.com/pb/29b5c/)

**Comment by nima-karimi** [comment]
> which links to `https://woocommerce.com/products/google-listings-and-ads/#reviews`

I wonder if we could link to the [WordPress.org reviews section](https://wordpress.org/support/plugin/google-listings-and-ads/reviews/#new-post) instead. Many users install the plugin from the WordPress.org plugin directory, and if they go to our [WooCommerce.com reviews page](https://woocommerce.com/products/google-listings-and-ads/#reviews), they get the following message:

> Only customers who have purchased this product may leave a review.

On the other hand, WordPress.org doesn't require this and anyone with an account there could leave a review. A direct link to "Add your own review" section of GLA on WordPress.org would be:
```
https://wordpress.org/support/plugin/google-listings-and-ads/reviews/#new-post
```

**Comment by j111q** [comment]
That's a great point. Let's do that instead 😅

**Comment by danielbitzer** [comment]
@j111q we could also randomize the link so half the time it links to wordpress.org vs woocommerce.com?

I also wonder if we should reach out to the wc.com team to ask them to allow reviews on free products even if the customer hasn't purchased it.

**Comment by danielbitzer** [comment]
> It could be a little awkward for stores which have MUCH more than 100 clicks, eg. they already have 2000 clicks, and then they read that we're congratulating them on 100 clicks

@j111q what about rounding to the nearest hundred and then showing that number in the note?

**Comment by j111q** [comment]
@danielbitzer:

> @j111q we could also randomize the link so half the time it links to wordpress.org vs woocommerce.com?

This makes sense to me! 👍 

> @j111q what about rounding to the nearest hundred and then showing that number in the note?

Oooh nice idea!
So to clarify, do you mean:
For **current/existing users, who have >100 clicks**, we round down to nearest hundred, and show that number.
For **current/existing users who have currently less than 100 clicks, AND future users** , we will detect when they hit 100 clicks and congratulate them on that number.

**Comment by danielbitzer** [comment]
> For **current/existing users, who have >100 clicks**, we round down to nearest hundred, and show that number.
> For **current/existing users who have currently less than 100 clicks, AND future users** , we will detect when they hit 100 clicks and congratulate them on that number.

Yes exactly this 😄 would be pretty easy I think.

**Comment by j111q** [comment]
> would be pretty easy I think.

My fav sentence 😜  Let's do it! Thanks for the great ideas @danielbitzer!

**Comment by danielbitzer** [comment]
<img width="534" alt="Screen Shot 2021-09-16 at 5 15 28 pm" src="https://user-images.githubusercontent.com/1892137/133571713-cdea9396-91f2-4a88-87e3-d9e12f65f45d.png">

It's kinda funny to me for some reason 😆

**Comment by j111q** [comment]
Hahahahhaha 'cause it's like so specific I think. WELL better than saying 100+ if you have 5300 clicks I guess 😆

**Comment by danielbitzer** [comment]
Haha nah I really like it!

Side note: I'm not sure why the note has been added "9 hours from now" maybe a WP Admin bug 😬

**Comment by j111q** [comment]
Yes it feels celebratory 🥳  Guess you are a time traveller 🙃

**Comment by danielbitzer** [comment]
> **Message 2 should be sent to:**
> Stores that
> 
> 1. **Have** set up at least 1 paid ad campaign, AND
> 2. **Have** more than 10 conversions total

@j111q technically speaking do you think we can just check for 10 conversions? They would have to setup at least 1 ad campaign in order to have any conversions right?

**Comment by j111q** [comment]
> do you think we can just check for 10 conversions?

True and yes 👍  😆  Let's just do that.

**Comment by danielbitzer** [comment]
> using Impressions instead of Clicks, so we reach out to more merchants

https://googleforwooextension.wordpress.com/2021/09/22/ops-design-dev-weekly-sync-with-google-22-september-2021/#comment-135

@j111q could you let me know what the updated title should be and the number of impressions to require before adding the note?

**Comment by findingsimple** [comment]
@j111q sorry to bother while you are on your Jam. Just wanted to triple-check the above to wrap things up.

**Comment by j111q** [comment]
Yes sorry, should've closed the loop here - it's good to go as is! 👍  🚢 

The team was aligned to revisit the other convo around Ad Budget / Set Up notifications separately, as those are still being discussed in terms of copy and timing.

**Comment by findingsimple** [comment]
Both  #1012 and  #1066 have been merged
