### ISSUE TITLE
Add test coverage report

### ISSUE THREAD

**Issue by nima-karimi** [woocommerce/google-listings-and-ads#864]
Add a test [coverage](https://phpunit.readthedocs.io/en/7.5/code-coverage-analysis.html) report for unit tests and include a check for Travis.

Some useful links:
- https://phpunit.readthedocs.io/en/7.5/code-coverage-analysis.html
- https://tomasvotruba.com/blog/2019/09/02/how-to-speedup-test-coverage-on-travis-by-95-percent/
- https://dev.to/acho_arnold/php-test-coverage-with-travis-ci-and-code-climate-using-clover-eih
- https://docs.travis-ci.com/user/coveralls/

**Comment by tomalec** [comment]
For the front-end tests/jest we can start with just `--coverage`, but I :+1: Coveralls

**Comment by mikkamp** [comment]
After updating to phpunit 9.5 in PR #1867, as long as we have a PHP version with xdebug installed then a coverage report can be produced as follows.

1. Add the following section to `phpunit.xml.dist`
```xml
	<coverage>
		<include>
			<directory suffix=".php">./src</directory>
			<directory suffix=".php">./views</directory>
			<file>google-listings-and-ads.php</file>
		</include>
	</coverage>
```

2. Setup tests: `bin/install-wp-tests.sh <db_name> <db_user> <db_pass>`
3. Run the tests with a coverage report: `XDEBUG_MODE=coverage vendor/bin/phpunit --coverage-text`

Example output:
![image](https://user-images.githubusercontent.com/11388669/215832210-df1c16d2-9125-4d81-a2df-fb3ebeeb10bf.png)

**Comment by mikkamp** [comment]
Update: A codecov report has been added in #1915
So far this only covers PHP, we also do unit testing in JS which we could include in the coverage report.
