### ISSUE TITLE
missing the most important options, Category Mapping

### ISSUE THREAD

**Issue by ybestoreservice** [woocommerce/google-listings-and-ads#873]

**Comment by layoutd** [comment]
Thanks for the suggestion @ybestoreservice, it would be great to have you add your ideas to the [Ideas Board](https://ideas.woocommerce.com/forums/133476-woocommerce?category_id=403986), which is where developers go to look for future plugin features and improvements.

**Comment by SirDarcanos** [comment]
@layoutd I do not think this should be considered a feature to be added. It should be considered as something important just missing in the plugin and to be added. Sometimes Google might assign the wrong category automatically. We should be able to map WC categories to Google Categories in WooCommerce, or set it individually for each product.
