### ISSUE TITLE
Add e2e tests for onboarding flow

### ISSUE THREAD

**Issue by tomalec** [woocommerce/google-listings-and-ads#886]
Onboarding flow is our critical path, which preferably should be rock solid and stable.
End-to-end tests could significantly help to assure that. Unfortunately, this is actually the trickiest part to test, as it requires the site to be live to connect it to Jetpack, WP, Google, and MC accounts.

## User story

As a developer, I'd like to quickly assert that critical functionality - onboarding setup, works correctly.

## Technical
So far I see two ways to go:
1. Make e2e tests run ngrok, use actual external accounts
	Pros:
	- Tests the full stack and the full flow 
	
	Cons:
	- probably tricky to implement
	- resource and time consuming
2. Mock account connection, either by some server-side flag, or mock external API calls
	Pros:
	- Would execute faster
	
	Cons:
	- not really end-to-end
	- Personally, it could be hard for me to mock all those external calls. Hopefully, for PHP experts it could be easier.
	

Does anybody have a better idea?

## Figma link
n/a

## Acceptance criteria
- [ ] There is an automated test for the onboarding flow

## Event tracking
n/a

## Additional notes:
- I created it as a follow-up for the [fix](https://github.com/woocommerce/google-listings-and-ads/pull/885) for a critical issue https://github.com/woocommerce/google-listings-and-ads/issues/884 that happened with the latest (buggy and accidentally backward-incompatible WooCommerce release)

**Comment by findingsimple** [comment]
> Make e2e tests run ngrok

I think that will be tricky to do without investing a lot of time with setup and also maintainance.

> Mock account connection

It won't be true e2e as you say but I think mocking or having some way to mock connection states is probably a better approach.

**Comment by tomalec** [comment]
We discussed it today on Dev call, the general summary was:
- Testing it to-the-very-end of external APIs may be problematic for a number of reasons:
	- Tests would become fragile when we depend on external APIs and server
	- they would take much longer to execute
	- we may reach API call limits, or even account creation limits for our MC accounts.
- We would try to mock external/Google APIs, so we will test it from end-to-our-end. This way we could be more flexible with scenarios we test, independent from external servers connection.
- We could try extending the existing test proxy server for requests other than reports.
- Later, if we would really need to test the plugin from end to the very end, we could add a limited number of specific cases for **read-only** external API calls.

**Comment by tomalec** [comment]
Besides mocking Google API, we also need to find a way to mock/test Jetpack connection, which is not even tested by `woocommerce` itself https://github.com/woocommerce/woocommerce/issues/25741

**Comment by tomalec** [comment]
(assigning to myself, as frust…motivated with support rotation experience :sunglasses:, I did some experiments and managed to mock Jetpack connection in e2e tests. I'd publish a draft with my findings probably after the rotation week)

**Comment by findingsimple** [comment]
@tomalec wondering how far we got to completing this one and whether we can look at breaking it up, removing you from assigned in case others want to tackle it etc.

**Comment by mikkamp** [comment]
This issue is superseded by https://github.com/woocommerce/google-listings-and-ads/issues/2070
Closing this since the onboarding flows will be covered in separate E2E tests tracked in #2070
