### ISSUE TITLE
🏗 Bring back colors for Travis builds - move bundlewatch to GH actions

### ISSUE THREAD

**Issue by tomalec** [woocommerce/google-listings-and-ads#890]
It seems Travis loos all colors when any environment variable is set.
https://travis-ci.community/t/ansi-colors-in-console-does-not-work-anymore/6608/2

We do have one for bundlewatch job. That means we lost colors for all builds and jobs just to support this one.

We could move it to GH actions, so only this action will be colorless.

## User story
As a developer, I'd like to see colorful lobs in CI.

## Technical

Travis hides colors for envs set in settings and in ones secured in `.travis.yml`.

We can also try a workaround with `unbuffer`
https://github.com/travis-ci/travis-ci/issues/7967#issuecomment-424521694

## Figma link
n/a

## Event tracking
n/a

**Comment by findingsimple** [comment]
I think we can close this one right?

**Comment by eason9487** [comment]
> I think we can close this one right?

Yes. And some workflows of GitHub Actions have similar missing color problems. I updated to #1047. Closed this one.
