### ISSUE TITLE
Does not Activate 

### ISSUE THREAD

**Issue by Fusionbytetech** [woocommerce/google-listings-and-ads#895]
### Describe the bug:
Activation fails with fatal error.

### Actual behavior:
Plugin could not be activated because it triggered a fatal error.

Fatal error: Uncaught RuntimeException: Failed to locate plugin /var/www/wp-content/plugins/google-listings-and-ads in /var/www/wp-content/plugins/google-listings-and-ads/vendor/jetpack-autoloader/class-plugin-locator.php:47 Stack trace: #0 /var/www/wp-content/plugins/google-listings-and-ads/vendor/jetpack-autoloader/class-autoloader.php(46): Automattic\Jetpack\Autoloader\jpf071ae0bd1cba37dda4b34413db935ac\Plugin_Locator->find_current_plugin() #1 /var/www/wp-content/plugins/google-listings-and-ads/vendor/autoload_packages.php(13): Automattic\Jetpack\Autoloader\jpf071ae0bd1cba37dda4b34413db935ac\Autoloader::init() #2 /var/www/wp-content/plugins/google-listings-and-ads/src/Autoloader.php(37): require('/var/www/wp-con...') #3 /var/www/wp-content/plugins/google-listings-and-ads/google-listings-and-ads.php(35): Automattic\WooCommerce\GoogleListingsAndAds\Autoloader::init() #4 /var/www/wp-admin/includes/plugin.php(2300): include('/var/www/wp-con...') #5 /var/www/wp-admin/plugins.php(191): plugin_sandbox_scrape('google-listings. in /var/www/wp-content/plugins/google-listings-and-ads/vendor/jetpack-autoloader/class-plugin-locator.php on line 47

### Steps to reproduce:

1.download plugin 
2.click activate plugin 
3.get error

### Additional details:

Plugin version  1.2.1

**Comment by mikkamp** [comment]
Hi there,

This repository is not intended for support requests.

The best place to get support is the [WordPress.org Google Listings and Ads forum.](https://wordpress.org/support/plugin/google-listings-and-ads/)

If you have a WooCommerce.com account, you can [start a chat or open a ticket on WooCommerce.com](https://woocommerce.com/my-account/create-a-ticket/).

Based on the error message it looks like the plugin didn't install fully. Also in the stack trace the line numbers for the files in `google-listings-and-ads/vendor/jetpack-autoloader` do not match up. The other line numbers in the stack trace do.

The vendor folder is quite large so you might want to try removing the plugin completely and install it through FTP (all settings will remain when doing so).
