### ISSUE TITLE
Bump WordPress tested version to 5.8

### ISSUE THREAD

**Issue by mikkamp** [woocommerce/google-listings-and-ads#900]
### Describe the issue:
Normally we can use the WooRelease option `--wp_tested=x.y` to bump the WordPress tested up to version. However in our extension we only have the header line in the readme.txt file and not in the main plugin file. WooRelease throws an error if we try to bump this version.

So the following header should be included:

```
Tested up to: 5.8
```

Once that's added WooRelease will take care of bumping the version both in the main plugin file and the readme.txt when we provide the option `--wp_tested=x.y`

We can also update the steps in the Wiki to clarify usage of the WooRelease option for bumping the version: https://github.com/woocommerce/google-listings-and-ads/wiki/Release-Process

**Comment by mikkamp** [comment]
Travis can be bumped as well to test with recent versions: https://github.com/woocommerce/google-listings-and-ads/blob/trunk/.travis.yml#L31
Latest up to L-2

**Comment by ecgan** [comment]
@mikkamp , I have created PR #904 for this. If it looks good, I will merge it and then make a release tomorrow. 🙏
