### ISSUE TITLE
Supporting new multi-client account Merchant Center account

### ISSUE THREAD

**Issue by solstudioim** [woocommerce/google-listings-and-ads#906]
### Describe the bug:
I came across a user, 4166380-Zen, who has a [multi-client account Merchant Center account](https://support.google.com/merchants/answer/188487?hl=en) and they can't use this type of Merchant Center account with Google Listing & Ads.

Also, it seems there is no mention of incompatibility of multi-client Merchant Accounts with Google Listings & Ads

### Expected behavior:
When users go through onboarding flow, they connect an existing Gmail account, corresponding existing Merchant Centers Account either regular Merchant Center account or multi-client Merchant Account should be listed to connect to.

### Actual behavior:
Users go through onboarding flow, multi-client Merchant Account isn't listed to connect to

![Annotation on 2021-07-27 at 19-01-25](https://user-images.githubusercontent.com/17371139/127150381-877bac2d-f7ce-431c-a692-5cef627791fb.png)

### Steps to reproduce:

1. Need to have a multi-client Merchant Account with sub-accounts, etc
2. Go through the onboarding flow
3. Existing multi-client Merchant Account not listed

**Comment by tomalec** [comment]
It happens to be our core architectural limitation, that we do not support multi-client accounts.

It seems we need to state that clearer in our docs.

If that's about to be a feature request. We would have to request new APIs and architecture from Google.

**Comment by solstudioim** [comment]
Hi @tomalec we've stated in our doc lately that this extension doesn't support multi-client accounts yet: https://docs.woocommerce.com/document/google-listings-and-ads/google-listings-and-ads-faqs/#section-44

**Comment by tomalec** [comment]
Thank you @solstudioim.

----

I wonder if there is also an alternative path for a merchant that has a multi-client account, so they could move an existing sub-account from their MCA to our MCA. Like:
1. Disconnect Merchant Center and Google accounts via /wp-admin/admin.php?page=connection-test-admin-page
2. Go to Google MCA account,
3. disconnect individual sub-account,
4. Go to the onboarding, Connect a Google Account
5. Choose a disconnected individual account.

As far as I tested at step 3 we can only **delete** the account. But maybe there is _"disconnect"_ somewhere, that would allow reconnecting the same sub-account without deleting all the data?
@jconroy

**Comment by thuautp** [comment]
Hi @jconroy ,

The user in the ticket came back with more details about why they have an MCA account:

> The thing is, i started to work in paid media several years ago, and it was not possible to create individual merchant accounts with same user/e-mail address. So google gave me an MCA in order i can manage all my clients accounts. So that's why i use a MCA. In order to use regular merchant accounts i would have to create news ones and lose all the data and configurations. In this particular case, it's only a client that have a wordpress website and i wanted to try this plugin with him.

**Comment by findingsimple** [comment]
Closing for now. As per https://github.com/woocommerce/google-listings-and-ads/issues/906#issuecomment-890877121 we have a doc that indicates we don't support multi-client accounts.
