### ISSUE TITLE
Add an option, hook, or dedicated description field which can process shortcodes for synced descriptions.

### ISSUE THREAD

**Issue by melek** [woocommerce/google-listings-and-ads#907]
## User story

A forum user is using shortcodes to help construct their product descriptions ([click here to view the post](https://wordpress.org/support/topic/description-is-not-synced-along-with-products-2/)). For a large shop, custom shortcodes are one useful  strategy to keep description content aligned across many products. Including allowed HTML is already a great step for store owners to choose how they present their products(#905), and enabling store owners to add shortcodes would make the plugin even more useful for larger stores which need to keep up with updating content for large catalogs.

Since shortcodes are also used for formatting and other purposes inappropriate for a product description on Google (see #784), it would be useful to be able to load and process shortcodes before syncing the product description as an all-or-nothing setting, or in a special product description box that would be checked before the long and short description areas that could contain shortcodes.

## Technical

I'm unsure of the technical limitations on such a feature, but I do worry about complicating the user experience for most shop owners who may not even be aware of shortcodes their other plugins may be adding (such as Visual Composer and other page builders), so making this flag optional in the code is probably best in the short term.

I don't know how caching might be leveraged for descriptions in the plugin, so I can't comment there except to say processing shortcodes ahead of time when the product is saved might be better than trying to do it all at once on sync (but that is speculation on my part - I'm not a developer!)

I didn't fill out other areas of the new feature template, but I didn't know what to put in them. Sorry!

**Comment by philfutureproof** [comment]
Please can this funtionality be added to the WooCommerce / Google Listings & Ads plugin. It is most frustrating that as our (Avada) template uses shortcodes we get a syncing error. As suggested in this post, to add an option, hook, or dedicated description field which can process shortcodes for synced descriptions would allow us to use the plugin successfully on our WooCommerce store. Thank you in advance for considering

**Comment by mikkamp** [comment]
@philfutureproof 

This was resolved by adding a filter to turn on processing of shortcodes in PR #911 
So to enable processing of shortcodes in the description you'd use the following code snippet:

```
add_filter( 'woocommerce_gla_product_description_apply_shortcodes', '__return_true' );
```

Does that resolve the issue with your templates or is there something different you were looking for?

**Comment by philfutureproof** [comment]
@mikkamp 

Thanks for your help. I've tried adding  `add_filter( 'woocommerce_gla_product_description_apply_shortcodes', '__return_true' );` to the website's functions.php file but I still getting the warning: Description: the value should not be blank [See here](https://snipboard.io/cUfFET.jpg)

Is that the only piece of code I need to add?

See functions file [here](https://snipboard.io/7jNMJi.jpg)

Please advise.

**Comment by mikkamp** [comment]
The code snippet looks like it's placed in the right location. Seems like you have some additional filters in there for allowing iframe content. The description does also strip out "unallowed" html, so it would depend a little bit on what content is being provided through those shortcodes. If it's not mostly text then it could still be removed.

The alternative is to use the filter `woocommerce_gla_product_attribute_value_description` where you can provide your own description. You'll need the help of a developer to get a code snippet to format the description correctly. Take note that it should follow the guidelines outlined by Google here: https://support.google.com/merchants/answer/6324468

**Comment by philfutureproof** [comment]
The additional filters you're seeing relate to ACF fields (created via the Advance Custom Fields plugin) & shouldn't affect the product description field.

Since my last communication though, the [description warning](https://snipboard.io/cUfFET.jpg) has disappeared so presumably your suggested filter is now working! However, one thing that's puzzling me is there may be a link between the description field & the GTIN field. 

To explain... when I look on MC it says the product is missing its GTIN - [see here](https://snipboard.io/VZnpk7.jpg) but there is a recognised barcode in that GTIN field on the website! I tried removing the GTIN and then re-entering it in case it had got corrupted but when I did, I noticed that while the GTIN field on the website was empty the same 'description warning' reappeared?

I'm therefore wondering if the 'description warning' also appears when the GTIN field is being blocked by a shortcode as well (hence why MC cannot read it).

So I'm wondering... is there another filter like `woocommerce_gla_product_description_apply_shortcodes` that can be applied to the GTIN field in order to process any shortcodes in the same way?

Does that make sense?

**Comment by philfutureproof** [comment]
@mikkamp

Further to my last message to you, when I woke up this morning all the GTIN issues seem to have cleared up! So many thanks for your help on this. That aspect seems to be resolved

The only issue left now regarding the Google Listings & Ads plugin is why do some of the products say 'Available Soon' on Google MC - [see here](https://snipboard.io/e1z2W4.jpg)

Are you able to explain?

**Comment by mikkamp** [comment]
Glad to hear that's working for you now. The product updates are synced in the background, so it's common that it can take a while to update.

As for the "Available Soon", I'm not able to see the full column where that's from, however it looks to be from the "Click potential" column. Google explains that as follows:

![image](https://github.com/user-attachments/assets/e8b44aa8-f196-42db-8914-882b0d90d968)

They'll need to collect a few more metrics on those products, to be able to calculate that score.
