### ISSUE TITLE
Consider switching to **`@woocommerce/`**`dependency-extraction-webpack-plugin`

### ISSUE THREAD

**Issue by tomalec** [woocommerce/google-listings-and-ads#916]
Currently we use `@wordpress/dependency-extraction-webpack-plugin` in quite outdated version, to [wrangle](https://github.com/woocommerce/google-listings-and-ads/blob/trunk/webpack.config.js#L19-L20) WooCommerce components.

So far there is no problem directly connected to it. But I recall struggling with some `/components` dependencies in the past (like https://github.com/woocommerce/google-listings-and-ads/pull/234).

After reading a comment https://github.com/saucal/pinterest-for-woocommerce/pull/105/files#r678799560 I think it may be worth changing it here, to save us some problems in the future, plus maybe workaround WP package update related problems https://github.com/woocommerce/google-listings-and-ads/pull/821

**Comment by findingsimple** [comment]
Thanks @tomalec

**Comment by tomalec** [comment]
In a comment @psealock mentioned (105-gh-woocommerce/pinterest-for-woocommerce #discussion_r679554818):
> With Woo’s flavour of [Dependency Extraction Webpack Plugin](https://github.com/woocommerce/woocommerce-admin/tree/main/packages/dependency-extraction-webpack-plugin), you can remove the custom requestToExternal / requestToHandle and simply use the plugin in webpack
> 
> https://github.com/woocommerce/woocommerce-admin/blob/106e18e75992433cd842e7ba3ed2cf9a91e5391f/webpack.config.js#L198

Unfortunately, it wasn't  "simply" removing `requestToExternal`, as we still need some parts of it to prevent the Card component from rendering incorrectly. But we can remove all the bits related to `@woocommerce/`, ee https://github.com/woocommerce/google-listings-and-ads/pull/976
