### ISSUE TITLE
Remove all "STEP [NUMBER]" headers

### ISSUE THREAD

**Issue by eason9487** [woocommerce/google-listings-and-ads#923]
It's a follow-up of https://github.com/woocommerce/google-listings-and-ads/pull/914#discussion_r680147956

> Per the latest Figma, this header is no longer there.

Remove all "STEP [NUMBER]" headers from

- MC setup
- Ads setup
- Free listings edit

**Comment by j111q** [comment]
Yes, thanks for catching that - it was one of the design tweaks proposed by @shivanarrthine and I think it's better too, removes any unnecessary text. 👍 Thank you!!

**Comment by eason9487** [comment]
@j111q, thank you for confirming!
