### ISSUE TITLE
Change the step number icon style to align with the latest design

### ISSUE THREAD

**Issue by eason9487** [woocommerce/google-listings-and-ads#924]
It's a follow-up of https://github.com/woocommerce/google-listings-and-ads/pull/914#issuecomment-890087206

> In the latest designs "Confirm store requirements" headers is on a white background, whereas in this PR it's transparent/grey
> ![Screenshot from Figma](https://user-images.githubusercontent.com/17435/127698584-5d89d69a-8509-46d3-9a92-ae76b16d169d.png)

Change the step number icon style to align with the latest design.

## Unknowns

Do we need to 100% stick to the Figma design for the shared components imported from `@wordpress/components` and `@woocommerce/components`?

**Comment by j111q** [comment]
>Do we need to 100% stick to the Figma design for the shared components imported from @wordpress/components and @woocommerce/components?

Generally no. Use shared components instead! Unless it's really really different, in which case, please let me know. But for this one, I think it's pretty similar so it should be fine.

**Comment by eason9487** [comment]
@j111q, thank you for clarifying!

> But for this one, I think it's pretty similar so it should be fine.

Close this issue according to this comment.
