### ISSUE TITLE
Postcode is not always required

### ISSUE THREAD

**Issue by mikkamp** [woocommerce/google-listings-and-ads#939]
### Describe the bug:
When we edit the contact information we only allow the address to be updated if street,city,country,postcode are all populated. State can be optional for some countries so it's not included in the list. But postcode is another one which is optional for some countries. In the WooCommerce backend it does not require these store fields, but in the frontend there is some conditional logic [whether a postcode is required](https://github.com/woocommerce/woocommerce/blob/5.5.2/includes/class-wc-countries.php#L801-L804) (or is even displayed).

A quick solution might be to make postcode optional (like state is optional), but we might want to consider making it conditional based on the country in the future.

### Expected behavior:
For countries where the postcode is not a requirement we should not enforce it when trying to save contact information.

### Steps to reproduce:
1. Set the store address without a zipcode (optionally a country like Ireland that doesn't require a zipcode but it's not enforced for store address)
2. Go to edit contact information page and confirm that we are unable to save details

**Comment by mikkamp** [comment]
This is also evident in the initial onboarding.

![image](https://user-images.githubusercontent.com/11388669/128699507-dcd57fe1-a5ad-453b-bfa8-90fa626b76b1.png)

I'm unable to click the "complete setup" button until I've added a postcode. Related to #634 it would be helpful to get feedback on why the button is disabled, it's not directly evident that the postcode is missing.

**Comment by findingsimple** [comment]
cc @j111q @shivanarrthine for input

**Comment by eason9487** [comment]
Hi @j111q,

Consider that almost all fields of store address in the WC settings are optional, and we didn't show any required address fields hint/error to users. I think we could take the quick solution that makes the postcode to be optional for now. Although it would still block the submition if one of address-line-1/city/country is empty*, I'm assuming that most users would not be confused by those fields are required even we didn't tell them. And for making up this, we could add a required field hint on the address card UI.

In the future, we could patch with more detailed rules for all/some countries if the hidden rules still confuse users or the Google side ask for it.

\*Just noticed that [the city field is not required in Singapore](https://github.com/woocommerce/woocommerce/blob/5.5.2/includes/class-wc-countries.php#L1287-L1294). And I saw some Singapore addresses use "Singapore" as city. Wonder if we do not make adjustments for Singapore at this moment, would it confuse Singaporeans?

What do you think?

**Comment by j111q** [comment]
Sorry for late reply Eason!!

>I think we could take the quick solution that makes the postcode to be optional for now.

Can we make it optional **only** for the countries where it is not required (eg. Ireland)? 
OR, Not sure if you mean `make it optional for all countries`. My worry regarding`make it optional for all countries` is some countries might have a require postal code by Google, and if so, what would happen? 

>*Just noticed that the city field is not required in Singapore. And I saw some Singapore addresses use "Singapore" as city. Wonder if we do not make adjustments for Singapore at this moment, would it confuse Singaporeans?

I think Singaporeans are pretty used to being an outlier here 😆  and we will generally fill in "Singapore" as the city, country and state, because it's almost always compulsory. I feel touched that you empathise with the silly feeling of it for us though 😂

**Comment by findingsimple** [comment]
@jorgemd24 this is perhaps something you could investigate and try and progress.

**Comment by eason9487** [comment]
Reopen this issue because it has not been resolved and there's another new problem.

Please refer to https://github.com/woocommerce/google-listings-and-ads/pull/1169#pullrequestreview-845505681 for more details.
