### ISSUE TITLE
Guzzle conflict

### ISSUE THREAD

**Issue by jakehodges** [woocommerce/google-listings-and-ads#952]
Still getting a conflict with Guzzle after updating to 1.4.0. Having this plugin activated is throwing a Guzzle error with my application. 

PHP Fatal error:  Uncaught Error: Call to undefined function GuzzleHttp\\choose_handler() in /nas/content/live/theflagstaging/wp-content/themes/twentyfifteen-child/vendor/guzzlehttp/guzzle/src/HandlerStack.php:42

Please let me know if I can provide any more information.

**Comment by JPry** [comment]
@jakehodges `twentyfifteen-child` sounds like a custom child theme. Could you provide a sample of how you're using the Guzzle library in the child theme?
