### ISSUE TITLE
Merchants left hanging during billing setup for existing accounts

### ISSUE THREAD

**Issue by findingsimple** [woocommerce/google-listings-and-ads#953]
**How to replicate**

* Attempt to connect an existing Google Ads account that does not have billing set up and create an ad campaign
* On step 3 of the initial Ads setup flow you'll see a "Setup billing" button that takes you to https://support.google.com/google-ads/answer/2375375
* The help text says "Once you have completed your billing setup, your campaign will launch automatically" however there is no way to actually continue the process.

**Video**

I have a video demoing it I will add in slack

**What I would expect**

I was confused. Going through the flow I was expecting a button to continue - instead, I had to get all the way back out of the ad campaign setup.

Possibly need to change the text in this situation - give some better guidance on what to do.

**Other**

We added the fallback link to support in issue https://github.com/woocommerce/google-listings-and-ads/issues/447 and PR https://github.com/woocommerce/google-listings-and-ads/pull/505 for some more context.

cc @j111q  and @shivanarrthine - probably worth us checking the wcadmin_gla_ads_set_up_billing_click event to see how many times we've been pointing merchants to https://support.google.com/google-ads/answer/2375375

**Comment by mikkamp** [comment]
This flow has drastically changed, and we are now entering a new phase of changes in #2215 
As such I'm going to close this issue, if it appears again with the newer flow we can reopen it.
