### ISSUE TITLE
Unable to type to filter countries during ads onboarding

### ISSUE THREAD

**Issue by findingsimple** [woocommerce/google-listings-and-ads#954]
### Describe the bug:

I noticed we can type to filter countries during MC onboarding but during Ads onboarding its not possible. 

I'm wondering if this is intended (perhaps I need a certain number of countries to be available) or an issue with the component or our implementation? 

<img width="489" alt="Screen Shot 2021-08-12 at 2 33 22 pm" src="https://user-images.githubusercontent.com/355014/129141360-4b0da4bf-161f-4f41-830d-8882b88d46e3.png">

vs

<img width="1106" alt="Screen Shot 2021-08-12 at 2 35 39 pm" src="https://user-images.githubusercontent.com/355014/129141388-1c48fef3-3ddc-42dd-b6b7-de7c85e1049a.png">

### Expected behavior:
I can type a letter like "N" to filter to only show N results like New Zealand.

### Actual behavior:
Can't filter

### Steps to reproduce:
1. Target multiple countries during MC onboarding
2. Create a paid campaign
3. Select audience dropdown and then type the letter of one of your countries - notice you can't filter the countries like you did during MC onboarding

**Comment by tomalec** [comment]
It has an attribute `isSearchable` set to `false` https://github.com/woocommerce/google-listings-and-ads/blob/add/886-e2e-jetpack/js/src/components/paid-ads/audience-section.js#L44:L44 but I'm not sure if that was on purpose.

**Comment by findingsimple** [comment]
@j111q do you think this should be consistent?

**Comment by j111q** [comment]
Yes it should be consistent and you should be able to search by typing! Good catch!!

**Comment by findingsimple** [comment]
Thank you!
