### ISSUE TITLE
Support stores without title

### ISSUE THREAD

**Issue by tomalec** [woocommerce/google-listings-and-ads#969]
### User story
As a merchant, I'd like to be able to create MC account, even though my store does not have a name.

### Describe the bug:
When [we request](https://github.com/woocommerce/google-listings-and-ads/blob/add/886-e2e-jetpack/src/API/Google/Proxy.php#L108:L108) a new Google Merchant Center account, we use [blog name](https://github.com/woocommerce/google-listings-and-ads/blob/add/886-e2e-jetpack/src/API/Google/Proxy.php#L595). Which may happen to be empty, resulting in the request to me rejected, with a not very helpful message:
```
Error creating account: Invalid request payload input.
```

### Expected behavior:
An account should be created with an empty/some autogenerated/fallback name, or the merchant should be given clear guidance.

### Actual behavior:
The merchant is unable to finish the onboarding and doesn't know why.

### Steps to reproduce:
1. Set your [**Site title**](https://8752cbe49a74.ngrok.io/wp-admin/options-general.php) to empty
2. Disconnect all your accounts
3. Go to [step 1 of onboarding](https://8752cbe49a74.ngrok.io/wp-admin/admin.php?page=wc-admin&path=%2Fgoogle%2Fsetup-mc) 
3. Connect your Google account
4. Click "Or, create a new Merchant Center account"
5. Click "Create Account"
6. Wath the errors.

![Empty title](https://user-images.githubusercontent.com/17435/130103567-a897ade6-77cc-49ae-8d2c-4de487437aa5.gif)

### Additional details:

- Reported by a merchant at 4222300-zd-woothemes
- Discussed on Slack p1628989272193400-slack-C7U3Y3VMY
- > That error message comes from the Joi library doing the validation for the request. Although it's just the name and URL that are required: https://github.com/Automattic/woocommerce-connect-server/blob/woogle/lib/google/handlers/manager/create-merchant.js#L8-L11

**Comment by mikkamp** [comment]
Just want to link PR #964 as it also implements a default site name `Account Y-m-d` when site_title is empty.
