### ISSUE TITLE
GuzzleHttp autoloader conflicts

### ISSUE THREAD

**Issue by smazur** [woocommerce/google-listings-and-ads#979]
Hi!

We use guzzlehttp library in our WordPress setup. After we installed Google Listings & Ads plugin we start getting fatal errors that certain functions from GuzzleHttp namespace are undefined. I investigated this issue and found that your plugin also uses guzzle library but with namespace prefixing. And the reason why we get those fatals is because of composer autoloader uses the same hash keys for static files for original (unprefixed) and your (prefixed) versions of guzzle library. So autoloader loads your’s version of guzzle and skips our’s because it thinks that those files are the same.

So there are two ways to fix this:
1. Change original guzzle package name in composer.json.
2. Change the path to src files of guzzle package.

In both cases that will produce different hash keys in autoloader.

**Comment by mikkamp** [comment]
Thanks for the report @smazur 
Would you be able to confirm if you continue to have this problem with version 1.4.2 which was released a few days ago?

The problem you are describing was resolved in #957. In that PR we ensure that the static files are only loaded using the hashed key from our package name. So it shouldn't be loading them anymore for both keys.

If it's still causing issues then would you be able to provide some additional information and some stack traces to show where it's loading the files incorrectly. In case there is something else we missed.

**Comment by smazur** [comment]
The issue is not reproducing any more. Thanks for quick update.

**Comment by findingsimple** [comment]
Thanks @smazur , closing
