### ISSUE TITLE
Phone Verification: Add API endpoints for requesting phone verification code and verifying it

### ISSUE THREAD

**Issue by nima-karimi** [woocommerce/google-listings-and-ads#982]
As part of #962 to implement the full version of phone verification.

We need two new API endpoints that allow requesting a phone verification code from Google (and sending the code to the user's phone), and verifying the user-provided code.

We can build them as part of the current `mc/contact-information` API or create a new route for just the phone verification. Given that we're going to be removing the phone number update functionality from the contact information API (https://github.com/woocommerce/google-listings-and-ads/issues/981), it might make sense to replace that with our phone verification functionality instead of building it on a new route.

## Request phone verification code

This API will accept a phone number, a phone region code, and a phone verification method as input and passes them to the `PhoneVerification` service in order to request a phone verification from Google.

The `PhoneVerification` service (https://github.com/woocommerce/google-listings-and-ads/issues/980), sends the request to Google and returns an ID of type string. This ID should be returned as the API response so that the front-end can store it and then return it in the next verification request along with the verification code input by the user.

## Verify the code

This API accepts a verification code, a verification ID, and a phone verification method as input. It will then pass them to the `PhoneVerification` service in order to verify the phone number and set it in the user's Merchant Center account.

The `PhoneVerification` service (https://github.com/woocommerce/google-listings-and-ads/issues/980), sends the code to Google along with the ID and method, and if the verification is successful returns without throwing any exceptions. This method doesn't return any values and returns `void`.

## Error handling

If there are any errors while requesting the verification code or while verifying the phone number, a custom exception is thrown including the error message. The API class should catch these exceptions and return an appropriate response for the user.

All errors and exceptions must have a unique code/ID assigned to them, and return that code along with the error message in the API response when something fails. 

Google already provides an error code in their API. However, we seem to strip that code in our other endpoints and only return a generic error message. We can use the same error code as Google, or preferably have our own custom codes defined in exception classes.

In this case, an error code can be useful for the UI to, for example, disable the "Resend" button for a while until the rate limit is reset.

## Additional Notes

- The phone verification method must be either `SMS` or `PHONE_CALL` and has to be validated/sanitized
- The phone number must be validated and sanitized by the API before passing it to the PhoneVerification` service
- There is a rate limit applied to the number of verifications that can be done for the same phone number: `You can try to verify the same phone number a maximum of five times every four hours.`

**Comment by eason9487** [comment]
📝  Dev note for @nima-karimi 

> If there are any errors while requesting the verification code or while verifying the phone number, a custom exception is thrown including the error message. The API class should catch these exceptions and return an appropriate response for the user.

> * There is a rate limit applied to the number of verifications that can be done for the same phone number: `You can try to verify the same phone number a maximum of five times every four hours.`

Even though we will add a cooldown time to lock the next retry of calling request phone verification API on the UI, I guess there're still some users who might run into the rate limit. Please help to notice whether the rate limit (error) could be distinguished from Google side response if you happen to reach that limit. 🙏 

![image](https://user-images.githubusercontent.com/17420811/131282100-b3ce8c05-772f-406b-a03c-125fda373467.png)

**Comment by nima-karimi** [comment]
> notice whether the rate limit (error) could be distinguished from Google side response if you happen to reach that limit

I added a few notes to the `Error handling` section of the issue:

> All errors and exceptions must have a unique code/ID assigned to them, and return that code along with the error message in the API response when something fails.
> 
> Google already provides an error code in their API. However, we seem to strip that code in our other endpoints and only return a generic error message. We can use the same error code as Google, or preferably have our own custom codes defined in exception classes.
> 
> In this case, an error code can be useful for the UI to, for example, disable the "Resend" button for a while until the rate limit is reset.

Is this what you meant by distinguishing the rate limit error, @eason9487?

**Comment by eason9487** [comment]
> Is this what you meant by distinguishing the rate limit error?

Yes. I was thinking it would be nicer if we could tell users, who already have reached the rate limit, that they need to wait four hours till later. Thanks!

**Comment by danielbitzer** [comment]
> I was thinking it would be nicer if we could tell users, who already have reached the rate limit, that they need to wait four hours till later.

@eason9487 currently I have the response as this:

<img width="745" alt="Screen Shot 2021-09-10 at 11 38 36 am" src="https://user-images.githubusercontent.com/1892137/132787691-cdc9e9e6-0814-4f8b-8f70-d294ffedfc46.png">
