### ISSUE TITLE
PHP notice when adding variations

### ISSUE THREAD

**Issue by layoutd** [woocommerce/google-listings-and-ads#988]
### Describe the bug:
When adding a new variation to a variable product, a PHP notice is thrown:
```
PHP Notice:  Undefined index: catalog_visibility in /…/plugins/woocommerce/includes/class-wc-product-variation.php on line 419
PHP Stack trace:
…
PHP  13. Automattic\WooCommerce\GoogleListingsAndAds\Product\SyncerHooks->Automattic\WooCommerce\GoogleListingsAndAds\Product\{closure:/…/plugins/google-listings-and-ads/src/Product/SyncerHooks.php:111-113}() /…/wp-includes/class-wp-hook.php:303
PHP  14. Automattic\WooCommerce\GoogleListingsAndAds\Product\SyncerHooks->handle_update_products() /…/plugins/google-listings-and-ads/src/Product/SyncerHooks.php:112
PHP  15. Automattic\WooCommerce\GoogleListingsAndAds\Product\ProductHelper->is_sync_ready() /…/plugins/google-listings-and-ads/src/Product/SyncerHooks.php:189
PHP  16. WC_Product_Variation->is_visible() /…/plugins/google-listings-and-ads/src/Product/ProductHelper.php:304
PHP  17. WC_Product_Variation->is_visible_core() /…/plugins/woocommerce/includes/abstracts/abstract-wc-product.php:1536
PHP  18. WC_Product_Variation->get_catalog_visibility() /…/plugins/woocommerce/includes/abstracts/abstract-wc-product.php:1546
```

### Expected behavior:
No PHP notice when adding a variation.

### Actual behavior:
PHP Notice when adding a variation.

### Steps to reproduce:
1. Install GLA and complete the Merchant Center onboarding.
2. Add or edit a variable product.
3. Use "Product data" > "Variations" > "Add Variation" > "Go" to add a variation.
4. Confirm the notice in the log.

### Additional details:
- Based on the trace, it looks like the problem is that in `SyncerHooks::register`, the `woocommerce_new_product_variation` hook is used to call `handle_update_products`, which invokes `product_helper->is_sync_ready`, which uses `$product->is_visible()` on the variation before it has a `catalog_visiblity` attribute.

**Comment by findingsimple** [comment]
Thanks @layoutd - this looks similar to https://github.com/woocommerce/google-listings-and-ads/issues/986

@nima-karimi can you double check the handling for everything when adding/editing products please?
