### ISSUE TITLE
Increase in merchants submitting blank domains from mid-july

### ISSUE THREAD

**Issue by findingsimple** [woocommerce/google-listings-and-ads#989]
### Describe the bug:

The Google team noticed an increase during July of blank domains being submitted during MC onboarding.

<img width="1283" alt="Screen Shot 2021-09-02 at 12 56 33 pm" src="https://user-images.githubusercontent.com/355014/131777018-97e13d1c-a32b-4542-b08c-d1f6a1726a35.png">

We shipped https://github.com/woocommerce/google-listings-and-ads/issues/796 i[n June](https://github.com/woocommerce/google-listings-and-ads/releases/tag/1.1.0) but did have releases in mid-July [such as 1.2.0](https://github.com/woocommerce/google-listings-and-ads/releases/tag/1.2.0) 

This is an issue to cover investigating the situation some more. We don't have any steps to replicate at the moment.

### Expected behavior:
Blank domains technically aren't valid - all sites should have a domain - especially when submitting to the MC

### Actual behavior:
Blank domains submitted

### Steps to reproduce:
TBC - currently needs investigation

### Additional details:
Increased from mid-July.

We are also seeing a drop-off in the rate at which merchants were successfully able to complete MC Onboarding and become ads ready customers - speculation is that these may be related - even in a small way.

**Comment by findingsimple** [comment]
Follow up question to be answered as I couldn't tell -> "Are we allowing merchants to submit empty values as their domain?"

I can see we validate the URL but not sure if we allow blank

**Comment by layoutd** [comment]
> Follow up question to be answered as I couldn't tell -> "Are we allowing merchants to submit empty values as their domain?"

After a bit of review, the answer looks like a NO:

- The Merchant Center connection process always uses the [`PluginHelper::get_site_url()` method](https://github.com/woocommerce/google-listings-and-ads/blob/24795b3cfcee28543d752d995490c77ac483b3b0/src/PluginHelper.php#L181) to determine the store's base URL, which in turn invokes the WP `get_home_url()` function, which _does_ have the `home_url` filter. 
    However,
- When connecting an existing Merchant Center account, we update the account's URL to match the site URL, and _do_ perform URL validation:
    https://github.com/woocommerce/google-listings-and-ads/blob/fad9d7d6199f9807deeca08aaf806dbf1e07ceb8/src/API/Site/Controllers/MerchantCenter/AccountController.php#L586-L588
- When creating an new Merchant Center account, we _also_ perform URL validation:
    https://github.com/woocommerce/google-listings-and-ads/blob/bd62aaed77f591e3d7f69d6b9b01625adb5c0eca/src/API/Google/Proxy.php#L98-L100
- There's also a [`woocommerce_gla_site_url` filter](woocommerce_gla_site_url) that can modify the detected site URL but, again, this value is passed through the above validations before connecting or creating a Merchant Center account, so an empty value would stop the process.

**Comment by findingsimple** [comment]
Thanks for the investigation @layoutd I'll see if we can get any more info from the Google team that might help us pin point things

**Comment by findingsimple** [comment]
Closing pending more info
