### ISSUE TITLE
Check compatibility with WC 5.7

### ISSUE THREAD

**Issue by tomalec** [woocommerce/google-listings-and-ads#995]
WooCommerce 5.7 is scheduled for release on 14th September 2021

This issue is to track the progress in checking/implementing the compatibility of the plugin with it.

- [x] Check that WC updates to 5.7 without any errors
- [x] Check if WC bundle delivers different/incompatible versions of dependencies we use.
	- I'm not sure if that's the right process to do so (for more see internal article pb0Spc-1LK-p2). But I checked the diff between WC-admin version used by WC 5.7 and the one used by 5.6. I was looking for changes in `/package.json` and the version bump in any `/packages/**/package.json`s. There were updates in testing libraries, that explains problems with tests mentioned below, but no `/packages/**/package.json` was bumped, so I read that as "the same version as before is used"
	- Actually, it rather mean "WC ships unreleased branch of `@woocommerce/components` - see https://github.com/woocommerce/woocommerce-admin/issues/7628. But for now I'd act like :see_no_evil: and continue with smoke tests.
- [x] Run e2e tests
	- 3 fails but fails also for earlier versions - so probably unrelated issue. Tested those flows manually, and worked.
- [x] Smoke test
	- [x] Getting started
	- [x] MC setup
	- [x] Ads setup
	- [x] Dashboard
	- [x] Add campaign
	- [x] Edit free/paid campaign
	- [x] Reports
	- [x] Product feed
	- [x] Settings
	- [x] Disconnecting accounts

**Comment by tomalec** [comment]
I performed the checks mentioned above. Didn't find any new or blocking issue.
@layoutd do you want to do some check from the PHP perspective, or should we just bump the versions?

**Comment by layoutd** [comment]
If you did the smoke tests, that should about do it. I ran the compatibility analyzer and didn't come up with anything  either. Thanks @tomalec!

**Comment by tomalec** [comment]
Closing as done, then. I added the note to our release sheet. Version bump should be released as [`1.4.4`](https://github.com/woocommerce/google-listings-and-ads/releases/tag/1.4.3)

**Comment by findingsimple** [comment]
Thanks @tomalec ❤️ 

We can bump the versions on the next release with actual code changes. No need for a specific release to bump tags if its not generating any warnings.
